import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import * as pending from '@/lib/i18n-pending';

// docs/translation/pending-isizulu.csv is a committed, hand-off snapshot of every
// *_ENGLISH_PENDING dictionary in lib/i18n-pending.ts (see docs/translation/README.md). It is
// generated by `npm run i18n:pending` (scripts/pending-translations.mjs) rather than hand-edited,
// so this guard rebuilds the same rows here and fails if someone edited a dictionary without
// regenerating the CSV.

function csvField(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

function expectedCsv(): string {
  const rows: string[][] = [['group', 'key', 'english', 'isizulu']];
  for (const [exportName, dict] of Object.entries(pending)) {
    if (!exportName.endsWith('_ENGLISH_PENDING') || typeof dict !== 'object' || dict === null) continue;
    const group = exportName.slice(0, -'_ENGLISH_PENDING'.length);
    for (const [key, english] of Object.entries(dict as Record<string, string>)) {
      rows.push([group, key, english, '']);
    }
  }
  return rows.map((row) => row.map(csvField).join(',')).join('\n') + '\n';
}

test('docs/translation/pending-isizulu.csv matches the current *_ENGLISH_PENDING dictionaries', () => {
  const committed = readFileSync(new URL('../docs/translation/pending-isizulu.csv', import.meta.url), 'utf8');
  assert.equal(committed, expectedCsv(),
    'pending-isizulu.csv is out of date — run `npm run i18n:pending` and commit the result');
});

test('every *_ENGLISH_PENDING dictionary is represented in the CSV', () => {
  const committed = readFileSync(new URL('../docs/translation/pending-isizulu.csv', import.meta.url), 'utf8');
  const groups = Object.keys(pending).filter((name) => name.endsWith('_ENGLISH_PENDING'));
  assert.ok(groups.length > 0, 'lib/i18n-pending.ts must export at least one *_ENGLISH_PENDING dictionary');
  for (const exportName of groups) {
    const group = exportName.slice(0, -'_ENGLISH_PENDING'.length);
    assert.match(committed, new RegExp(`^${group},`, 'm'), `pending-isizulu.csv is missing rows for ${exportName}`);
  }
});
