import MenuButton from '@/components/MenuButton';
import BackButton from '@/components/BackButton';
import { DESIGN_COURSE, DESIGN_LESSONS } from '@/lib/course-design';
import PathwayOfflineDownload from '@/components/studies/PathwayOfflineDownload';
import OfflinePageLink from '@/components/studies/OfflinePageLink';
import styles from '@/components/studies/FinanceCourse.module.css';

export const metadata = { title: 'Design a working homestead — teaching preview', robots: { index: false, follow: false } };

export default function DesignCoursePage() {
  return <div className={styles.page}>
    <header className={styles.header}><MenuButton /><BackButton fallback="/student" /><OfflinePageLink href="/student">My Studies</OfflinePageLink><span>Permaculture design</span></header>
    <main className={styles.main}>
      <section className={styles.hero}><div className={styles.heroText}><p className={styles.eyebrow}>From observation to a working plan</p><h1>Design for the people.<br />Work with the place.</h1><p>Bring water, soil, growing systems, access, care and money into one reasoned plan. Follow six stages, then explain and improve your decisions.</p><div className={styles.actions}><OfflinePageLink className={styles.primary} href="/student/design/d1-1">Start with the household brief →</OfflinePageLink><OfflinePageLink href="/student/design/case">Meet the practice household</OfflinePageLink></div></div><img src="/studies-guides/sketch-the-site.jpg" alt="Illustrated growers discussing a paper plan beside a homestead garden; the drawing is illustrative, not surveyed" /></section>
      <aside className={`${styles.notice} ${styles.projectNotice}`}><p><strong>English teaching preview · {DESIGN_LESSONS.length} lesson drafts.</strong> Read and practise with a facilitator or learning partner. A supplied fictional worked demonstration and scale exercise are available; a real field plan still needs its own checked measurements, evidence and review. Narration and translations are not yet available. Save the reading pathway for offline use here before leaving signal. Reading these pages does not award course credit or certify a design.</p></aside>
      <PathwayOfflineDownload pathwayId="design" />
      <section className={styles.section}><h2>Build one design folder as you learn</h2><p>Keep your brief, observations, existing map, alternatives, chosen plan, work and care arrangements, and revisions together. Use paper, spoken explanations or the app. Each stage adds a reasoned decision, not just another feature on a drawing.</p><p>Use the existing technical modules when checking a water, soil, planting or animal proposal. This pathway teaches how to connect those decisions. A field plan still needs suitable measurements, local evidence and any relevant advice or permissions.</p><div className={styles.actions}><OfflinePageLink className={styles.primary} href="/student/design/folder">Open your design learning folder →</OfflinePageLink></div></section>
      <div className={styles.grid}>{DESIGN_COURSE.units.map(unit => <section key={unit.id} className={styles.card}><p className={styles.eyebrow}>Stage {unit.number}</p><h2>{unit.title}</h2><p>{unit.output}</p><ol>{unit.lessons.map(lesson => <li key={lesson.id}><OfflinePageLink href={`/student/design/${lesson.id}`}>{lesson.title}</OfflinePageLink></li>)}</ol></section>)}</div>
      <section className={styles.section}><h2>Two examples, with their limits visible</h2><p>The busy-yard example teaches what to observe before drawing. The worked demonstration is a separate fictional model with supplied coordinates, fair alternatives and a revision after later care evidence. Neither is a construction plan or a record of a real household.</p><div className={styles.actions}><OfflinePageLink className={styles.primary} href="/student/design/worked">Follow the worked design demonstration →</OfflinePageLink><OfflinePageLink href="/student/design/case">Read the early evidence case →</OfflinePageLink><OfflinePageLink href="/student/design/scale">Read the scale and check the space →</OfflinePageLink><OfflinePageLink href="/student/guides/design">Use the Design Studio guide →</OfflinePageLink><OfflinePageLink href="/student/finance">Connect the plan to Farm Finance →</OfflinePageLink></div></section>
      <section className={styles.section}><h2>Learning takes observation and practice</h2><p>Work at a pace that allows field observation, discussion and another attempt after feedback. Eighteen reading pages do not establish a course duration or replace seasonal evidence. The facilitator reviews what you can explain and demonstrate.</p><details><summary>Sources behind the pathway</summary><p>The teaching sequence draws on Rory’s Imbewu course outlines, Southern African gardening handbook and RVCC training/garden planning material. Historical technical prescriptions have not been copied as universal instructions.</p><ul>{DESIGN_COURSE.sources.map(source => <li key={source.url}><a href={source.url}>{source.label}</a></li>)}</ul></details></section>
    </main>
  </div>;
}
