import Link from 'next/link';
import MenuButton from '@/components/MenuButton';
import BackButton from '@/components/BackButton';
import { DESIGN_COURSE, DESIGN_LESSONS } from '@/lib/course-design';
import styles from '@/components/studies/FinanceCourse.module.css';

export const metadata = { title: 'Design a working homestead — teaching preview', robots: { index: false, follow: false } };

export default function DesignCoursePage() {
  return <div className={styles.page}>
    <header className={styles.header}><MenuButton /><BackButton fallback="/student" /><Link href="/student">My Studies</Link><span>Permaculture design</span></header>
    <main className={styles.main}>
      <section className={styles.hero}><div className={styles.heroText}><p className={styles.eyebrow}>From observation to a working plan</p><h1>Design for the people.<br />Work with the place.</h1><p>Bring water, soil, growing systems, access, care and money into one reasoned plan. Follow six stages, then explain and improve your decisions.</p><div className={styles.actions}><Link className={styles.primary} href="/student/design/d1-1">Start with the household brief →</Link><Link href="/student/design/case">Meet the practice household</Link></div></div><img src="/studies-guides/sketch-the-site.jpg" alt="Illustrated growers discussing a paper plan beside a homestead garden; the drawing is illustrative, not surveyed" /></section>
      <aside className={`${styles.notice} ${styles.projectNotice}`}><p><strong>English teaching preview · {DESIGN_LESSONS.length} lesson drafts.</strong> Read and practise with a facilitator or learning partner. The full measured example and illustrated plan set are still being prepared. Narration, translations and offline downloads are not yet provided for this pathway. Reading these pages does not award course credit or certify a design.</p></aside>
      <section className={styles.section}><h2>Build one design folder as you learn</h2><p>Keep your brief, observations, existing map, alternatives, chosen plan, work and care arrangements, and revisions together. Use paper, spoken explanations or the app. Each stage adds a reasoned decision, not just another feature on a drawing.</p><p>Use the existing technical modules when checking a water, soil, planting or animal proposal. This pathway teaches how to connect those decisions. A field plan still needs suitable measurements, local evidence and any relevant advice or permissions.</p><div className={styles.actions}><Link className={styles.primary} href="/student/design/folder">Open your design learning folder →</Link></div></section>
      <div className={styles.grid}>{DESIGN_COURSE.units.map(unit => <section key={unit.id} className={styles.card}><p className={styles.eyebrow}>Stage {unit.number}</p><h2>{unit.title}</h2><p>{unit.output}</p><ol>{unit.lessons.map(lesson => <li key={lesson.id}><Link href={`/student/design/${lesson.id}`}>{lesson.title}</Link></li>)}</ol></section>)}</div>
      <section className={styles.section}><h2>One example, with its limits visible</h2><p>The busy-yard example follows a household that wants food, usable access and manageable care. Its early observations and choices are supplied for discussion. It has no measured source pack or claimed field results; do not treat its sketch or story as a construction plan.</p><div className={styles.actions}><Link href="/student/design/case">Read the case and try the evidence checks →</Link><Link href="/student/guides/design">Use the Design Studio guide →</Link><Link href="/student/finance">Connect the plan to Farm Finance →</Link></div></section>
      <section className={styles.section}><h2>Learning takes observation and practice</h2><p>Work at a pace that allows field observation, discussion and another attempt after feedback. Eighteen reading pages do not establish a course duration or replace seasonal evidence. The facilitator reviews what you can explain and demonstrate.</p><details><summary>Sources behind the pathway</summary><p>The teaching sequence draws on Rory’s Imbewu course outlines, Southern African gardening handbook and RVCC training/garden planning material. Historical technical prescriptions have not been copied as universal instructions.</p><ul>{DESIGN_COURSE.sources.map(source => <li key={source.url}><a href={source.url}>{source.label}</a></li>)}</ul></details></section>
    </main>
  </div>;
}
