'use client';
import { Sprout, Droplets, Trees, HandCoins, Users, GraduationCap, ClipboardCheck, BarChart3 } from 'lucide-react';
import { PROGRESS_AREAS, progressArea, progressValue, type ProgressArea, type ProgrammeRecords } from '@/lib/programme-progress';
import { milestoneAt, type ProgrammeMilestone } from '@/lib/programme-evidence';
import styles from './ProgrammeProgress.module.css';

const icons = { growing:Sprout, 'water-energy':Droplets, 'land-nature':Trees, livelihoods:HandCoins, participation:Users, learning:GraduationCap, delivery:ClipboardCheck, other:BarChart3 };
export default function ProgrammeProgress({ records, targets, asOf, category, onCategory, onAdd, currentScope, showCurrentRecords=true }: { records: ProgrammeRecords | null; targets: ProgrammeMilestone[]; asOf: string; category: ProgressArea | ''; onCategory: (area: ProgressArea | '') => void; onAdd?: (area: ProgressArea) => void; currentScope: boolean; showCurrentRecords?: boolean }) {
  const shown = targets.filter(m=>!category || progressArea(m)===category);
  return <div className={styles.progress}>
    <div className={styles.heading}><div><h2>What the programme is changing</h2><p>Explore the evidence across seven areas of work.</p></div><button onClick={()=>onCategory('')} aria-pressed={!category}>All areas</button></div>
    <div className={styles.coverage}>{PROGRESS_AREAS.filter(a=>a.id!=='other'||targets.some(m=>progressArea(m)==='other')).map(area=>{const Icon=icons[area.id];const observed=targets.filter(m=>progressArea(m)===area.id&&milestoneAt(m,asOf).actual!==null).length;const current=currentScope ? records?.metrics.filter(m=>m.category===area.id&&m.value!==null).length??0 : 0;return <button key={area.id} className={styles.area} aria-pressed={category===area.id} onClick={()=>onCategory(category===area.id?'':area.id)}><Icon size={26}/><strong>{area.title}</strong><span>{observed ? `${observed} dated indicator${observed===1?'':'s'}` : current ? `${current} current measure${current===1?'':'s'}` : 'No reported measure yet'}</span></button>;})}</div>
    {showCurrentRecords && (currentScope ? records ? <section className={styles.section}><h2>Latest organisation records</h2><p>Current totals from the garden and farmer registers. These are separate from the dated targets below.</p>{records.errors.map(error=><p role="alert" key={error}>{error}</p>)}
      {PROGRESS_AREAS.filter(a=>!category||a.id===category).map(area=>{const metrics=records.metrics.filter(m=>m.category===area.id);return metrics.length>0&&<div key={area.id}><h3>{area.title}</h3><div className={styles.metrics}>{metrics.map(metric=><article key={metric.id}><p>{metric.label}</p><strong>{progressValue(metric.value,metric.unit)}</strong><small>{metric.note}</small></article>)}</div></div>;})}
      <details><summary>Coverage and calculation basis</summary>{records.notes.map(note=><p key={note}>{note}</p>)}</details>
    </section> : <p>Loading the latest shared production, area and finance records…</p> : <p className={styles.scope}>Latest organisation totals are shown when you select all projects and today’s date. For this selection, the dated indicators below define the reporting scope.</p>)}
    <section className={styles.section}><div className={styles.heading}><div><h2>Dated indicators & targets</h2><p>Latest observation on or before {asOf}. Each measure keeps its own unit and target.</p></div></div>
      <div className={styles.indicators}>{shown.map(m=>{const v=milestoneAt(m,asOf);const area=PROGRESS_AREAS.find(a=>a.id===progressArea(m))!;return <article key={m.id} className={styles.indicator}><div className={styles.meta}><span>{area.title}</span><strong>{v.actual===null?'Awaiting evidence':v.status}</strong></div><h3>{m.title}</h3><strong className={styles.value}>{progressValue(v.actual,m.unit)}</strong><p>{m.target===null?'Target not yet agreed':`Target: ${progressValue(m.target,m.unit)}`}</p>{v.percent!==null&&<><progress aria-label={m.title} value={Math.min(100,v.percent)} max={100}/><p>{Math.round(v.percent)}% of target · {progressValue(v.remaining,m.unit)} remaining</p></>}<div className={styles.meta}><span>Baseline: {progressValue(m.baseline,m.unit)}</span><span>{m.target===null?'Review':'Due'}: {m.due}</span></div><p><strong>Observed:</strong> {v.observedOn??'Not yet recorded'}</p><p>{v.evidence}</p><details><summary>Method and recorded observations</summary><p>{m.method}</p>{m.observations.filter(o=>o.date<=asOf).sort((a,b)=>a.date.localeCompare(b.date)).map(o=><p key={o.date}>{o.date} · {progressValue(o.actual,m.unit)} · {o.evidence}</p>)}</details></article>;})}</div>
      {!shown.length&&<p>No {category ? PROGRESS_AREAS.find(a=>a.id===category)?.title.toLowerCase() : ''} indicators have been shared for this selection.</p>}
    </section>
    <section className={styles.section}><h2>Build the evidence across the project</h2><p>These measures can be recorded by the organisation with a definition, reporting period and evidence reference.</p><div className={styles.gaps}>{PROGRESS_AREAS.filter(a=>a.id!=='other'&&(!category||a.id===category)).map(area=><article key={area.id}><h3>{area.title}</h3><p>{area.examples}</p>{onAdd&&<button onClick={()=>onAdd(area.id)}>Add {area.title.toLowerCase()} indicator</button>}</article>)}</div></section>
  </div>;
}
