'use client';
import { Sprout, Droplets, Trees, HandCoins, Users, GraduationCap, ClipboardCheck, BarChart3 } from 'lucide-react';
import { useLanguage } from '@/lib/i18n';
import { PROGRESS_AREAS, progressArea, progressValue, type ProgressArea, type ProgrammeRecords } from '@/lib/programme-progress';
import { milestoneAt, type ProgrammeMilestone } from '@/lib/programme-evidence';
import styles from './ProgrammeProgress.module.css';

const icons = { growing:Sprout, 'water-energy':Droplets, 'land-nature':Trees, livelihoods:HandCoins, participation:Users, learning:GraduationCap, delivery:ClipboardCheck, other:BarChart3 };
const areaZu: Record<ProgressArea, string> = {
  growing: 'Ukulima nokukhiqiza', 'water-energy': 'Amanzi namandla', 'land-nature': 'Umhlaba nokuhlukahluka kwemvelo',
  livelihoods: 'Imali yokuziphilisa', participation: 'Ukubamba iqhaza nemizi', learning: 'Ukufunda nokwenza',
  delivery: 'Ukuhlinzeka nokweseka', other: 'Ezinye izilinganiso okuvunyelwene ngazo',
};
const examplesZu: Record<ProgressArea, string> = {
  growing: 'Izingadi ezikhiqizayo, imibhede yemifino, amasimu okudla okuyisisekelo, ukuvuna nokudla okwabiwe.',
  'water-energy': 'Amathangi afakiwe, ukutholakala kwamanzi okuthembekile, amanzi aqoqiwe namandla elanga asebenzayo.',
  'land-nature': 'Izihlahla ezitshalwe nezisaphila, isimo somhlabathi, umquba nomhlaba obuyiselwayo.',
  livelihoods: 'Umkhiqizo othengisiwe, imali nezindleko eziqoshiwe, umsebenzi okhokhelwayo nokufinyelela emakethe.',
  participation: 'Abalimi abasebenzayo, imizi efinyelelwe, ukufinyelela ekudleni nokulandelwa kwezinyathelo eziqediwe.',
  learning: 'Ababekhona, amakhono akhonjisiwe nemikhuba yokulima esetshenziswe ngemva kokuqeqeshwa.',
  delivery: 'Ukufakwa okuqediwe, ukuvakashelwa ngumeluleki, izinyathelo okuvunyelwene ngazo nokuhlolwa kobufakazi.',
  other: 'Izinkomba ezengeziwe ezichazwe yinhlangano eqhuba uhlelo.',
};
function Copy({ en, zu, lang }: { en: string; zu: string; lang: string }) {
  return lang === 'zu' ? <>{zu}<small className={styles.source}>English source: {en}</small></> : <>{en}</>;
}
export default function ProgrammeProgress({ records, targets, asOf, category, onCategory, onAdd, currentScope, showCurrentRecords=true }: { records: ProgrammeRecords | null; targets: ProgrammeMilestone[]; asOf: string; category: ProgressArea | ''; onCategory: (area: ProgressArea | '') => void; onAdd?: (area: ProgressArea) => void; currentScope: boolean; showCurrentRecords?: boolean }) {
  const {lang} = useLanguage();
  const name = (area: ProgressArea) => lang === 'zu' ? areaZu[area] : PROGRESS_AREAS.find(a=>a.id===area)!.title;
  const shown = targets.filter(m=>!category || progressArea(m)===category);
  return <div className={styles.progress}>
    <div className={styles.heading}><div><h2><Copy lang={lang} en="What the programme is changing" zu="Okuguqukayo ngenxa yohlelo"/></h2><p><Copy lang={lang} en="Explore the evidence across seven areas of work." zu="Hlola ubufakazi emikhakheni eyisikhombisa yomsebenzi."/></p></div><button onClick={()=>onCategory('')} aria-pressed={!category}><Copy lang={lang} en="All areas" zu="Yonke imikhakha"/></button></div>
    <div className={styles.coverage}>{PROGRESS_AREAS.filter(a=>a.id!=='other'||targets.some(m=>progressArea(m)==='other')).map(area=>{const Icon=icons[area.id];const observed=targets.filter(m=>progressArea(m)===area.id&&milestoneAt(m,asOf).actual!==null).length;const current=currentScope ? records?.metrics.filter(m=>m.category===area.id&&m.value!==null).length??0 : 0;const en=observed ? `${observed} dated indicator${observed===1?'':'s'}` : current ? `${current} current measure${current===1?'':'s'}` : 'No reported measure yet';const zu=observed ? `${observed} inkomba enedethi` : current ? `${current} isilinganiso samanje` : 'Asikabikwa isilinganiso';return <button key={area.id} className={styles.area} aria-pressed={category===area.id} onClick={()=>onCategory(category===area.id?'':area.id)}><Icon size={26}/><strong>{name(area.id)}</strong><span><Copy lang={lang} en={en} zu={zu}/></span></button>;})}</div>
    {showCurrentRecords && (currentScope ? records ? <section className={styles.section}><h2><Copy lang={lang} en="Latest organisation records" zu="Amarekhodi akamuva enhlangano"/></h2><p><Copy lang={lang} en="Current totals from the garden and farmer registers. These are separate from the dated targets below." zu="Izamba zamanje ezivela kumarejista ezingadi nawabalimi. Zihlukile emigomweni enezinsuku engezansi."/></p>{records.errors.map(error=><p role="alert" key={error}>{error}</p>)}
      {PROGRESS_AREAS.filter(a=>!category||a.id===category).map(area=>{const metrics=records.metrics.filter(m=>m.category===area.id);return metrics.length>0&&<div key={area.id}><h3>{name(area.id)}</h3><div className={styles.metrics}>{metrics.map(metric=><article key={metric.id}><p>{metric.label}</p><strong>{progressValue(metric.value,metric.unit)}</strong><small>{metric.note}</small></article>)}</div></div>;})}
      <details><summary><Copy lang={lang} en="Coverage and calculation basis" zu="Ububanzi nokuthi izibalo zenziwe kanjani"/></summary>{records.notes.map(note=><p key={note}>{note}</p>)}</details>
    </section> : <p><Copy lang={lang} en="Loading the latest shared production, area and finance records…" zu="Kusalayishwa amarekhodi akamuva okwabelwana ngawo okukhiqiza, endawo nawezimali…"/></p> : <p className={styles.scope}><Copy lang={lang} en="Latest organisation totals are shown when you select all projects and today’s date. For this selection, the dated indicators below define the reporting scope." zu="Izamba zakamuva zenhlangano ziboniswa uma ukhetha wonke amaphrojekthi nosuku lwanamuhla. Kulokhu okukhethiwe, izinkomba ezinezinsuku ezingezansi zichaza okubikwa ngakho."/></p>)}
    <section className={styles.section}><div className={styles.heading}><div><h2><Copy lang={lang} en="Dated indicators & targets" zu="Izinkomba nemigomo enezinsuku"/></h2><p><Copy lang={lang} en={`Latest observation on or before ${asOf}. Each measure keeps its own unit and target.`} zu={`Ukuqaphela kwakamuva ngalolu suku noma ngaphambi kuka-${asOf}. Isilinganiso ngasinye sigcina iyunithi nomgomo waso.`}/></p></div></div>
      <div className={styles.indicators}>{shown.map(m=>{const v=milestoneAt(m,asOf);const area=PROGRESS_AREAS.find(a=>a.id===progressArea(m))!;const statusEn=v.actual===null?'Awaiting evidence':v.status;const statusZu=v.actual===null?'Kulindwe ubufakazi':v.status==='Target met'?'Umnqopho ufinyelelwe':v.status==='In progress'?'Kuyaqhubeka':v.status==='Overdue'?'Isikhathi sesidlulile':v.status==='Reported · no target'?'Kubikiwe · awukho umgomo':'Asikabikwa isimo';const evidence=v.evidence==='No observation by this date'&&lang==='zu'?<Copy lang={lang} en={v.evidence} zu="Akukho kuqaphela ngalolu suku"/>:v.evidence;return <article key={m.id} className={styles.indicator}><div className={styles.meta}><span>{name(area.id)}</span><strong><Copy lang={lang} en={statusEn} zu={statusZu}/></strong></div><h3>{m.title}</h3><strong className={styles.value}>{progressValue(v.actual,m.unit)}</strong><p>{m.target===null?<Copy lang={lang} en="Target not yet agreed" zu="Akukavunyelwana ngomgomo"/>:<><Copy lang={lang} en="Target:" zu="Umnqopho:"/> {progressValue(m.target,m.unit)}</>}</p>{v.percent!==null&&<><progress aria-label={m.title} value={Math.min(100,v.percent)} max={100}/><p>{Math.round(v.percent)}% <Copy lang={lang} en={`of target · ${progressValue(v.remaining,m.unit)} remaining`} zu={`womgomo · kusasele ${progressValue(v.remaining,m.unit)}`}/></p></>}<div className={styles.meta}><span><Copy lang={lang} en="Baseline:" zu="Isilinganiso sokuqala:"/> {progressValue(m.baseline,m.unit)}</span><span><Copy lang={lang} en={m.target===null?'Review:':'Due:'} zu={m.target===null?'Ukubuyekeza:':'Umnqamulajuqu:'}/> {m.due}</span></div><p><strong><Copy lang={lang} en="Observed:" zu="Kuqashelwe:"/></strong> {v.observedOn??(lang==='zu'?'Akukarekhodwa':'Not yet recorded')}</p><p>{evidence}</p><details><summary><Copy lang={lang} en="Method and recorded observations" zu="Indlela nokuqaphela okurekhodiwe"/></summary><p>{m.method}</p>{m.observations.filter(o=>o.date<=asOf).sort((a,b)=>a.date.localeCompare(b.date)).map(o=><p key={o.date}>{o.date} · {progressValue(o.actual,m.unit)} · {o.evidence}</p>)}</details></article>;})}</div>
      {!shown.length&&<p><Copy lang={lang} en={`No ${category ? PROGRESS_AREAS.find(a=>a.id===category)?.title.toLowerCase() : ''} indicators have been shared for this selection.`} zu={`Azikho izinkomba ezabelwene ngazo kulokhu okukhethiwe${category?` komkhakha othi ${name(category)}`:''}.`}/></p>}
    </section>
    <section className={styles.section}><h2><Copy lang={lang} en="Build the evidence across the project" zu="Qoqa ubufakazi kulo lonke iphrojekthi"/></h2><p><Copy lang={lang} en="These measures can be recorded by the organisation with a definition, reporting period and evidence reference." zu="Inhlangano ingaqopha lezi zilinganiso kanye nencazelo, isikhathi sokubika nereferensi yobufakazi."/></p><div className={styles.gaps}>{PROGRESS_AREAS.filter(a=>a.id!=='other'&&(!category||a.id===category)).map(area=><article key={area.id}><h3>{name(area.id)}</h3><p><Copy lang={lang} en={area.examples} zu={examplesZu[area.id]}/></p>{onAdd&&<button onClick={()=>onAdd(area.id)}><Copy lang={lang} en={`Add ${area.title.toLowerCase()} indicator`} zu={`Faka inkomba: ${name(area.id)}`}/></button>}</article>)}</div></section>
  </div>;
}
