'use client';
import { useEffect, useRef, useState } from 'react';
import { useAuth } from '@/lib/auth';
import { fieldApi } from '@/lib/field-api';
import { DEVICE_SAVE_NOTICE } from '@/lib/field-request-model';
import { useFieldSync } from '@/lib/use-field-sync';
import FieldDraft, { clearFieldDraft } from './FieldDraft';
import { isSampleMode } from '@/lib/sample-mode';
import { sampleRead, sampleWrite } from '@/lib/sample-operations';
import { readSampleProgramme } from './SampleProgramme';
import { completeSampleFieldWorkspace, freshFieldWorkspace, projectFieldWorkspace } from '@/lib/field-teams';
import { sampleAssessments } from '@/lib/sample-programme';
import { resizeLogoForStorage } from '@/lib/invoice-logo';
import { completeSampleEvidence, freshEvidenceData, milestoneAt, publishedTraining, trainingTotals, validTrainingRecord, validProgrammeMilestone, type EvidenceData, type TrainingRecord, type ProgrammeMilestone } from '@/lib/programme-evidence';
import ReportComposer from './ReportComposer';
import ProgrammeProgress from './ProgrammeProgress';
import { loadProgrammeProgressRecords } from '@/lib/programme-progress-records';
import { PROGRESS_AREAS, PROGRESS_TEMPLATES, progressArea, progressValue, progressRecordSections, programmeRecordMetrics, type ProgrammeRecords, type ProgressArea } from '@/lib/programme-progress';
import VenueLocation from './VenueLocation';
import TrainingSignature from './TrainingSignature';
import TrainingFeedback from './TrainingFeedback';
import { TRAINING_PHOTO_KINDS, trainingEvidenceSummary, type TrainingPhotoKind } from '@/lib/programme-evidence';
import trainingStyles from './TrainingEvidence.module.css';
import styles from './MelDashboard.module.css';
import FieldDataStatus from './FieldDataStatus';
import { useLanguage } from '@/lib/i18n';

type Tab = 'progress' | 'training' | 'targets' | 'branding';
const ERROR_DRAFTS: Record<string, string> = {
  'Complete the pending observation total and evidence reference, or clear both.': 'Gcwalisa isamba salokhu kuqaphela nereferensi yobufakazi, noma kusule kokubili.',
  'Check the session and confirm the shared content before publishing.': 'Hlola isikhathi sokuqeqesha bese uqinisekisa okuqukethwe okwabelwana ngakho ngaphambi kokushicilela.',
  'Check the target, dates, units and evidence notes.': 'Hlola umgomo, izinsuku, amayunithi namanothi obufakazi.',
  'Training access is not enabled.': 'Imvume yokufinyelela ekuqeqeshweni ayivuliwe.',
  'Organisation management access is required.': 'Kudingeka imvume yokuphatha inhlangano.',
  'Use members of your current assigned group.': 'Sebenzisa amalungu eqembu owabelwe lona njengamanje.',
  'Enter an observed total and evidence reference.': 'Faka isamba esiqashelwe nereferensi yobufakazi.',
};
const today=()=>new Date().toISOString().slice(0,10);
const emptySession=():TrainingRecord=>({id:crypto.randomUUID(),project:'',title:'',date:today(),venue:'',latitude:null,longitude:null,facilitator:'',ownerId:'',attendance:[],presentCount:0,registeredCount:0,report:'',nextSteps:'',assessmentId:'',published:false,photos:[],photoCount:0,updatedAt:''});
const emptyTarget=():ProgrammeMilestone=>({id:crypto.randomUUID(),project:'',category:'other',title:'',unit:'',baseline:null,target:null,due:today(),owner:'',method:'',published:false,observations:[],updatedAt:''});
export default function ProgrammeEvidence({ funder=false, mentor=false, initialTab='progress' }: { funder?:boolean; mentor?:boolean; initialTab?:Tab }) {
  const {user,profile}=useAuth();
  const {lang}=useLanguage();
  const ui=(en:string,zu:string)=>lang==='zu'?zu:en;
  const statusCopy=(en:string,zu:string)=>lang==='zu'?<>{zu}<small style={{display:'block',fontSize:12,lineHeight:1.45}}>English source: {en}</small></>:en;
  const requestVersion=useRef(0);
  const [data,setData]=useState<EvidenceData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [org,setOrg]=useState(''),[orgs,setOrgs]=useState<{id:string;name:string}[]>([]),[tab,setTab]=useState<Tab>(initialTab),[asOf,setAsOf]=useState(today()),[project,setProject]=useState('');
  const [sessionDraft,setSession]=useState<TrainingRecord|null>(null),[target,setTarget]=useState<ProgrammeMilestone|null>(null),[reviewed,setReviewed]=useState(false),[photosBusy,setPhotosBusy]=useState(false);
  const [guestCode,setGuestCode]=useState(''),[guestName,setGuestName]=useState('');
  const [photoKind,setPhotoKind]=useState<TrainingPhotoKind>('activity');
  const session=sessionDraft?{...sessionDraft,photoCount:sessionDraft.photos.length,...(!funder?{presentCount:sessionDraft.attendance.filter(a=>a.present).length,registeredCount:sessionDraft.attendance.length}:{})}:null;
  const [observation,setObservation]=useState({date:today(),actual:'',evidence:''});
  const [category,setCategory]=useState<ProgressArea|''>('');
  const [records,setRecords]=useState<ProgrammeRecords|null>(null);
  async function request(body?:unknown,query='') {
    if(isSampleMode()) throw Error("This action must remain in the tour.");
    return fieldApi(`/api/programme-evidence?org=${encodeURIComponent(org)}${query}`,body);
  }
  async function reload() {
    const version=++requestVersion.current; setError('');
    try {
      if(isSampleMode()) {
        const d=completeSampleEvidence(sampleRead('programme-evidence',freshEvidenceData));
        if(mentor && !readSampleProgramme().people.find(p=>p.id==='sample-mentor')?.training) throw Error("Training access is off for the mentor. Enable it in Organisation → People & access.");
        if(funder && !readSampleProgramme().funderAccess) throw Error("The organisation has switched off funder access.");
        const workspace=projectFieldWorkspace(completeSampleFieldWorkspace(sampleRead('field-teams',freshFieldWorkspace)),'sample-mentor',!mentor);
        setData({...d,assessments:funder?[]:sampleAssessments(readSampleProgramme()).map(a=>({id:a.assessment.id,title:a.assessment.title})),sessions:funder?d.sessions.filter(s=>s.published).map(publishedTraining):mentor?d.sessions.filter(s=>s.ownerId==='sample-mentor'):d.sessions,milestones:funder?d.milestones.filter(m=>m.published):d.milestones,people:funder?[]:workspace.people.filter(p=>['farmer','student'].includes(p.role)).map(p=>({id:p.id,name:p.name})),canManage:!funder&&!mentor,canRecord:!funder&&(!mentor||readSampleProgramme().people.find(p=>p.id==='sample-mentor')?.training===true),canBrand:!funder&&!mentor,canAssess:!funder&&!mentor,canAnalyse:!funder&&!mentor});
      } else {const result=await request();if(version===requestVersion.current)setData(result);}
    } catch(e){if(version===requestVersion.current){setData(null);setError((e as Error).message);}}
  }
  useEffect(()=>{let cancelled=false;if(isSampleMode()){setOrgs([{id:'sample-ngo',name:"Imbewu KZN"}]);setOrg('sample-ngo');return;}if(!user)return;if(profile?.role==='mentor'&&profile.org_id){setOrg(profile.org_id);return;}void (async()=>{try{const d=await fieldApi('/api/network/orgs');if(!cancelled){setOrgs(d.orgs);setOrg(d.orgs[0]?.id??'');}}catch(e){if(!cancelled)setError((e as Error).message);}})();return()=>{cancelled=true;};},[user,profile]);
  useEffect(()=>{setData(null);setSession(null);setTarget(null);if(org)void reload();return()=>{requestVersion.current++;};},[org,funder,mentor]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{
    let cancelled=false;setRecords(null);
    if(!data||data.brandingOnly||mentor||!org)return;
    void loadProgrammeProgressRecords(org,funder,data.sample).then(result=>{if(!cancelled)setRecords(result);}).catch(e=>{
      if(!cancelled)setRecords({...programmeRecordMetrics(null,null),errors:[e instanceof Error?e.message:'Shared programme records are unavailable.']});
    });
    return()=>{cancelled=true;};
  },[data,org,funder,mentor]);
  function addIndicator(area:ProgressArea='other') {
    setTarget({...emptyTarget(),project,category:area});setObservation({date:today(),actual:'',evidence:''});setTab('targets');
  }
  async function save(action:'session'|'milestone'|'branding') {
    if(!data||busy)return;const version=requestVersion.current;setBusy(true);setError('');setNotice('');
    try{
      const now=new Date().toISOString();let queued=false;
      const s=session ? {...session,id:session.id||crypto.randomUUID(),ownerId:session.ownerId||(data.sample?(mentor?'sample-mentor':'sample-organisation'):user?.uid??''),presentCount:session.attendance.filter(a=>a.present).length,registeredCount:session.attendance.length,photoCount:session.photos.length} : null;
      const m=target ? {...target,id:target.id||crypto.randomUUID()} : null;
      if(action==='milestone' && m && (observation.actual.trim() || observation.evidence.trim())) {
        if(!observation.actual.trim() || !observation.evidence.trim())throw Error('Complete the pending observation total and evidence reference, or clear both.');
        m.observations=[...m.observations.filter(o=>o.date!==observation.date),{date:observation.date,actual:+observation.actual,evidence:observation.evidence.trim(),recordedAt:now}];
      }
      if(action==='session'&&(!validTrainingRecord(s,today())||s?.published&&!reviewed))throw Error('Check the session and confirm the shared content before publishing.');
      if(action==='milestone'&&!validProgrammeMilestone(m,today()))throw Error('Check the target, dates, units and evidence notes.');
      if(isSampleMode()){
        const all=completeSampleEvidence(sampleRead('programme-evidence',freshEvidenceData));
        if(action==='session' && (!data.canRecord || mentor && !readSampleProgramme().people.find(p=>p.id==='sample-mentor')?.training))throw Error('Training access is not enabled.');
        if(action==='milestone'&&!data.canManage)throw Error('Organisation management access is required.');
        if(action==='session' && s?.attendance.some(a=>!a.id.startsWith('guest-')&&!data.people.some(p=>p.id===a.id)))throw Error('Use members of your current assigned group.');
        sampleWrite('programme-evidence',action==='session'?{...all,sessions:[...all.sessions.filter(r=>r.id!==s!.id),{...s!,updatedAt:now}]}:action==='milestone'?{...all,milestones:[...all.milestones.filter(r=>r.id!==m!.id),{...m!,updatedAt:now}]}:{...all,branding:data.branding});
      }else{if(data.sample)throw Error('This practice workspace has ended. Reopen the workspace.');const result=await request(action==='session'?{action,session:s,reviewed,expectedUpdatedAt:session?.updatedAt}:action==='milestone'?{action,milestone:m,expectedUpdatedAt:target?.updatedAt}:{action,branding:data.branding});queued=result.queued===true;}
      if(version!==requestVersion.current)return;setNotice(queued?DEVICE_SAVE_NOTICE:'Saved. Reports now include the updated record.');if(action==='session')void clearFieldDraft(`training:${org}`).catch(()=>{});setSession(null);setTarget(null);await reload();
    }catch(e){if(version===requestVersion.current)setError((e as Error).message);}finally{setBusy(false);}
  }
  async function editSession(s:TrainingRecord){const version=requestVersion.current;setError('');setPhotosBusy(true);setReviewed(false);try{const photos=data?.sample?s.photos:s.photoCount===0?[]:(await request(undefined,`&mode=photos&id=${encodeURIComponent(s.id)}`)).photos;if(version===requestVersion.current)setSession({...s,photos,published:data?.canRecord&&!data.canManage?false:s.published});}catch(e){setError((e as Error).message);}finally{setPhotosBusy(false);}}
  async function addVenuePhotos(files: FileList | null) {
    if (!session || !data?.canRecord || photosBusy || !files?.length) return;
    const sessionId=session.id, version=requestVersion.current;
    const selectedCount=files.length, remaining=8-session.photos.length, chosen=Array.from(files).slice(0,remaining);
    setPhotosBusy(true);setError('');
    try {
      const photos=await Promise.all(chosen.map(async file=>({image:await resizeLogoForStorage(file,1000,70000),caption:'',kind:photoKind,shared:false})));
      if(version===requestVersion.current)setSession(s=>s?.id===sessionId?{...s,photos:[...s.photos,...photos].slice(0,8)}:s);
      if(version===requestVersion.current&&selectedCount>remaining)setNotice('Added the first available photos. Each session supports up to eight photographs.');
    } catch(e) { if(version===requestVersion.current)setError((e as Error).message); }
    finally { if(version===requestVersion.current)setPhotosBusy(false); }
  }
  useFieldSync(()=>void reload(),!busy&&!session&&!target);
  const sessions=data?.sessions.filter(s=>!project||s.project===project)??[],targets=data?.milestones.filter(m=>!project||m.project===project)??[];
  const totals=trainingTotals(sessions,asOf,!funder), dated=sessions.filter(s=>s.date<=asOf);
  const currentScope=asOf===today()&&!project&&!mentor;
  const selectedTargets=targets.filter(m=>!category||progressArea(m)===category);
  const selectedRecords=records?{...records,metrics:records.metrics.filter(m=>!category||m.category===category)}:null;
  const showTraining=!category||category==='learning';
  const dates=[...new Set([today(),...sessions.map(s=>s.date),...targets.flatMap(m=>m.observations.map(o=>o.date))])].sort();
  const projects=[...new Set([...(data?.sessions.map(s=>s.project)??[]),...(data?.milestones.map(m=>m.project)??[])])].sort();
  const setS=(key:keyof TrainingRecord,value:unknown)=>setSession(s=> { if (!s) return s; const next={...s,[key]:value}; return {...next,presentCount:next.attendance.filter(a=>a.present).length,registeredCount:next.attendance.length}; });
  const setM=(key:keyof ProgrammeMilestone,value:unknown)=>setTarget(m=>m?{...m,[key]:value}:m);
  const logoUpload=async(key:'organisation'|'garden'|'funder',file?:File)=>{if(!file||!data)return;setBusy(true);try{const image=await resizeLogoForStorage(file);setData(d=>d?{...d,branding:{...d.branding,[key]:{...d.branding[key],image}}}:d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className={styles.root} style={initialTab==='branding'?{padding:0,background:'transparent'}:undefined}><div className={styles.wrap}>
    <FieldDataStatus data={data} />
    {lang==='zu'&&<p role="note">{statusCopy('This interface is an unreviewed isiZulu draft. Indicator names, values, reports and evidence notes are kept exactly as entered and may be in English.','Lesi sixhumi siwuhlaka lwesiZulu olungakabuyekezwa. Amagama ezinkomba, amanani, imibiko namanothi obufakazi agcinwa njengoba efakiwe futhi angase abe ngesiNgisi.')}</p>}
    {initialTab!=='branding'&&<div className={styles.hero}><h1>{funder?ui('Project progress & evidence','Inqubekelaphambili nobufakazi bephrojekthi'):ui('Programme evidence & progress','Ubufakazi nenqubekelaphambili yohlelo')}</h1><p>{ui('Growing, water, land, livelihoods, participation, learning and delivery. Follow the recorded results and the evidence behind them.','Ukulima, amanzi, umhlaba, izindlela zokuziphilisa, ukubamba iqhaza, ukufunda nokulethwa kwezinsiza. Landela imiphumela eqoshiwe nobufakazi bayo.')}</p></div>}
    {orgs.length>1&&<label>{ui('Organisation','Inhlangano')}<select disabled={busy||photosBusy} value={org} onChange={e=>setOrg(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
    {error&&<p role="alert" className={styles.error}>{ERROR_DRAFTS[error]&&lang==='zu'?<>{ERROR_DRAFTS[error]}<small style={{display:'block',fontSize:12,lineHeight:1.45}}>English source: {error}</small></>:error}</p>}{notice&&<p role="status" className={styles.notice}>{lang==='zu'&&notice===DEVICE_SAVE_NOTICE?statusCopy(notice,'Kulondolozwe kule divayisi, kuhlanganise nezithombe namasiginesha anamathiselwe. Kulindwe ukuthunyelwa uma sekuxhunyiwe ku-inthanethi.'):lang==='zu'&&notice==='Saved. Reports now include the updated record.'?statusCopy(notice,'Kulondoloziwe. Imibiko isifaka irekhodi elibuyekeziwe.'):notice}</p>}
    {!data&&!error&&<p>{ui('Loading authorised programme evidence…','Kusalayishwa ubufakazi bohlelo obugunyaziwe…')}</p>}
    {data&&<>
      {initialTab!=='branding'&&<div className={styles.row}>{((data.brandingOnly?['branding']:['progress','training',...(!funder?['targets']:[]),...(data.canBrand?['branding']:[])]) as Tab[]).map(t=><button key={t} aria-pressed={tab===t} disabled={busy||photosBusy} onClick={()=>setTab(t)}>{{progress:ui('Progress report','Umbiko wenqubekelaphambili'),training:ui('Training register','Irejista yokuqeqeshwa'),targets:ui('Indicators & targets','Izinkomba nemigomo'),branding:ui('Names & logos','Amagama namalogo')}[t]}</button>)}</div>}
      {tab!=='branding'&&!data.brandingOnly&&<label>{ui('Project','Iphrojekthi')}<select value={project} onChange={e=>setProject(e.target.value)}><option value="">{ui('All visible projects','Wonke amaphrojekthi abonakalayo')}</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label>}
      {!data.brandingOnly&&tab==='progress'&&<>
        <div className={styles.card}><label>{ui('Progress as of','Inqubekelaphambili kusukela')}<input type="date" value={asOf} max={today()} onChange={e=>{if(e.target.value)setAsOf(e.target.value);}} /></label><label>{ui('Timeline · recorded dates','Umugqa wesikhathi · izinsuku eziqoshiwe')}<input aria-label={ui('Progress timeline','Umugqa wesikhathi wenqubekelaphambili')} style={{accentColor:'#285c3e'}} type="range" min={0} max={Math.max(0,dates.length-1)} value={Math.max(0,dates.findLastIndex(d=>d<=asOf))} onChange={e=>setAsOf(dates[+e.target.value])} /></label><p>Shows observations dated on or before {asOf}, using the latest corrected records. This is not a reconstruction of what had been entered at that time.</p></div>
        <ProgrammeProgress records={records} targets={targets} asOf={asOf} category={category} onCategory={setCategory} onAdd={data.canManage?addIndicator:undefined} currentScope={currentScope} showCurrentRecords={!mentor}/>
        {showTraining&&<section className={styles.card}><h2>{ui('Training delivery','Ukuqhutshwa kokuqeqeshwa')}</h2><div className={styles.grid}>{[[ui('Sessions delivered','Izikhathi zokuqeqesha ezenziwe'),totals.sessions],[ui('Attendances','Ababekhona'),totals.attendances],[ui('Distinct participants','Abahlanganyeli abahlukene'),totals.uniqueParticipants??'Not included in funder projection']].map(([l,n])=><div key={l}><h3>{l}</h3><strong className={styles.stat}>{n}</strong></div>)}</div><p>Repeat attendance counts as another attendance, not another person. Attendance and satisfaction are delivery evidence; they do not alone establish skills gained or impact.</p></section>}
        <ReportComposer deviceData={data} title="Project progress report" sample={data.sample} branding={data.branding} reportDate={asOf}
          metrics={[{label:'Indicators',value:String(selectedTargets.length),detail:project||'All visible projects'}, {label:'Targets met',value:String(selectedTargets.filter(m=>milestoneAt(m,asOf).status==='Target met').length),detail:`As of ${asOf}`}, ...(showTraining?[{label:'Sessions delivered',value:String(totals.sessions),detail:'Completed sessions'},{label:'Attendances',value:String(totals.attendances),detail:'Includes repeat attendance'}]:[])]}
          chart={{title:`Progress against agreed targets · ${asOf}`,suffix:'%',minimumScale:100,rows:selectedTargets.flatMap(m=>{const v=milestoneAt(m,asOf);return v.percent===null?[]:[{label:m.title,value:v.percent,display:`${Math.round(v.percent)}%`}];})}} sections={[
          {title:'Reporting scope',lines:[project||'All visible projects',category?PROGRESS_AREAS.find(a=>a.id===category)!.title:'All areas of work',`As of ${asOf}. Generated from the latest available records. ${funder?'Published evidence and consented portfolio records only.':'Includes internal records.'}`,currentScope?'Latest register totals have their own coverage and periods, as stated below.':'Current organisation totals are excluded from this dated or project-specific selection.']},
          ...(currentScope&&selectedRecords?[...progressRecordSections(selectedRecords),{title:'Register coverage',lines:[...selectedRecords.notes,...selectedRecords.errors]}]:[]),
          {title:'Dated indicators & targets',lines:selectedTargets.map(m=>{const v=milestoneAt(m,asOf);return `${m.title}: ${progressValue(v.actual,m.unit)}; target ${progressValue(m.target,m.unit)}; baseline ${progressValue(m.baseline,m.unit)}; due / review ${m.due}. ${v.status}. Observed ${v.observedOn??'not recorded'}. Method: ${m.method} Evidence: ${v.evidence}`;})},
          ...(showTraining?[
            {title:'Training delivery',lines:[`${totals.sessions} sessions; ${totals.attendances} attendances.`,totals.uniqueParticipants===null?'Distinct participant identities are excluded from this funder view.':`${totals.uniqueParticipants} distinct participants.`,...dated.map(s=>`${s.date}: ${s.title} | ${s.venue} | ${s.presentCount} present of ${s.registeredCount} registered.`)]},
            {title:'Session reports',lines:dated.map(s=>`${s.title}: ${s.report}`)},
            {title:'Follow-up actions',lines:funder?['Internal follow-up notes and named attendance registers are excluded.']:dated.map(s=>`${s.title}: ${s.nextSteps||'No next step recorded.'}`)},
          ]:[]),
          {title:'Further evidence to record',lines:PROGRESS_AREAS.filter(a=>a.id!=='other'&&(!category||a.id===category)).map(a=>`${a.title}: ${a.examples} These are possible measures, not reported results.`)},
        ]}/>
      </>}
      {!data.brandingOnly&&tab==='training'&&<>
        {data.canRecord&&<FieldDraft name={`training:${org}`} value={session} onRestore={value=>{setSession(value);setReviewed(false);}} />}
        {data.canRecord&&<button className={styles.primary} disabled={busy||photosBusy} onClick={()=>{setSession({...emptySession(),project,attendance:data.people.map(p=>({...p,present:false})),facilitator:data.sample?(mentor?"Sibusiso Ndlovu":"Nosipho Khumalo"):profile?.full_name??''});setReviewed(false);}}>{ui('Record a training session','Rekhoda isikhathi sokuqeqesha')}</button>}
        {photosBusy&&<p>{ui('Loading session photos…','Kulayishwa izithombe zesikhathi sokuqeqesha…')}</p>}
        {sessions.map(s=><article key={s.id} className={styles.card} style={{marginTop:16}}><h2>{s.title}</h2><p>{s.date} · {s.project} · {s.venue}</p><p>{s.presentCount} {ui('present','bekhona')} / {s.registeredCount} {ui('registered','ababhalisile')} · {s.photoCount} {ui('photographs','izithombe')} · {s.published?ui('Shared with funders','Kwabelwane nabaxhasi'):ui('Internal','Okwangaphakathi')}</p><p>{s.report}</p><button disabled={busy||photosBusy} onClick={()=>void editSession(s)}>{data.canRecord?ui('Open register / edit','Vula irejista / hlela'):ui('Open session report','Vula umbiko wesikhathi')}</button></article>)}
        {session&&<form className={styles.card} style={{marginTop:20}} onSubmit={e=>{e.preventDefault();void save('session');}}>
          <h2>{data.canRecord?ui('Session record & attendance','Irekhodi lesikhathi nababekhona'):ui('Published session report','Umbiko wesikhathi oshicilelwe')}</h2><div className={trainingStyles.summary}>{[[ui('Present','Abakhona'),session.presentCount],...(!funder?[[ui('Signed','Abasayindile'),trainingEvidenceSummary(session).signed],[ui('Certificates','Izitifiketi'),trainingEvidenceSummary(session).certificates]]:[]),[ui('Photographs','Izithombe'),session.photos.length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
          <fieldset disabled={!data.canRecord||busy||photosBusy} style={{minWidth:0}}>
            <div className={styles.grid}>{(['project','title','venue','facilitator'] as const).map(k=><label key={k}>{{project:ui('Project / cohort','Iphrojekthi / iqembu'),title:ui('Session title','Isihloko sesikhathi'),venue:ui('Training venue','Indawo yokuqeqesha'),facilitator:ui('Facilitator','Umqeqeshi')}[k]}<input required maxLength={k==='project'||k==='facilitator'?120:160} value={session[k]} onChange={e=>setS(k,e.target.value)} /></label>)}<label>{ui('Training date','Usuku lokuqeqesha')}<input type="date" required max={today()} value={session.date} onChange={e=>setS('date',e.target.value)}/></label></div>
            {!funder&&<VenueLocation key={session.id} latitude={session.latitude} longitude={session.longitude} sample={data.sample} venue={session.venue} onChange={point=>setSession(s=>s?{...s,...point}:s)} />}
            {!funder&&<><h3>{ui('Attendance register','Irejista yababekhona')}</h3><p>Keep only the people expected at this session on the register, then tick Present for those who attended. Reuse guest codes across sessions so each person counts once.</p><div className={trainingStyles.register}>{session.attendance.map(p=><article key={p.id} className={trainingStyles.person}><div><label className={styles.option}><input type="checkbox" checked={p.present} onChange={e=>{const present=e.target.checked;setSession(s=>s?{...s,attendance:s.attendance.map(a=>a.id===p.id?{...a,present,...(!present?{signature:undefined,certificate:undefined}:{})}:a),feedback:present?s.feedback:s.feedback?.filter(f=>f.participantId!==p.id)}:s);}}/><strong>{p.name}</strong></label><span>{p.present?ui('Present','Ukhona'):ui('Absent','Akekho')} · {p.id.startsWith('guest-')?ui('Guest','Isivakashi'):ui('Enrolled','Obhalisile')}</span><label>{ui('ID / participant reference (optional)','Inombolo kamazisi / yereferensi yomhlanganyeli (akuphoqelekile)')}<input maxLength={80} value={p.reference??''} onChange={e=>setS('attendance',session.attendance.map(a=>a.id===p.id?{...a,reference:e.target.value,signature:undefined}:a))}/></label></div><div>{p.present?<TrainingSignature name={p.name} value={p.signature} onChange={signature=>setS('attendance',session.attendance.map(a=>a.id===p.id?{...a,signature}:a))}/>:<p>{ui('Mark present to sign attendance.','Maka ukuthi ukhona ukuze usayine irejista.')}</p>}</div><div><label>{ui('Certificate reference','Inombolo yesitifiketi')}<input maxLength={80} disabled={!p.present} value={p.certificate??''} placeholder={ui('When issued','Uma sesikhishiwe')} onChange={e=>setS('attendance',session.attendance.map(a=>a.id===p.id?{...a,certificate:e.target.value}:a))}/></label><button type="button" aria-label={ui(`Remove ${p.name} from register`,`Susa u-${p.name} erejisteni`)} onClick={()=>setSession(s=>s?{...s,attendance:s.attendance.filter(a=>a.id!==p.id),feedback:s.feedback?.filter(f=>f.participantId!==p.id)}:s)}>{ui('Remove from register','Susa erejisteni')}</button></div></article>)}</div><label>{ui('Add an enrolled participant','Faka umhlanganyeli obhalisile')}<select value="" onChange={e=>{const p=data.people.find(p=>p.id===e.target.value);if(p)setS('attendance',[...session.attendance,{...p,present:false}]);}}><option value="">{ui('Choose a participant','Khetha umhlanganyeli')}</option>{data.people.filter(p=>!session.attendance.some(a=>a.id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
            <div className={styles.row}><label>Guest code<input value={guestCode} placeholder="same code each visit" onChange={e=>setGuestCode(e.target.value)}/></label><label>Guest name<input value={guestName} maxLength={120} onChange={e=>setGuestName(e.target.value)}/></label><button type="button" onClick={()=>{if(!/^[\w-]{1,90}$/.test(guestCode)||!guestName.trim()){setError('Enter a guest name and a stable code using letters, numbers or dashes.');return;}const id='guest-'+guestCode;if(session.attendance.some(a=>a.id===id)){setError('This guest code is already on the register. Use the existing row.');return;}setS('attendance',[...session.attendance.filter(a=>a.id!==id),{id,name:guestName.trim(),present:true}]);setGuestName('');setGuestCode('');}}>Add guest</button></div>
            <TrainingFeedback key={session.id} session={session} onChange={setSession}/><label>Linked assessment<select value={session.assessmentId} onChange={e=>setS('assessmentId',e.target.value)}><option value="">No assessment linked</option>{data.assessments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{(data.canAssess||data.canAnalyse)&&<p>{session.assessmentId?<a href={`/assessments?assessment=${encodeURIComponent(session.assessmentId)}&org=${encodeURIComponent(org)}`}>Open linked assessment →</a>:<a href={`/assessments?org=${encodeURIComponent(org)}`}>Open assessments →</a>}</p>}</>}
            <label>Mini report · suitable for funders<textarea required maxLength={4000} value={session.report} onChange={e=>setS('report',e.target.value)} placeholder="Topics covered, activities completed and evidence. Leave private participant information out."/></label>
            {!funder&&<label>Internal follow-up<textarea maxLength={2000} value={session.nextSteps} onChange={e=>setS('nextSteps',e.target.value)}/></label>}
            <h3>Training photographs & documents</h3><p>Group, activities, certificates and venue photos belong to this session. Photograph a paper register if signing on the device is impractical.</p><div className={styles.grid}>{session.photos.map((p,i)=><figure key={i}><img data-photo-preview src={p.image} alt={p.caption} style={{width:'100%',maxHeight:220,objectFit:'contain',borderRadius:12}}/>{data.canRecord?<><label>Photo type<select value={p.kind??'venue'} onChange={e=>setS('photos',session.photos.map((p,j)=>j===i?{...p,kind:e.target.value as TrainingPhotoKind,shared:false}:p))}>{Object.entries(TRAINING_PHOTO_KINDS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><input aria-label={`Photo ${i+1} caption`} required maxLength={240} value={p.caption} onChange={e=>setS('photos',session.photos.map((p,j)=>j===i?{...p,caption:e.target.value}:p))}/><label className={styles.option}><input type="checkbox" disabled={p.kind==='register'} checked={p.shared===true} onChange={e=>setS('photos',session.photos.map((p,j)=>j===i?{...p,shared:e.target.checked}:p))}/>{lang==='zu'?statusCopy(p.kind==='register'?'Reviewed for funder sharing · registers stay private':'Reviewed for funder sharing',p.kind==='register'?'Kuhloliwe ukuze kwabelwane nabaxhasi · izithombe zerejista zihlala ziyimfihlo':'Kuhloliwe ukuze kwabelwane nabaxhasi'):<>Reviewed for funder sharing{p.kind==='register'?' · registers stay private':''}</>}</label><button type="button" onClick={()=>setS('photos',session.photos.filter((_,j)=>j!==i))}>Remove photo</button></>:<figcaption>{p.caption}</figcaption>}</figure>)}</div>
            {data.canRecord&&session.photos.length<8&&<div className={styles.grid}><label>Photo category<select value={photoKind} onChange={e=>setPhotoKind(e.target.value as TrainingPhotoKind)}>{Object.entries(TRAINING_PHOTO_KINDS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Take a photograph<input type="file" accept="image/*" capture="environment" onChange={e=>{void addVenuePhotos(e.target.files);e.target.value='';}} /></label><label>Choose photographs (up to eight)<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{void addVenuePhotos(e.target.files);e.target.value='';}} /></label></div>}
            {data.canManage&&<><label className={styles.option}><input type="checkbox" checked={session.published} onChange={e=>setS('published',e.target.checked)}/>{lang==='zu'?statusCopy('Share this session summary and reviewed photos with linked funders','Yabelana ngesifinyezo seseshini nezithombe ezibuyekeziwe nabaxhasi abaxhunyiwe'):'Share this session summary and reviewed photos with linked funders'}</label>{session.published&&<label className={styles.option}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{lang==='zu'?statusCopy('I reviewed the summary and photos for sharing. Attendance names, IDs, signatures, register photos and written feedback stay private.','Ngibuyekeze isifinyezo nezithombe ngaphambi kokwabelana. Amagama ababekhona, omazisi, amasiginesha, izithombe zerejista nempendulo ebhaliwe kuhlala kuyimfihlo.'):'I reviewed the summary and photos for sharing. Attendance names, IDs, signatures, register photos and written feedback stay private.'}</label>}</>}
            {data.canRecord&&<button className={styles.primary} disabled={busy||photosBusy}>Save session</button>}
          </fieldset>
          <button type="button" disabled={busy||photosBusy} onClick={()=>setSession(null)}>Close record</button>
          <p>{data.canRecord?'This preview includes your current edits. Save the session to update project progress reports.':'Published summary; named attendance remains with the organisation.'}</p>
          <ReportComposer deviceData={data} title="Training session report" sample={data.sample} branding={data.branding} photos={session.photos} photosByDefault photoHeading="Training evidence" session={session} funder={funder} sections={[{title:'Session delivery',lines:[session.report]},{title:'Assessment & follow-up',lines:[session.assessmentId?`Linked assessment: ${data.assessments.find(a=>a.id===session.assessmentId)?.title??'Course assessment'}`:'Feedback is recorded with this session.',...(funder?[]:[session.nextSteps||'No follow-up recorded.'])]}]}/>
        </form>}
      </>}
      {!data.brandingOnly&&tab==='targets'&&<>
        <p>Record production, water, land, livelihoods and other agreed indicators. Enter the total or reading on each date; repeated observations are not added together. Leave an unknown baseline or unagreed target blank.</p>
        {data.canManage&&<button onClick={()=>addIndicator()}>{ui('Add a project indicator','Faka inkomba yephrojekthi')}</button>}
        {targets.map(m=><article key={m.id} className={styles.card} style={{marginTop:16}}><h2>{m.title}</h2><p>{PROGRESS_AREAS.find(a=>a.id===progressArea(m))!.title} · {m.target===null?ui('Target not yet agreed','Umnqopho awukavunyelwana'):ui(`Target ${progressValue(m.target,m.unit)}`,`Umnqopho ${progressValue(m.target,m.unit)}`)} · {ui('due / review','umnqamulajuqu / ukubuyekeza')} {m.due}</p><p>{m.method}</p>{data.canManage&&<button onClick={()=>{setTarget(m);setObservation({date:today(),actual:'',evidence:''});}}>{ui('Update indicator / record progress','Buyekeza inkomba / rekhoda inqubekelaphambili')}</button>}</article>)}
        {target&&data.canManage&&<form className={styles.card} style={{marginTop:20}} onSubmit={e=>{e.preventDefault();void save('milestone');}}><fieldset disabled={busy} style={{minWidth:0}}><h2>{ui('Indicator and measurement','Inkomba nesilinganiso')}</h2>
          {!target.updatedAt&&<label>{ui('Start with a suggested measure','Qala ngesilinganiso esiphakanyisiwe')}<select value="" onChange={e=>{const template=PROGRESS_TEMPLATES.find(t=>t.id===e.target.value);if(template)setTarget({...target,category:template.category,title:template.title,unit:template.unit,method:template.method});}}><option value="">{ui('Choose a measure, or write your own','Khetha isilinganiso noma uzibhalele esakho')}</option>{PROGRESS_AREAS.map(area=><optgroup key={area.id} label={area.title}>{PROGRESS_TEMPLATES.filter(t=>t.category===area.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</optgroup>)}</select></label>}
          <label>{ui('Area of work','Indawo yomsebenzi')}<select value={progressArea(target)} onChange={e=>setM('category',e.target.value)}>{PROGRESS_AREAS.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>
          <div className={styles.grid}>{(['project','title','unit','owner'] as const).map(k=><label key={k}>{{project:ui('Project','Iphrojekthi'),title:ui('Indicator','Inkomba'),unit:ui('Unit','Iyunithi'),owner:ui('Responsible person','Umuntu onesibopho')}[k]}<input required value={target[k]} onChange={e=>setM(k,e.target.value)}/></label>)}<label>{ui('Baseline (leave blank if unknown)','Inani lokuqala (shiya kungenalutho uma lingaziwa)')}<input type="number" min="0" step="any" value={target.baseline??''} onChange={e=>setM('baseline',e.target.value===''?null:+e.target.value)}/></label><label>{ui('Target (optional)','Umnqopho (akuphoqelekile)')}<input type="number" min="0.001" step="any" value={target.target??''} onChange={e=>setM('target',e.target.value===''?null:+e.target.value)}/></label><label>{ui('Target / review date','Usuku lomnqopho / lokubuyekeza')}<input required type="date" value={target.due} onChange={e=>setM('due',e.target.value)}/></label></div><label>{ui('Definition, source, reporting period and measurement frequency','Incazelo, umthombo, isikhathi sokubika nobuningi bezilinganiso')}<textarea required maxLength={1000} value={target.method} onChange={e=>setM('method',e.target.value)}/></label>
          <h3>{ui('Dated observations','Okubhekwe ngezinsuku')}</h3>{target.observations.map(o=><p key={o.date}>{o.date} · {o.actual} {target.unit} · {o.evidence}</p>)}<div className={styles.grid}><label>{ui('Observation date','Usuku lokubheka')}<input type="date" max={today()} value={observation.date} onChange={e=>setObservation({...observation,date:e.target.value})}/></label><label>{ui('Total or reading on this date','Isamba noma isilinganiso salolu suku')}<input type="number" min="0" step="any" value={observation.actual} onChange={e=>setObservation({...observation,actual:e.target.value})}/></label></div><label>{ui('Evidence / record reference','Ubufakazi / inombolo yerekhodi')}<textarea maxLength={1500} value={observation.evidence} onChange={e=>setObservation({...observation,evidence:e.target.value})}/></label><button type="button" onClick={()=>{if(!observation.actual.trim()||!observation.evidence.trim()){setError('Enter an observed total and evidence reference.');return;}setM('observations',[...target.observations.filter(o=>o.date!==observation.date),{...observation,actual:+observation.actual,recordedAt:new Date().toISOString()}]);setObservation({date:today(),actual:'',evidence:''});}}>{ui('Add / replace dated observation','Faka / shintsha okubhekwe ngosuku')}</button>
          <label className={styles.option}><input type="checkbox" checked={target.published} onChange={e=>setM('published',e.target.checked)}/>{ui('Share this indicator and its evidence notes with linked funders','Yabelana ngale nkomba namanothi ayo obufakazi nabaxhasi abaxhunyiwe')}</label><button className={styles.primary}>{ui('Save indicator','Londoloza inkomba')}</button><button type="button" onClick={()=>setTarget(null)}>{ui('Cancel','Khansela')}</button></fieldset></form>}
      </>}
      {(tab==='branding'||data.brandingOnly)&&data.canBrand&&<div className={styles.card}><h2>{ui('Organisation, garden & funder identity','Ubunikazi benhlangano, bengadi nobomxhasi')}</h2><p>These are the default partner identities for this organisation’s programme reports. Use a programme-wide community name when several gardens are included. Upload logos you are authorised to use.</p><div className={styles.grid}>{(['organisation','garden','funder'] as const).map(key=><div key={key}><h3>{key==='organisation'?ui('Implementing organisation','Inhlangano eqhuba uhlelo'):key==='garden'?ui('Community garden / project','Ingadi yomphakathi / iphrojekthi'):ui('Funding partner','Uzakwethu oxhasa ngemali')}</h3>{data.branding[key].image&&<img src={data.branding[key].image} alt={`${key} logo`} style={{width:120,height:90,objectFit:'contain'}}/>}<label>{ui('Display name','Igama eliboniswayo')}<input maxLength={120} value={data.branding[key].label} onChange={e=>setData({...data,branding:{...data.branding,[key]:{...data.branding[key],label:e.target.value}}})}/></label><label>{ui('Upload logo','Layisha ilogo')}<input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void logoUpload(key,e.target.files?.[0])}/></label><button onClick={()=>setData({...data,branding:{...data.branding,[key]:{...data.branding[key],image:''}}})}>{ui('Remove logo','Susa ilogo')}</button></div>)}</div><button className={styles.primary} disabled={busy} onClick={()=>void save('branding')}>{ui('Save names & logos','Londoloza amagama namalogo')}</button><ReportComposer deviceData={data} title="Branded report preview" sample={data.sample} branding={data.branding} sections={[{title:'Programme identity',lines:['The saved names and logos are used on training and progress reports.']}]} /></div>}
    </>}
  </div></section>;
}
