// GENERATED by scripts/build-animal-enterprises.mjs from research/animal-sources/*.json.
// Do not edit by hand: correct the dossier and re-run the script. See lib/animal-enterprises.ts.

import type { AnimalEnterprise } from './animal-enterprises';

export const ANIMAL_ENTERPRISE_DATA: Record<string, AnimalEnterprise> = {
  "bees": {
    "enterpriseId": "bees",
    "name": "Honeybee (managed hives)",
    "animal": "bee",
    "animalUnit": "hive",
    "product": "honey",
    "outputUnit": "kg honey/hive/year",
    "outputPerAnimal": {
      "value": [
        25,
        25
      ],
      "source": {
        "quote": "The national average honey yield of in the region of 25 kilograms of honey per hive per year in Table 7 is un-weighted across beekeepers.",
        "url": "https://open.uct.ac.za/bitstreams/5d2ecb2c-3a9d-4560-aa17-b4774df6b5e2/download",
        "doc": "Survey of Beekeeping in South Africa, CSSR Working Paper No. 221 (Conradie & Nortje, 2008, UCT Centre for Social Science Research)",
        "page": 14
      },
      "note": "From a 2008 national postal survey of 112 SABIO-member beekeepers (22.4% response rate) managing an estimated 19,520 hives at 2,094 apiary sites; figure is self-reported and un-weighted. Table 7 (same doc, p.13-14) shows wide variance by region/operation-focus/size for the same year: e.g. 'All' region, honey-focused, all-size operations = 25.1-26.9 kg/hive/yr across 3 survey sites; Western Cape honey-focused = 23.6-27.9 kg/hive/yr; Western Cape pollination-focused, small operations = only 7.0-7.5 kg/hive/yr. The same document also quotes an earlier, more rigorously validated study: 'Their average reported yield is very low, at just 13.4 kilograms per hive' for Western Cape hives (Allsopp & Cherry 2004, cited p.2 of this working paper), and historical national bee-census data of 8.3 kg/hive/annum (1911-1988 average) rising to 24 kg/hive in the 1974/5 census (same doc, p.1). No single number can be called definitive; 25 kg/hive/yr is used as the document's own headline national estimate."
    },
    "windows": [],
    "seasonalPattern": null,
    "weeksToFirstProduct": null,
    "productiveLifeYears": null,
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": null,
    "welfare": [
      {
        "point": "Inspect every colony regularly for signs of notifiable bee disease and Cape-bee (Capensis) infection.",
        "source": {
          "quote": "Every beekeeper shall conduct regular inspections of every colony kept in beehives at each apiary site to detect- (a)clinical symptoms of notifiable bee diseases; or (b)Capensis-infected colonies.",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, Government Notice No. R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 5
        }
      },
      {
        "point": "Site and secure hives against theft and vandalism, which is one of the biggest challenges facing South African beekeepers.",
        "source": {
          "quote": "One of the big challenges for beekeepers in South Africa is that their hives are damaged and/or stolen.",
          "url": "https://www.sanbi.org/wp-content/uploads/2018/05/gumsbees-web-version-hyperlinks.pdf",
          "doc": "Gums & Bees: A roadmap for landowners in South Africa (South African National Biodiversity Institute, SANBI)",
          "page": 21
        }
      }
    ],
    "legal": [
      {
        "point": "Every beekeeper (commercial or hobbyist) must register with the national Department between 1 January and 31 March each year.",
        "source": {
          "quote": "Every beekeeper shall register with the Department between 1 January and 31 March of each year.",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 3
        }
      },
      {
        "point": "A beekeeper who fails to re-register annually is automatically deregistered.",
        "source": {
          "quote": "In the case of failure to comply with control measure 2 (1), a registered beekeeper shall be deregistered.",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 4
        }
      },
      {
        "point": "Every beehive must be clearly and legibly marked with the beekeeper's registration number.",
        "source": {
          "quote": "Every beekeeper must mark his beehives to display clearly and legibly the registration number allocated to him in terms of control measure 2 (3).",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 4
        }
      },
      {
        "point": "Keep written records of how many colonies you keep, where each apiary is, and any disease found.",
        "source": {
          "quote": "Every beekeeper shall, during the period of registration, keep written records of the- (a)number of colonies kept; (b)location of every apiary; (c)presence of any notifiable or other disease in the apiaries kept by the beekeeper;",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 4
        }
      },
      {
        "point": "Do not move honeybees across the Cape bee line, or keep Cape bees north of it, without written approval.",
        "source": {
          "quote": "No person may- (a)remove honey-bees across the line; ... (b)remove or keep Cape bees north of the line; (c)remove any Capensis-infected colony, without the prior written approval of executive officer.",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015)",
          "page": 5
        }
      },
      {
        "point": "Report any suspected notifiable disease (American foulbrood is listed); officials can order an infected colony destroyed.",
        "source": {
          "quote": "Every beekeeper shall notify the executive officer or area official of the presence or suspected presence of any notifiable disease or Capensis-infected colony ... instruct a beekeeper to destroy a colony, beehive or bee product.",
          "url": "https://faolex.fao.org/docs/pdf/saf128823.pdf",
          "doc": "Agricultural Pests Act, 1983 (Act No. 36 of 1983) - Control Measures Relating to Honey-bees, GN R.858 of 15 November 2013 (Government Gazette No. 37015), Annexure A: List of Notifiable Diseases",
          "page": 8
        }
      }
    ]
  },
  "duck": {
    "enterpriseId": "duck",
    "name": "Meat duck (Pekin / Muscovy, backyard)",
    "animal": "duck",
    "animalUnit": "bird",
    "product": "meat",
    "outputUnit": "kg live weight/bird at slaughter",
    "outputPerAnimal": {
      "value": [
        2.29,
        2.93
      ],
      "source": {
        "quote": "Steklenev (1990) reported live weight at slaughter at 8-10 weeks for the Pekin and Muscovy to be 2.93 and 2.29 kg respectively.",
        "url": "https://www.lrrd.org/lrrd18/11/solo18154.htm",
        "doc": "Livestock Research for Rural Development 18(11) 2006 - Solomon et al. (Guyana; not an SA figure), citing Steklenev 1990",
        "page": null
      },
      "note": "Non-SA (Guyana study reporting a citation to Steklenev 1990); no SA-specific absolute slaughter live-weight figure was found (see gaps). 2.93 kg = Pekin at 8-10 weeks, 2.29 kg = Muscovy at 8-10 weeks - matches this enterprise's two breeds. The same LRRD paper's own experiment (Table 2, intensive system, Guyana) measured live weight at slaughter (8 weeks) as: Pekin drakes 2.53 kg, Pekin hens 2.29 kg, Muscovy drakes 2.47 kg, Muscovy hens 1.51 kg - broadly consistent with, but not merged into, the cited range above since it is a separate dataset/table in the same source. No sourced eggs/duck/year figure was found for either breed (see gaps); the LRRD and SAJAS sources used here studied ducks reared only for meat."
    },
    "windows": [],
    "seasonalPattern": null,
    "weeksToFirstProduct": {
      "value": [
        7,
        12
      ],
      "source": {
        "quote": "P44 ducks and drakes were kept until 7 weeks of age, whereas the MR71 ducks until 10 weeks of age, and MR71 drakes until 12 weeks of age.",
        "url": "https://www.scielo.org.za/scielo.php?script=sci_arttext&pid=S0375-15892014000200001",
        "doc": "South African Journal of Animal Science 44(2): Effect of production system and slaughter age on meat quality of ducks",
        "page": null
      },
      "note": "P44 = Pekin (7 weeks to slaughter); MR71 = Muscovy (10 weeks for ducks/hens, 12 weeks for drakes). Treated as 'time to first product' = age to slaughter, since this is a single-cycle meat enterprise (no repeat product like eggs). South Africa-specific (SAJAS)."
    },
    "productiveLifeYears": null,
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": {
      "value": [
        12.5,
        12.5
      ],
      "source": {
        "quote": "birds were kept according to the guidelines for intensive production system on deep litter and at a stocking density of 2.9 bird/m 2 . Thereafter, half the ducks and drakes of each genetic group was allowed to use free ranges, at a stock density of 0.08 bird/m 2 (outdoor system - OS).",
        "url": "https://www.scielo.org.za/scielo.php?script=sci_arttext&pid=S0375-15892014000200001",
        "doc": "South African Journal of Animal Science 44(2): Effect of production system and slaughter age on meat quality of ducks",
        "page": null
      },
      "note": "0.08 bird/m2 (outdoor/free-range system) = 1/0.08 = 12.5 m2/bird - used here as the primary figure since smallholder/backyard duck-keeping is closer to this free-range system than to intensive deep-litter housing. The same source's INTENSIVE deep-litter system gives 2.9 bird/m2 = 1/2.9 = 0.34 m2/bird (a very different, much more confined figure) - noted here for context but NOT merged into the range above, per the instruction not to mix figures from different systems. South Africa-specific (SAJAS)."
    },
    "welfare": [
      {
        "point": "It is an offence to deny a duck food or water, or keep it somewhere lacking adequate space, ventilation, light or shelter from heat and cold.",
        "source": {
          "quote": "confines, chains, tethers or secures any animal unnecessarily or under such conditions or in such a manner or position as to cause that animal unnecessary suffering or in any place which affords inadequate space, ventilation, light, protection or shelter from heat, cold or weather ... unnecessarily starves ... or denies water or food to any animal",
          "url": "https://cer.org.za/wp-content/uploads/2019/11/Animals-Protection-Act-No.-71-of-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962 (consolidated text, s.2(1)(b)-(c))",
          "page": 2
        }
      },
      {
        "point": "Watch flocks for sudden deaths, ruffled feathers, swollen wattles/combs or a sudden drop in egg production - these are signs of avian influenza and should be reported at once.",
        "source": {
          "quote": "The disease may cause a large number (up to 100%) of sudden deaths in a flock. ... sudden drop in production of eggs ... wattles and combs become swollen and congested",
          "url": "https://www.westerncape.gov.za/agriculture/files/wcg-blob-files?file=2024-07%2Favian-infl_0.pdf&type=file",
          "doc": "Western Cape Department of Agriculture, Avian Influenza (Bird Flu) factsheet",
          "page": 2
        }
      },
      {
        "point": "Keep ducks away from wild birds and open water/feed that attracts them, and control visitors' access to duck housing, to reduce avian-influenza risk.",
        "source": {
          "quote": "Keep poultry away from areas frequented by wild fowl ... Keep control over access to poultry houses by people and equipment",
          "url": "https://www.westerncape.gov.za/agriculture/files/wcg-blob-files?file=2024-07%2Favian-infl_0.pdf&type=file",
          "doc": "Western Cape Department of Agriculture, Avian Influenza (Bird Flu) factsheet",
          "page": 2
        }
      }
    ],
    "legal": [
      {
        "point": "Ducks are one of the domesticated animal species listed in the Meat Safety Act, so its rules on registered abattoirs and hygiene apply to them.",
        "source": {
          "quote": "Donkey Duck Farmed deer Fowl",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, Schedule 1 (Animals to which this Act applies)",
          "page": 16
        }
      },
      {
        "point": "Ducks slaughtered to be sold must be slaughtered at a registered abattoir; slaughter for the farmer's own consumption is exempt but that meat may not be sold.",
        "source": {
          "quote": "slaughter any animal at any place other than an abattoir; ... (2) (a) Subsection (1) does not apply to slaughter for own consumption or for cultural or religious purposes.",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.7",
          "page": 6
        }
      },
      {
        "point": "At the abattoir, ducks must be handled humanely during loading, transport, offloading, housing, immobilising and killing, under the Animals Protection Act.",
        "source": {
          "quote": "an animal presented for slaughter at an abattoir must be handled humanely during loading, transportation, off-loading, housing, immobilizing and killing as prescribed in accordance with the requirements of the Animals Protection Act, 1962 (Act No. 71 of 1962)",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.9",
          "page": 7
        }
      },
      {
        "point": "Ducks are birds/poultry, so an outbreak of avian influenza in a duck flock is a controlled animal disease under the Animal Diseases Act and must be reported to the state vet immediately.",
        "source": {
          "quote": "It is also a controlled animal disease listed under the Animal Diseases Act, 1984 (Act No. 35 of 1984).",
          "url": "https://www.westerncape.gov.za/agriculture/files/wcg-blob-files?file=2024-07%2Favian-infl_0.pdf&type=file",
          "doc": "Western Cape Department of Agriculture, Avian Influenza (Bird Flu) factsheet",
          "page": 2
        }
      }
    ]
  },
  "goat-dairy": {
    "enterpriseId": "goat-dairy",
    "name": "Dairy goat (Saanen / Toggenburg / British Alpine)",
    "animal": "goat",
    "animalUnit": "doe",
    "product": "milk",
    "outputUnit": "kg milk/doe/305-day lactation",
    "outputPerAnimal": {
      "value": [
        775.4,
        1073.4
      ],
      "source": {
        "quote": "Third parity dams gave the highest lactation yields (1073.4 ± 40.0 kg, 40.6 ± 1.6 kg, 31.3 ± 1.4 kg, and 46.7 ± 1.9 kg for MY, FY, PY, and LY, respectively), whereas lowest lactation yields for these traits were estimated in the > 7th parity group (775.4 ± 56.6, 29.5 ± 2.3, 20.6 ± 2.0, and 33.0 ± 2.9 kg for MY, FY, PY, and LY, respectively).",
        "url": "https://www.scielo.org.za/scielo.php?pid=S0375-15892024000500009&script=sci_arttext&tlng=en",
        "doc": "Malemela, M.J., Nemutandani, K.R. & Tada, O. (2024). Non-genetic sources of variation influencing yield and composition of milk production parameters in South African Saanen goats. S. Afr. J. Anim. Sci. 54(5):620-630",
        "page": null
      },
      "note": "Lowest (>7th parity) and highest (3rd parity) parity-group means for milk yield per 305-day standardised lactation, 16 407 ARC milk-recording lactations of SA Saanen goats, 1955-2018, mostly intensive/semi-intensive stud herds. Kept in kg as the source gives it."
    },
    "windows": [],
    "seasonalPattern": {
      "text": "Milk yield and lactose yield are significantly affected by season of kidding, with does that kid in spring giving the highest lactation milk yields; breeders are advised to plan mating for spring kidding.",
      "source": {
        "quote": "There was a substantial variation due to dam kidding season in all parameters except protein yield and urea concentration, with dams kidding in spring attaining the highest average lactation milk and lactose yields. ... For optimal lactation performance, planned breeding should be applied for spring kidding.",
        "url": "https://www.scielo.org.za/scielo.php?pid=S0375-15892024000500009&script=sci_arttext&tlng=en",
        "doc": "Malemela, M.J., Nemutandani, K.R. & Tada, O. (2024). Non-genetic sources of variation influencing yield and composition of milk production parameters in South African Saanen goats. S. Afr. J. Anim. Sci. 54(5):620-630",
        "page": null
      }
    },
    "weeksToFirstProduct": null,
    "productiveLifeYears": null,
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": null,
    "welfare": [
      {
        "point": "It is an offence to keep a goat somewhere with inadequate space, ventilation, light or shelter from heat, cold or weather, or to confine/tether it in a way that causes unnecessary suffering.",
        "source": {
          "quote": "confines, chains, tethers or secures any animal unnecessarily or under such conditions or in such a manner or position as to cause that animal unnecessary suffering or in any place which affords inadequate space, ventilation, light, protection or shelter from heat, cold or weather",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(b)",
          "page": 1
        }
      },
      {
        "point": "It is an offence to starve, under-feed, or deny water or food to a goat.",
        "source": {
          "quote": "unnecessarily starves or under-feeds or denies water or food to any animal",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(c)",
          "page": 1
        }
      },
      {
        "point": "An owner must not let a goat stay in a dirty or parasite-infested condition, and must get veterinary or other treatment for a sick, injured or diseased animal when able to.",
        "source": {
          "quote": "being the owner of any animal, deliberately or negligently keeps such animal in a dirty or parasitic condition or allows it to become infested with external parasites or fails to render or procure veterinary or other medical treatment or attention which he is able to render or procure for any such animal in need of such treatment or attention",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(e)",
          "page": 1
        }
      }
    ],
    "legal": [
      {
        "point": "Foot-and-mouth disease (FMD) is a controlled animal disease under the Animal Diseases Act: veterinary services enforce isolation and movement restrictions, and a suspected case must be reported.",
        "source": {
          "quote": "FMD is classified as a controlled animal disease under the Animal Diseases Act, 1984 (Act No. 35 of 1984), which mandates specific control measures, such as isolation and movement restrictions, enforced by Veterinary Services.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Inside a declared FMD-affected zone, goats and their products (including milk) cannot be moved into, out of, or within the zone without a state veterinary movement permit and compliance with its conditions.",
        "source": {
          "quote": "No cloven-hoofed animals, their products, or genetic material may be moved from, to, or within the DMA unless authorised by a state veterinary permit and in full compliance with the stipulated conditions of such [a] permit.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Every goat owner must register an official identification mark and mark their goats with it, under the Animal Identification Act.",
        "source": {
          "quote": "Each owner of animals must- (a) apply for registration of an identification mark in terms of section 5 (1); (b) mark his or her animals in the prescribed manner",
          "url": "https://www.kzndard.gov.za/images/Documents/AnimalHealth/VeterinaryActs/Act-No.-6-of-2002.pdf",
          "doc": "Animal Identification Act 6 of 2002, s.7(1)",
          "page": 4
        }
      },
      {
        "point": "A goat may only be slaughtered for sale at a registered abattoir under the Meat Safety Act (relevant when culled dairy does or male kids are sold for meat); slaughtering for the farmer's own consumption, or for cultural/religious purposes, is exempt but that meat may not then be sold.",
        "source": {
          "quote": "Subsection (1) does not apply to slaughter for own consumption or for cultural or religious purposes.",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.7(2)(a)",
          "page": 6
        }
      }
    ]
  },
  "goat-indigenous": {
    "enterpriseId": "goat-indigenous",
    "name": "Indigenous veld / communal goat (e.g. Nguni, Tankwa, Xhosa lob-ear)",
    "animal": "goat",
    "animalUnit": "doe",
    "product": "meat",
    "outputUnit": "kids weaned/doe/year",
    "outputPerAnimal": null,
    "windows": [],
    "seasonalPattern": {
      "text": "Breeding is not controlled and happens all year, but in one Mpumalanga communal study kidding rates were highest in autumn (96%) and spring (93%), lower in winter (63%) and nil in summer.",
      "source": {
        "quote": "Breeding is not controlled and occurs all year round, which creates managerial problems. ... the highest kidding rates were attained in autumn (96%), followed by spring (93%), winter (63%) and summer (0%)",
        "url": "https://scielo.org.za/scielo.php?script=sci_arttext&pid=S0375-15892004000500070&lng=pt&nrm=iso",
        "doc": "Webb, E.C. & Mamabolo, M.J. (2004). Production and reproduction characteristics of South African indigenous goats in communal farming systems. S. Afr. J. Anim. Sci. 34(5):236-239",
        "page": null
      }
    },
    "weeksToFirstProduct": {
      "value": [
        69.6,
        78.3
      ],
      "source": {
        "quote": "the indigenous goats in Mpumalanga are early breeders, reaching puberty at 6 to 7 months of age. The age at first kidding varied between 16 to 18 months of age",
        "url": "https://scielo.org.za/scielo.php?script=sci_arttext&pid=S0375-15892004000500070&lng=pt&nrm=iso",
        "doc": "Webb, E.C. & Mamabolo, M.J. (2004). Production and reproduction characteristics of South African indigenous goats in communal farming systems. S. Afr. J. Anim. Sci. 34(5):236-239",
        "page": null
      },
      "note": "This is age at first KIDDING (birth of first kids), not first weaned kids. 16 months x 4.35 = 69.6 weeks; 18 months x 4.35 = 78.3 weeks, from doe birth to her giving birth for the first time. Adding the source's own ~150-day (~5-month, ~21.75-week) weaning assumption would put first WEANED kids at roughly 91-100 weeks of doe age, but that compound figure is not shown as the primary value since the field is documented as 'age/time from start (hatch, birth) to first product' and first kidding is the clearer, directly-stated milestone; the weaning offset is noted here for transparency."
    },
    "productiveLifeYears": null,
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": null,
    "welfare": [
      {
        "point": "It is an offence to keep a goat somewhere with inadequate space, ventilation, light or shelter from heat, cold or weather, or to confine/tether it in a way that causes unnecessary suffering.",
        "source": {
          "quote": "confines, chains, tethers or secures any animal unnecessarily or under such conditions or in such a manner or position as to cause that animal unnecessary suffering or in any place which affords inadequate space, ventilation, light, protection or shelter from heat, cold or weather",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(b)",
          "page": 1
        }
      },
      {
        "point": "It is an offence to starve, under-feed, or deny water or food to a goat.",
        "source": {
          "quote": "unnecessarily starves or under-feeds or denies water or food to any animal",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(c)",
          "page": 1
        }
      },
      {
        "point": "An owner must not let a goat stay in a dirty or parasite-infested condition, and must get veterinary or other treatment for a sick, injured or diseased animal when able to.",
        "source": {
          "quote": "being the owner of any animal, deliberately or negligently keeps such animal in a dirty or parasitic condition or allows it to become infested with external parasites or fails to render or procure veterinary or other medical treatment or attention which he is able to render or procure for any such animal in need of such treatment or attention",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(e)",
          "page": 1
        }
      },
      {
        "point": "Winter feed shortage on communal sourveld is a known welfare/production risk: does that kid in autumn must feed kids through winter, and does that kid in spring suffer poor nutrition during late pregnancy, so winter feed supplementation matters.",
        "source": {
          "quote": "Winter nutrition is thus a definite constraint to goat production in the sourveld areas. The time of kidding exacerbates the problem since the majority of ewes kid either in spring or in autumn. Those kidding in autumn must feed their lambs through winter while those kidding in spring suffer from poor nutrition during late gestation",
          "url": "https://www.kzndard.gov.za/images/Documents/RESOURCE_CENTRE/GUIDELINE_DOCUMENTS/RESEARCH_REPORTS/Constraints%20to%20Small-scale%20Goat%20Production%20in%20KZN.pdf",
          "doc": "Letty, B. & Madiba, S., KZN DARD. Constraints to Small-Scale Goat Production in the Highland Sourveld Area of KwaZulu-Natal",
          "page": 3
        }
      }
    ],
    "legal": [
      {
        "point": "Foot-and-mouth disease (FMD) is a controlled animal disease under the Animal Diseases Act: veterinary services enforce isolation and movement restrictions, and a suspected case must be reported.",
        "source": {
          "quote": "FMD is classified as a controlled animal disease under the Animal Diseases Act, 1984 (Act No. 35 of 1984), which mandates specific control measures, such as isolation and movement restrictions, enforced by Veterinary Services.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Inside a declared FMD-affected zone, goats and their products cannot be moved into, out of, or within the zone without a state veterinary movement permit and compliance with its conditions.",
        "source": {
          "quote": "No cloven-hoofed animals, their products, or genetic material may be moved from, to, or within the DMA unless authorised by a state veterinary permit and in full compliance with the stipulated conditions of such [a] permit.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Every goat owner, including communal/smallholder owners, must register an official identification mark and mark their goats with it, under the Animal Identification Act.",
        "source": {
          "quote": "Each owner of animals must- (a) apply for registration of an identification mark in terms of section 5 (1); (b) mark his or her animals in the prescribed manner",
          "url": "https://www.kzndard.gov.za/images/Documents/AnimalHealth/VeterinaryActs/Act-No.-6-of-2002.pdf",
          "doc": "Animal Identification Act 6 of 2002, s.7(1)",
          "page": 4
        }
      },
      {
        "point": "A goat may only be slaughtered for sale at a registered abattoir under the Meat Safety Act; slaughtering it for the farmer's own consumption, or for cultural/religious purposes (including ceremonial slaughter, common with indigenous goats), is exempt from that rule, but that meat may not then be sold.",
        "source": {
          "quote": "Subsection (1) does not apply to slaughter for own consumption or for cultural or religious purposes.",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.7(2)(a)",
          "page": 6
        }
      }
    ]
  },
  "goat-meat": {
    "enterpriseId": "goat-meat",
    "name": "Boer goat (meat enterprise)",
    "animal": "goat",
    "animalUnit": "doe",
    "product": "meat",
    "outputUnit": "kids weaned/doe/year",
    "outputPerAnimal": {
      "value": [
        1.49,
        1.49
      ],
      "source": {
        "quote": "According to the National Department of Agriculture, Boer goat females under extensive conditions with a precipitation of 295 mm, have an average conception rate of 90%, kidding rate of 187%, fecundity (kids born/does kidded) of 210%, and weaning rate (kids weaned/doe mated) of 149% over a twenty year period (Malan, 2000).",
        "url": "https://scholar.ufs.ac.za/server/api/core/bitstreams/46b48d9c-608a-40b2-bcbd-c429533189ef/content",
        "doc": "King, F.J.M. (2009). Production Parameters for Boer Goats in South Africa (MSc dissertation, University of the Free State), citing National Dept of Agriculture data via Malan, S.W. (2000)",
        "page": null
      },
      "note": "Weaning rate (kids weaned/doe mated) of 149% = 1.49 kids weaned per doe per year. This is a 20-year national average for Boer does under EXTENSIVE conditions at 295 mm rainfall (low-rainfall/arid veld), not a feedlot or high-input system. The same source (Casey & Van Niekerk, 1988, quoted a few sentences later) separately reports mean litter SIZE (kids born per parturition, not per year) of 1.93 for Boer does - not merged into this per-year figure since it measures a different thing. A South Africa-wide extensive-system kidding percentage of 180% (not weaning rate) is corroborated independently in a different source (see gaps/seasonalPattern sourcing), which is consistent with the 187% kidding rate reported here."
    },
    "windows": [],
    "seasonalPattern": null,
    "weeksToFirstProduct": null,
    "productiveLifeYears": null,
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": null,
    "welfare": [
      {
        "point": "It is an offence to keep a goat somewhere with inadequate space, ventilation, light or shelter from heat, cold or weather, or to confine/tether it in a way that causes unnecessary suffering.",
        "source": {
          "quote": "confines, chains, tethers or secures any animal unnecessarily or under such conditions or in such a manner or position as to cause that animal unnecessary suffering or in any place which affords inadequate space, ventilation, light, protection or shelter from heat, cold or weather",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(b)",
          "page": 1
        }
      },
      {
        "point": "It is an offence to starve, under-feed, or deny water or food to a goat.",
        "source": {
          "quote": "unnecessarily starves or under-feeds or denies water or food to any animal",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(c)",
          "page": 1
        }
      },
      {
        "point": "An owner must not let a goat stay in a dirty or parasite-infested condition, and must get veterinary or other treatment for a sick, injured or diseased animal when able to.",
        "source": {
          "quote": "being the owner of any animal, deliberately or negligently keeps such animal in a dirty or parasitic condition or allows it to become infested with external parasites or fails to render or procure veterinary or other medical treatment or attention which he is able to render or procure for any such animal in need of such treatment or attention",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201505/act-71-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962, s.2(1)(e)",
          "page": 1
        }
      }
    ],
    "legal": [
      {
        "point": "Foot-and-mouth disease (FMD) is a controlled animal disease under the Animal Diseases Act: veterinary services enforce isolation and movement restrictions, and a suspected case must be reported.",
        "source": {
          "quote": "FMD is classified as a controlled animal disease under the Animal Diseases Act, 1984 (Act No. 35 of 1984), which mandates specific control measures, such as isolation and movement restrictions, enforced by Veterinary Services.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Inside a declared FMD-affected zone, goats and their products cannot be moved into, out of, or within the zone without a state veterinary movement permit and compliance with its conditions.",
        "source": {
          "quote": "No cloven-hoofed animals, their products, or genetic material may be moved from, to, or within the DMA unless authorised by a state veterinary permit and in full compliance with the stipulated conditions of such [a] permit.",
          "url": "https://www.sanews.gov.za/south-africa/kzn-foot-and-mouth-disease-boundaries-extended",
          "doc": "SAnews: KZN Foot and Mouth Disease boundaries extended (Dept of Agriculture statement)",
          "page": null
        }
      },
      {
        "point": "Every goat owner must register an official identification mark and mark their goats with it, under the Animal Identification Act.",
        "source": {
          "quote": "Each owner of animals must- (a) apply for registration of an identification mark in terms of section 5 (1); (b) mark his or her animals in the prescribed manner",
          "url": "https://www.kzndard.gov.za/images/Documents/AnimalHealth/VeterinaryActs/Act-No.-6-of-2002.pdf",
          "doc": "Animal Identification Act 6 of 2002, s.7(1)",
          "page": 4
        }
      },
      {
        "point": "A goat may only be slaughtered for sale at a registered abattoir under the Meat Safety Act; slaughtering it for the farmer's own consumption, or for cultural/religious purposes, is exempt from that rule, but that meat may not then be sold.",
        "source": {
          "quote": "Subsection (1) does not apply to slaughter for own consumption or for cultural or religious purposes.",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.7(2)(a)",
          "page": 6
        }
      }
    ]
  },
  "rabbit": {
    "enterpriseId": "rabbit",
    "name": "Meat rabbit (New Zealand White / Californian, backyard hutches)",
    "animal": "rabbit",
    "animalUnit": "doe",
    "product": "meat",
    "outputUnit": "kits weaned/doe/year",
    "outputPerAnimal": {
      "value": [
        30,
        35
      ],
      "source": {
        "quote": "For backyard rabbitries, it is as- sumed that weaning takes place at 42 days, servicing at 24 days after kindling, and the average conception rate is 70 percent. This gives an average of six litters per doe per year. ... If an average six young per litter are weaned and 5.5 reach slaughter or reproduction age, the objective is then 30 rabbits per doe annually. This modest goal is realistic for back- yard rabbitries not based exclusively on pelleted feed. ... This would give an additional litter per doe, raising the annual goal to 35 rabbits per doe.",
        "url": "https://www.fao.org/4/t1690e/t1690e.pdf",
        "doc": "FAO Animal Production and Health Series No.21 - The Rabbit: Husbandry, Health and Production (Lebas et al.)",
        "page": 107
      },
      "note": "FAO (general, not SA-specific). Figure is explicitly for 'backyard rabbitries not based exclusively on pelleted feed' (extensive/semi-intensive, not industrial). 30 = number of young reaching slaughter/reproduction age per doe/year at the base backyard rate (6 young weaned x 5.5 litters, allowing for post-weaning loss); 35 = same backyard system but with an extra litter gained by remating 7 days earlier (day 17 vs day 24 post-kindling). The source calls a 40-50/doe target 'not a realistic goal' for many countries, so that higher industrial figure was excluded. No SA-specific (ARC/SAJAS/provincial) doe-productivity figure was found (see gaps)."
    },
    "windows": [],
    "seasonalPattern": {
      "text": "In hot, humid wet-season conditions rabbit reproduction rates fall; artificial lighting in managed hutches can largely offset this.",
      "source": {
        "quote": "In tropical climates a drop in the rate of reproduction is noted during the same period, the wet season",
        "url": "https://www.fao.org/4/t1690e/t1690e.pdf",
        "doc": "FAO Animal Production and Health Series No.21 - The Rabbit: Husbandry, Health and Production (Lebas et al.)",
        "page": 79
      }
    },
    "weeksToFirstProduct": null,
    "productiveLifeYears": {
      "value": [
        0.76,
        0.76
      ],
      "source": {
        "quote": "The yearly renewal rate of does of 131 percent means that in order to maintain 100 breeding females year-round, 131 new does must be introduced each year, i.e. the average produc- tive life of a doe is just over nine months (365 days ÷ 1.31 = 279 days) between the first mating and withdrawal (culled or dead).",
        "url": "https://www.fao.org/4/t1690e/t1690e.pdf",
        "doc": "FAO Animal Production and Health Series No.21 - The Rabbit: Husbandry, Health and Production (Lebas et al.)",
        "page": 201
      },
      "note": "279 days / 365 = 0.76 years. This figure is from French INTENSIVE commercial rabbitries (average of 1992 national recording-scheme data), NOT backyard/extensive hutches - the source gives no separate productive-life figure for backyard systems (see gaps). Treat as a lower-bound / industrial-system reference only."
    },
    "feedKgPerDay": null,
    "waterLPerDay": null,
    "spaceM2": {
      "value": [
        0.48,
        0.7
      ],
      "source": {
        "quote": "Cages for breeding animals usually have at least a 60 to 70 cm x 80 to 100 cm floor space and are 50 to 60 cm high.",
        "url": "https://www.fao.org/4/t1690e/t1690e.pdf",
        "doc": "FAO Animal Production and Health Series No.21 - The Rabbit: Husbandry, Health and Production (Lebas et al.)",
        "page": 172
      },
      "note": "0.60x0.80=0.48 m2 to 0.70x1.00=0.70 m2, indoor/hutch cage per single breeding adult (one buck or doe per cage), 50-60 cm high. FAO (general, not SA-specific). A separate FAO table (p.174, Fort & Martin 1981) gives a doe's cage as 65-70 cm (front) x 50 cm (depth) = 0.325-0.35 m2 and a buck's cage as 40x50 cm = 0.20 m2 - a narrower alternative figure from the same book, not merged into the range above to avoid mixing two different tabulated sources."
    },
    "welfare": [
      {
        "point": "It is an offence to deny a rabbit food or water, or keep it somewhere lacking adequate space, ventilation, light or shelter from heat and cold.",
        "source": {
          "quote": "confines, chains, tethers or secures any animal unnecessarily or under such conditions or in such a manner or position as to cause that animal unnecessary suffering or in any place which affords inadequate space, ventilation, light, protection or shelter from heat, cold or weather ... unnecessarily starves ... or denies water or food to any animal",
          "url": "https://cer.org.za/wp-content/uploads/2019/11/Animals-Protection-Act-No.-71-of-1962.pdf",
          "doc": "Animals Protection Act 71 of 1962 (consolidated text, s.2(1)(b)-(c))",
          "page": 2
        }
      },
      {
        "point": "Give breeding rabbits roughly 0.48-0.70 m2 of hutch floor space each, 50-60 cm high, not a cramped cage.",
        "source": {
          "quote": "Cages for breeding animals usually have at least a 60 to 70 cm x 80 to 100 cm floor space and are 50 to 60 cm high.",
          "url": "https://www.fao.org/4/t1690e/t1690e.pdf",
          "doc": "FAO Animal Production and Health Series No.21 - The Rabbit: Husbandry, Health and Production (Lebas et al.)",
          "page": 172
        }
      }
    ],
    "legal": [
      {
        "point": "Rabbits are one of the domesticated animal species listed in the Meat Safety Act, so the Act's rules on abattoirs and hygiene apply to them, as they do to ducks and other listed species.",
        "source": {
          "quote": "Pigeon Quail Rabbit Sheep Turkey",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, Schedule 1 (Animals to which this Act applies)",
          "page": 16
        }
      },
      {
        "point": "Rabbits slaughtered to be sold must be slaughtered at a registered abattoir; slaughter for the farmer's own consumption is exempt from this rule but the meat from it may not be sold.",
        "source": {
          "quote": "slaughter any animal at any place other than an abattoir; ... (2) (a) Subsection (1) does not apply to slaughter for own consumption or for cultural or religious purposes.",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.7",
          "page": 6
        }
      },
      {
        "point": "At the abattoir, rabbits (like other listed animals) must be handled humanely during loading, transport, offloading, housing, immobilising and killing, under the Animals Protection Act.",
        "source": {
          "quote": "an animal presented for slaughter at an abattoir must be handled humanely during loading, transportation, off-loading, housing, immobilizing and killing as prescribed in accordance with the requirements of the Animals Protection Act, 1962 (Act No. 71 of 1962)",
          "url": "https://www.gov.za/sites/default/files/gcis_document/201409/a40-000.pdf",
          "doc": "Meat Safety Act 40 of 2000, s.9",
          "page": 7
        }
      },
      {
        "point": "The wild European rabbit (the same species as farmed New Zealand White/Californian rabbits) is only listed as an invasive species under NEMBA on South Africa's off-shore islands - it is not a listed/restricted species on the mainland.",
        "source": {
          "quote": "28 Oryctolagus cuniculus European rabbit See below a. 1a for off-shore islands. b. Not listed elsewhere.",
          "url": "https://invasives.org.za/wp-content/uploads/2022/05/South-Africa-Listed-Invasive-Species-A5-Booklet.pdf",
          "doc": "South Africa's National Listed Invasive Species booklet (NEMBA Alien and Invasive Species Lists)",
          "page": 27
        }
      }
    ]
  }
};
