/** Practical expansion from Rory's July 2026 Training Audit and 36 Week Plan.
 * These are learning activities, not replacements for persisted lesson IDs, gates or awards.
 * A course week is a sequence marker: weather and crop stage decide when field work is possible.
 * Technical figures remain in the existing readings; these activities invent no crop prescriptions.
 */
export interface FieldCycle {
  id: string;
  week?: number;
  title: string;
  lessonIds: string[];
  why: string;
  see: string;
  steps: string[];
  record: string;
  reflect: string;
  mentorCheck: string;
  whenBlocked: string;
  sourceIds?: string[];
}

export const FIELDWORK_SOURCES = {
  observation: { title: 'FAO: field observation and decision making', url: 'https://www.fao.org/4/x7925m/X7925M07.htm' },
  food: { title: 'WHO: Five keys to safer food', url: 'https://www.who.int/publications/i/item/9789241594639' },
  business: { title: 'FAO: Entrepreneurship in farming', url: 'https://www.fao.org/uploads/media/5-EntrepreneurshipInternLores.pdf' },
  margin: { title: 'Department of Primary Industries: Using gross margins', url: 'https://library.dpird.wa.gov.au/bulletins/313/' },
} as const;

export const CORE_FIELD_CYCLES: FieldCycle[] = [
  {
    id: 'core-01', week: 1, title: 'Start with your household and your phone', lessonIds: ['intro-permaculture-l1'],
    why: 'Your starting point gives the course a purpose. A useful baseline describes what you have today, including the work you already know how to do. You do not need to make the farm look better for a photograph.',
    see: 'Compare a note saying “the garden is poor” with a dated note naming the bed, what is growing and the problem you can actually see.',
    steps: ['Name one change your household wants from the course and one strength you bring.', 'Practise opening a lesson and making a dated note. Use paper or a voice note if writing on a phone is difficult.', 'Choose what you are comfortable sharing. Ask before including another person in a photograph.'],
    record: 'Keep your starting note, chosen goal and a picture or sketch of one growing area. Keep personal household details private.',
    reflect: 'What could you show at the end of the course that would tell you something has improved?',
    mentorCheck: 'The learner can find the lesson, describe their starting point and explain what they consent to share.',
    whenBlocked: 'Practise with paper and a borrowed demonstration phone; lack of a personal phone does not prevent the baseline activity.',
  },
  {
    id: 'core-02', week: 2, title: 'Turn household goals into a farm brief', lessonIds: ['intro-permaculture-l1', 'market-community-l1'],
    why: 'A farm plan makes choices about food, money, water and time. A brief keeps those choices connected to the people who will live with them.',
    see: 'A household may want more food and more sales, while the same person does most of the watering. Show where those aims compete for labour.',
    steps: ['Discuss food needs, available work time and the jobs people can realistically share.', 'List resources you have, resources you can borrow with permission and resources still missing.', 'Write a short brief: what you want, who will do the work and the limits the first plan must respect.'],
    record: 'Keep the brief and mark which statements are agreed facts and which still need checking.',
    reflect: 'Which attractive idea would put too much pressure on the household this season?',
    mentorCheck: 'The proposed work fits the learner’s stated resources and includes the household’s own priorities.',
    whenBlocked: 'Write your own provisional brief and leave shared commitments undecided until the people concerned can discuss them.',
  },
  {
    id: 'core-03', week: 3, title: 'Use ethics and principles to make a decision', lessonIds: ['intro-permaculture-l1', 'intro-permaculture-l2'],
    why: 'Knowing the names of the ethics is only a beginning. Their value appears when a decision helps one part of the farm but creates a cost somewhere else.',
    see: 'Use the lesson’s surplus example: food can support household meals, sales, seed saving and returning material to the soil. Each destination serves a purpose.',
    steps: ['Choose a real decision you face, such as where a harvest or a limited supply of mulch will go.', 'Describe who and what benefits from each choice, and who carries the cost.', 'Choose an action and explain it using the three ethics and a relevant design principle.'],
    record: 'Write the decision, the alternatives you considered and the reason for your choice.',
    reflect: 'What new observation would make you change your mind?',
    mentorCheck: 'The learner applies an ethic to a concrete trade-off instead of only reciting its name.',
    whenBlocked: 'Use a situation from the lesson, clearly labelled as an example, then revisit the exercise with a real decision.',
  },
  {
    id: 'core-04', week: 4, title: 'Walk, observe and keep a useful journal', lessonIds: ['reading-landscape-l1', 'reading-landscape-l4'],
    why: 'A journal becomes useful when you can return to the same place and compare what changed. “I saw this” and “I think this caused it” belong in different parts of the note.',
    see: 'Compare a close picture of a damaged leaf with a wider picture that shows where the plant sits in the bed. Together they tell a fuller story.',
    steps: ['Choose a safe walking route and name the places you will revisit.', 'At each place record what you can see: crop condition, ground cover, water marks or recent disturbance.', 'Add a separate question or possible explanation, then choose something to check on the next visit.'],
    record: 'A dated observation with a location, sketch or photo, your question and the next visit’s purpose.',
    reflect: 'Which part of your note is evidence, and which part is still a guess?',
    mentorCheck: 'Another person can locate the observation and distinguish a finding from an explanation.',
    whenBlocked: 'Observe an accessible garden edge or container. Do not enter flooded, unstable or otherwise unsafe ground.',
    sourceIds: ['observation'],
  },
  {
    id: 'core-05', week: 5, title: 'Draw the land you actually have', lessonIds: ['reading-landscape-l4'],
    why: 'A base map records the site before you add a design. If the starting features are wrong, later choices about beds, access and water can be wrong too.',
    see: 'Look at the same site as a photograph and a simple plan. Find the house, paths, existing trees, water points and places you cannot use.',
    steps: ['Walk the accessible boundary with the person who knows the site and note any uncertainty about access or permission.', 'Draw existing features on paper or in the mapping tool. Mark orientation and label measurements as measured or estimated.', 'Ask someone familiar with the site to follow your map and point out what is missing.'],
    record: 'Keep the first base map and a list of corrections. Date later versions so the original observation is not lost.',
    reflect: 'Which missing feature would cause the biggest mistake in your planting plan?',
    mentorCheck: 'The map is recognisable, distinguishes existing features from proposals and identifies uncertain boundaries.',
    whenBlocked: 'Map only the accessible area and mark the rest as unverified. A learning map does not establish legal boundaries.',
  },
  {
    id: 'core-06', week: 6, title: 'Map sun, wind, slope and movement', lessonIds: ['reading-landscape-l2', 'reading-landscape-l3', 'intro-permaculture-l3'],
    why: 'The same crop or structure can behave differently in different places. Sectors describe influences crossing the site; they help you ask where a proposal will be exposed or sheltered.',
    see: 'Use one fixed viewpoint to compare shade at different times. Add observed wind exposure and the paths people and animals already use on a separate map layer.',
    steps: ['Mark the shadows you observe and note the time and date.', 'Ask about local frost, strong wind and fire experience, recording who provided the account rather than treating memory as a measurement.', 'Add those observations to the base map and identify a place that needs more observation before a design decision.'],
    record: 'A sector overlay with dated observations and clearly labelled local accounts.',
    reflect: 'What can today’s visit tell you, and what still needs another season?',
    mentorCheck: 'The learner can connect a proposed location to site evidence and name the limits of that evidence.',
    whenBlocked: 'Use existing observations and mark seasonal gaps. Do not stage a fire or enter hazardous weather to complete the activity.',
  },
  {
    id: 'core-07', week: 7, title: 'Audit water before placing the garden', lessonIds: ['water-harvesting-l1', 'water-harvesting-l2', 'water-harvesting-l3', 'water-harvesting-l4'],
    why: 'A water point on a map does not tell you whether it will serve the garden when needed. Source, reliability, access and intended use all matter.',
    see: 'Trace the route from source to storage to use. Include where overflow or used water goes. Keep observations about quantity separate from evidence about water quality.',
    steps: ['List each existing water source, who may use it and when it has failed or run short.', 'Walk the visible supply route safely and mark leaks, difficult carrying routes and unknown connections.', 'Place a provisional growing area on the map and explain how it would receive water. List any permissions or technical checks still needed.'],
    record: 'A water map and an unanswered-questions list for the owner, facilitator or relevant local specialist.',
    reflect: 'What happens to the proposed garden when its usual source is unavailable?',
    mentorCheck: 'The learner can trace the water route and does not treat clear-looking water as proof of safety.',
    whenBlocked: 'Inspect visible components and use a paper route. Do not enter tanks, dams or excavations, or build waterworks for this mapping exercise.',
  },
  {
    id: 'core-08', week: 8, title: 'Make a first whole-farm concept', lessonIds: ['intro-permaculture-l3', 'reading-landscape-l4', 'food-forest-l3'],
    why: 'A first concept connects household needs with the site you observed. It should make daily work easier and leave room to learn before committing to expensive changes.',
    see: 'Compare a layout that puts frequently visited work near convenient access with one that makes the same person walk repeatedly across the property.',
    steps: ['Place proposed activities on a copy of the base map, using the lesson’s zone guidance and the visits each activity needs.', 'Trace carrying routes, daily work and access for maintenance. Check them against water and sector observations.', 'Choose what can start now, what comes later and what must wait for advice or permission.'],
    record: 'Your first concept, the household brief and a short explanation of the first phase.',
    reflect: 'Which connection between activities saves work, and which might create a conflict?',
    mentorCheck: 'Review point 1: the concept responds to the brief, water, access and known site constraints.',
    whenBlocked: 'Keep uncertain areas as alternatives on paper. A concept is a proposal, not authority to carry out construction.',
  },
  {
    id: 'core-09', week: 9, title: 'Compare soils in the field', lessonIds: ['soil-health-l1'],
    why: 'Soils can differ within one garden. A comparison helps you decide what to investigate instead of assuming every bed needs the same treatment.',
    see: 'Compare samples and ground surfaces from named places. Observe texture by the lesson’s method, visible structure, roots, cover and signs of water movement.',
    steps: ['Choose contrasting accessible places and describe their recent use and conditions.', 'Use the same observation method at each place so the comparison is fair. Record the conditions as well as the result.', 'Identify a question that needs a repeat observation, a laboratory result or help from a facilitator.'],
    record: 'A comparison sheet with locations, method, conditions, observations and remaining questions.',
    reflect: 'Could moisture, recent cultivation or a different method explain part of the difference?',
    mentorCheck: 'The learner describes evidence about soil without claiming a visual observation is a nutrient or pH test.',
    whenBlocked: 'Use clean, accessible soil samples and photographs of their locations. Leave unsafe or contaminated areas alone.',
  },
  {
    id: 'core-10', week: 10, title: 'Build a compost and soil-cover routine', lessonIds: ['soil-health-l2', 'soil-health-l3', 'plant-guilds-l2'],
    why: 'Composting and cover are ongoing jobs. A plan works when suitable materials are available and someone knows what to check after the first day.',
    see: 'Use the compost and mulch readings to identify materials and actions. Compare a covered patch with a nearby exposed patch without treating one visit as proof of a long-term result.',
    steps: ['List suitable materials actually available and check uncertain materials with the facilitator.', 'Prepare a small demonstration using the authored lesson method and record the starting condition.', 'Agree who will revisit it, what they will observe and how changes will be recorded.'],
    record: 'Materials used, the location, a starting photo or sketch and a follow-up observation.',
    reflect: 'What would you change if materials become scarce or the first attempt does not behave as expected?',
    mentorCheck: 'The learner can explain the chosen materials and show a maintenance observation, not just an opening photograph.',
    whenBlocked: 'Make a materials and maintenance plan now, then return for the practical work when suitable materials are available.',
  },
  {
    id: 'core-11', week: 11, title: 'Ask better soil-fertility questions', lessonIds: ['soil-health-l1', 'plant-guilds-l1'],
    why: 'A weak or discoloured plant is a clue, not a complete diagnosis. Soil conditions, water and crop history help you decide what evidence to collect next.',
    see: 'Compare affected and less-affected plants of the same crop where possible. Look at where the pattern occurs rather than naming a deficiency from one leaf.',
    steps: ['Record the pattern, crop stage, watering and recent inputs without guessing missing dates.', 'Ask a local laboratory or extension adviser what sample and background information they need for the question you have.', 'Prepare a labelled sampling plan using those instructions. Discuss a result with the facilitator before choosing an amendment.'],
    record: 'A crop-history note, a sampling question and any actual result, clearly separated from assumptions.',
    reflect: 'What else could explain the symptom, and what observation would help distinguish the possibilities?',
    mentorCheck: 'The learner asks an answerable question and does not select a treatment solely from leaf colour.',
    whenBlocked: 'Keep the question and observation record; do not fabricate a laboratory result or substitute an unverified application rate.',
  },
  {
    id: 'core-12', week: 12, title: 'Check irrigation and keep it working', lessonIds: ['water-harvesting-l3', 'water-harvesting-l4', 'soil-health-l3'],
    why: 'An irrigation plan must be checked on the ground. A blocked outlet or uneven delivery can make the plan on the phone different from what the crop receives.',
    see: 'Trace an existing system during normal safe operation with its operator. Compare places receiving water and note visible faults or differences.',
    steps: ['Identify the source, controls, outlets and the person responsible for maintenance.', 'Record a normal watering event, weather, soil observations and visible delivery problems using the operator’s safe procedure.', 'Review the observations with the facilitator and agree a maintenance task and a follow-up check.'],
    record: 'A dated watering log, fault list and the result after a permitted repair or adjustment.',
    reflect: 'Which decision needs a crop-specific recommendation before you change the schedule?',
    mentorCheck: 'Review point 2: the learner can explain the supply route, detect a problem and name an appropriate next action.',
    whenBlocked: 'Use a labelled system sketch and maintenance discussion. Do not work on pressurised or electrical equipment without competent help.',
  },
  {
    id: 'core-13', week: 13, title: 'Plan food for home and a realistic surplus', lessonIds: ['vegetables-staples-l3', 'market-community-l2'],
    why: 'A production target should start with what the household will use and what buyers actually want. A large harvest is not automatically a useful harvest.',
    see: 'Lay out a household food-use calendar beside a buyer’s requested product, quantity and collection time. Notice where supply and demand may fail to meet.',
    steps: ['Record foods the household grows, buys and finds difficult to obtain, without requiring anyone to disclose private health information.', 'Ask a willing potential buyer about product, quality, unit and timing; distinguish an enquiry from an order.', 'Choose a provisional crop purpose: household use, a confirmed need, or a small market trial.'],
    record: 'A household-use calendar and a market enquiry with its date, unit and unanswered questions.',
    reflect: 'What will you do with a surplus if the hoped-for buyer does not buy it?',
    mentorCheck: 'The learner separates household needs, observed demand and hoped-for sales.',
    whenBlocked: 'Use your own food-use record and mark market assumptions as unconfirmed until a buyer can be consulted.',
  },
  {
    id: 'core-14', week: 14, title: 'Turn bed measurements into a planting plan', lessonIds: ['vegetables-staples-l1'],
    why: 'The whole site is not plantable area. Paths, access and unused corners must be accounted for before a planting plan can describe what fits.',
    see: 'Mark the edges of an existing bed and its paths. Compare the gross area with the space actually available for planting.',
    steps: ['Measure the usable bed and record the units and any uncertain measurements.', 'Use the crop spacing from the authored lesson or a checked local recommendation, recording its source.', 'Mark rows and positions on paper first, then count the places that fit with access. Compare the result with the app’s plan.'],
    record: 'A measured bed sketch, spacing source and counted planting positions.',
    reflect: 'Where would treating a path as growing space overstate your planned production?',
    mentorCheck: 'The learner can explain their units, usable area and plant count without inventing a yield.',
    whenBlocked: 'Use a measured demonstration bed or a labelled paper example. Keep it separate from the learner’s unmeasured site.',
  },
  {
    id: 'core-15', week: 15, title: 'Choose crops for the local season', lessonIds: ['vegetables-staples-l3', 'food-forest-l2'],
    why: 'A planting date copied from another place may not fit your site. Crop choice needs local season information, water availability and a clear purpose.',
    see: 'Compare the site observations with the crop and climate guidance in the readings. Separate an annual crop’s planting window from a tree’s longer-term suitability.',
    steps: ['List candidate crops already covered by the course and the purpose each would serve.', 'Check local planting guidance with a reliable local source and record where it came from.', 'Choose a first crop and an alternative, explaining the water, season, space and household or market reasons.'],
    record: 'A crop-choice note with local evidence, source dates and any conditions still unverified.',
    reflect: 'What change in water availability or planting conditions would make the alternative more suitable?',
    mentorCheck: 'The learner can justify the choice for their location and avoids treating a national calendar as a site guarantee.',
    whenBlocked: 'Keep a shortlist and arrange a local check before committing seed, money or a planting date.',
  },
  {
    id: 'core-16', week: 16, title: 'Plan crops through space and time', lessonIds: ['vegetables-staples-l2', 'plant-guilds-l3'],
    why: 'A bed has a history and a next use. Succession, rotation and mixed planting need enough space and a workable sequence, not just a list of crops.',
    see: 'Draw the same bed at successive stages: what is there now, the next planting and what follows harvest. Mark any period when the bed is still occupied.',
    steps: ['Record the bed’s known crop history and label gaps in that history.', 'Place proposed sowings and harvest windows using the chosen crop guidance, marking estimates as estimates.', 'Check water, access and labour where tasks overlap. Revise the plan if two crops need the same space at the same time.'],
    record: 'A bed sequence with sources for timing, expected overlaps and a contingency if the first crop remains longer.',
    reflect: 'How would a delayed harvest affect the next planting?',
    mentorCheck: 'Review point 3: the learner explains a feasible crop sequence connected to measured space and local conditions.',
    whenBlocked: 'Plan a trial bed on paper and wait for the appropriate planting window before field implementation.',
  },
  {
    id: 'core-17', week: 17, title: 'Track seed and nursery batches', lessonIds: ['seeds-sovereignty-l1', 'seeds-sovereignty-l3', 'vegetables-staples-l1'],
    why: 'A nursery label connects a seed source with what happens next. Without it, a successful batch cannot easily be repeated and a failed batch is difficult to investigate.',
    see: 'Compare an unlabelled tray with one carrying the crop, variety where known, seed source and sowing date. The second tray has a history you can follow.',
    steps: ['Choose a suitable course crop and check its propagation method with the facilitator.', 'Create a batch label and sow using the checked method, recording seed quantity and starting conditions.', 'Keep observations of emergence and care. Count what happened instead of describing the whole batch as simply good or bad.'],
    record: 'A batch record linking source, sowing, observations and the number of usable seedlings when assessed.',
    reflect: 'Which missing record would make it hardest to understand poor emergence?',
    mentorCheck: 'The learner can trace the batch and distinguish seed sown, seedlings emerged and seedlings suitable for the next step.',
    whenBlocked: 'Prepare labels and a batch sheet, then observe an existing nursery with permission until sowing is appropriate.',
  },
  {
    id: 'core-18', week: 18, title: 'Prepare, sow and establish a bed', lessonIds: ['vegetables-staples-l1', 'soil-health-l2'],
    why: 'A planting plan becomes useful when the actual bed matches it. Recording what was planted gives later scouting and harvest records a reliable starting point.',
    see: 'Place the measured plan beside the bed. Identify the crop, positions, preparation and initial care described in the authored lesson.',
    steps: ['Confirm the planting window, available water, seed or seedlings and the agreed method before starting.', 'Prepare and plant the bed following the lesson and locally checked crop guidance.', 'Count and record the actual planting, including any difference from the plan. Agree who will check establishment.'],
    record: 'Planting date, bed, crop and batch, quantity planted, method and a dated starting picture or sketch.',
    reflect: 'Which difference between the plan and actual planting should change the next tasks?',
    mentorCheck: 'The learner demonstrates the method and can connect planted material to its bed and batch record.',
    whenBlocked: 'Practise layout and tool handling in a demonstration area; record planting as pending rather than claiming a crop is in the ground.',
  },
  {
    id: 'core-19', week: 19, title: 'Make a task calendar someone can follow', lessonIds: ['vegetables-staples-l2', 'market-community-l1'],
    why: 'A task is useful when somebody knows where to go, what to do and what would count as done. A long list without responsibility can leave essential care undone.',
    see: 'Compare “look after vegetables” with a task naming the bed, the check, the responsible person and the observation to bring back.',
    steps: ['List upcoming work from the actual planted bed and the agreed crop plan.', 'Give each task a location, purpose, responsible person and suitable timing or trigger.', 'Walk through the calendar with the people doing the work and adjust clashes with household responsibilities.'],
    record: 'A practical calendar and one completed task note stating what actually happened.',
    reflect: 'Which task must change when rain, labour or crop stage changes?',
    mentorCheck: 'Another person can understand a task and report its result without guessing the intended action.',
    whenBlocked: 'Create a calendar for a demonstration bed and mark it as practice. Do not create fictional completion records.',
  },
  {
    id: 'core-20', week: 20, title: 'Review establishment and correct the plan', lessonIds: ['vegetables-staples-l1', 'soil-health-l1'],
    why: 'The planting date is not the end of establishment. Missing plants and uneven growth change what the bed can do, and they deserve an explanation before you spend more seed.',
    see: 'Compare the original planting sketch with the bed now. Mark gaps and differences without hiding the places that did poorly.',
    steps: ['Revisit the same bed and record established plants, gaps and visible patterns.', 'Review watering, weather, handling and batch records with the facilitator to identify what needs checking.', 'Agree a suitable correction or further observation, then update tasks and planned quantities to match the field.'],
    record: 'A dated establishment map, possible causes, the agreed action and a follow-up observation.',
    reflect: 'What evidence would show that your correction helped?',
    mentorCheck: 'Review point 4: the learner compares plan with actual establishment and can justify the next step.',
    whenBlocked: 'Use a previous real bed record or a supervised example; return to the learner’s crop when the stage is appropriate.',
  },
  {
    id: 'core-21', week: 21, title: 'Scout the crop and choose a next step', lessonIds: ['vegetables-staples-l4'],
    why: 'Regular scouting connects a crop observation to a decision. Looking only at the worst plant can miss the pattern across a bed.',
    see: 'Compare crop condition, soil moisture observations, weeds, visible insects and damage across a repeatable route. Record helpful organisms as well as suspected pests.',
    steps: ['Choose a repeatable observation route with the facilitator and identify the crop stage.', 'Record the pattern and extent of what you see, including places without the problem.', 'Discuss the findings and choose a next observation, a checked action or an escalation to someone qualified to advise.'],
    record: 'A dated scouting sheet with bed, observations, decision, responsible person and follow-up.',
    reflect: 'What changed since the previous visit, and how did that change your decision?',
    mentorCheck: 'The learner bases the next step on recorded field observations and returns to check the outcome.',
    whenBlocked: 'Practise the observation method in an accessible demonstration plot; do not invent pest counts for an absent crop.',
    sourceIds: ['observation'],
  },
  {
    id: 'core-22', week: 22, title: 'Use crop photos and Lima Vision carefully', lessonIds: ['vegetables-staples-l4', 'reading-landscape-l4'],
    why: 'A useful crop photograph gives context. An image-based suggestion still needs checking against the crop history and what is happening around the plant.',
    see: 'Take a wider view, a whole-plant view and a clear detail of the symptom. Compare what can and cannot be inferred from each.',
    steps: ['Photograph the crop with permission and avoid including people or private information unnecessarily.', 'Add bed, crop, date, affected part and relevant recent care. If using Lima Vision, keep its suggestion separate from your own observation.', 'Discuss uncertainty with the facilitator before any treatment decision. Retain the original evidence for follow-up.'],
    record: 'A photo set, context note, any tool suggestion and the person or source used to check it.',
    reflect: 'What important fact could the photograph fail to show?',
    mentorCheck: 'The learner explains the limits of an image suggestion and can identify the next verification step.',
    whenBlocked: 'Use the same photo-and-context method with a facilitator. The learning activity does not require an AI service or a paid request.',
  },
  {
    id: 'core-23', week: 23, title: 'Make an integrated pest-management decision', lessonIds: ['vegetables-staples-l4', 'plant-guilds-l2'],
    why: 'Pest management begins with understanding the crop situation. A decision should consider the problem, helpful organisms and what happened after earlier action.',
    see: 'Use the scouting record to compare the affected crop with nearby less-affected plants. Discuss prevention and the options already taught in the course.',
    steps: ['Describe the problem using observed evidence and list what remains unidentified.', 'With the facilitator, compare suitable options from checked guidance and select an action or a reason to continue observing.', 'Set a follow-up observation and record the result, including any unwanted effects.'],
    record: 'The problem, evidence, checked advice, chosen action and outcome in the same crop record.',
    reflect: 'What result would make you stop, change the approach or seek specialist help?',
    mentorCheck: 'The learner explains the choice from evidence rather than treating every insect as a reason to spray.',
    whenBlocked: 'Work through an actual past scouting record. Do not apply a product merely to demonstrate activity.',
    sourceIds: ['observation'],
  },
  {
    id: 'core-24', week: 24, title: 'Know when crop protection needs more help', lessonIds: ['vegetables-staples-l4', 'soil-health-l1'],
    why: 'Similar symptoms can have different causes. The useful skill is to recognise the limits of your evidence and give an adviser the information needed to help.',
    see: 'Put the crop history, symptom photos and scouting map together. Ask which possible causes the evidence supports and which remain untested.',
    steps: ['Prepare a clear problem report with crop, location, timing, pattern and recent care.', 'Ask an extension adviser or other qualified local specialist what further information is needed.', 'Record the advice and its source. Before any crop-protection product is used, have a qualified facilitator check the current label and applicable local requirements.'],
    record: 'A complete problem report and advice record, including unresolved questions and the follow-up plan.',
    reflect: 'What could go wrong if you confidently named a disease from a single picture?',
    mentorCheck: 'Review point 5: the learner recognises uncertainty, knows where to seek help and does not invent a treatment or dose.',
    whenBlocked: 'Practise preparing the report. Treatment stays pending until identification and safe, locally appropriate advice are available.',
  },
  {
    id: 'core-25', week: 25, title: 'Record a harvest and account for losses', lessonIds: ['market-community-l1', 'vegetables-staples-l3'],
    why: 'Harvest records should describe what left the bed and where it went. Household use and damaged produce matter even when no money changes hands.',
    see: 'Follow one real harvest from bed to sorting and destination. Use the same clearly named unit throughout or record an actual conversion.',
    steps: ['Check readiness for the chosen crop using the lesson and locally appropriate guidance.', 'Harvest with the agreed method and record the quantity, unit, date and bed.', 'Account for household use, sale, sharing, retained produce and losses without counting the same produce twice.'],
    record: 'A harvest record whose destinations reconcile with the measured total, plus a note on any loss.',
    reflect: 'At which point did produce lose quality or become difficult to account for?',
    mentorCheck: 'The learner can trace the harvest to a bed and explain where the recorded quantity went.',
    whenBlocked: 'Use a real harvest from a demonstration plot with permission, or defer the field assessment until a crop is ready. Do not force a harvest to fit the week number.',
  },
  {
    id: 'core-26', week: 26, title: 'Handle food carefully and keep its history', lessonIds: ['market-community-l1', 'market-community-l2'],
    why: 'The work after picking affects the food people receive. A batch record also helps you trace produce back to its harvest if a problem is reported.',
    see: 'Walk the route from harvest container to sorting place, storage and handover. Identify where food contacts hands, tools, surfaces and water.',
    steps: ['Use WHO’s food-hygiene guidance to discuss cleanliness, separation of raw and cooked food, thorough cooking, safe temperatures, and safe water and ingredients.', 'Check the handling method for the actual crop with the facilitator and identify a practical improvement.', 'Label the harvest batch and record its origin, handling and destination.'],
    record: 'A batch trail and a before-and-after note on the handling improvement.',
    reflect: 'Could you identify the source and recipients of this batch if someone reported a problem?',
    mentorCheck: 'The learner can trace a real batch and explain the hygiene practices relevant to its handling.',
    whenBlocked: 'Practise the batch trail on paper and inspect the handling area; do not use doubtful food for a tasting demonstration.',
    sourceIds: ['food'],
  },
  {
    id: 'core-27', week: 27, title: 'Use the harvest well at home', lessonIds: ['vegetables-staples-l3', 'market-community-l2'],
    why: 'Farm success includes food used by the household. A plan for meals, sharing and sales can make the harvest more useful than treating everything as market stock.',
    see: 'Compare the household’s earlier food-use calendar with what is actually being harvested. Discuss gaps and preferences without assuming every household eats the same meals.',
    steps: ['Choose a current harvest and discuss how the household would like to use it.', 'Record what is kept, shared or sold and connect those choices to the original household brief.', 'If considering processing for sale, list the handling skills, equipment, costs and local requirements that must be checked before starting.'],
    record: 'A household-use note and a realistic next action for a gap or surplus.',
    reflect: 'Did the crop improve food access at home, and what evidence supports that answer?',
    mentorCheck: 'The learner includes household use in the farm record and separates a processing idea from a verified production method.',
    whenBlocked: 'Use an actual earlier harvest or plan for the next one. This activity does not require a new recipe or preservation trial.',
  },
  {
    id: 'core-28', week: 28, title: 'Save seed with a traceable method', lessonIds: ['seeds-sovereignty-l1', 'seeds-sovereignty-l2', 'seeds-sovereignty-l3'],
    why: 'Saving seed is a chain of decisions from choosing a plant to labelling and storing the seed. A record makes the next sowing and any sharing more informed.',
    see: 'Return to the Seeds module’s dry and wet demonstrations. Explain why the chosen crop needs its particular method rather than using one method for all seed.',
    steps: ['Choose a suitable seed-saving opportunity using the reviewed Seeds lessons and identify the parent plant or source.', 'Follow the appropriate saving, drying and storage method when the crop is ready.', 'Label the batch and record what you know and what remains uncertain before storing or sharing it.'],
    record: 'A seed-batch history from source through method to storage, plus the checks taught in the Seeds module.',
    reflect: 'What information would you want if a neighbour gave you this seed?',
    mentorCheck: 'Review point 6: the learner demonstrates the appropriate method and can trace the batch. A label alone is not proof of seed quality.',
    whenBlocked: 'Prepare the batch record and practise identification with the facilitator. Complete collection when suitable seed is mature, not on an arbitrary calendar date.',
  },
  {
    id: 'core-29', week: 29, title: 'Keep farm and household money understandable', lessonIds: ['market-community-l1'],
    why: 'A money record should let you explain what happened. Household spending, a farm input and a long-lived tool are different events even if they were paid for from the same pocket.',
    see: 'Review actual receipts or a clearly labelled practice set. Identify the date, purpose, amount and the farm activity, if any, that the payment belongs to.',
    steps: ['Gather available records and enter actual income and spending with a clear description.', 'Separate farm transactions, household use and equipment purchases using the existing record system.', 'Reconcile the entries with receipts and cash movements; mark missing evidence instead of making it up.'],
    record: 'A dated money record and a list of entries that still need clarification.',
    reflect: 'Which transaction would make the crop look more profitable if it were left out?',
    mentorCheck: 'The learner can explain a sample of entries and distinguish recorded facts from reconstructed estimates.',
    whenBlocked: 'Use a labelled practice record with the facilitator. Do not present invented receipts or figures as the learner’s farm history.',
  },
  {
    id: 'core-30', week: 30, title: 'Find the work and costs behind a crop', lessonIds: ['market-community-l1', 'market-community-l2'],
    why: 'A sale has work and costs behind it. Recording those inputs helps you compare ways of growing and selling without making unpaid household work disappear.',
    see: 'Trace one crop from seed to buyer and list the inputs, transport, packaging and work actually used at each stage.',
    steps: ['Choose a real crop batch and collect its recorded costs.', 'Record labour time and who did the work, keeping paid cash costs distinct from an explicitly valued estimate of unpaid work.', 'Identify shared items and explain how you allocated them, or leave them visibly unallocated for discussion.'],
    record: 'A crop cost sheet with units, receipts or sources, labour time and labelled estimates.',
    reflect: 'Which cost changes when you sell through a different route?',
    mentorCheck: 'The learner accounts for relevant work and costs without counting a shared expense twice.',
    whenBlocked: 'Build the sheet with the costs known so far and mark the rest pending; an incomplete honest record is useful for the next visit.',
  },
  {
    id: 'core-31', week: 31, title: 'Compare margin, price and cash timing', lessonIds: ['market-community-l2'],
    why: 'Money from sales is not the same as profit, and a promising season can still run short of cash before harvest. Keep the definitions clear when comparing options.',
    see: 'Gross margin is enterprise income less its variable costs. It does not by itself account for all fixed costs. Put expected receipts and payments on their actual or expected dates to see cash timing.',
    steps: ['Use one crop’s real income and variable-cost record to calculate its gross margin, naming the period and units.', 'With the facilitator, identify other costs before discussing the price needed to cover the chosen cost basis.', 'Place expected payments and receipts on a calendar; change a clearly labelled sales assumption and discuss what happens to the cash gap.'],
    record: 'A checked calculation, its cost basis and a cash calendar separating actual transactions from estimates.',
    reflect: 'Could the crop show a positive gross margin while the household still cannot pay an earlier bill?',
    mentorCheck: 'The learner distinguishes revenue, gross margin, wider costs and cash availability.',
    whenBlocked: 'Use a facilitator’s clearly labelled worked example, then return to the farm’s records when available.',
    sourceIds: ['margin'],
  },
  {
    id: 'core-32', week: 32, title: 'Test a route to market', lessonIds: ['market-community-l2'],
    why: 'A buyer’s price is only part of a selling decision. Quantity, quality, packaging, travel, payment timing and unsold produce affect whether the route works for you.',
    see: 'Compare two possible selling routes using the same product and unit. Include the work and costs needed to reach each buyer.',
    steps: ['Ask willing buyers about their requirements and record the date and status of each enquiry.', 'Compare routes against the crop’s likely availability and the household’s transport and work capacity.', 'Plan a small feasible sale or a documented market enquiry, then compare the result with the expectation.'],
    record: 'A buyer-requirements note, route comparison and any actual sale, cost or unsold quantity.',
    reflect: 'Which buyer requirement would be hardest to meet consistently?',
    mentorCheck: 'Review point 7: the learner connects costs and production evidence to a realistic market decision.',
    whenBlocked: 'Complete the enquiry and comparison first. A market interview is not a purchase agreement or a completed sale.',
    sourceIds: ['business'],
  },
  {
    id: 'core-33', week: 33, title: 'Make a clear agreement with neighbours', lessonIds: ['market-community-l3'],
    why: 'Shared work depends on people understanding the same agreement. Clear quantities, responsibilities and a way to handle changes can prevent a useful exchange becoming a dispute.',
    see: 'Compare “we will help each other at harvest” with an agreement naming the work, people, date or trigger, contribution and what happens if plans change.',
    steps: ['Choose a possible exchange, group task or shared transport arrangement with willing participants.', 'Discuss contributions, responsibilities, records and a fair way to raise disagreements.', 'Write the agreed points in plain language and ask each participant to explain their understanding before acting.'],
    record: 'An agreement or a clearly labelled practice draft, plus any agreed change after discussion.',
    reflect: 'Which unspoken assumption could cause a disagreement later?',
    mentorCheck: 'The learner can explain both their own responsibility and the other participants’ understanding.',
    whenBlocked: 'Role-play the discussion with a facilitator; do not commit another person’s labour, produce or money without their agreement.',
  },
  {
    id: 'core-34', week: 34, title: 'Collect evidence that tells the truth', lessonIds: ['market-community-l1', 'market-community-l3', 'reading-landscape-l4'],
    why: 'An impact story is stronger when someone can trace it to real evidence. A photograph, a survey answer and a measured harvest show different things.',
    see: 'Compare a claim such as “food access improved” with the dated records that might support it. Identify what those records cannot establish on their own.',
    steps: ['Choose a course outcome and gather only the information needed to examine it.', 'Explain the purpose before asking someone for information or a photograph, and respect their choice about sharing.', 'Check dates, units and duplicated entries. Keep missing answers missing and separate observations from conclusions.'],
    record: 'An evidence index naming each item, its date, what it supports and any sharing limits.',
    reflect: 'What would be misleading if this evidence were shown without its context?',
    mentorCheck: 'The learner can trace a claim to evidence, explain its limits and respect the contributor’s choices.',
    whenBlocked: 'Use the learner’s own records. Do not fabricate survey answers or use another household’s information without permission.',
  },
  {
    id: 'core-35', week: 35, title: 'Bring the farm plan together in phases', lessonIds: ['intro-permaculture-l3', 'food-forest-l3', 'market-community-l1'],
    why: 'The integrated plan should reflect what the season taught you. A phased plan shows which actions are feasible now and which depend on money, water, advice or earlier work.',
    see: 'Lay the first concept beside the current map, crop records and household brief. Identify a change supported by experience rather than a more attractive drawing.',
    steps: ['Update the map with actual work and clearly distinguish proposed additions.', 'Connect crops, water, soil care, access, labour and costs in the next phase.', 'Choose dependencies and review points: what must be checked or completed before each later action begins?'],
    record: 'An updated concept, phased work list, resource needs and evidence for the main revisions.',
    reflect: 'Which proposed investment should wait until its assumption has been checked?',
    mentorCheck: 'Review point 8: the integrated plan is traceable to site observations, household priorities and realistic resources.',
    whenBlocked: 'Leave unresolved technical or permission-dependent work clearly pending and develop the parts that can be planned from current evidence.',
  },
  {
    id: 'core-36', week: 36, title: 'Review your portfolio and plan next season', lessonIds: ['market-community-l1', 'seeds-sovereignty-l3', 'intro-permaculture-l1'],
    why: 'The final review is a chance to explain what you learned, including attempts that did not work. A useful next-season plan grows from that evidence.',
    see: 'Follow one chain through the portfolio: starting goal, plan, field action, observation, result and revision. Check that the dates and records tell the same story.',
    steps: ['Select the records that best demonstrate your work and identify any missing field evidence.', 'Explain a success and a difficulty to the facilitator, using the records rather than memory alone.', 'Write the next-season priorities, the first action, the support needed and the conditions you will check before starting.'],
    record: 'A portfolio index, review feedback and a next-season action plan. Keep deferred seasonal activities explicitly open.',
    reflect: 'What can you now decide or demonstrate that you could not at the start?',
    mentorCheck: 'Review point 9: the learner explains a coherent evidence trail and a realistic next step. Certification follows the programme’s existing assessment rules.',
    whenBlocked: 'Review the evidence available now and schedule the outstanding field observation for the right crop stage; do not substitute a fictional result.',
  },
];

export interface FieldPathway { id: string; title: string; purpose: string; cycles: FieldCycle[] }

export const ELECTIVE_FIELD_PATHWAYS: FieldPathway[] = [
  {
    id: 'food-forest', title: 'Food Forest', purpose: 'Develop a site-specific perennial plan and a record of establishment and care.',
    cycles: [
      { id: 'forest-01', title: 'Read the layers and plant roles', lessonIds: ['food-forest-l1', 'plant-guilds-l1', 'plant-guilds-l2'], why: 'A layered planting works through relationships between plants and the site. Copying a list does not show whether those relationships can work in your space.', see: 'Use the lesson’s forest section to identify layers, light access and the roles of soil-feeding and mulch plants.', steps: ['Sketch an existing planting or a course example in plan and section.', 'Label the roles described in the readings and identify gaps or competing space needs.', 'Discuss which roles the proposed site can support and which need more evidence.'], record: 'A labelled section and role map, with observed facts separated from proposals.', reflect: 'Where could an upper layer change the conditions for a lower one?', mentorCheck: 'The learner explains a relationship between layers rather than only naming seven layers.', whenBlocked: 'Use the course illustration and mark the exercise as a concept study until a site visit is possible.' },
      { id: 'forest-02', title: 'Choose a guild for this site', lessonIds: ['food-forest-l2', 'plant-guilds-l3'], why: 'A plant that serves a useful role still needs to suit the climate, space and intended management. The site decides which example can become a workable plan.', see: 'Compare the reviewed guild example with the learner’s sun, water and climate observations.', steps: ['Use only species already covered in the reviewed course to prepare a shortlist.', 'Check local suitability, availability and any current restrictions with a qualified local adviser before obtaining planting material.', 'Draw a provisional guild using checked spacing and explain access and future maintenance.'], record: 'A shortlist with evidence and unresolved checks, plus a provisional guild sketch.', reflect: 'Which plant choice depends most strongly on an assumption you have not checked?', mentorCheck: 'The learner connects selection to local conditions and identifies what needs confirmation.', whenBlocked: 'Keep the selection provisional; the exercise does not require buying or propagating plants.' },
      { id: 'forest-03', title: 'Establish, observe and revise', lessonIds: ['food-forest-l3', 'plant-guilds-l2'], why: 'Establishment is a sequence of work and observation. A planting photograph cannot show whether plants survived or the maintenance plan was workable.', see: 'Compare the lesson’s establishment stages with water, protection and labour actually available on the site.', steps: ['Choose a feasible first phase and confirm the planting method and season with the facilitator.', 'Implement the agreed work where appropriate and record the actual planting and care.', 'Return to observe establishment, gaps and maintenance needs, then revise the next phase.'], record: 'A phased plan and dated establishment observations linked to the planting map.', reflect: 'What did the first phase teach you before committing to the next?', mentorCheck: 'The learner shows follow-up evidence and can justify a revision.', whenBlocked: 'Complete the phased plan and defer planting or survival assessment to the appropriate season.' },
    ],
  },
  {
    id: 'small-livestock', title: 'Small Livestock', purpose: 'Assess animal-care responsibilities before adding livestock, and learn through supervised observation.',
    cycles: [
      { id: 'livestock-01', title: 'Plan daily chicken care', lessonIds: ['small-livestock-l1'], why: 'Chickens need reliable daily care. Their place in a garden system must be considered alongside their own needs and the household’s capacity to meet them.', see: 'Observe an existing flock with its keeper, including housing, water, feed, protection and the daily routine.', steps: ['Ask the keeper to explain normal checks and who provides backup care.', 'Map the proposed relationship to beds and household work using the reviewed lesson.', 'Prepare a care and cost plan and obtain locally appropriate animal-health advice before acquiring animals.'], record: 'A daily-care plan, backup arrangement and questions for the keeper or animal-health adviser.', reflect: 'Who cares for the animals when the usual keeper is absent?', mentorCheck: 'The learner can explain the care responsibility before claiming a benefit to the garden.', whenBlocked: 'Use a keeper interview or supervised demonstration. Do not acquire or handle animals to satisfy the exercise.' },
      { id: 'livestock-02', title: 'Observe pollination and understand beekeeping responsibility', lessonIds: ['small-livestock-l2'], why: 'Observing flower visitors and managing a hive are different skills. Understanding that difference helps you assess whether beekeeping belongs in your plan.', see: 'Observe flowers from a safe position and ask an experienced beekeeper to explain site choice, routine care and training needs.', steps: ['Record flower visitors without disturbing nests or hives.', 'Discuss access, neighbours, household safety and the work involved with an experienced beekeeper.', 'List the training, equipment, permissions and local advice needed before considering a hive.'], record: 'A pollinator observation and a beekeeping readiness question list.', reflect: 'What can you learn from watching flower visitors that does not require keeping a hive?', mentorCheck: 'The learner distinguishes observation from competence to manage a colony.', whenBlocked: 'Use the course material and an interview. Opening or moving a hive is outside this introductory activity.' },
      { id: 'livestock-03', title: 'Trace resources through an animal system', lessonIds: ['small-livestock-l3', 'soil-health-l2'], why: 'A loop on a drawing can hide costs or unsafe handling. Trace what actually enters and leaves the system before describing it as self-sustaining.', see: 'Draw feed, water, bedding, products, manure and work around an existing animal enterprise, using the reviewed lesson as a starting point.', steps: ['Ask the keeper which inputs come from outside the farm and record them.', 'Trace products and waste to their actual destinations and identify handling questions for the facilitator.', 'Compare the proposed benefits with care, cost and management responsibilities.'], record: 'A resource-flow map with outside inputs, outputs, responsibilities and unresolved handling questions.', reflect: 'Which outside input would stop the system if it became unavailable?', mentorCheck: 'The learner can describe a real resource flow without assuming every waste stream is automatically safe to reuse.', whenBlocked: 'Use an observed enterprise or a labelled course example. Do not introduce animal waste into food production for this mapping exercise.' },
    ],
  },
  {
    id: 'seed-steward', title: 'Seed Steward', purpose: 'Extend the Seeds module into repeatable batch records, observation and responsible sharing.',
    cycles: [
      { id: 'seed-01', title: 'Choose and document a seed source', lessonIds: ['seeds-sovereignty-l1'], why: 'A seed collection needs a history. Knowing where a batch came from helps you explain what you know about it and what you still need to learn.', see: 'Compare the course’s seed choices and the information available on a real packet or saved batch.', steps: ['Identify a suitable course crop and its source with the facilitator.', 'Record crop, variety where known, source and the reason for selection.', 'Follow the selected plants through the season and record relevant observations.'], record: 'A source record linked to the selected plants and dated observations.', reflect: 'Which information would be difficult to reconstruct after seed has been mixed?', mentorCheck: 'The learner can trace a batch without claiming an unknown variety as known.', whenBlocked: 'Prepare the record and observe an existing planting until suitable seed parents are available.' },
      { id: 'seed-02', title: 'Demonstrate the right saving method', lessonIds: ['seeds-sovereignty-l2'], why: 'The method must match the crop and seed condition. A demonstration should show the decisions as well as the finished seed.', see: 'Review the actual dry and wet teaching sequences in Seeds and identify which applies to the chosen batch.', steps: ['Explain the selected method before beginning.', 'Carry out the reviewed sequence when suitable seed is ready, keeping batches distinct.', 'Record observations at each stage and ask the facilitator to check the result.'], record: 'A batch-linked process record with the method and any problems encountered.', reflect: 'Which stage would be most difficult to check from a photograph of the finished batch alone?', mentorCheck: 'The learner demonstrates the crop-appropriate sequence and explains its main decisions.', whenBlocked: 'Use the Seeds demonstrations for preparation and defer the practical assessment until the right material is available.' },
      { id: 'seed-03', title: 'Store, check and share with a history', lessonIds: ['seeds-sovereignty-l3', 'market-community-l3'], why: 'Storage and sharing continue the work after collection. Honest information about the batch is part of caring for the person who will sow it.', see: 'Inspect labels and storage using the reviewed Seeds guidance. Compare the information carried by a labelled batch with an anonymous packet.', steps: ['Store and label the batch using the lesson method.', 'Carry out the lesson’s appropriate checks and record dates and results.', 'Prepare a sharing note that includes the batch history, known limits and the recipient’s questions.'], record: 'A storage and checking log plus a sharing note, if any seed is actually exchanged.', reflect: 'What would make you hold a batch back from sharing?', mentorCheck: 'The learner can show the batch history and describe its limits without promising unverified performance.', whenBlocked: 'Prepare the log and sharing note. Do not claim a storage result or exchange before it happens.' },
    ],
  },
  {
    id: 'market-enterprise', title: 'Market Garden Enterprise', purpose: 'Follow one crop from a buyer enquiry through production records, costs and an actual review.',
    cycles: [
      { id: 'enterprise-01', title: 'Connect a buyer enquiry to a crop plan', lessonIds: ['market-community-l2', 'vegetables-staples-l2'], why: 'A market plan needs both demand and a feasible production sequence. Enthusiasm from a buyer does not remove the need to check space, timing and resources.', see: 'Place a dated buyer enquiry beside the measured bed plan and local planting guidance.', steps: ['Confirm the product, unit, timing and quality requested by a willing buyer.', 'Check whether the proposed production fits available space, water and labour.', 'Record the assumptions and choose a feasible trial or further enquiry.'], record: 'A buyer-to-bed plan with explicit assumptions and a contingency for unsold produce.', reflect: 'Which part of the promise to the buyer depends on conditions outside your control?', mentorCheck: 'The learner distinguishes an enquiry from an order and a forecast from a guaranteed harvest.', whenBlocked: 'Complete the enquiry and feasibility check; a growing trial waits for suitable conditions.' },
      { id: 'enterprise-02', title: 'Follow the batch through costs and sales', lessonIds: ['market-community-l1', 'market-community-l2'], why: 'An enterprise can only be reviewed fairly when income, losses and the work behind them belong to the same batch and period.', see: 'Trace a real crop batch from sowing and care records to harvest destinations and receipts.', steps: ['Connect actual inputs and labour to the crop batch.', 'Record harvest, sales, household use and unsold produce in consistent units.', 'Reconcile the records and ask the facilitator to check unexplained gaps.'], record: 'A linked production, cost and sales record with missing evidence visibly marked.', reflect: 'What would you misunderstand if you looked only at money received?', mentorCheck: 'The learner can trace a sale back to production evidence and associated costs.', whenBlocked: 'Use the records available and leave future sales as forecasts, not actual income.' },
      { id: 'enterprise-03', title: 'Decide what to repeat or change', lessonIds: ['market-community-l2', 'market-community-l3'], why: 'The next production decision should use the result of the trial. Keeping a smaller reliable enterprise may serve the household better than expanding before its constraints are understood.', see: 'Compare the original buyer-to-bed plan with actual production, costs, household work and buyer feedback.', steps: ['Review the differences with the facilitator and identify the most important cause to investigate.', 'Compare repeating, changing or stopping the trial against the household brief.', 'Write the next action and the evidence needed before expanding or making a shared commitment.'], record: 'An enterprise review with a reasoned next decision and the assumptions still to check.', reflect: 'What would have to become more reliable before you increased production?', mentorCheck: 'The learner justifies the next decision from records rather than sales revenue alone.', whenBlocked: 'Review the evidence available now and schedule the final decision after the remaining harvest or payment is recorded.' },
    ],
  },
];

export const ALL_FIELD_CYCLES = [...CORE_FIELD_CYCLES, ...ELECTIVE_FIELD_PATHWAYS.flatMap((p) => p.cycles)];
export function fieldworkForLesson(lessonId: string): FieldCycle[] {
  return ALL_FIELD_CYCLES.filter((cycle) => cycle.lessonIds.includes(lessonId));
}
