// isiZulu drafts for the Farm Finance course (lib/course-finance-content.json / lib/course-finance.ts).
//
// SOURCE-PAIRED, UNREVIEWED — same convention as lib/course-translation-drafts*.ts: each isiZulu
// string is stored beside the exact English text it was machine-translated from. financeZu() only
// returns the isiZulu half when it still matches the live English string, so an edit to the
// reviewed English source (course-finance-content.json is rebuilt from its manuscript by
// scripts/build-finance-course.py — never hand-edited) silently falls back to English instead of
// showing stale isiZulu. Nothing here has had fluent-isiZulu or local-farming review; the app shows
// the same "isiZulu draft" badge every other unreviewed course translation uses
// (t('studentZuluLessonDraftBadge')).
//
// Scope of this first pass: unit titles/summaries, lesson titles/outcomes/reading, and the
// practical project's question labels and prompts (lib/finance-project.ts). Each unit's "shared"
// source-card material, the per-lesson practice sections (Demonstration/Guided sorting/Independent
// check/Feedback/Field task) and course-finance-project.json's case data are still English-only —
// see PROGRESS.md / the PR description for what remains.

export interface FinanceZuPair { en: string; zu: string }

/** Returns the isiZulu draft only if it is still paired to the exact live English string. */
export function financeZu(map: Record<string, FinanceZuPair>, id: string, liveEnglish: string): string | null {
  const pair = map[id];
  if (!pair || pair.en !== liveEnglish) return null;
  return pair.zu;
}

export const FINANCE_ZU_UNIT_TITLE: Record<string, FinanceZuPair> = {
  'f1': { en: `Understand the farm's money`, zu: `Qonda imali yepulazi` },
  'f2': { en: `Keep and reconcile useful records`, zu: `Gcina uphinde uqhathanise amarekhodi awusizo` },
  'f3': { en: `Know costs and set prices`, zu: `Yazi izindleko futhi umise amanani` },
  'f4': { en: `Budget and manage cash through the season`, zu: `Yakha ibhajethi uphinde uphathe imali kuyo yonke isizini` },
  'f5': { en: `Sell, invoice and collect payment`, zu: `Thengisa, khipha i-invoyisi bese uqoqa inkokhelo` },
  'f6': { en: `Equipment, borrowing and reserves`, zu: `Izinsiza zokusebenza, ukuboleka nokugcinelwa` },
  'f7': { en: `Read results and prepare reliable records`, zu: `Funda imiphumela futhi ulungiselele amarekhodi athembekile` },
  'f8': { en: `Plan, compare and improve the business`, zu: `Hlela, qhathanisa futhi uthuthukise ibhizinisi` },
};

export const FINANCE_ZU_UNIT_SUMMARY: Record<string, FinanceZuPair> = {
  'f1': { en: `Separate household and farm money, follow sales and payments, and keep evidence.`, zu: `Hlukanisa imali yasekhaya nemali yepulazi, landela ukuthengisa nezinkokhelo, futhi ugcine ubufakazi.` },
  'f2': { en: `Follow produce and money, reconcile records and explain corrections.`, zu: `Landela umkhiqizo nemali, uqhathanise amarekhodi bese uchaza ukulungiswa.` },
  'f3': { en: `Include costs, compare prices and test a bounded break-even calculation.`, zu: `Faka izindleko, uqhathanise amanani, uphinde uhlole isibalo se-break-even esinemikhawulo.` },
  'f4': { en: `Build a budget, put money on dates and investigate a cash gap.`, zu: `Yakha ibhajethi, ubeke imali ezinsukwini ezithile futhi uhlole igebe lemali.` },
  'f5': { en: `Connect orders, deliveries, invoices and payments without duplicate sales.`, zu: `Xhumanisa ama-oda, ukulethwa, ama-invoyisi nezinkokhelo ngaphandle kokuphinda ukuthengisa okufanayo.` },
  'f6': { en: `Compare equipment options, understand commitments and plan reserves.`, zu: `Qhathanisa izindlela zokuthola izinsiza, uqonde izibopho, uphinde uhlele okugcinelwe.` },
  'f7': { en: `Separate cash, period result and financial position; prepare reliable records.`, zu: `Hlukanisa imali yesandla, umphumela wesikhathi kanye nesimo sezimali; ulungiselele amarekhodi athembekile.` },
  'f8': { en: `Test market evidence, write a checkable plan and review a season.`, zu: `Hlola ubufakazi bemakethe, ubhale icebo elingahlolwa, uphinde ubuyekeze isizini.` },
};

export const FINANCE_ZU_LESSON_TITLE: Record<string, FinanceZuPair> = {
  'f1-1': { en: `Household and farm money`, zu: `Imali yasekhaya nemali yepulazi` },
  'f1-2': { en: `Cash, sales, amounts owed and profit`, zu: `Imali yesandla, ukuthengisa, imali ekweletwayo nenzuzo` },
  'f1-3': { en: `Keep an evidence trail`, zu: `Gcina umkhondo wobufakazi` },
  'f2-1': { en: `Harvest, stock and destinations`, zu: `Isivuno, isitoko nalapho kuya khona` },
  'f2-2': { en: `Sales, payments and expenses`, zu: `Ukuthengisa, izinkokhelo nezindleko` },
  'f2-3': { en: `Reconcile the book and correct mistakes`, zu: `Qhathanisa incwadi bese ulungisa amaphutha` },
  'f3-1': { en: `Direct costs, shared costs and family labour`, zu: `Izindleko eziqondile, izindleko ezabelwanayo nomsebenzi womndeni` },
  'f3-2': { en: `Unit cost, contribution and break-even`, zu: `Izindleko ngeyunithi, umnikelo ne-break-even` },
  'f3-3': { en: `Compare buyers and agree a price`, zu: `Qhathanisa abathengi bese uvumelana ngenani` },
  'f4-1': { en: `Build an enterprise and whole-farm budget`, zu: `Yakha ibhajethi yebhizinisi neyepulazi lonke` },
  'f4-2': { en: `Put receipts and payments on their dates`, zu: `Beka izimali ezingenayo nezinkokhelo ezinsukwini zazo` },
  'f4-3': { en: `Test changes and make a reasoned response`, zu: `Hlola izinguquko bese wenza isinyathelo esinombono` },
  'f5-1': { en: `Follow the order, delivery, invoice and receipt`, zu: `Landela i-oda, ukulethwa, i-invoyisi nokwamukelwa kwemali` },
  'f5-2': { en: `Choose the right invoice route and verify the saved result`, zu: `Khetha indlela efanele ye-invoyisi uphinde uqinisekise umphumela ogciniwe` },
  'f5-3': { en: `Reconcile deposits, part payments and unresolved balances`, zu: `Qhathanisa idiphozithi, izinkokhelo ezingezona ezigcwele nemali esele engakaxazululwa` },
  'f6-1': { en: `Compare buying, hiring and sharing`, zu: `Qhathanisa ukuthenga, ukuqasha nokwabelana` },
  'f6-2': { en: `Read the whole borrowing commitment`, zu: `Funda sonke isibopho sokuboleka` },
  'f6-3': { en: `Set money aside and test a shock`, zu: `Beka imali eceleni bese uhlola isigigaba` },
  'f7-1': { en: `Three views of one business`, zu: `Izindlela ezintathu zokubuka ibhizinisi elilodwa` },
  'f7-2': { en: `Close the period without hiding gaps`, zu: `Vala isikhathi ngaphandle kokufihla izikhala` },
  'f7-3': { en: `Prepare records and ask the right tax questions`, zu: `Lungiselela amarekhodi bese ubuza imibuzo efanele yentela` },
  'f8-1': { en: `Choose an enterprise from evidence`, zu: `Khetha ibhizinisi ngokususela obufakazini` },
  'f8-2': { en: `Turn the idea into a checkable plan`, zu: `Guqula umqondo ube icebo elingahlolwa` },
  'f8-3': { en: `Review the season without rewriting its history`, zu: `Buyekeza isizini ngaphandle kokuloba kabusha umlando wayo` },
};

export const FINANCE_ZU_LESSON_OUTCOME: Record<string, FinanceZuPair> = {
  'f1-1': { en: `Explain why money can enter or leave the farm without being a produce sale or an ordinary production cost.`, zu: `Chaza ukuthi kungani imali ingangena noma iphume epulazini ingabi ukuthengiswa komkhiqizo noma indleko ejwayelekile yokukhiqiza.` },
  'f1-2': { en: `Follow a credit sale into a later payment without counting it twice, and explain why closing cash is not enough to establish profit.`, zu: `Landela ukuthengisa ngesikweletu kuze kube senkokhelweni yakamuva ngaphandle kokukubala kabili, uphinde uchaze ukuthi kungani imali esele ekugcineni ingenele ukubonisa inzuzo.` },
  'f1-3': { en: `Reopen a record, locate its supporting reference, and correct a duplicate or wrong unit without inventing a missing value.`, zu: `Vula kabusha irekhodi, uthole ireferensi elisekelayo, uphinde ulungise okuphindiwe noma iyunithi engalungile ngaphandle kokuqamba inani elingekho.` },
  'f2-1': { en: `Trace one product from opening stock and harvest into its recorded destinations, then compare the calculated remainder with a separate count.`, zu: `Landela umkhiqizo owodwa kusukela esitokweni sokuvula nasesivunweni kuze kufike lapho kurekhodwa khona, bese uqhathanisa insalela ebaliwe nokubalwa okwehlukile.` },
  'f2-2': { en: `Keep delivery, sale and payment linked; track what a buyer still owes; separate an internal transfer from new farm income or spending.`, zu: `Gcina ukulethwa, ukuthengisa nenkokhelo kuxhunyaniswe; landelela lokho umthengi asakweletayo; hlukanisa ukudluliswa kwangaphakathi nemali entsha engenayo noma esetshenzisiwe yepulazi.` },
  'f2-3': { en: `Compare independent evidence with records, locate the cause of a difference, and retain a clear correction trail without concealing an unresolved amount.`, zu: `Qhathanisa ubufakazi obuzimele namarekhodi, uthole imbangela yomehluko, uphinde ugcine umkhondo wokulungiswa ocacile ngaphandle kokufihla imali engakaxazululwa.` },
  'f4-1': { en: `Combine two activity budgets without counting shared bills twice, distinguish cash spending from unpaid resource use, and identify missing costs and capacity evidence.`, zu: `Hlanganisa amabhajethi amabili emisebenzi ngaphandle kokubala izikweletu ezabelwanayo kabili, wehlukanise ukusetshenziswa kwemali yesandla nokusetshenziswa kwezinsiza okungakakhokhelwa, uphinde ukhombe izindleko ezingekho nobufakazi bamandla.` },
  'f4-2': { en: `Calculate a dated cash projection, carry closing balances forward, and detect a shortfall hidden by a positive month-end balance.`, zu: `Bala isibikezelo semali sinezinsuku, uthwale imali esele iye phambili, uphinde uthole igebe elifihlwe yimali esele enhle ekupheleni kwenyanga.` },
  'f4-3': { en: `Change timing, amounts and uncertainty separately, identify combined stress, and explain a response that is feasible before the first shortfall.`, zu: `Shintsha isikhathi, izinani nokungaqiniseki ngokwehlukene, ukhombe ingcindezi ehlangene, uphinde uchaze isinyathelo esingenzeka ngaphambi kwegebe lokuqala.` },
  'f5-1': { en: `Explain what each document proves, preserve the quantity and unit, and distinguish a sale from cash collected against it.`, zu: `Chaza ukuthi idokhumenti ngayinye ifakazelani, ugcine inani neyunithi, uphinde wehlukanise ukuthengisa nemali eqoqwe ngokumelene nakho.` },
  'f5-2': { en: `Choose new, past or paper entry appropriately; preserve a source reference; reopen or link an existing sale; and check the saved result without creating duplicate income.`, zu: `Khetha ukufaka okusha, kwangaphambilini noma kwephepha ngokufanele; ugcine ireferensi lomthombo; uvule kabusha noma uxhumanise ukuthengisa osekukhona; uphinde uhlole umphumela ogciniwe ngaphandle kokudala imali engenayo ephindiwe.` },
  'f5-3': { en: `Keep cash receipts, allocations, adjustments and questions distinct; explain a remaining balance; and know when the current app needs a separate supporting schedule.`, zu: `Gcina ukwamukelwa kwemali, ukwabiwa, ukulungiswa nemibuzo kuhlukene; uchaze imali esele; uphinde wazi ukuthi uhlelo lwamanje ludinga nini uhlu oluhlukile lokusekela.` },
  'f6-1': { en: `Compare the same service need, identify cash tied up before use, retain missing information, and explain why a low purchase contribution does not prove a tool will be available.`, zu: `Qhathanisa isidingo esifanayo senkonzo, ukhombe imali ebotshiwe ngaphambi kokusetshenziswa, ugcine ulwazi olungekho, uphinde uchaze ukuthi kungani umnikelo omncane wokuthenga ungafakazeli ukuthi ithuluzi lizotholakala.` },
  'f6-2': { en: `Reconcile money received, fees, principal and repayment dates; recognise an incomplete quote; and connect a proposed repayment to a dated cash plan without claiming that arithmetic alone proves affordability.`, zu: `Qhathanisa imali etholiwe, izimali zokukhokha, imali eyisisekelo nezinsuku zokubuyisela; ubone ukucaphuna okungaphelele; uphinde uxhumanise ukubuyisela okuhlongozwayo necebo lemali elinezinsuku ngaphandle kokusho ukuthi ukubala kuphela kufakazela ukukwazi ukukhokha.` },
  'f6-3': { en: `Distinguish a reserve allocation from money received or spent, retain restricted/earmarked funds in the correct scope, and identify a later cash gap after an unexpected repair.`, zu: `Yehlukanise ukwabiwa kokugcinelwe nemali etholiwe noma esetshenzisiwe, ugcine imali ekhethelwe umsebenzi othile endaweni yayo efanele, uphinde ukhombe igebe lemali lakamuva ngemva kokulungiswa okungalindelekile.` },
  'f7-1': { en: `Point to the record that answers each question: what cash moved during a period; what income and costs belong to that period; and what the business owns and owes at a date. Explain why one total cannot answer all three.`, zu: `Khomba irekhodi eliphendula umbuzo ngamunye: yimuphi imali eyahamba ngesikhathi esithile; yimuphi imali engenayo nezindleko ezingezalesosikhathi; kanye nalokho ibhizinisi elikunikho nelikukweletayo ngosuku oluthile. Chaza ukuthi kungani inani elilodwa lingekwazi ukuphendula konke okuthathu.` },
  'f7-2': { en: `Separate event, document and payment dates. Explain why stock, equipment, unpaid costs and future services matter at the period boundary. Keep an unsupported value unknown.`, zu: `Hlukanisa izinsuku zesenzakalo, edokhumenti nenkokhelo. Chaza ukuthi kungani isitoko, izinsiza, izindleko ezingakakhokhelwa nezinsiza zesikhathi esizayo zibaluleke emkhawulweni wesikhathi. Gcina inani elingasekelwe lingaziwa.` },
  'f7-3': { en: `Assemble an evidence pack and find the appropriate current official guidance. Distinguish a readable app invoice from a verified compliant tax invoice. State what remains unconfirmed without guessing a tax rate, deadline or registration outcome.`, zu: `Hlanganisa iphakethe lobufakazi bese uthola umhlahlandlela osemthethweni ofanele wamanje. Yehlukanise i-invoyisi yohlelo efundekayo ne-invoyisi yentela eqinisekisiwe nehambisana nemithetho. Sho lokho okusengakaqinisekiswa ngaphandle kokuqagela izinga lentela, usuku lokugcina noma umphumela wokubhaliswa.` },
  'f8-1': { en: `Compare two options using demand evidence, the same period, available resources and dated cash needs; explain a missing assumption before choosing a next action.`, zu: `Qhathanisa izinketho ezimbili usebenzisa ubufakazi besidingo, isikhathi esifanayo, izinsiza ezikhona nezidingo zemali ezinezinsuku; uchaze umcabango ongekho ngaphambi kokukhetha isinyathelo esilandelayo.` },
  'f8-2': { en: `Present a connected plan whose claims lead back to evidence, show timing and constraints, and distinguish an unapproved funding request from available cash.`, zu: `Ethula icebo elixhumene lapho izimangalo zalo ziholela emuva ebufakazini, ubonise isikhathi nemikhawulo, uphinde wehlukanise isicelo soxhaso esingakavunyelwa nemali ekhona.` },
  'f8-3': { en: `Reconcile an original forecast with actual records, separate quantity, price, collection and cost differences, preserve a missing value, and set a justified next action.`, zu: `Qhathanisa isibikezelo sokuqala namarekhodi angempela, uhlukanise imehluko yenani, yentengo, yokuqoqwa neyezindleko, ugcine inani elingekho, uphinde umise isinyathelo esilandelayo esinesizathu.` },
};

export const FINANCE_ZU_LESSON_READING: Record<string, FinanceZuPair> = {
  'f1-1': { en: `Follow what happened. A buyer paid for produce. The owner added some of their own money. The farm borrowed money. All three can put money in the tin, but they are different events. Write the reason beside each amount. When the owner takes money home, record that too. Do not hide it among packaging or transport. The farm and household both matter. Clear records help you see how they support each other.`, zu: `Landela okwenzekile. Umthengi ukhokhele umkhiqizo. Umnikazi wengeze eyakhe imali. Ipulazi liboleke imali. Zontathu zingafaka imali ethinini, kodwa ziyizenzakalo ezahlukene. Bhala isizathu eceleni kwenani ngalinye. Uma umnikazi ethatha imali ayise ekhaya, kurekhode nalokho. Ungakufihli phakathi kokuphakishwa noma ukuthuthwa. Ipulazi nekhaya kubalulekile kokubili. Amarekhodi acacile akusiza ubone ukuthi kusekelana kanjani.` },
  'f1-2': { en: `A buyer can take produce today and pay later. Record the sale and what the buyer owes. When the payment arrives, match it to that sale. The payment clears the amount owed; it is not a second basket sold. Cash answers how much money is available. Profit needs the income and costs for the period. Some costs or stock information may still be missing. Say what you know and what you still need.`, zu: `Umthengi angathatha umkhiqizo namuhla akhokhe kamuva. Rekhoda ukuthengisa nalokho umthengi akukweletayo. Uma inkokhelo ifika, iqondanise nalokho kuthengiswa. Inkokhelo icacisa imali ekweletwayo; akusona isilulu sesibili esithengisiwe. Imali yesandla iphendula ukuthi imali engakanani ekhona. Inzuzo idinga imali engenayo nezindleko zesikhathi. Ezinye izindleko noma ulwazi lwesitoko lungase lusengabikho. Sho lokho okwaziyo nalokho osadinga khona.` },
  'f1-3': { en: `Give each record a date and a clear reason. Keep the receipt, invoice or another useful reference. After saving, open the entry again and compare it with the source. Check the amount and the unit. A kilogram and a bunch are different. If evidence is missing, write what is unknown. Do not use zero to mean ‘I do not know’. Keep a note of a correction so you can explain it later.`, zu: `Nikeza irekhodi ngalinye usuku nesizathu esicacile. Gcina irisidi, i-invoyisi noma enye ireferensi ewusizo. Ngemva kokugcina, vula kabusha okufakiwe uphinde ukuqhathanise nomthombo. Hlola inani neyunithi. Ikhilogremu nesixha kuyahluka. Uma ubufakazi bungekho, bhala lokho okungaziwa. Ungasebenzisi u-0 ukusho ukuthi 'angazi'. Gcina inothi lokulungiswa ukuze ukwazi ukukuchaza kamuva.` },
  'f2-1': { en: `Start with what was already here. Add what you picked. Record what left and why. A sale, food for home and a gift are different uses. Keep the same unit. At the end, count or weigh what is still here. Compare that with the book. If they differ, look for the cause. A difference is a question to investigate, not proof that someone stole food.`, zu: `Qala ngalokho obekukhona kakade. Engeza lokho okuvuniwe. Rekhoda lokho okuphumile nesizathu sakho. Ukuthengisa, ukudla kwasekhaya nesipho kuwukusetshenziswa okuhlukene. Gcina iyunithi efanayo. Ekugcineni, bala noma kalinganise lokho okusekhona. Kuqhathanise nencwadi. Uma kuhluka, funa imbangela. Umehluko ungumbuzo okufanele uwuphenye, hhayi ubufakazi bokuthi kukhona oweba ukudla.` },
  'f2-2': { en: `Write the sale when the agreed produce is delivered in this exercise. Keep the payment beside that sale, with the date it arrived. If only some money arrives, show what is still owed. Moving your own money from the cash tin to the wallet does not create another sale. It changes where the money is kept. A fee is a separate payment if the evidence shows one. Keep the amount and cents from the source.”

This exercise's agreed delivery is the point used to record its sale. It is not a rule covering every contract, deposit, return or accounting policy. Those need their own terms and bookkeeping review.`, zu: `Bhala ukuthengisa lapho umkhiqizo ovunyelwene ngawo ulethwa kulesi sifundo. Gcina inkokhelo eceleni kwaleso kuthengisa, nosuku efika ngalo. Uma imali engaphelele ifika, bonisa lokho okusakweletwa. Ukudlulisa eyakho imali kusuka ethinini kuya esikhwameni akudali okunye ukuthengisa. Kushintsha lapho imali igcinwe khona. Imali yenkokhelo iyinkokhelo ehlukile uma ubufakazi bubonisa njalo. Gcina inani namasenti kusukela emthonjeni.

Ukulethwa okuvunyelwene ngakho kulesi sifundo yipoyinti elisetshenziswa ukurekhoda ukuthengiswa kwaso. Akulona umthetho omboza zonke izinkontileka, idiphozithi, ukubuyisa noma inqubomgomo yokugcina amabhuku. Lezo zidinga imigomo yazo kanye nokubuyekezwa kokugcinwa kwamabhuku.` },
  'f2-3': { en: `Reconcile means compare and explain. Count the cash. Read the wallet statement. Match deliveries, sales, payments and receipts by their references. Check the dates and units as well as the totals. When you find a mistake, keep the original reference and write what changed and why. If you cannot explain a difference yet, say so. Do not add a guessed entry just to make the totals agree.`, zu: `Ukuqhathanisa kusho ukuqhathanisa nokuchaza. Bala imali yesandla. Funda isitatimende sesikhwama. Qondanisa ukulethwa, ukuthengisa, izinkokhelo nokwamukelwa kwemali ngamareferensi awo. Hlola izinsuku namayunithi kanye namanani ayo onke. Uma uthola iphutha, gcina ireferensi yokuqala bese ubhala lokho okushintshile nesizathu sakho. Uma ungakwazi ukuchaza umehluko okwamanje, sho njalo. Ungangezi okufakiwe ngokuqagela ukuze nje amanani onke avumelane.` },
  'f3-1': { en: `Start with a product and a period. A direct cost belongs to that product. A shared cost serves more than one product. Use a record of how it was used to divide it, and explain your choice. Divide the cost; do not copy the whole bill into both crops. Keep the family's work hours visible too. No wage paid does not mean no work done. An amount used to value that time is different from cash paid out.`, zu: `Qala ngomkhiqizo nesikhathi. Indleko eqondile ingeyalowo mkhiqizo. Indleko eyabelwanayo isebenzela ngaphezu komkhiqizo owodwa. Sebenzisa irekhodi lokuthi kwasetshenziswa kanjani ukuyihlukanisa, bese uchaza ukukhethwa kwakho. Hlukanisa indleko; ungakopishi sonke isikweletu uyifake kuzo zombili izitshalo. Gcina namahora omsebenzi womndeni ebonakala. Ukungakhokhelwa umholo akusho ukuthi awukho umsebenzi owenziwe. Inani elisetshenziswa ukulinganisa leso sikhathi lihlukile kwimali ekhokhiwe.` },
  'f3-2': { en: `A cost per unit needs two things: the costs you included and the quantity you divided by. Say both. Produce available for sale is not always produce sold. A selling price may cover some costs and still leave others unpaid. Contribution is what remains after the included variable costs. It must still cover fixed costs. A break-even answer is useful only when its assumptions fit and the required sales can be achieved.`, zu: `Indleko ngeyunithi idinga izinto ezimbili: izindleko ozifakile nenani owahlukanise ngalo. Sho zombili. Umkhiqizo okhona ukuze uthengiswe akusho njalo ukuthi ngumkhiqizo osuthengisiwe. Intengo yokuthengisa ingase imboze ezinye izindleko kodwa ishiye ezinye zingakhokhelwa. Umnikelo yilokho okusalayo ngemva kwezindleko eziguquguqukayo ezifakiwe. Kusadingeka ukuthi umboze izindleko ezimile. Impendulo ye-break-even iwusizo kuphela lapho imicabango yayo ihambisana futhi ukuthengisa okudingekayo kungafinyelelwa.` },
  'f3-3': { en: `Compare the whole offer. Check the weight, quality, price, packaging, delivery and payment date. Use the same unit for both buyers. A higher price can leave less after delivery. Money promised for next week is not money available today. Write down what is agreed, and check what is still unknown before choosing.`, zu: `Qhathanisa sonke isiphakamiso. Hlola isisindo, ikhwalithi, inani, ukuphakishwa, ukulethwa nosuku lwenkokhelo. Sebenzisa iyunithi efanayo kubo bobabili abathengi. Inani eliphakeme lingashiya okuncane ngemva kokulethwa. Imali ethenjisiwe ngesonto elizayo akuyona imali ekhona namuhla. Bhala phansi lokho okuvunyelwene ngakho, uphinde uhlole lokho okusengaziwa ngaphambi kokukhetha.` },
  'f4-1': { en: `A budget is a plan with reasons behind the numbers. Name the activity and the period. Show what you expect to sell and what you expect to use. Keep shared bills once in the farm total. Family work still matters when no wage is paid. Write down what you do not yet know. A positive answer on paper does not prove that the land, water, time or buyers are available.`, zu: `Ibhajethi iyicebo elinezizathu ngemuva kwezinombolo. Qamba umsebenzi nesikhathi. Bonisa lokho ohlose ukukuthengisa nalokho ohlose ukukusebenzisa. Gcina izikweletu ezabelwanayo kanye kuphela enanini lonke lepulazi. Umsebenzi womndeni usabalulekile lapho kungakhokhelwa muholo. Bhala phansi lokho ongakakwazi. Impendulo enhle ephepheni ayifakazeli ukuthi umhlaba, amanzi, isikhathi noma abathengi bayatholakala.` },
  'f4-2': { en: `Start with money that is available at the beginning. Add a receipt when you expect the money to arrive. Subtract a payment when it must leave. Carry the balance to the next date. An invoice is not cash received. Check the dates between month ends too. A good total at the end cannot pay a bill that comes before the money arrives.`, zu: `Qala ngemali ekhona ekuqaleni. Engeza imali engenayo lapho ulindele ukuthi imali ifike. Susa inkokhelo lapho kudingeka ukuthi iphume. Thwala imali esele iye osukwini olulandelayo. I-invoyisi akuyona imali etholiwe. Hlola nezinsuku phakathi kokuphela kwezinyanga. Inani elihle ekugcineni alikwazi ukukhokha isikweletu esifika ngaphambi kokuthi imali ifike.` },
  'f4-3': { en: `Ask what changes if the buyer pays late, less produce sells, or an input costs more. Change the matching card and recalculate from that point onward. A delay changes when cash arrives. A lower sale changes how much arrives. Test them together too. Write down the evidence needed for your response, and check the plan again before committing.`, zu: `Buza ukuthi yini eshintshayo uma umthengi ekhokha sekwephuze, kuthengiswa umkhiqizo omncane, noma into esetshenziswa ekukhiqizeni ibiza kakhulu. Shintsha ikhadi elifanayo bese ubala kabusha kusukela kuleyo ndawo kuqhubeke. Ukubhala kwephuza kushintsha ukuthi imali ifika nini. Ukuthengisa okuncane kushintsha ukuthi kufika malini. Zihlole futhi kanyekanye. Bhala phansi ubufakazi obudingekayo esinyathelweni sakho, bese uhlola icebo futhi ngaphambi kokuzibophezela.` },
  'f5-1': { en: `Keep the story of one sale together. First, agree what the buyer wants and how payment will work. Check what you deliver. Check the invoice against that delivery and the agreed price. When money arrives, match it to the same invoice. The payment does not create another basket of produce. Keep its date and reference so you can show what is still owed.`, zu: `Gcina indaba yokuthengisa okukodwa ihlangene. Okokuqala, vumelana ngalokho umthengi akufunayo nokuthi inkokhelo izosebenza kanjani. Hlola lokho okulethayo. Qhathanisa i-invoyisi nalokho kulethwa nenani elivunyelwene ngalo. Uma imali ifika, iqondanise ne-invoyisi efanayo. Inkokhelo ayidali esinye isilulu somkhiqizo. Gcina usuku nereferensi lwayo ukuze ukwazi ukubonisa lokho okusakweletwa.` },
  'f5-2': { en: `Look in your records before you add anything. If the invoice is already there, open it. If the sale is there but needs an invoice, use that sale. If you are bringing in an older or paper record, keep its original reference and dates. Read the save message. Open the saved document and check it. A second copy of a document must not become a second sale.`, zu: `Bheka emarekhodini akho ngaphambi kokungeza noma yini. Uma i-invoyisi isivele ikhona, iyivule. Uma ukuthengisa sekukhona kodwa kudinga i-invoyisi, sebenzisa lokho kuthengisa. Uma ungenisa irekhodi lakudala noma lephepha, gcina ireferensi nezinsuku zalo zangempela. Funda umlayezo wokugcina. Vula idokhumenti egciniwe uyihlole. Ikhophi yesibili yedokhumenti akufanele ibe ukuthengisa kwesibili.` },
  'f5-3': { en: `Write down every payment once, with its evidence. A deposit may arrive before produce is delivered. Keep it linked to that customer and order. Later, applying that same deposit to an invoice does not bring in more money. Keep questions and agreed corrections visible. If money arrives and you do not know who sent it, investigate before matching it to a sale.`, zu: `Bhala phansi inkokhelo ngayinye kanye kuphela, nobufakazi bayo. Idiphozithi ingafika ngaphambi kokuba umkhiqizo ulethwe. Igcine ixhunyaniswe naleyo khasimende nakuleyo oda. Kamuva, ukusebenzisa leyo diphozithi efanayo ku-invoyisi akulethi imali eyengeziwe. Gcina imibuzo nokulungiswa okuvunyelwene ngakho kubonakala. Uma imali ifika ungazi ukuthi ithunyelwe ngubani, phenya ngaphambi kokuyiqondanisa nokuthengisa.` },
  'f6-1': { en: `Start with the work you need done and the dates. Ask what each offer includes. Buying, hiring and sharing move money at different times. A deposit may come back later, but you still need it before use. Keep the value of a tool you still own separate from cash in your hand. Check who can use a shared tool, when it is available and who pays for damage or repairs.`, zu: `Qala ngomsebenzi odinga wenziwe nezinsuku. Buza ukuthi isiphakamiso ngasinye sifaka ini. Ukuthenga, ukuqasha nokwabelana kuhambisa imali ngezikhathi ezahlukene. Idiphozithi ingase ibuye kamuva, kodwa usadinga yona ngaphambi kokusebenzisa. Gcina inani lethuluzi osenalo lihlukile kwimali esesandleni sakho. Hlola ukuthi ubani ongasebenzisa ithuluzi elabelwanayo, ithuluzi litholakala nini nokuthi ubani okhokha ngomonakalo noma ngokulungiswa.` },
  'f6-2': { en: `The amount borrowed is not the amount you may have left to spend. Read the fees and when they are paid. Each instalment may contain repayment of the amount borrowed, interest and other charges. If a charge is already included, do not add it again. Keep the dates. A smaller-looking instalment is not enough information to choose a loan.`, zu: `Imali ebolekiwe akuyona imali esasele ukuze uyisebenzise. Funda izimali zokukhokha nokuthi zikhokhwa nini. Inkokhiso ngayinye ingase iqukathe ukubuyiselwa kwemali ebolekiwe, inzalo nezinye izindleko. Uma indleko isivele ifakiwe, ungayengezi futhi. Gcina izinsuku. Inkokhiso ebonakala incane ayanele njengolwazi lokukhetha imalimboleko.` },
  'f6-3': { en: `Setting money aside gives it a job. It does not create more money. If you move it between two accounts you own, the total is unchanged unless there is a fee. When you pay someone else for a repair, money leaves. Keep the amount still set aside separate from money for daily work. A reserve target is a plan, not an account balance.`, zu: `Ukubeka imali eceleni kuyinika umsebenzi. Akudali imali eyengeziwe. Uma uyidlulisa phakathi kwama-akhawunti amabili ongawe, inani lonke alishintshi ngaphandle uma kukhona imali yokukhokha. Uma ukhokhela omunye umuntu ngokulungiswa, imali iyaphuma. Gcina inani elisagcinelwe lihlukile kwimali yomsebenzi wansuku zonke. Umgomo wokugcinela iyicebo, hhayi imali esele ku-akhawunti.` },
  'f7-1': { en: `Start by saying which business and which dates you mean. Our stall starts with money, stock, equipment and amounts owed. A cash summary follows money received and paid. A profit-and-loss view follows the period's income and costs. A balance sheet shows the position on a date: assets, liabilities and what remains for the owner. The views are connected, but their totals need not match. Borrowed money increases cash and debt. It does not become a sale. A customer can owe us for goods already delivered. That sale can be recorded before the money reaches us.`, zu: `Qala ngokusho ukuthi ibhizinisi elinye nezinsuku ezinye ozisho. Isitolo sethu siqala ngemali, isitoko, izinsiza nemali ekweletwayo. Isifinyezo semali yesandla silandela imali etholiwe nekhokhiwe. Umbono wenzuzo-nokulahlekelwa ulandela imali engenayo nezindleko zesikhathi. Ishidi lebhalansi libonisa isimo ngosuku oluthile: impahla, izikweletu nalokho okusalayo emnikazini. Imibono ixhumene, kodwa amanani ayo awadingi ukufana. Imali eboliwe yandisa imali yesandla nesikweletu. Ayibi ukuthengisa. Ikhasimende lingasikweleta ngempahla esivele ilethiwe. Lokho kuthengisa kungarekhodwa ngaphambi kokuba imali ifike kithi.` },
  'f7-2': { en: `A document can arrive after the work. Payment can happen before or after the service. Keep those dates together. At the end of our month, ask what was delivered, used, owed and still available. A bank line alone cannot answer every question. Check the stock and equipment records too. When evidence is missing, write what you still need. Do not enter zero just to finish a total.`, zu: `Idokhumenti ingafika ngemva komsebenzi. Inkokhelo ingenzeka ngaphambi noma ngemva kwenkonzo. Gcina lezo zinsuku zihlangene. Ekupheleni kwenyanga yethu, buza ukuthi yini elethiwe, esetshenzisiwe, ekweletwayo nesekhona. Umugqa webhange wodwa awukwazi ukuphendula yonke imibuzo. Hlola nemarekhodi esitoko nezinsiza. Uma ubufakazi bungekho, bhala lokho osadinga khona. Ungafaki u-0 ukuze nje uqede inani.` },
  'f7-3': { en: `Keep the story behind a number. Who supplied what? When did it happen? Which document supports it? Which money movement belongs with it? Keep records organised and safe. Tax and record duties depend on the business and its circumstances. Use current SARS guidance and suitable help. A saved invoice, tax-reference field or app export cannot confirm all those duties for you.`, zu: `Gcina indaba engemuva kwenombolo. Ubani ohlinzeke ini? Kwenzeke nini? Yiliphi idokhumenti elikusekelayo? Iyiphi ukuhamba kwemali okungeyakho? Gcina amarekhodi ehlelekile futhi ephephile. Imisebenzi yentela namarekhodi incike ebhizinisini nasezimweni zalo. Sebenzisa umhlahlandlela wamanje we-SARS nosizo olufanele. I-invoyisi egciniwe, isikhala se-tax reference noma ukukhishwa kohlelo akukwazi ukuqinisekisa yonke leyo misebenzi.` },
  'f8-1': { en: `Start with a buyer and a task you can deliver. What does the buyer need? How much, in which unit, at what quality, and by when? Interest is not an order. A high sales total does not tell you what you will keep or whether you can pay the earlier bills. Put the alternatives beside each other. Keep the missing evidence visible.`, zu: `Qala ngomthengi nomsebenzi ongawuletha. Umthengi udingani? Malini, ngayiphi iyunithi, ngayiphi ikhwalithi, futhi kunini? Ukuthakazelela akulona i-oda. Inani eliphakeme lokuthengisa alikutsheli ukuthi uzosala nani noma ungakwazi yini ukukhokha izikweletu zangaphambilini. Beka izinketho eduze komunye nomunye. Gcina ubufakazi obungekho bubonakala.` },
  'f8-2': { en: `A useful plan lets another person follow your reasoning. Say what you intend to sell, why a buyer may want it, and what you need to deliver it. Show the work and payments in order. Keep estimates separate from records. If a number or permission is missing, name it and say how you will check it. A neat document cannot turn an application into money.`, zu: `Icebo eliwusizo livumela omunye umuntu ukuthi alandele umqondo wakho. Sho lokho ohlose ukukuthengisa, ukuthi kungani umthengi engase akufune, nalokho okudingayo ukuze ukulethe. Bonisa umsebenzi nezinkokhelo ngokulandelana. Gcina izilinganiso zihlukile emarekhodini. Uma inombolo noma imvume ingekho, iqambe uphinde usho ukuthi uzoyihlola kanjani. Idokhumenti ehlelekile ayikwazi ukuguqula isicelo sibe imali.` },
  'f8-3': { en: `Keep the plan you started with. Put the actual records beside it for the same period and units. What sold? What money arrived? What was paid? Which amounts are still owed? Explain each difference with evidence before saying why it happened. Then make the next plan. Changing the old plan to match the result hides what you learned.`, zu: `Gcina icebo owaqala ngalo. Beka amarekhodi angempela eceleni kwalo esikhathini nasemayunithini afanayo. Yini eyathengiswa? Yimalini efikile? Kwakhokhwani? Yimalini esakweletwa? Chaza umehluko ngamunye ngobufakazi ngaphambi kokusho ukuthi kwenzekeni. Bese wenza icebo elilandelayo. Ukushintsha icebo elidala ukuze lifanane nomphumela kufihla lokho okufundile.` },
};

// The practical project's worksheet (lib/finance-project.ts, components/studies/FinanceProjectWorksheet.tsx).
// Keyed by PROJECT_NUMBER_QUESTIONS/PROJECT_REASONING's own `id`, paired against their live `label`
// (and `prompt` for the reasoning questions) exactly as financeZu() expects.
export const FINANCE_ZU_PROJECT_NUMBER_LABEL: Record<string, FinanceZuPair> = {
  closingGrams: { en: `Harvest left at month end`, zu: `Isivuno esisele ekupheleni kwenyanga` },
  knownPlannedCosts: { en: `Total of the two included packaging and transport quotes`, zu: `Inani lezicaphuno ezimbili ezifakiwe zokuphakishwa nokuthutha` },
  plannedMinimum: { en: `Lowest forecast cash balance, including any gap as a negative number`, zu: `Imali yesandla ephansi kunazo zonke ebikeziwe, kufaka igebe njengenombolo engaphansi kuka-0` },
  plannedClosing: { en: `Closing cash in the original forecast`, zu: `Imali esele ekugcineni esibikezelweni sokuqala` },
  actualSales: { en: `Value of produce actually delivered and invoiced`, zu: `Inani lomkhiqizo ngempela olethiwe nolu-invoyiswe` },
  received: { en: `Payment received from the buyer within this month`, zu: `Inkokhelo etholiwe kumthengi kule nyanga` },
  owed: { en: `Amount the buyer still owes at month end`, zu: `Imali umthengi asakweletayo ekupheleni kwenyanga` },
  actualClosing: { en: `Actual closing cash after all supplied cash movements`, zu: `Imali yangempela esele ngemva kwakho konke ukuhamba kwemali okuhlinzekiwe` },
  cashDifference: { en: `Actual closing cash minus original forecast closing cash`, zu: `Imali yangempela esele ohlisiwe imali esele esibikezelweni sokuqala` },
};

export const FINANCE_ZU_PROJECT_REASONING_LABEL: Record<string, FinanceZuPair> = {
  trail: { en: `Show your evidence trail`, zu: `Bonisa umkhondo wakho wobufakazi` },
  plan: { en: `Explain the plan and the shortfall`, zu: `Chaza icebo negebe lemali` },
  review: { en: `Explain what actually changed`, zu: `Chaza lokho okwashintsha ngempela` },
  limits: { en: `Keep the unknowns visible`, zu: `Gcina lokho okungaziwa kubonakala` },
  action: { en: `Write a practical next step`, zu: `Bhala isinyathelo esilandelayo esisebenzayo` },
};

export const FINANCE_ZU_PROJECT_REASONING_PROMPT: Record<string, FinanceZuPair> = {
  trail: { en: `Name the order, delivery, invoice and payment references. Explain why they describe one sale. Keep the later payment outside this month. Explain how you would show the unpaid balance without marking the invoice paid in full.`, zu: `Qamba amareferensi we-oda, ukulethwa, i-invoyisi nenkokhelo. Chaza ukuthi kungani achaza ukuthengisa okukodwa. Gcina inkokhelo yakamuva ingaphandle kwale nyanga. Chaza ukuthi ungayibonisa kanjani imali esele engakakhokhelwa ngaphandle kokumaka i-invoyisi njengekhokhiwe ngokugcwele.` },
  plan: { en: `Keep the original forecast. Identify when cash first falls short and what evidence would be needed before changing the plan. Compare the basket alternative, keeping items and kilograms separate. Check buyer commitment and available work hours.`, zu: `Gcina isibikezelo sokuqala. Khomba ukuthi imali iqala nini ukwehluleka futhi yini ubufakazi obudingekayo ngaphambi kokushintsha icebo. Qhathanisa enye indlela yesilulu, ugcine izinto namakhilogremu kuhlukene. Hlola isibopho somthengi namahora omsebenzi akhona.` },
  review: { en: `Explain the effects of quantity, payment timing, actual expenses, funding and household withdrawal. A matching closing total does not prove the plan was followed. Name the source of each difference.`, zu: `Chaza imiphumela yenani, isikhathi senkokhelo, izindleko zangempela, uxhaso nokukhishwa kwemali yasekhaya. Inani lokugcina elifanayo alifakazeli ukuthi icebo lalandelwa. Qamba umthombo womehluko ngamunye.` },
  limits: { en: `Explain why the water charge cannot be entered as zero, why closing cash is not full profit, and what evidence is missing. Explain why a mapped plot does not prove land rights or harvest. Classify the funding card as its stated owner contribution or loan, not sales.`, zu: `Chaza ukuthi kungani imali yamanzi ingafakwa njenga-0, ukuthi kungani imali esele ingeyona inzuzo egcwele, nokuthi yini ubufakazi obungekho. Chaza ukuthi kungani isiza esidwetshiwe singafakazeli amalungelo omhlaba noma isivuno. Hlela ikhadi loxhaso njengomnikelo womnikazi noma imalimboleko esho, hhayi ukuthengisa.` },
  action: { en: `Write one action, the evidence needed, who would obtain it, and a review date. Use classroom roles and dates only. Do not put real customer, household or bank details here.`, zu: `Bhala isinyathelo esisodwa, ubufakazi obudingekayo, ubani ozobuthola, nosuku lokubuyekeza. Sebenzisa izindima nezinsuku zasekilasini kuphela. Ungafaki imininingwane yangempela yamakhasimende, yasekhaya noma yebhange lapha.` },
};
