/**
 * Optional hand-drawn artwork per crop, keyed by CropDef.key from
 * lib/crop-catalog.ts. Deliberately a SIBLING lookup rather than a field on
 * CropDef itself — lib/crop-catalog.ts has in-flight unpushed changes on
 * another branch (codex/crop-plan-continuity), so this file avoids touching
 * it at all.
 *
 * Falls back to the crop's existing emoji `icon` wherever a key has no entry
 * here, so wiring this lookup in cannot change what a farmer sees until real
 * art actually exists for that crop. See docs/CROP-ART-BRIEF.md for the
 * generation brief, the self-check script, and the naming convention
 * (public/crop-art/<key>.png).
 *
 * All 26 catalog crops now have art — generated by Codex, self-checked
 * (1024x1024 RGBA, transparent corners, 10-85% transparent fraction) and
 * visually spot-checked for the 11 green-dominant crops the brief flagged
 * as collision risks.
 */
export const CROP_ART: Record<string, string> = {
  maize: '/crop-art/maize.png',
  'dry-beans': '/crop-art/dry-beans.png',
  'green-beans': '/crop-art/green-beans.png',
  butternut: '/crop-art/butternut.png',
  pumpkin: '/crop-art/pumpkin.png',
  'swiss-chard': '/crop-art/swiss-chard.png',
  kale: '/crop-art/kale.png',
  cabbage: '/crop-art/cabbage.png',
  carrots: '/crop-art/carrots.png',
  beetroot: '/crop-art/beetroot.png',
  onions: '/crop-art/onions.png',
  tomatoes: '/crop-art/tomatoes.png',
  peppers: '/crop-art/peppers.png',
  'sweet-potato': '/crop-art/sweet-potato.png',
  potato: '/crop-art/potato.png',
  lettuce: '/crop-art/lettuce.png',
  amadumbe: '/crop-art/amadumbe.png',
  groundnuts: '/crop-art/groundnuts.png',
  garlic: '/crop-art/garlic.png',
  peas: '/crop-art/peas.png',
  'broad-beans': '/crop-art/broad-beans.png',
  broccoli: '/crop-art/broccoli.png',
  cucumber: '/crop-art/cucumber.png',
  watermelon: '/crop-art/watermelon.png',
  coriander: '/crop-art/coriander.png',
  oats: '/crop-art/oats.png',
};

/** Returns the art path for a crop key, or undefined if none exists yet. */
export function getCropArt(key: string): string | undefined {
  return CROP_ART[key];
}
