// Design Studio — element catalog.
//
// Pure data module (no 'use client' needed, but harmless either way): every placeable
// item a farmer can drop onto the Design Studio canvas, at true real-world footprint
// scale (wM/hM in metres). Mirrors the conventions in lib/site-elements.ts (icon/color
// metadata keyed by a string id) but keeps its own storage-free catalog — this file
// has no localStorage of its own; placement state lives in lib/design-canvas.ts.

export type ElementCategory = 'water' | 'structure' | 'growing' | 'animal' | 'access';

export interface DesignElementDef {
  id: string;
  category: ElementCategory;
  name: string;
  icon: string; // emoji
  shape: 'circle' | 'rect'; // footprint drawn at true scale
  wM: number; // footprint metres (circle: wM = diameter, hM = wM)
  hM: number;
  color: string; // accent hex
  zoneRec: number[] | null; // recommended zones, e.g. [1,2]
  tip: string; // one-line placement tip shown on select
  castsShade?: boolean; // large canopy → southern-hemisphere shade rule
  needsSun?: boolean; // veg/beds → shade victim
  nearRoofM?: number; // should be within N metres of house/structure (tanks)
  nearHouseMaxM?: number; // daily-use max distance from house (herbs/veg)
}

export const ZONE_COLORS: Record<0 | 1 | 2 | 3 | 4 | 5, string> = {
  0: '#3A352C',
  1: '#B53A3A',
  2: '#C66A1C',
  3: '#9B8B1E',
  4: '#2F7A4A',
  5: '#1A6B58',
};

export const ZONE_KEY: Array<{ z: 0 | 1 | 2 | 3 | 4 | 5; label: string; desc: string }> = [
  { z: 0, label: 'House', desc: 'Dwelling & immediate surroundings' },
  { z: 1, label: 'Daily use', desc: 'Herbs, kitchen garden, chickens' },
  { z: 2, label: 'Intensive', desc: 'Veggie beds, small animals' },
  { z: 3, label: 'Orchard / food forest', desc: 'Trees, perennials, larger plots' },
  { z: 4, label: 'Low-care', desc: 'Grazing, woodlot, fodder' },
  { z: 5, label: 'Conservation / buffer', desc: 'Wild, tree belts, boundary' },
];

export const CATEGORY_META: Record<ElementCategory, { label: string; icon: string }> = {
  water: { label: 'Water', icon: '💧' },
  structure: { label: 'Structures', icon: '🏚️' },
  growing: { label: 'Growing', icon: '🌱' },
  animal: { label: 'Animals', icon: '🐔' },
  access: { label: 'Access & Extras', icon: '🚪' },
};

// Reuse the app's existing zone palette (see components/GeometryDesignStudio.tsx ZONE_COLORS /
// ZONE_KEY): 0 charcoal House, 1 red Daily use, 2 orange Intensive, 3 amber Orchard/food forest,
// 4 pale-green Low-care, 5 teal Conservation/buffer.
export const ZONE_DEFS: Record<0 | 1 | 2 | 3 | 4 | 5, { label: string; color: string }> = {
  0: { label: ZONE_KEY[0].label, color: ZONE_COLORS[0] },
  1: { label: ZONE_KEY[1].label, color: ZONE_COLORS[1] },
  2: { label: ZONE_KEY[2].label, color: ZONE_COLORS[2] },
  3: { label: ZONE_KEY[3].label, color: ZONE_COLORS[3] },
  4: { label: ZONE_KEY[4].label, color: ZONE_COLORS[4] },
  5: { label: ZONE_KEY[5].label, color: ZONE_COLORS[5] },
};

import type { GroundFeatureKind } from '@/lib/design-canvas';

// Ground/built features the farmer draws to record WHAT IS THERE (house, paving, lawn,
// existing veg garden, orchard, cleared ground). Rendered as filled, labelled polygons —
// deliberately reading as solid ground, distinct from the dashed permaculture effort-zone
// rings. Colours: roof grey, light paving grey, soft lawn green, kitchen-green veg,
// deeper orchard green, neutral cleared.
export const GROUND_FEATURES: Record<GroundFeatureKind, { label: string; color: string; icon: string }> = {
  house: { label: 'House', color: '#8A8D91', icon: '🏠' },
  patio: { label: 'Patio / Paving', color: '#C7C3BB', icon: '▦' },
  lawn: { label: 'Lawn', color: '#8FBF6B', icon: '🟩' },
  veg_garden: { label: 'Veg garden', color: '#4E8B3B', icon: '🥬' },
  orchard: { label: 'Orchard / food forest', color: '#2F7A4A', icon: '🌳' },
  cleared: { label: 'Cleared / other', color: '#B8AF9E', icon: '⬚' },
};

export const ELEMENT_CATALOG: DesignElementDef[] = [
  {
    id: 'jojo_1000',
    category: 'water',
    name: 'JoJo Tank 1000L',
    icon: '⛽',
    shape: 'circle',
    wM: 1,
    hM: 1,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    nearRoofM: 3,
    tip: 'Place within 3 m of a roof downpipe on a compacted, level base.',
  },
  {
    id: 'jojo_2500',
    category: 'water',
    name: 'JoJo Tank 2500L',
    icon: '⛽',
    shape: 'circle',
    wM: 1.4,
    hM: 1.4,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    nearRoofM: 3,
    tip: 'Needs a solid concrete ring base — full tank weighs ~2.5 t.',
  },
  {
    id: 'jojo_5000',
    category: 'water',
    name: 'JoJo Tank 5000L',
    icon: '⛽',
    shape: 'circle',
    wM: 1.85,
    hM: 1.85,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    nearRoofM: 3,
    tip: '1.82 m diameter — check eave clearance and allow space to walk around for maintenance.',
  },
  {
    id: 'jojo_10000',
    category: 'water',
    name: 'JoJo Tank 10000L',
    icon: '⛽',
    shape: 'circle',
    wM: 2.2,
    hM: 2.2,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    nearRoofM: 3,
    tip: '2.2 m diameter, 3.15 m tall — site on a reinforced slab near the largest roof catchment.',
  },
  {
    id: 'rain_barrel',
    category: 'water',
    name: 'Rain Barrel',
    icon: '🛢️',
    shape: 'circle',
    wM: 0.6,
    hM: 0.6,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    nearRoofM: 3,
    tip: 'Good starter option under a small downpipe before investing in a JoJo.',
  },
  {
    id: 'pond_small',
    category: 'water',
    name: 'Small Pond',
    icon: '🐸',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#2F7A4A',
    zoneRec: [3, 4],
    tip: 'Line with clay or pond liner; site in a natural low point to catch runoff.',
  },
  {
    id: 'dam',
    category: 'water',
    name: 'Farm Dam',
    icon: '🌊',
    shape: 'circle',
    wM: 12,
    hM: 12,
    color: '#2F7A4A',
    zoneRec: [4],
    tip: 'Site on-contour below a catchment area; check DWS licensing thresholds for dam size.',
  },
  {
    id: 'greywater_basin',
    category: 'water',
    name: 'Greywater Basin',
    icon: '♻️',
    shape: 'circle',
    wM: 1.5,
    hM: 1.5,
    color: '#2F7A4A',
    zoneRec: [1, 2],
    tip: 'Feed from kitchen/laundry outlet into a mulch-filled banana or fruit tree basin.',
  },
  {
    id: 'borehole',
    category: 'water',
    name: 'Borehole',
    icon: '🕳️',
    shape: 'circle',
    wM: 0.6,
    hM: 0.6,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    tip: 'Get a hydrogeological siting survey before drilling — avoid septic/kraal runoff zones.',
  },
  {
    id: 'tap_point',
    category: 'water',
    name: 'Tap Point',
    icon: '🚰',
    shape: 'circle',
    wM: 0.4,
    hM: 0.4,
    color: '#2F7A4A',
    zoneRec: [0, 1],
    tip: 'Place at bed corners for easy hose access without crossing paths.',
  },
  {
    id: 'water_trough',
    category: 'water',
    name: 'Water Trough',
    icon: '🥛',
    shape: 'rect',
    wM: 0.6,
    hM: 2,
    color: '#2F7A4A',
    zoneRec: [4],
    tip: 'Position on firm, well-drained ground away from the dam edge to reduce erosion.',
  },
  {
    id: 'shed',
    category: 'structure',
    name: 'Shed',
    icon: '🏚️',
    shape: 'rect',
    wM: 3,
    hM: 3,
    color: '#7A5C3E',
    zoneRec: [1, 2],
    tip: 'Keep tools near the main work zone but out of prevailing rain direction.',
  },
  {
    id: 'greenhouse_tunnel',
    category: 'structure',
    name: 'Greenhouse Tunnel',
    icon: '🏡',
    shape: 'rect',
    wM: 3,
    hM: 6,
    color: '#7A5C3E',
    zoneRec: [1, 2],
    tip: 'Orient the ridge north-south for even light; anchor well against wind.',
  },
  {
    id: 'shade_house',
    category: 'structure',
    name: 'Shade House',
    icon: '🕶️',
    shape: 'rect',
    wM: 3,
    hM: 3,
    color: '#7A5C3E',
    zoneRec: [1, 2],
    tip: 'Use 40-50% shade netting for SA summer sun; site near the nursery table.',
  },
  {
    id: 'chicken_coop',
    category: 'structure',
    name: 'Chicken Coop',
    icon: '🐔',
    shape: 'rect',
    wM: 2,
    hM: 2,
    color: '#7A5C3E',
    zoneRec: [2, 3],
    tip: 'Close enough for daily egg collection, downwind of the house.',
  },
  {
    id: 'chicken_tractor',
    category: 'structure',
    name: 'Chicken Tractor',
    icon: '🚜',
    shape: 'rect',
    wM: 1.2,
    hM: 2.4,
    color: '#7A5C3E',
    zoneRec: [2, 3],
    tip: 'Movable — rotate across beds or orchard rows for pest control and manure.',
  },
  {
    id: 'kraal',
    category: 'structure',
    name: 'Kraal',
    icon: '🐄',
    shape: 'rect',
    wM: 6,
    hM: 6,
    color: '#7A5C3E',
    zoneRec: [3, 4],
    tip: 'Site downhill and downwind of the house; capture runoff for a manure compost pit.',
  },
  {
    id: 'compost_bay',
    category: 'structure',
    name: 'Compost Bay (3-bin)',
    icon: '🪱',
    shape: 'rect',
    wM: 1,
    hM: 3,
    color: '#7A5C3E',
    zoneRec: [1, 2],
    tip: 'Three ~1x1m bins in a row for turning stages; keep near veg beds to shorten wheelbarrow runs.',
  },
  {
    id: 'worm_farm',
    category: 'structure',
    name: 'Worm Farm',
    icon: '🪱',
    shape: 'rect',
    wM: 0.6,
    hM: 1.2,
    color: '#7A5C3E',
    zoneRec: [1],
    tip: 'Keep in shade near the kitchen for easy scrap disposal.',
  },
  {
    id: 'nursery_table',
    category: 'structure',
    name: 'Nursery Table',
    icon: '🌱',
    shape: 'rect',
    wM: 1,
    hM: 2,
    color: '#7A5C3E',
    zoneRec: [1],
    tip: 'Site close to a tap for daily seedling watering.',
  },
  {
    id: 'market_stall',
    category: 'structure',
    name: 'Market Stall',
    icon: '🧺',
    shape: 'rect',
    wM: 3,
    hM: 3,
    color: '#7A5C3E',
    zoneRec: [0, 1],
    tip: 'Place near the gate/road frontage for customer access.',
  },
  {
    id: 'veg_bed',
    category: 'growing',
    name: 'Vegetable Bed',
    icon: '🥬',
    shape: 'rect',
    wM: 1.2,
    hM: 3,
    color: '#4E8B3B',
    zoneRec: [1, 2],
    nearHouseMaxM: 35,
    needsSun: true,
    tip: 'Keep within daily-visit distance of the kitchen door; full sun, north-facing rows.',
  },
  {
    id: 'keyhole_bed',
    category: 'growing',
    name: 'Keyhole Bed',
    icon: '🔑',
    shape: 'circle',
    wM: 2,
    hM: 2,
    color: '#4E8B3B',
    zoneRec: [1],
    needsSun: true,
    tip: 'Central compost basket feeds the whole bed — ideal near the kitchen door.',
  },
  {
    id: 'herb_spiral',
    category: 'growing',
    name: 'Herb Spiral',
    icon: '🌿',
    shape: 'circle',
    wM: 2,
    hM: 2,
    color: '#4E8B3B',
    zoneRec: [1],
    nearHouseMaxM: 15,
    needsSun: true,
    tip: 'Build up to 1-1.2 m high with rubble core; place right outside the kitchen door.',
  },
  {
    id: 'banana_circle',
    category: 'growing',
    name: 'Banana Circle',
    icon: '🍌',
    shape: 'circle',
    wM: 3.5,
    hM: 3.5,
    color: '#4E8B3B',
    zoneRec: [2],
    castsShade: true,
    tip: 'Dig a 2 m pit for the compost core; feeds off greywater and kitchen waste.',
  },
  {
    id: 'tree_citrus',
    category: 'growing',
    name: 'Citrus Tree',
    icon: '🍊',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Full sun, frost-protected spot; keep 4 m from structures for mature canopy.',
  },
  {
    id: 'tree_mango',
    category: 'growing',
    name: 'Mango Tree',
    icon: '🥭',
    shape: 'circle',
    wM: 10,
    hM: 10,
    color: '#4E8B3B',
    zoneRec: [3],
    castsShade: true,
    tip: 'Mature canopy can reach 10 m+ — give it real room, frost-free warm zone.',
  },
  {
    id: 'tree_avocado',
    category: 'growing',
    name: 'Avocado Tree',
    icon: '🥑',
    shape: 'circle',
    wM: 8,
    hM: 8,
    color: '#4E8B3B',
    zoneRec: [3],
    castsShade: true,
    tip: 'Needs good drainage, wind shelter, and 8 m clearance at maturity.',
  },
  {
    id: 'tree_macadamia',
    category: 'growing',
    name: 'Macadamia Tree',
    icon: '🌰',
    shape: 'circle',
    wM: 9,
    hM: 9,
    color: '#4E8B3B',
    zoneRec: [3],
    castsShade: true,
    tip: 'Slow-growing but wide canopy eventually — plant well back from paths and beds.',
  },
  {
    id: 'tree_guava',
    category: 'growing',
    name: 'Guava Tree',
    icon: '🍈',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Tolerant and fast-fruiting — good filler tree near the homestead zone.',
  },
  {
    id: 'tree_litchi',
    category: 'growing',
    name: 'Litchi Tree',
    icon: '🍒',
    shape: 'circle',
    wM: 8,
    hM: 8,
    color: '#4E8B3B',
    zoneRec: [3],
    castsShade: true,
    tip: 'Wide dense canopy at maturity — needs subtropical frost-free conditions.',
  },
  {
    id: 'tree_pawpaw',
    category: 'growing',
    name: 'Pawpaw Tree',
    icon: '🌴',
    shape: 'circle',
    wM: 2.5,
    hM: 2.5,
    color: '#4E8B3B',
    zoneRec: [2],
    castsShade: true,
    tip: 'Fast-growing and short-lived — good gap-filler near the kitchen garden.',
  },
  {
    id: 'tree_moringa',
    category: 'growing',
    name: 'Moringa Tree',
    icon: '🌳',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Prune hard annually for leaf harvest to control size near beds.',
  },
  {
    id: 'banana_clump',
    category: 'growing',
    name: 'Banana Clump',
    icon: '🍌',
    shape: 'circle',
    wM: 3,
    hM: 3,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Heavy feeder — site near greywater outflow or compost area.',
  },
  {
    id: 'tree_indigenous',
    category: 'growing',
    name: 'Indigenous Shade Tree',
    icon: '🌲',
    shape: 'circle',
    wM: 10,
    hM: 10,
    color: '#4E8B3B',
    zoneRec: [4, 5],
    castsShade: true,
    tip: 'Use for windbreaks and wildlife corridors on the property edge.',
  },
  // Temperate / cold-climate fruit & nut trees — for Highveld grassland, Afromontane and other
  // frosty areas where the subtropical trees above won't set fruit. Suitability by climate is
  // in TREE_CLIMATES below.
  {
    id: 'tree_apple',
    category: 'growing',
    name: 'Apple Tree',
    icon: '🍎',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Needs winter cold (chill) to fruit — good on the Highveld; pick a low-chill variety in milder spots.',
  },
  {
    id: 'tree_pear',
    category: 'growing',
    name: 'Pear Tree',
    icon: '🍐',
    shape: 'circle',
    wM: 5,
    hM: 5,
    color: '#4E8B3B',
    zoneRec: [3],
    castsShade: true,
    tip: 'Cold-hardy and long-lived; needs a second variety nearby for good pollination.',
  },
  {
    id: 'tree_plum',
    category: 'growing',
    name: 'Plum Tree',
    icon: '🍑',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Frost-hardy stone fruit; blossoms early so avoid the coldest frost pockets.',
  },
  {
    id: 'tree_peach',
    category: 'growing',
    name: 'Peach Tree',
    icon: '🍑',
    shape: 'circle',
    wM: 4,
    hM: 4,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Prune to an open vase each winter; needs some chill but tolerates mild-frost hinterland too.',
  },
  {
    id: 'tree_fig',
    category: 'growing',
    name: 'Fig Tree',
    icon: '🫒',
    shape: 'circle',
    wM: 5,
    hM: 5,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: true,
    tip: 'Very adaptable — handles frost, heat and dry spells. Roots are vigorous, keep clear of walls/pipes.',
  },
  {
    id: 'tree_pomegranate',
    category: 'growing',
    name: 'Pomegranate',
    icon: '🔴',
    shape: 'circle',
    wM: 3,
    hM: 3,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    castsShade: false,
    tip: 'Loves hot dry summers; drought-hardy once established. Good for Karoo and Highveld gardens.',
  },
  {
    id: 'tree_olive',
    category: 'growing',
    name: 'Olive Tree',
    icon: '🫒',
    shape: 'circle',
    wM: 6,
    hM: 6,
    color: '#4E8B3B',
    zoneRec: [3, 4],
    castsShade: true,
    tip: 'Mediterranean and Karoo star — drought- and frost-tolerant; needs a dry, sunny, well-drained spot.',
  },
  {
    id: 'pollinator_strip',
    category: 'growing',
    name: 'Pollinator Strip',
    icon: '🐝',
    shape: 'rect',
    wM: 1,
    hM: 5,
    color: '#4E8B3B',
    zoneRec: [2],
    needsSun: true,
    tip: 'Mix indigenous flowering species along orchard edges to boost fruit set.',
  },
  {
    id: 'mulch_bank',
    category: 'growing',
    name: 'Mulch Bank',
    icon: '🍂',
    shape: 'rect',
    wM: 2,
    hM: 2,
    color: '#4E8B3B',
    zoneRec: [2, 3],
    tip: 'Stockpile chip/straw near orchard rows to save wheelbarrow trips.',
  },
  {
    id: 'spekboom_hedge',
    category: 'growing',
    name: 'Spekboom Hedge',
    icon: '🌵',
    shape: 'rect',
    wM: 0.5,
    hM: 5,
    color: '#4E8B3B',
    zoneRec: [2, 3, 4],
    tip: 'Plant cuttings 20-30 cm apart as a firebreak/browse hedge — extremely drought-hardy.',
  },
  {
    id: 'vetiver_row',
    category: 'growing',
    name: 'Vetiver Row',
    icon: '🌾',
    shape: 'rect',
    wM: 0.3,
    hM: 5,
    color: '#4E8B3B',
    zoneRec: [2, 3, 4],
    tip: 'Plant on-contour with slips 10-15 cm apart to stop erosion on slopes.',
  },
  {
    id: 'beehive',
    category: 'animal',
    name: 'Beehive',
    icon: '🐝',
    shape: 'rect',
    wM: 0.5,
    hM: 0.5,
    color: '#C98A2C',
    zoneRec: [4, 5],
    tip: 'Face entrance east, away from foot traffic; keep 5-10 m clear approach path.',
  },
  {
    id: 'goat_pen',
    category: 'animal',
    name: 'Goat Pen',
    icon: '🐐',
    shape: 'rect',
    wM: 4,
    hM: 4,
    color: '#C98A2C',
    zoneRec: [3, 4],
    tip: 'Sturdy fencing essential — goats browse anything reachable, keep away from young trees.',
  },
  {
    id: 'pig_pen',
    category: 'animal',
    name: 'Pig Pen',
    icon: '🐖',
    shape: 'rect',
    wM: 4,
    hM: 4,
    color: '#C98A2C',
    zoneRec: [3, 4],
    tip: 'Downhill of water sources, with shade and a wallow; strong odour control needed near house.',
  },
  {
    id: 'duck_pond',
    category: 'animal',
    name: 'Duck Pond',
    icon: '🦆',
    shape: 'circle',
    wM: 2,
    hM: 2,
    color: '#C98A2C',
    zoneRec: [3],
    tip: 'Pair with the orchard for natural snail and pest control.',
  },
  {
    id: 'rabbit_hutch',
    category: 'animal',
    name: 'Rabbit Hutch',
    icon: '🐇',
    shape: 'rect',
    wM: 1,
    hM: 2,
    color: '#C98A2C',
    zoneRec: [2],
    tip: 'Raise off ground; manure drops straight to a compost or worm bin below.',
  },
  {
    id: 'water_trough2',
    category: 'animal',
    name: 'Livestock Trough',
    icon: '🥛',
    shape: 'rect',
    wM: 0.6,
    hM: 2,
    color: '#C98A2C',
    zoneRec: [3, 4],
    tip: 'Place at the kraal fence line for easy refilling without entering the pen.',
  },
  {
    id: 'biodigester',
    category: 'structure',
    name: 'Biodigester',
    icon: '🔥',
    shape: 'circle',
    wM: 2,
    hM: 2,
    color: '#7A5C3E',
    zoneRec: [2, 3],
    tip: 'Site near the kraal/pig pen for manure feedstock; pipe gas to the kitchen.',
  },
  {
    id: 'shade_sail',
    category: 'structure',
    name: 'Shade Sail',
    icon: '⛱️',
    shape: 'rect',
    wM: 4,
    hM: 4,
    color: '#7A5C3E',
    zoneRec: [1, 2],
    tip: 'Anchor over seating or nursery areas; orient to block harsh afternoon sun.',
  },
  {
    id: 'gate',
    category: 'access',
    name: 'Gate',
    icon: '🚪',
    shape: 'rect',
    wM: 1.5,
    hM: 0.3,
    color: '#8C8577',
    zoneRec: [0],
    tip: 'Align with the main path for straightforward vehicle and foot access.',
  },
  {
    id: 'bench',
    category: 'access',
    name: 'Bench',
    icon: '🪑',
    shape: 'rect',
    wM: 1.5,
    hM: 0.5,
    color: '#8C8577',
    zoneRec: [1, 2],
    tip: 'Site under shade with a view over the main growing area.',
  },
  {
    id: 'sign',
    category: 'access',
    name: 'Sign',
    icon: '🪧',
    shape: 'rect',
    wM: 0.5,
    hM: 0.1,
    color: '#8C8577',
    zoneRec: [0, 1],
    tip: 'Place at path junctions for orientation or market-day signage.',
  },
  {
    id: 'solar_panel_ground',
    category: 'access',
    name: 'Ground Solar Panel',
    icon: '🔆',
    shape: 'rect',
    wM: 2,
    hM: 1,
    color: '#8C8577',
    zoneRec: [0, 1],
    tip: 'Angle north-facing and unshaded for peak SA solar yield.',
  },
  {
    id: 'washline',
    category: 'access',
    name: 'Washing Line',
    icon: '🧺',
    shape: 'rect',
    wM: 3,
    hM: 0.3,
    color: '#8C8577',
    zoneRec: [1],
    tip: 'Site in full sun close to the house, clear of tree drip lines.',
  },
];

export const ELEMENTS_BY_ID: Record<string, DesignElementDef> = ELEMENT_CATALOG.reduce(
  (acc, def) => {
    acc[def.id] = def;
    return acc;
  },
  {} as Record<string, DesignElementDef>,
);

// ── Climate suitability for fruit/nut trees ─────────────────────────────────────
// The owner's ask: "depending on the climate zone we must have specific trees accordingly."
// Coarse SA climate buckets a tree can crop in. Frost-tenderness and chill needs are the main
// drivers here (well-established horticulture), not fine-grained cultivar advice.
export type ClimateZone = 'subtropical' | 'temperate' | 'mediterranean' | 'arid';

// Which climates each tree crops well in. A tree NOT listed here (e.g. the indigenous shade
// tree, or non-tree growing items) is treated as climate-agnostic and always shown.
export const TREE_CLIMATES: Record<string, ClimateZone[]> = {
  tree_citrus: ['subtropical', 'mediterranean'],
  tree_mango: ['subtropical'],
  tree_avocado: ['subtropical'],
  tree_macadamia: ['subtropical'],
  tree_guava: ['subtropical'],
  tree_litchi: ['subtropical'],
  tree_pawpaw: ['subtropical'],
  tree_moringa: ['subtropical', 'arid'],
  banana_clump: ['subtropical'],
  banana_circle: ['subtropical'],
  tree_apple: ['temperate'],
  tree_pear: ['temperate'],
  tree_plum: ['temperate'],
  tree_peach: ['temperate', 'subtropical'],
  tree_fig: ['temperate', 'mediterranean', 'arid', 'subtropical'],
  tree_pomegranate: ['arid', 'mediterranean', 'temperate'],
  tree_olive: ['mediterranean', 'arid', 'temperate'],
};

// SA biome NAME (as stored on site.biome, from lib/biome.ts BIOMES[].name) → the climates that
// grow there. Returns null when the biome is unknown/outside SA, meaning "show every tree".
export function biomeClimates(biomeName?: string | null): ClimateZone[] | null {
  switch ((biomeName ?? '').trim().toLowerCase()) {
    case 'indian ocean coastal belt':
    case 'savanna':
      return ['subtropical'];
    case 'albany thicket':
      return ['subtropical', 'arid'];
    case 'afromontane forest':
      return ['temperate', 'subtropical'];
    case 'grassland':
      return ['temperate'];
    case 'fynbos':
      return ['mediterranean', 'temperate'];
    case 'succulent karoo':
    case 'nama-karoo':
    case 'desert':
      return ['arid'];
    default:
      return null; // unknown / outside SA → don't filter
  }
}

// Is this element suited to the site's climate? Non-trees and unmapped trees are always suited.
export function elementSuitsClimate(defId: string, siteClimates: ClimateZone[] | null): boolean {
  if (!siteClimates) return true; // unknown site climate → show everything
  const treeClimates = TREE_CLIMATES[defId];
  if (!treeClimates) return true; // climate-agnostic (indigenous, support planting, etc.)
  return treeClimates.some((c) => siteClimates.includes(c));
}
