// Shared by the main locale dictionary and the context's English default. The latter keeps
// isolated player previews and tests readable when they render outside LanguageProvider.
export const LEARNER_UI_ENGLISH: Record<string, string> = {
  studentGuidesDescription: 'Map your site, follow a harvest, keep a cost and its receipt, or make an invoice. Practise in the sample farm before using your own records.',
  courseNarrationLanguage: 'Narration language',
  courseAudioListen: 'Listen',
  courseAudioLanguageMissing: 'This module has not been recorded in {appLanguage} yet — playing {playingLanguage}.',
  courseAudioPauseTrack: 'Pause {title}',
  courseAudioPlayTrack: 'Play {title}',
  courseAudioPlayFailed: 'Could not play this clip — check your connection and try again.',
  courseDeckRegion: 'Lesson slides. Use Left and Right arrow keys to change slides.',
  courseDeckFullscreenEnterAria: 'Show slides full screen',
  courseDeckFullscreenExitAria: 'Exit full screen',
  courseDeckFullscreenEnter: 'Full screen',
  courseDeckFullscreenExit: 'Exit full screen',
  courseDeckViewMode: 'Choose how to view this slide',
  courseDeckReadText: 'Read text',
  courseDeckSeeSlide: 'See slide',
  courseDeckSlideNarration: 'Slide narration',
  courseDeckSlideImageSize: 'Slide image size',
  courseDeckZoomOut: 'Zoom out',
  courseDeckZoomIn: 'Zoom in',
  courseDeckPanHint: 'Drag to move around',
  courseDeckClose: 'Close',
  courseDeckWatch: 'Watch · {seconds}s · {size}',
  courseDeckOpenImageAria: 'Open still image for {title} at full size',
  courseDeckOpenImage: 'View slide image · zoom',
  courseDeckNarrationAria: 'Narration for {title}',
  courseDeckNarrationFailed: 'Narration could not play. Check your connection and press Play lesson again, or read this slide below.',
  courseDeckAnimationFailed: 'The animation could not load. You can keep listening, read the slide, or tap Watch to try again.',
  courseDeckSlideLanguage: 'This slide is in {language}.',
  courseDeckNarrationFallback: 'Narration is in {spokenLanguage}. {appLanguage} narration is not available for this module yet.',
  courseDeckStopAria: 'Stop the lesson',
  courseDeckPlayAria: 'Play the lesson',
  courseDeckStop: 'Stop',
  courseDeckPlay: 'Play lesson',
  courseDeckBack: '‹ Back',
  courseDeckNext: 'Next ›',
  courseDeckReadSlide: 'Read this slide · {language}',
  offlineDownloadUnsupported: 'This browser cannot store lessons for offline use. Chrome on Android can.',
  offlineGetWhileSignal: 'Get the slides, the narration and the clips onto this phone while you have signal. They then work with no airtime at all.',
  offlineOnThisPhone: 'On this phone · {size}',
  offlineRemovePack: 'Remove saved lessons',
  offlineStopDownload: 'Stop',
  offlineFinishDownload: 'Finish download · {size} left',
  offlineDownloadPack: 'Download · {size}',
  offlineDownloadQuality: 'Download quality',
  offlineQualityStandard: 'Standard',
  offlineQualityStandardNote: 'for phones on data',
  offlineQualityHigher: 'Higher quality',
  offlineQualityHigherNote: 'facilitators & funders · wifi',
  offlineDownloadBytesProgress: '{current} of {total}',
  offlineEnglishMediaFallback: 'This pack includes English slides or narration where isiZulu is not available yet.',
  offlineFilesProgress: '{done} of {total} files',
  offlineFilesFailed: '{count} files did not download. Tap Finish download again while you still have signal — the rest is already saved.',
  offlineSavedMayClear: 'Saved, but this phone may clear it if storage runs low. Check your saved lessons again before leaving signal.',
  offlineLowStorage: 'This phone is low on space — the download may not fit.',
};
