// GENERATED by scripts/build-perennial-harvest.mjs from research/perennial-sources/*.json.
// Do not edit by hand: correct the dossier and re-run the script. See lib/perennial-harvest.ts.

import type { PerennialHarvest } from './perennial-harvest';

export const PERENNIAL_HARVEST_DATA: Record<string, PerennialHarvest> = {
  "carica-papaya": {
    "speciesId": "carica-papaya",
    "name": "Pawpaw",
    "product": "fruit",
    "windows": [
      {
        "region": "KwaZulu-Natal",
        "months": [
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          1
        ],
        "source": {
          "quote": "The cropping season usually extends from about April to January, with a peak from September to November.",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes), section 1.6 Papaya, 'Bearing age'",
          "page": 18
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        0.75,
        0.83
      ],
      "source": {
        "quote": "Commercial pawpaws are normally harvested 9 to 10 months after being transplanted from nurseries.",
        "url": "https://www.fao.org/fileadmin/user_upload/inpho/docs/Post_Harvest_Compendium_-_Pawpaw__Papaya_.pdf",
        "doc": "FAO, 'Pawpaw (Papaya): Post-harvest Operations' (Post-Harvest Compendium)",
        "page": 21
      },
      "note": "9-10 months converted to years: 9/12=0.75, 10/12≈0.83. This is a general (non-South-Africa-specific) commercial figure from FAO's global compendium, not a South African source; South African government (nda.gov.za) papaya production guideline PDFs were found via search but returned HTTP 503 on every fetch attempt during this pass (see gaps)."
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "carissa-macrocarpa": {
    "speciesId": "carissa-macrocarpa",
    "name": "Num-num",
    "product": "fruit",
    "windows": [],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "carpobrotus-edulis": {
    "speciesId": "carpobrotus-edulis",
    "name": "Sour fig",
    "product": "fruit",
    "windows": [],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "carya-illinoinensis": {
    "speciesId": "carya-illinoinensis",
    "name": "Pecan",
    "product": "nut in shell",
    "windows": [
      {
        "region": "South Africa (general — Southern Hemisphere phenology; main areas Vaalharts/Northern Cape, Lower Orange River)",
        "months": [
          3,
          4,
          5,
          6
        ],
        "source": {
          "quote": "Shell hardening and nut-fill is complete around end of February, taking approximately three weeks. At this stage shuck-split will take place which indicates the start of the harvesting period, ending in middle June. Trees then enter dormancy after natural leaf drop end of July.",
          "url": "https://www.sappa.za.org/download/16968/?tmstv=1790592292",
          "doc": "Lötze, E., 'Literature Review: Factors influencing pollination of pecans for commercial production', published by SAPPA (South African Pecan Nut Producers' Association)",
          "page": 3
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "needs-cross-pollinator",
      "source": {
        "quote": "In pecans [Carya illinoinensis (Wangenh. K. Koch)], male (staminate) and female (pistillate) flowers occur on the same tree (monoecious) and exhibits heterodichogamy ... Therefore, trees were divided into two groups: “Protandrous” (Type I) which is when pollen from the male flowers is shed before the female flowers are receptive, and “Protogynous” (Type II), where female flowers are receptive to pollen before pollen is shed from the male flowers ... Compatible cultivars need to be in close proximity to each other for successful cross-pollination ... It is possible for fruit to set through self-pollination in the case of incomplete dichogamy, but this often results in smaller and lighter nuts ... Under self-pollination, pecan yield is 35 – 75% lower with nut quality severely reduced (Polles et al., 1980). Complete dichogamy will result in a self-sterile cultivar, as there is no overlap between pollen shed and pistil receptivity.",
        "url": "https://www.sappa.za.org/download/16968/?tmstv=1790592292",
        "doc": "Lötze, E., 'Literature Review: Factors influencing pollination of pecans for commercial production', published by SAPPA",
        "page": 2
      },
      "note": "Pecan is wind-pollinated and monoecious (male and female flowers on the same tree) but exhibits heterodichogamy — male and female flowers on a given tree mature at different times (Type I protandrous vs Type II protogynous) — so a single tree/cultivar alone generally cannot pollinate itself well or at all (many named cultivars are effectively self-sterile), and commercial orchards in South Africa are planted with complementary Type I x Type II cultivar combinations. Self-pollination is possible in some cultivars with incomplete dichogamy but yields 35-75% less with poorer nut quality — hence 'needs-cross-pollinator' rather than 'partly-self-fertile' or 'self-fertile'."
    }
  },
  "citrus-limon": {
    "speciesId": "citrus-limon",
    "name": "Lemon",
    "product": "fruit",
    "windows": [
      {
        "region": "KZN (hot low-lying areas, e.g. Nkwaleni, Mkhuze vs. cooler KZN Midlands)",
        "months": [
          2,
          3,
          5,
          6,
          7
        ],
        "source": {
          "quote": "Lemons – Grow well in warmer areas.  Adaptable to different areas.  HU 1100 to 1500. Main crop in hotter areas produced in February to March, while crop in cooler areas produced during May to July.",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes)",
          "page": 11
        }
      },
      {
        "region": "South Africa (general; main areas Eastern Cape, Limpopo, Western Cape)",
        "months": [
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "source": {
          "quote": "Eureka lemons can have as much as three fruit sets. This means that at the same time there can be as much as three lots of fruit on a tree that are at different stages of maturity. Because of this characteristic, trees can produce marketable fruit from as early as February in hotter areas, and to as late as mid-September in cooler regions.",
          "url": "https://www.crw.org.za/home/document-home/learning-aids-and-resources/ca-citrus-av-series-learning-material/citrus-planting-management/5808-ca-av-series-cpm-lm-m02-citrus-types-and-cultivars-1/file",
          "doc": "Citrus Growers' Association / Citrus Academy — 'Citrus Planting Management 2: Citrus Types and Cultivars' Learner Guide (1st edition), Citrus Resource Warehouse (crw.org.za)",
          "page": 10
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        3,
        3
      ],
      "source": {
        "quote": "First crop (years) [...] 3",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes) — Citrus Yields table",
        "page": 11
      },
      "note": "Source table lists 'First crop (years)' for Valencias / Navels / Grapefruit / Lemons as 4 / 4 / 3 / 3 respectively (single row, so column order is unambiguous); Lemons value is 3 years. 'Expected lifespan (years)' in the same table is given as 23 years for lemons."
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": {
      "value": [
        79,
        131
      ],
      "source": {
        "quote": "Potential production: Mature trees (tons/ha) [Valencias] 60 45-50 35 [Navels] 45 40 30 [Grapefruit] 65 50 35 [Lemons] 65 50 40",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes) — Citrus Yields table",
        "page": 11
      },
      "note": "CONVERTED, arithmetic shown: the PDF table's text-extraction order groups three yield figures per crop column (interpreted as [potential/mature, likely, conservative] tons/ha, in the same crop order as the header row Valencias/Navels/Grapefruit/Lemons); this reconstruction of table alignment could not be double-checked against the original table grid, so it is a best-effort read, not a certainty. Using the 'likely production' figure for lemons (50 t/ha) and the source's own lemon spacings: hot areas '7.0-8.0 x 3.0-4.0m' (midpoint 7.5 x 3.5m = 26.25 m²/tree → 381 trees/ha → 50000kg / 381 = ~131 kg/tree) and cool/KZN-Midlands areas '5.5-6.0 x 2.5-3.0m' (midpoint 5.75 x 2.75m = 15.8 m²/tree → 632 trees/ha → 50000kg / 632 = ~79 kg/tree). Range [79,131] kg/tree reflects this spacing-driven spread, not cultivar variation. Editor review: table layout checked against the PDF (p.11). Each crop column lists Potential / Likely / Conservative from top to bottom, and the Lemons column reads 65 / 50 / 40 t/ha, so the read above is correct."
    },
    "chillUnits": null,
    "pollination": null
  },
  "citrus-reticulata": {
    "speciesId": "citrus-reticulata",
    "name": "Soft citrus",
    "product": "fruit",
    "windows": [
      {
        "region": "Eastern & Western Cape (main soft citrus areas) — Satsuma cultivars",
        "months": [
          3,
          4,
          5
        ],
        "source": {
          "quote": "Miho Wase is also the cultivar that matures the earliest of the Satsuma cultivars, and can be harvested from as early as mid-March. Other Satsuma cultivars are harvested until around the end of May.",
          "url": "https://www.crw.org.za/home/document-home/learning-aids-and-resources/ca-citrus-av-series-learning-material/citrus-planting-management/5808-ca-av-series-cpm-lm-m02-citrus-types-and-cultivars-1/file",
          "doc": "Citrus Growers' Association / Citrus Academy — 'Citrus Planting Management 2: Citrus Types and Cultivars' Learner Guide (1st edition), Citrus Resource Warehouse (crw.org.za), citing CRI Cultivar Fact Sheets",
          "page": 8
        }
      },
      {
        "region": "Eastern & Western Cape (main soft citrus areas) — Clementine cultivars",
        "months": [
          3,
          4,
          5,
          6
        ],
        "source": {
          "quote": "The earliest commercial clementine cultivar mature towards the end of March, with the last one finishing around mid-June.",
          "url": "https://www.crw.org.za/home/document-home/learning-aids-and-resources/ca-citrus-av-series-learning-material/citrus-planting-management/5808-ca-av-series-cpm-lm-m02-citrus-types-and-cultivars-1/file",
          "doc": "Citrus Growers' Association / Citrus Academy — 'Citrus Planting Management 2: Citrus Types and Cultivars' Learner Guide (1st edition), citing CRI Cultivar Fact Sheets",
          "page": 8
        }
      },
      {
        "region": "Eastern & Western Cape (main soft citrus areas) — Mandarin cultivars (incl. Nadorcott)",
        "months": [
          5,
          6,
          7,
          8,
          9
        ],
        "source": {
          "quote": "Nadorcott is the most common mandarin cultivar, and accounts for about two thirds of the hectares planted with mandarin cultivars. Early mandarin cultivars are ready to be harvested around mid-May, and the season from there stretches as late as September.",
          "url": "https://www.crw.org.za/home/document-home/learning-aids-and-resources/ca-citrus-av-series-learning-material/citrus-planting-management/5808-ca-av-series-cpm-lm-m02-citrus-types-and-cultivars-1/file",
          "doc": "Citrus Growers' Association / Citrus Academy — 'Citrus Planting Management 2: Citrus Types and Cultivars' Learner Guide (1st edition), citing CRI Cultivar Fact Sheets",
          "page": 9
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "dovyalis-afra": {
    "speciesId": "dovyalis-afra",
    "name": "Kei apple",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general / southern Africa)",
        "months": [
          11,
          12,
          1
        ],
        "source": {
          "quote": "The species is dioecious. In southern Africa, flowering and fruiting occur from November to January. D. caffra starts to fruit when at least 3 years old. Pollination is carried out by insects, and fruits are developed within 4 months.",
          "url": "https://apps.worldagroforestry.org/treedb2/AFTPDFS/Dovyalis_caffra.PDF",
          "doc": "Agroforestree Database 4.0 (Orwa et al. 2009), Dovyalis caffra fact sheet, BIOLOGY section",
          "page": 1
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        3,
        3
      ],
      "source": {
        "quote": "D. caffra starts to fruit when at least 3 years old.",
        "url": "https://apps.worldagroforestry.org/treedb2/AFTPDFS/Dovyalis_caffra.PDF",
        "doc": "Agroforestree Database 4.0 (Orwa et al. 2009), Dovyalis caffra fact sheet, BIOLOGY section",
        "page": 1
      },
      "note": "Source gives only a minimum ('at least 3 years old'), no upper bound. [3,3] repeats the single sourced value as both array entries to fit the schema; treat this as a lower-bound estimate, not a true min-max range. Editor review: the source says 'at least 3 years old', so 3 is the earliest age, not a typical one."
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "separate-male-female-plants",
      "source": {
        "quote": "The species is dioecious.",
        "url": "https://apps.worldagroforestry.org/treedb2/AFTPDFS/Dovyalis_caffra.PDF",
        "doc": "Agroforestree Database 4.0 (Orwa et al. 2009), Dovyalis caffra fact sheet, BIOLOGY section",
        "page": 1
      },
      "note": "Confirmed independently by SANBI: 'Male and female flowers on separate trees.' (Dovyalis caffra PZA botanic description, https://pza.sanbi.org/dovyalis-caffra) and the Dovyalis afra PZA page describes separate 'Male flowers' and 'Female flowers' paragraphs. Insects (and birds) are the pollen vector between the separate-sex trees: ICRAF states 'Pollination is carried out by insects'; SANBI's Dovyalis afra Ecology section states 'Insects and birds play a very important role in pollinating this tree.'"
    }
  },
  "englerophytum-magalismontanum": {
    "speciesId": "englerophytum-magalismontanum",
    "name": "Transvaal milkplum",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general; SA distribution given as Gauteng, KwaZulu-Natal, Limpopo, Mpumalanga, North West)",
        "months": [
          12,
          1,
          2
        ],
        "source": {
          "quote": "These trees flower from June to December and sometimes flowers and fruits can be found on the plant at the same time... The fruit is bright red when ripe and ripens from December to February.",
          "url": "https://pza.sanbi.org/englerophytum-magalismontanum",
          "doc": "Englerophytum magalismontanum | PlantZAfrica (SANBI)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "ficus-carica": {
    "speciesId": "ficus-carica",
    "name": "Fig",
    "product": "fruit",
    "windows": [
      {
        "region": "Western Cape (Breede River valley, near Worcester)",
        "months": [
          1,
          2,
          3,
          4,
          5
        ],
        "source": {
          "quote": "Common type figs produce their main crop from buds in the axils of leaves on the current season’s growth (McEachern, 1996; Flaishman et al., 2008).  Harvest may start in the middle of summer and can last several months, until the onset of winter.",
          "url": "https://www.figdatabase.com/uploads/Tree%20Training%20And%20Managing%20Complexcity%20and%20Yield%20In%20Figs.pdf",
          "doc": "Gerber, H.J. (2010) 'Tree training and managing complexity and yield in fig (Ficus carica L.)', MSc(Agric) thesis, University of Stellenbosch",
          "page": 38
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "self-fertile",
      "source": {
        "quote": "The common fig, to which ‘Bourjasotte Noire’, ‘Col de Dame Noire’ and ‘Noire de Caromb’ belong, develops parthenocarpically and usually does not require the stimulus of pollination (Condit, 1955).",
        "url": "https://www.figdatabase.com/uploads/Tree%20Training%20And%20Managing%20Complexcity%20and%20Yield%20In%20Figs.pdf",
        "doc": "Gerber, H.J. (2010) 'Tree training and managing complexity and yield in fig (Ficus carica L.)', MSc(Agric) thesis, University of Stellenbosch",
        "page": 13
      },
      "note": "More precisely 'parthenocarpic' (fruit sets without any pollination at all, i.e. requires neither a wasp nor cross-pollen) for the common-type fig cultivars grown commercially in South Africa; mapped to the closest schema option 'self-fertile'. Other fig types (Smyrna, Capri, San Pedro) do need pollination/caprification but are not the type commercially grown in SA per this source."
    }
  },
  "fragaria-x-ananassa": {
    "speciesId": "fragaria-x-ananassa",
    "name": "Strawberry",
    "product": "fruit",
    "windows": [
      {
        "region": "Western Cape",
        "months": [
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "In the western Cape the season is September to December.",
          "url": "https://ishs.org/ishs-article/265_125/",
          "doc": "J.P. Human & E.P. Evans, 'STRAWBERRY PRODUCTION IN SOUTH AFRICA', Acta Horticulturae 265 (International Strawberry Symposium), abstract (article 265_125)",
          "page": 757
        }
      },
      {
        "region": "Transvaal (now Gauteng/Limpopo/Mpumalanga/North West), grown in tunnels",
        "months": [
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "In the Transvaal some farmers grow strawberries in tunnels (10–15 ha). This enalbes them to produce fruit from late May until mid-December.",
          "url": "https://ishs.org/ishs-article/265_125/",
          "doc": "J.P. Human & E.P. Evans, 'STRAWBERRY PRODUCTION IN SOUTH AFRICA', Acta Horticulturae 265 (International Strawberry Symposium), abstract (article 265_125)",
          "page": 757
        }
      },
      {
        "region": "South Africa (industry body overview, all regions)",
        "months": [
          6,
          7,
          8,
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "Depending on the variety of the strawberry and the production region, strawberries are planted from March to April, and harvested from June to December.",
          "url": "https://strawberries.org.za/an-overview-of-strawberry-cultivation-in-south-africa/",
          "doc": "South African Strawberry Growers Association (SASGA), An overview of strawberry cultivation in South Africa",
          "page": null
        }
      },
      {
        "region": "KwaZulu-Natal, frost-free areas",
        "months": [
          5,
          6,
          7,
          8
        ],
        "source": {
          "quote": "In KwaZulu-Natal, flower and fruit production occurs in late autumn/winter in frost-free areas, in spring to early summer where light frosts occur",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
          "page": 34
        }
      },
      {
        "region": "KwaZulu-Natal, areas with light frosts",
        "months": [
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "In KwaZulu-Natal, flower and fruit production occurs in late autumn/winter in frost-free areas, in spring to early summer where light frosts occur",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
          "page": 34
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "garcinia-livingstonei": {
    "speciesId": "garcinia-livingstonei",
    "name": "African mangosteen",
    "product": "fruit",
    "windows": [],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "grewia-occidentalis": {
    "speciesId": "grewia-occidentalis",
    "name": "Cross-berry",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          1,
          2,
          3,
          4,
          5
        ],
        "source": {
          "quote": "Purple star-shaped flowers (measuring 1.5 to 3cm across) appear in summer (October - January), followed by distinctive four-lobed fruits... Fruits turns shiny reddish-brown to light purple when ripe (January - May) and may remain on the tree for long periods.",
          "url": "https://pza.sanbi.org/grewia-occidentalis",
          "doc": "SANBI PlantZAfrica - Grewia occidentalis",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "harpephyllum-caffrum": {
    "speciesId": "harpephyllum-caffrum",
    "name": "Wild plum",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general; SANBI: Eastern Cape, KwaZulu-Natal, Limpopo, Mpumalanga)",
        "months": [
          3,
          4,
          5
        ],
        "source": {
          "quote": "The whitish green flowers are borne near the ends of the branches with male and female flowers on separate trees, throughout summer (November to February). The tasty plum-like fruits first appear green and then turn red when they ripen in autumn; they contain a single seed and are enjoyed by people, mammals and birds.",
          "url": "https://pza.sanbi.org/harpephyllum-caffrum",
          "doc": "Harpephyllum caffrum | PlantZAfrica (SANBI)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "separate-male-female-plants",
      "source": {
        "quote": "male and female flowers on separate trees",
        "url": "https://pza.sanbi.org/harpephyllum-caffrum",
        "doc": "Harpephyllum caffrum | PlantZAfrica (SANBI)",
        "page": null
      },
      "note": "No explicit statement of the pollinating agent (insect/wind/bird) was found for this species in the fetched PZA page; the Ecology section mentions only fruit-eating/leaf-eating animals (baboons, monkeys, birds), not flower visitors."
    }
  },
  "litchi-chinensis": {
    "speciesId": "litchi-chinensis",
    "name": "Litchi",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general — Mpumalanga lowveld, Limpopo, KZN coast)",
        "months": [
          11,
          12,
          1,
          2
        ],
        "source": {
          "quote": "Lychees mature between November and February with a peak in December and January.",
          "url": "https://rfcarchives.org.au/Next/Fruits/Litchi/LycheeSouthAfrica7-95.htm",
          "doc": "Menzel, C., 'Lychee Growing and Marketing in South Africa', The Archives of the Rare Fruit Council Australia, July 1995 (production regions cited: Eastern Transvaal Lowveld, Northern/North-Eastern Transvaal, North and South Coast of Natal)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "macadamia-integrifolia": {
    "speciesId": "macadamia-integrifolia",
    "name": "Macadamia",
    "product": "nut in shell",
    "windows": [
      {
        "region": "South Africa (general — Mpumalanga, KwaZulu-Natal, Limpopo)",
        "months": [
          3,
          4,
          5,
          6,
          7
        ],
        "source": {
          "quote": "Macadamia trees typically take 7-9 years to reach maturity, with yields increasing for the next 15-20 years. Flowering begins in July, and nuts begin to develop by October, with harvest season running from March through June/July (see Table 2).",
          "url": "https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=South+Africa%27s+Macadamia+Industry+Grows+Despite+Export+Uncertainty_Pretoria_South+Africa+-+Republic+of_SF2025-0023.pdf",
          "doc": "USDA Foreign Agricultural Service (FAS), GAIN Report SF2025-0023, 'South Africa's Macadamia Industry Grows Despite Export Uncertainty', FAS Pretoria Post, 2025",
          "page": 5
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": {
      "value": [
        7,
        9
      ],
      "source": {
        "quote": "Macadamia trees typically take 7-9 years to reach maturity, with yields increasing for the next 15-20 years.",
        "url": "https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=South+Africa%27s+Macadamia+Industry+Grows+Despite+Export+Uncertainty_Pretoria_South+Africa+-+Republic+of_SF2025-0023.pdf",
        "doc": "USDA Foreign Agricultural Service (FAS), GAIN Report SF2025-0023, 'South Africa's Macadamia Industry Grows Despite Export Uncertainty', FAS Pretoria Post, 2025",
        "page": 5
      },
      "note": "Taken as 'years to reach maturity' (7-9 years) rather than absolute peak yield, since the same sentence says yields then keep INCREASING for a further 15-20 years after that — i.e. macadamia in South Africa does not plateau at a stable 'full bearing' yield until roughly 22-29 years by this source's framing, but 7-9 years is the point industry treats trees as having reached commercial maturity."
    },
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "partly-self-fertile",
      "source": {
        "quote": "Cross-pollination increases yields by 52% when compared with open pollination. ... Cross-pollination increases yields by 48.5% and improves nut quality (size and kernel weight). ... Genotyping of macadamia kernel to determine pollen parents: A4 was highly outcrossing (97%), 695 was 64% outcrossed, 816 41% outcrossed and 814 showed 10% outcrossing. ... Results demonstrated the critical role of honeybee colonies in macadamia orchards, with the absence of bees resulting in only 30% production in both cultivars.",
        "url": "https://samac.org.za/wp-content/uploads/2024/05/SAMAC-What-have-we-learned-2024.pdf",
        "doc": "SAMAC (South African Macadamia Growers' Association), 'What have we learned 2024' research summary newsletter",
        "page": 13
      },
      "note": "Changed from needs-cross-pollinator to partly-self-fertile in editor review: the same SAMAC summary measures 10-97% outcrossing by kernel genotyping (so some nuts are selfed) and says cross-pollination RAISES yield by about half, which is a partly self-fertile tree, not one that needs a pollinator to bear. SAMAC's own research summaries show macadamia is capable of self/open pollination (a cultivar-dependent 10-97% outcrossing rate was measured by kernel genotyping, and orchards without managed bee colonies still achieved 30% of full production) but that yield is substantially higher (48.5-52% more) with cross-pollination (interplanted cultivars) and managed honeybee colonies (industry recommends at least two hives/ha). This mixed picture — fruit set possible alone, but commercially reliant on cross-pollination/bee activity — is why 'needs-cross-pollinator' (the industry-recommended practice) rather than 'self-fertile' was chosen, though 'partly-self-fertile' is also defensible given the cultivar-dependent self/open-pollination yield floor; see this nuance rather than treating the choice as clear-cut."
    }
  },
  "mangifera-indica": {
    "speciesId": "mangifera-indica",
    "name": "Mango",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general; Limpopo + Mpumalanga = 96% of SA mango area)",
        "months": [
          11,
          12,
          1,
          2,
          3
        ],
        "source": {
          "quote": "The mango season in South Africa normally begins in November and ends around late March thus making it the shortest season compared to other subtropical fruits such as avocadoes which stretch from February to November as well as litchis which stretch from November to late April (FPEF, 2024).",
          "url": "https://www.namc.co.za/wp-content/uploads/2024/11/SA-Fruit-Trade-Flow-Report-Issue-56-December-2024-submission.pdf",
          "doc": "National Agricultural Marketing Council (NAMC), South African Fruit Trade Flow Report, Issue 56, December 2024 (citing FPEF 2024)",
          "page": 3
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "mimusops-zeyheri": {
    "speciesId": "mimusops-zeyheri",
    "name": "Red milkwood",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general; SA distribution given as Gauteng, KwaZulu-Natal, Limpopo, Mpumalanga, North West)",
        "months": [
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "source": {
          "quote": "Small, white, sweetly scented flowers are borne in October to February. Fruits are oval with a pointed tip ripening yellow or orange from April to September.",
          "url": "https://pza.sanbi.org/mimusops-zeyheri",
          "doc": "Mimusops zeyheri | PlantZAfrica (SANBI)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "moringa-oleifera": {
    "speciesId": "moringa-oleifera",
    "name": "Moringa",
    "product": "leaves and pods",
    "windows": [
      {
        "region": "North West Province (pods)",
        "months": [
          3,
          4
        ],
        "source": {
          "quote": "Fruits production mainly occurs in March and April.",
          "url": "https://dard.nwpg.gov.za/wp-content/uploads/2022/05/Moringa-production-for-food-security.pdf",
          "doc": "North West Department of Agriculture and Rural Development, Moringa (Moringa oleifera) production: A possible solution to South African food security challenges",
          "page": 7
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        0.5,
        1
      ],
      "source": {
        "quote": "Leaves can be harvested after plants grow 1.5– 2.0 m, which usually takes 6 to 12 months after planting depending on the growth conditions",
        "url": "https://dard.nwpg.gov.za/wp-content/uploads/2022/05/Moringa-production-for-food-security.pdf",
        "doc": "North West Department of Agriculture and Rural Development, Moringa (Moringa oleifera) production: A possible solution to South African food security challenges",
        "page": 33
      },
      "note": "First LEAF harvest. Pods come later: 'Flowers and pods are normally produced during the second year of growth.' (same guide, p.34). Mabapa et al. (2017, Limpopo farmer survey) report farmers harvesting foliage 3-12 months after planting and 35.2%/32.3% of farmers at 5 and 6 months; not used as the value. Years = 6/12 to 12/12. PDF page (printed page 32)."
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "musa-acuminata-aaa-group": {
    "speciesId": "musa-acuminata-aaa-group",
    "name": "Banana",
    "product": "fruit (bunch of bananas)",
    "windows": [],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": {
      "value": [
        19,
        22.2
      ],
      "source": {
        "quote": "Apply 40 g LAN (28) per plant every month from September to April and 200 g KCI per plant in September, November and February. This should be sufficient for a 40 t/ha crop. ... Density should not exceed 2 100 plants/ha and the long term optimum would be 1 800 - 2 000 plants/ha. This may be established by spacings of 3 x 1.75 m or 2.8 x 1.9 m.",
        "url": "https://www.kzndard.gov.za/images/Documents/Research%20and%20Technology%20Development%20Services/Publications/RESEARCH%20REPORTS/BananasinKwaZulu-Natal.pdf",
        "doc": "Lagerwall, G., 'Bananas in KwaZulu-Natal', KwaZulu-Natal Dept. of Agriculture and Rural Development, Research Report",
        "page": 4
      },
      "note": "Converted from sourced t/ha at the sourced density for the 'Williams' cultivar in the cooler KZN subtropics: 40 000 kg/ha ÷ 2 100 plants/ha = 19.0 kg/plant; 40 000 kg/ha ÷ 1 800 plants/ha = 22.2 kg/plant. This represents kg per plant per fruiting cycle (~12-14 months, i.e. roughly one bunch/plant/year under continuous ratoon cropping), not a tree accumulating yield over many years as with a fruit tree. The same source gives a higher density (2 200-2 500 plants/ha) for the warmer 'Grand Nain'/'Chinese Cavendish' areas, which would give a somewhat lower kg/plant (16.0-18.2 kg) at the same 40 t/ha target; no separate density figure specific to 'Dwarf Cavendish' was given in this source."
    },
    "chillUnits": null,
    "pollination": {
      "value": "self-fertile",
      "source": {
        "quote": "parthenocarpic seedless fruits that develop in the absence of pollination ... the ability to produce a fruit in the absence of pollination",
        "url": "https://www.promusa.org/Domestication+of+the+banana",
        "doc": "ProMusa (Bioversity International-affiliated global banana knowledge platform), 'Domestication of the banana'",
        "page": null
      },
      "note": "Not South Africa-specific, but this is a fixed genetic trait of the edible triploid (AAA group) Cavendish/Williams/Dwarf Cavendish clones grown in SA, not something that varies by region: these cultivars are parthenocarpic and set seedless fruit without any pollination at all (stronger than ordinary self-fertility). 'self-fertile' is the closest available enum value; strictly no pollen transfer of any kind (self or cross) is required for fruit set."
    }
  },
  "pappea-capensis": {
    "speciesId": "pappea-capensis",
    "name": "Jacket plum",
    "product": "fruit (seed used for oil)",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          12,
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ],
        "source": {
          "quote": "The trees flower from September to May (southern hemisphere) and the rather special fruit is produced from December to July.",
          "url": "https://pza.sanbi.org/pappea-capensis",
          "doc": "SANBI PlantZAfrica - Pappea capensis",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "passiflora-edulis": {
    "speciesId": "passiflora-edulis",
    "name": "Purple granadilla",
    "product": "fruit",
    "windows": [
      {
        "region": "KwaZulu-Natal (Bioresource Groups 3 and 5, cool subtropical)",
        "months": [
          11,
          12,
          1,
          6,
          7
        ],
        "source": {
          "quote": "Heaviest crop in November to January, secondary crop in June to July, with light cropping in between.",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
          "page": 14
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        0.5,
        0.67
      ],
      "source": {
        "quote": "First harvests are obtained 6 to 8 months after transplanting, with full bearing within 18 months.",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
        "page": 14
      },
      "note": "6 to 8 months after transplanting = 0.5 to 0.67 years (rounded). Page is the PDF page number (the printed page number in the document is 4 lower for this section)."
    },
    "yearsToFullBearing": {
      "value": [
        1.5,
        1.5
      ],
      "source": {
        "quote": "First harvests are obtained 6 to 8 months after transplanting, with full bearing within 18 months.",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
        "page": 14
      },
      "note": "'within 18 months' is an upper bound, stored as 1.5. Same sentence as the first-crop figure. Page is the PDF page number (the printed page number in the document is 4 lower for this section)."
    },
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "persea-americana": {
    "speciesId": "persea-americana",
    "name": "Avocado",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general, SAAGA industry overview)",
        "months": [
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10
        ],
        "source": {
          "quote": "the South African avocado season extended from February to October, but with new plantings at higher elevations and more southerly latitudes harvesting now takes place from February in the to mid-January.",
          "url": "https://avocado.co.za/sa-avocado-industry-overview/",
          "doc": "SA Avocado Industry Overview – South African Avocado Growers' Association (SAAGA)",
          "page": null
        }
      },
      {
        "region": "South Africa - warm subtropical regions (Hass cultivar)",
        "months": [
          6,
          7,
          8,
          9,
          10
        ],
        "source": {
          "quote": "Hass ... Flowering and harvesting months ... Warm regions ... Flowering: July - September ... Harvesting: June - October",
          "url": "http://www.avocadosource.com/international/south_africa_papers/cultivation_of_avocados.pdf",
          "doc": "Directorate Communication: Cultivation of Avocados (South African Dept. of Agriculture / ARC-Institute for Tropical and Subtropical Crops)",
          "page": 5
        }
      },
      {
        "region": "South Africa - cool subtropical regions (Hass cultivar)",
        "months": [
          8,
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "Hass ... Cool regions ... Flowering: August - October ... Harvesting: August - December",
          "url": "http://www.avocadosource.com/international/south_africa_papers/cultivation_of_avocados.pdf",
          "doc": "Directorate Communication: Cultivation of Avocados (South African Dept. of Agriculture / ARC-Institute for Tropical and Subtropical Crops)",
          "page": 5
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        2,
        3
      ],
      "source": {
        "quote": "Hass was the most precocious cultivar, with bearing starting in the second season, and reaching 10 t ha-1 by year three.",
        "url": "https://www.avocadosource.com/Journals/SAAGA/SAAGA_1991/SAAGA_1991_PG_15-18.pdf",
        "doc": "Wolstenholme, Kaiser & Palmer, 'Yield Potential of Intensively Managed Avocados in the Natal Midlands — The Early Bearing Years', South African Avocado Growers' Association Yearbook 1991, 14:15-18",
        "page": 1
      },
      "note": "Trial orchard at Bruyns Hill, Natal midlands (bioclimatic group 2), Hass on Duke 7 rootstock, 7x7 m spacing (200 trees/ha), planted 1982-1984. A separate SAAGA 1995 paper (Hackney, Boshoff & Slabbert, Everdon Estate, KZN) corroborates: 'Hass trees after two seasons of growth usually have attained sufficient canopy size to set a reasonable crop' (p.1, https://www.avocadosource.com/journals/saaga/saaga_1995/saaga_1995_pg_054-055.pdf)."
    },
    "yearsToFullBearing": {
      "value": [
        6,
        8
      ],
      "source": {
        "quote": "Hass was the most precocious and consistent bearer, averaging over 15 t ha-1 and reaching an average of 20 t ha-1 by the sixth year. Thereafter, an average yield of about 22,5 t ha-1 appears to be sustainable.",
        "url": "https://www.avocadosource.com/Journals/SAAGA/SAAGA_1991/SAAGA_1991_PG_15-18.pdf",
        "doc": "Wolstenholme, Kaiser & Palmer, SAAGA Yearbook 1991, 14:15-18",
        "page": 7
      },
      "note": "Same paper also states orchards in this trial 'can be considered to be approaching maximum sustainable average yields' by year eight (p.7), giving the [6,8] range for reaching full/sustainable bearing."
    },
    "yieldKgPerTree": {
      "value": [
        100,
        112.5
      ],
      "source": {
        "quote": "reaching an average of 20 t ha-1 by the sixth year. Thereafter, an average yield of about 22,5 t ha-1 appears to be sustainable ... At a spacing of 7 x 7 m (200 trees per ha)",
        "url": "https://www.avocadosource.com/Journals/SAAGA/SAAGA_1991/SAAGA_1991_PG_15-18.pdf",
        "doc": "Wolstenholme, Kaiser & Palmer, SAAGA Yearbook 1991, 14:15-18",
        "page": 3
      },
      "note": "Converted from sourced t/ha at the sourced spacing: 20 000 kg/ha ÷ 200 trees/ha = 100 kg/tree; 22 500 kg/ha ÷ 200 trees/ha = 112.5 kg/tree. Same paper notes 'because number of trees per ha varies widely, yield per tree is meaningless unless related to trees per ha' (p.2) — flagged here since modern SA orchards are often planted much denser (up to 800 trees/ha per the same source), which would give a lower kg/tree at a similar or higher t/ha."
    },
    "chillUnits": null,
    "pollination": {
      "value": "partly-self-fertile",
      "source": {
        "quote": "Hass, an A-type flowerer, tended to be out of phase with Fuerte and Rinton on a seasonal yield basis ... favourable temperatures at fruit-set (especially in B flowering type cultivars such as Fuerte) can result in heavy cropping",
        "url": "https://www.avocadosource.com/Journals/SAAGA/SAAGA_1991/SAAGA_1991_PG_15-18.pdf",
        "doc": "Wolstenholme, Kaiser & Palmer, SAAGA Yearbook 1991, 14:15-18",
        "page": 6
      },
      "note": "SA source confirms avocado's type A / type B protogynous dichogamous flowering system (temporal separation of male and female phases within a single tree) rather than stating self-fertility directly. Supporting SA quote on the practical effect: DAFF/ARC 'Cultivation of Avocados' guide lists for Fuerte (a Type B cultivar) 'Comments: fruit set increased by a pollinator' (http://www.avocadosource.com/international/south_africa_papers/cultivation_of_avocados.pdf, p.5), i.e. trees do set fruit alone (self-fertile) but cross-pollination with the opposite flower type improves fruit set — hence 'partly-self-fertile' rather than 'self-fertile' or 'needs-cross-pollinator'."
    }
  },
  "phoenix-reclinata": {
    "speciesId": "phoenix-reclinata",
    "name": "Wild date palm",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          2,
          3,
          4
        ],
        "source": {
          "quote": "The flowers appear during August, September and October. Male and female plants are separate... The orange-brown fruits are borne during February, March and April.",
          "url": "https://pza.sanbi.org/phoenix-reclinata",
          "doc": "SANBI PlantZAfrica - Phoenix reclinata",
          "page": null
        }
      },
      {
        "region": "southern Africa",
        "months": [
          2,
          3,
          4,
          5
        ],
        "source": {
          "quote": "In southern Africa flowering usually occurs in August–December, and fruits mature in February–May.",
          "url": "https://uses.plantnet-project.org/en/Phoenix_reclinata_(PROTA)",
          "doc": "PROTA (Plant Resources of Tropical Africa) - Phoenix reclinata, via Pl@ntUse mirror",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "separate-male-female-plants",
      "source": {
        "quote": "Male and female plants are separate.",
        "url": "https://pza.sanbi.org/phoenix-reclinata",
        "doc": "SANBI PlantZAfrica - Phoenix reclinata",
        "page": null
      },
      "note": "Corroborated by PROTA's structural description: 'Dioecious, usually clustering, rarely solitary tree up to 15 m tall...' (https://uses.plantnet-project.org/en/Phoenix_reclinata_(PROTA)). Both sources independently and directly confirm dioecy (separate male and female plants), which maps cleanly onto the schema's 'separate-male-female-plants' category."
    }
  },
  "physalis-peruviana": {
    "speciesId": "physalis-peruviana",
    "name": "Cape gooseberry",
    "product": "fruit",
    "windows": [
      {
        "region": "Stellenbosch, Western Cape (tunnel trial, planted June 2021)",
        "months": [
          10,
          11,
          12,
          1
        ],
        "source": {
          "quote": "only the matured fruits were harvested (Lovelli et al., 2017; Patidar et al., 2018) from late October 2021 to January 2022.",
          "url": "http://hdl.handle.net/10019.1/127165",
          "doc": "Tuaandi D (2023) The response of two Cape gooseberry varieties to organic amendments on degraded soils in the Western Cape, South Africa. MSc thesis, Stellenbosch University",
          "page": 28
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "prunus-persica": {
    "speciesId": "prunus-persica",
    "name": "Low-chill peach",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa — low-chill cultivar 'Earligold' (ARC Infruitec-Nietvoorbij bred, low-chill growing areas)",
        "months": [
          12
        ],
        "source": {
          "quote": "Week 49 – 50 (2nd week December)",
          "url": "https://culdevco.co.za/peach-cultivar-info-earligold/",
          "doc": "Culdevco (Plant Breeders' Rights licensing body for ARC-bred deciduous fruit cultivars) — Earligold peach cultivar information sheet",
          "page": null
        }
      },
      {
        "region": "South Africa — low/medium-chill cultivars 'Cederberg' and 'Afrisun' (ARC Infruitec-Nietvoorbij bred)",
        "months": [
          1
        ],
        "source": {
          "quote": "Cederberg: Week 2 (2nd week January). Afrisun: Harvest date (first pick): Week 1 (1st week January).",
          "url": "https://culdevco.co.za/peach-cultivar-info-cederberg/",
          "doc": "Culdevco — Cederberg and Afrisun peach cultivar information sheets",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        3,
        3
      ],
      "source": {
        "quote": "Light cropping starts in year 3, with full production from year 7.  Commercial orchards last approximately 12-15 years.",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes)",
        "page": 28
      },
      "note": "Same source used for years-to-full-bearing; region context is the low-chill peach areas named by the source: Muden, Middelrus and Weenen river valleys, KZN."
    },
    "yearsToFullBearing": {
      "value": [
        7,
        7
      ],
      "source": {
        "quote": "Light cropping starts in year 3, with full production from year 7.  Commercial orchards last approximately 12-15 years.",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes)",
        "page": 28
      },
      "note": "'Commercial orchards last approximately 12-15 years' — recorded here as context, not as a schema field."
    },
    "yieldKgPerTree": {
      "value": [
        23,
        43
      ],
      "source": {
        "quote": "Yields (t/ha) Conservative:   12      Average: 15-18        Good: 25+",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes)",
        "page": 28
      },
      "note": "CONVERTED, arithmetic shown: took the 'Average' yield band (15-18 t/ha) and the same source's stated spacing ('Generally planted 6m x 4m or 5 m x 3 m'). At 6x4m = 24 m²/tree → 10000/24 = 416.7 trees/ha → 15000kg/416.7=36.0 and 18000kg/416.7=43.2 kg/tree. At 5x3m = 15 m²/tree → 666.7 trees/ha → 15000/666.7=22.5 and 18000/666.7=27.0 kg/tree. Combined range across both spacings, rounded: [23, 43] kg/tree. This spread reflects the two different sourced spacings, not cultivar variation."
    },
    "chillUnits": {
      "value": [
        200,
        600
      ],
      "source": {
        "quote": "Low chill areas (200-600PCU’s) \nPeaches – Transvalia, Sonette, Oom Sarel, Keisie",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, 'Fruit and Nut Production in KZN' (Horticultural Advisory Notes)",
        "page": 29
      },
      "note": "PCU = Peach Chill Units (Infruitec/ARC chill-unit model used for SA stone fruit). This source's 'low chill' band (200-600 PCU) is corroborated by per-cultivar Culdevco/ARC sheets: 'Earligold' = 'low to medium (200-400 Infruitec Chilling Units)'; 'Cederberg' and 'Afrisun' = 'Medium (400-600 Infruitec Chilling Units)'. The KZN source's own category label bundles both 'low' and 'medium' ARC sub-bands into one 'low chill areas' bracket contrasted with '>600 PCU's' for high-chill areas."
    },
    "pollination": {
      "value": "self-fertile",
      "source": {
        "quote": "‘Self’ – This cultivar is self-fertile and does not require a separate pollinator variety.",
        "url": "https://culdevco.co.za/peach-cultivar-info-earligold/",
        "doc": "Culdevco — Earligold peach cultivar information sheet",
        "page": null
      },
      "note": "Corroborated by the Cederberg sheet ('Self' pollinating) and the Afrisun sheet ('Pollinator: Self-compatible'), all three being ARC Infruitec-Nietvoorbij low/medium-chill peach cultivars."
    }
  },
  "prunus-salicina": {
    "speciesId": "prunus-salicina",
    "name": "Japanese plum",
    "product": "fruit",
    "windows": [
      {
        "region": "Western Cape (Boland / Klein Karoo / Robertson stone-fruit areas)",
        "months": [
          2
        ],
        "source": {
          "quote": "7. HARVESTING OF FRUIT [...] Harvest fruit during the coolest time of day [...] Fruit should be harvested between a minimum and maximum fruit firmness of 5.5 kg and 9 kg [...] the quality of fruit coming from trees [...] Week 8 – 10 (4th week February)",
          "url": "https://culdevco.co.za/plums-cultivar-info-african-delight/",
          "doc": "Culdevco (ARC/Deciduous Fruit Industry joint-venture cultivar licensing body) — African Delight® plum cultivar information; cross-referenced with Hortgro's 'TOP CULDEVCO LICENSED PLUM CULTIVARS' article",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        3,
        3
      ],
      "source": {
        "quote": "4. FIRST HARVEST a. Trees should preferably only bear its first harvest in the third growth season. b. The first 2 years should be used for the shaping of the tree.",
        "url": "https://www.hortgro.co.za/wp-content/uploads/docs/2020/12/Culdevco-Plum-article.-2020.pdf",
        "doc": "Hortgro / Culdevco, 'TOP CULDEVCO LICENSED PLUM CULTIVARS' (2020) — African Delight® section",
        "page": 4
      },
      "note": "Stated for African Delight® specifically, an ARC-bred Japanese plum cultivar; 'third growth season' interpreted as year 3."
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": {
      "value": [
        15,
        20
      ],
      "source": {
        "quote": "A yield of between 30 and 40 tons per hectare is attainable in adult orchards. [...] Tree spacing (m) 4.0 x 1.25 [...] Trees/ha 2000",
        "url": "https://www.hortgro.co.za/wp-content/uploads/docs/2020/12/Culdevco-Plum-article.-2020.pdf",
        "doc": "Hortgro / Culdevco, 'TOP CULDEVCO LICENSED PLUM CULTIVARS' (2020) — Ruby Crisp section and Table 1",
        "page": 2
      },
      "note": "CONVERTED, arithmetic shown: 'A yield of between 30 and 40 tons per hectare is attainable in adult orchards' (Ruby Crisp) combined with the spacing given in the same document's Table 1 for Ruby Crisp trial blocks ('Tree spacing (m) 4.0 x 1.25', 'Trees/ha 2000'): 4.0 x 1.25m = 5 m²/tree → 10000/5 = 2000 trees/ha (matches the table directly). 30000kg/2000 = 15 kg/tree; 40000kg/2000 = 20 kg/tree → [15,20] kg/tree. Note the source separately gives African Delight® yields as 'Mature orchards between 35 and 50 tons per hectare' but does not give African Delight's own spacing, so that figure was not converted to avoid assuming a spacing not stated for that cultivar."
    },
    "chillUnits": {
      "value": [
        200,
        600
      ],
      "source": {
        "quote": "African Delight®: Chilling requirement: Medium to low (400 – 200 Infruitec Chilling Units). [...] Ruby Crisp: Chilling Requirement: Medium (400-600 Infruitec Chilling Units).",
        "url": "https://culdevco.co.za/plums-cultivar-info-african-delight/",
        "doc": "Culdevco — African Delight® and Ruby Crisp plum cultivar information sheets",
        "page": null
      },
      "note": "Range spans the lowest (African Delight, 200 CU) to highest (Flavour Star, 'Medium (500-600 Infruitec Chilling Units)' per its own Culdevco sheet) Infruitec Chilling Unit figures found among the five ARC-bred cultivars documented in the Hortgro/Culdevco article. Not a single-cultivar figure but a range across cultivars grown in South Africa."
    },
    "pollination": {
      "value": "needs-cross-pollinator",
      "source": {
        "quote": "2. CROSS POLLINATION a. African Rose® is recommended as a cross-pollinator for most areas in South Africa at a 10% ratio. Where Pioneer is already used as a cross-pollinator it is not necessary to use African Rose®. b. Bees should be used in orchards to optimise the pollination process.",
        "url": "https://www.hortgro.co.za/wp-content/uploads/docs/2020/12/Culdevco-Plum-article.-2020.pdf",
        "doc": "Hortgro / Culdevco, 'TOP CULDEVCO LICENSED PLUM CULTIVARS' (2020) — African Delight® section",
        "page": 4
      },
      "note": "Consistent across all five ARC-bred Japanese plum cultivars documented in this source: Flavour Star needs 'Laetitia and Larry Ann' plus 'Songold' as pollinators ('It is recommended to plant both pollinators'); Ruby Crisp needs 'Harry Pickstone and Fortune ... as cross pollinators ... at a ratio of 10%'; Ruby Sun needs 'Harry Pickstone ... as a cross pollinator ... at a ratio of 10% to 15%'; Ruby Star needs 'Songold, Southern Belle, or both ... as cross pollinators ... in a 10% ratio'. This strongly and consistently supports 'needs-cross-pollinator' for commercial Japanese plum cultivars grown in South Africa (as opposed to a generic species-level claim; some plum cultivars elsewhere are self-fertile, but the SA commercial cultivars documented here are not)."
    }
  },
  "psidium-guajava": {
    "speciesId": "psidium-guajava",
    "name": "Guava",
    "product": "fruit",
    "windows": [],
    "yearsToFirstCrop": {
      "value": [
        1,
        2
      ],
      "source": {
        "quote": "Seedlings may flower within 2 years; clonally propagated trees often begin to bear during the first year after planting.",
        "url": "https://apps.worldagroforestry.org/treedb/AFTPDFS/Psidium_guajava.PDF",
        "doc": "World Agroforestry (ICRAF), Agroforestree Database 4.0 (Orwa et al. 2009), Psidium guajava species sheet",
        "page": 1
      },
      "note": "This is a global horticultural-biology reference, not South Africa-specific; no SA source (ARC-ITSC's own guava page returned HTTP 503 on every attempt) was reachable to confirm or refine this for South African conditions/cultivars."
    },
    "yearsToFullBearing": {
      "value": [
        5,
        8
      ],
      "source": {
        "quote": "Trees reach full bearing after 5-8 years, depending on growing conditions and spacing. The guava is not a long-lived tree (about 40 years), but the plants may bear heavily for 15-25 years.",
        "url": "https://apps.worldagroforestry.org/treedb/AFTPDFS/Psidium_guajava.PDF",
        "doc": "World Agroforestry (ICRAF), Agroforestree Database 4.0 (Orwa et al. 2009), Psidium guajava species sheet",
        "page": 1
      },
      "note": "Same caveat as yearsToFirstCrop: global reference, not SA-specific."
    },
    "yieldKgPerTree": {
      "value": [
        50,
        70
      ],
      "source": {
        "quote": "Average yields are between 30-40 kg/plant in 5 year-old plants and will reach a maximum production of 50-70 kg at about 7 years if well managed.",
        "url": "https://apps.worldagroforestry.org/treedb/AFTPDFS/Psidium_guajava.PDF",
        "doc": "World Agroforestry (ICRAF), Agroforestree Database 4.0 (Orwa et al. 2009), Psidium guajava species sheet",
        "page": 2
      },
      "note": "Took the 'about 7 years, well managed' maximum-production figure (50-70 kg/plant) as the mature-tree value rather than the 5-year-old figure (30-40 kg/plant), since 7 years falls within this same source's 5-8 year 'full bearing' range. Not South Africa-specific; no SA-specific per-tree yield figure was found (ARC-ITSC and a peer-reviewed SA journal article on guava wilt-disease-resistant selections were both unreachable/paywalled — see gaps)."
    },
    "chillUnits": null,
    "pollination": {
      "value": "partly-self-fertile",
      "source": {
        "quote": "Bees are the principal pollinators. There is some self- and cross-incompatibility but several cultivars have set fair crops of seedless or few-seeded fruit. Levels of 60-75% selfing have been found in natural populations; this has been used to produce homozygotic varieties that can be propagated from seed.",
        "url": "https://apps.worldagroforestry.org/treedb/AFTPDFS/Psidium_guajava.PDF",
        "doc": "World Agroforestry (ICRAF), Agroforestree Database 4.0 (Orwa et al. 2009), Psidium guajava species sheet",
        "page": 1
      },
      "note": "Guava is capable of substantial self-pollination (60-75% selfing measured in natural populations) but also benefits from bee-mediated cross-pollination and shows some self-incompatibility in certain cultivars, matching 'partly-self-fertile' rather than a clean 'self-fertile' or 'needs-cross-pollinator'. Not South Africa-specific."
    }
  },
  "punica-granatum": {
    "speciesId": "punica-granatum",
    "name": "Pomegranate",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          2,
          3,
          4
        ],
        "source": {
          "quote": "The Southern Hemisphere harvest season is from February to April.",
          "url": "https://postharvestinnovation.org.za/commodities/pomegranate/",
          "doc": "Post-Harvest Innovation Programme (PHI) — Pomegranate commodity page",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": {
      "value": [
        6,
        6
      ],
      "source": {
        "quote": "Pomegranate trees take six years to bear a full crop.",
        "url": "https://postharvestinnovation.org.za/commodities/pomegranate/",
        "doc": "Post-Harvest Innovation Programme (PHI) — Pomegranate commodity page",
        "page": null
      },
      "note": "Given as a single figure (six years), not a range, so recorded as [6,6]."
    },
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "rhoicissus-tomentosa": {
    "speciesId": "rhoicissus-tomentosa",
    "name": "Common wild grape",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          5,
          6
        ],
        "source": {
          "quote": "Flowering time is midsummer (Oct.-Jan.)... deep purplish black when fully ripe at the beginning of winter (May to June).",
          "url": "https://pza.sanbi.org/rhoicissus-tomentosa",
          "doc": "SANBI PlantZAfrica - Rhoicissus tomentosa",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "rubus-idaeus": {
    "speciesId": "rubus-idaeus",
    "name": "Raspberry",
    "product": "fruit",
    "windows": [
      {
        "region": "KwaZulu-Natal (spring-bearing cultivars: Glen Prosen, Glen Lyon, Tulameen)",
        "months": [
          11,
          12,
          1
        ],
        "source": {
          "quote": "Flowering 3-4 weeks later, with fruit maturity & harvest 8 weeks later (1st week November to late January).",
          "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
          "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
          "page": 37
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "sclerocarya-birrea-subsp-caffra": {
    "speciesId": "sclerocarya-birrea-subsp-caffra",
    "name": "Marula",
    "product": "fruit (also the nut/kernel inside the stone is eaten, but the picked product is the fruit)",
    "windows": [
      {
        "region": "South Africa (general; SA distribution given as KwaZulu-Natal, Limpopo, Mpumalanga)",
        "months": [
          2,
          3,
          4,
          5,
          6
        ],
        "source": {
          "quote": "Male and female flowers are borne on separate trees, the flowers of male plants producing pollen and the female flowers producing the fruit for which the tree is so well known. These are green on the tree and turn yellow after falling (Feb-June).",
          "url": "https://pza.sanbi.org/sclerocarya-birrea",
          "doc": "Sclerocarya birrea | PlantZAfrica (SANBI)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": {
      "value": [
        200,
        1500
      ],
      "source": {
        "quote": "The S. birrea ssp. caffra tree is a prolific seed bearer: between 0.2 and 1.5 t of fruit have been collected from a single tree in 1 season in the wild.",
        "url": "https://apps.worldagroforestry.org/treedb2/speciesprofile.php?Spid=1513",
        "doc": "ICRAF Agroforestree Species Profile, Sclerocarya birrea ssp. caffra (Spid=1513)",
        "page": null
      },
      "note": "Converted from tonnes to kg as stated by the source: 0.2 t x 1000 = 200 kg; 1.5 t x 1000 = 1500 kg. Source describes this as a wild-tree range, not necessarily a managed orchard tree. WebSearch (not fetched/verified verbatim) also surfaced other figures from Shackleton (2002) and a 2014 Agroforestry Systems paper (e.g. ~30-570 kg/tree/yr, up to ~1600 kg/tree) that roughly agree with this range but were NOT used as evidence here because they were only seen as paraphrased search-result summaries, never as verbatim fetched text."
    },
    "chillUnits": null,
    "pollination": {
      "value": "separate-male-female-plants",
      "source": {
        "quote": "Male and female flowers are borne on separate trees, the flowers of male plants producing pollen and the female flowers producing the fruit for which the tree is so well known.",
        "url": "https://pza.sanbi.org/sclerocarya-birrea",
        "doc": "Sclerocarya birrea | PlantZAfrica (SANBI)",
        "page": null
      },
      "note": "Confirmed by a second, independent source: ICRAF treedb2 species profile (Spid=1513) states 'Although male and female flowers occasionally occur on the same tree, it is considered dioecious.' PZA's own Ecology section also states 'Insects pollinate the flowers.' (https://pza.sanbi.org/sclerocarya-birrea), i.e. pollen is moved between separate male and female trees by insects."
    }
  },
  "strychnos-spinosa": {
    "speciesId": "strychnos-spinosa",
    "name": "Spiny monkey orange",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general)",
        "months": [
          8,
          9,
          10,
          11,
          12
        ],
        "source": {
          "quote": "Strychnos spinosa is a seasonal fruit tree that is harvested between August and December",
          "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8703348/",
          "doc": "Undervalued Spiny Monkey Orange (Strychnos spinosa Lam.): An Indigenous Fruit for Sustainable Food-Nutrition and Economic Prosperity (peer-reviewed review, PMC8703348)",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        3,
        5
      ],
      "source": {
        "quote": "Presently, Strychnos spinosa can be propagated via seeds, grafting, or budding, with the production of fruit starting 3–5 years after planting",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8703348/",
        "doc": "Undervalued Spiny Monkey Orange (Strychnos spinosa Lam.): An Indigenous Fruit for Sustainable Food-Nutrition and Economic Prosperity (peer-reviewed review, PMC8703348)",
        "page": null
      }
    },
    "yearsToFullBearing": null,
    "yieldKgPerTree": {
      "value": [
        40,
        100
      ],
      "source": {
        "quote": "Fruit weighs between 145 and 383 g, while about 300–700 fruits (40–100 kg) can be produced per tree stand.",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8703348/",
        "doc": "Undervalued Spiny Monkey Orange (Strychnos spinosa Lam.): An Indigenous Fruit for Sustainable Food-Nutrition and Economic Prosperity (peer-reviewed review, PMC8703348)",
        "page": null
      },
      "note": "Value taken directly as stated by the source in kg (40-100 kg per tree for 300-700 fruits); no conversion performed."
    },
    "chillUnits": null,
    "pollination": null
  },
  "syzygium-cordatum": {
    "speciesId": "syzygium-cordatum",
    "name": "Waterberry",
    "product": "fruit",
    "windows": [
      {
        "region": "southern Africa",
        "months": [
          11,
          12,
          1,
          2,
          3
        ],
        "source": {
          "quote": "In southern Africa flowering is in August–November, and fruiting in November–March.",
          "url": "https://uses.plantnet-project.org/en/Syzygium_cordatum_(PROTA)",
          "doc": "PROTA (Plant Resources of Tropical Africa) - Syzygium cordatum, via Pl@ntUse mirror",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "vaccinium-corymbosum": {
    "speciesId": "vaccinium-corymbosum",
    "name": "Blueberry",
    "product": "fruit",
    "windows": [
      {
        "region": "Western Cape (Hex River and Wolseley trial sites)",
        "months": [
          8,
          9,
          10,
          11
        ],
        "source": {
          "quote": "Cropping occurred from early August to mid-November, and volumes peaked in October, at both sites.",
          "url": "https://scholar.sun.ac.za/server/api/core/bitstreams/47824860-fa96-4626-b2b2-da6439d6a8f4/content",
          "doc": "Steyn, J. (2022) 'Investigating plant growth dynamics of selected southern highbush blueberry (V. corymbosum L. interspecific hybrids) cultivars under South African growing conditions', MSc(Agric) thesis, University of Stellenbosch",
          "page": 45
        }
      },
      {
        "region": "South Africa (national, USDA FAS GAIN)",
        "months": [
          9,
          10,
          11,
          12,
          1,
          2
        ],
        "source": {
          "quote": "The South African blueberry harvest season traditionally starts in September and ends in mid-February.",
          "url": "https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=The+Budding+Blueberry+Industry+in+South+Africa_Pretoria_South+Africa+-+Republic+of_10-05-2017",
          "doc": "USDA FAS GAIN report, 'The Budding Blueberry Industry in South Africa' (5 Oct 2017)",
          "page": 2
        }
      }
    ],
    "yearsToFirstCrop": {
      "value": [
        2,
        3
      ],
      "source": {
        "quote": "Blueberry plants take up to two to three years to start producing fruits of export quality.",
        "url": "https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=The+Budding+Blueberry+Industry+in+South+Africa_Pretoria_South+Africa+-+Republic+of_10-05-2017",
        "doc": "USDA FAS GAIN report, 'The Budding Blueberry Industry in South Africa' (5 Oct 2017)",
        "page": 3
      },
      "note": "Source wording is 'up to two to three years' for fruit of EXPORT quality, so it is an upper-ish estimate; earlier light fruiting is not excluded. USDA FAS GAIN 2017, PDF page."
    },
    "yearsToFullBearing": {
      "value": [
        6,
        7
      ],
      "source": {
        "quote": "Productive lifetime of 20-30 years. Time to full production: 6-7 years",
        "url": "https://www.kzndard.gov.za/images/Documents/Horticulture/Veg_prod/Fruit%20and%20%20Nut%20Production%20in%20KZN.pdf",
        "doc": "KwaZulu-Natal Department of Agriculture and Rural Development, Horticultural Advisory Notes: Fruit and Nut Production (in KZN)",
        "page": 38
      },
      "note": "KZN advisory notes for 'Blueberry (Vaccinium spp.)' with rabbiteye cultivars listed (Tifblue, Beckyblue, Climax), so not specific to southern highbush. Page is the PDF page number (the printed page number in the document is 4 lower for this section)."
    },
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "partly-self-fertile",
      "source": {
        "quote": "Cross-pollination increased fruit weight, seed number per fruit, as well as shortened the fruit development period.",
        "url": "https://scholar.sun.ac.za/server/api/core/bitstreams/47824860-fa96-4626-b2b2-da6439d6a8f4/content",
        "doc": "Steyn, J. (2022) 'Investigating plant growth dynamics of selected southern highbush blueberry (V. corymbosum L. interspecific hybrids) cultivars under South African growing conditions', MSc(Agric) thesis, University of Stellenbosch",
        "page": 31
      },
      "note": "Mapped from a study of 'Sharpblue' SHB self- versus cross-pollination cited in the thesis: self-pollinated fruit still develops, cross-pollination improves size, seed and ripening time. KZN notes are more cautious: 'Plant two or more compatible cultivars to ensure cross pollination and adequate fruit set.' PDF page."
    }
  },
  "vangueria-infausta": {
    "speciesId": "vangueria-infausta",
    "name": "Wild medlar",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa (general; SA distribution given as Eastern Cape, Free State, Gauteng, KwaZulu-Natal, Limpopo, Mpumalanga, North West, Northern Cape)",
        "months": [
          1,
          2,
          3,
          4
        ],
        "source": {
          "quote": "It can be found on the plants during summer, from January to April.",
          "url": "https://pza.sanbi.org/vangueria-infausta",
          "doc": "Vangueria infausta | PlantZAfrica (SANBI)",
          "page": null
        }
      },
      {
        "region": "southern Africa (general, per ICRAF; not South-Africa-specific wording)",
        "months": [
          11,
          12,
          1,
          2,
          3,
          4
        ],
        "source": {
          "quote": "In southern Africa, the tree flowers from September to November and fruits from November to April.",
          "url": "https://apps.worldagroforestry.org/treedb2/AFTPDFS/Vangueria_infausta.PDF",
          "doc": "Agroforestree Database 4.0 (Orwa et al. 2009), Vangueria infausta fact sheet, BIOLOGY section",
          "page": 1
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": null
  },
  "vitis-vinifera": {
    "speciesId": "vitis-vinifera",
    "name": "Grape vine",
    "product": "fruit",
    "windows": [
      {
        "region": "South Africa — Northern Province(s) region (SATI production region; mild sub-tropical, earliest SA harvest)",
        "months": [
          11,
          12
        ],
        "source": {
          "quote": "produces South Africa's earliest grapes from November to mid-December",
          "url": "https://www.satgi.co.za/about/",
          "doc": "South African Table Grape Industry (SATI) — 'About' page, production regions section",
          "page": null
        }
      },
      {
        "region": "South Africa (overall, all regions combined)",
        "months": [
          11,
          12,
          1,
          2,
          3,
          4,
          5
        ],
        "source": {
          "quote": "South Africa boasts five major growing regions...enable growers to supply the markets with the latest varieties from November to May.",
          "url": "https://www.satgi.co.za/about/",
          "doc": "South African Table Grape Industry (SATI) — 'About' page",
          "page": null
        }
      }
    ],
    "yearsToFirstCrop": null,
    "yearsToFullBearing": null,
    "yieldKgPerTree": null,
    "chillUnits": null,
    "pollination": {
      "value": "self-fertile",
      "source": {
        "quote": "Hermaphroditic (perfect) flowers were a key trait in grapevine domestication, enabling a drastic increase in yields due to the efficiency of self-pollination in the domesticated grapevine (Vitis vinifera L. ssp. vinifera).",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8053984/",
        "doc": "Zou, Massonnet, Minio et al., 'Multiple independent recombinations led to hermaphroditism in grapevine', Proceedings of the National Academy of Sciences (PNAS), Vol. 118, No. 15, e2023548118 (2021)",
        "page": null
      },
      "note": "This is a general (not South Africa-specific) peer-reviewed genetics/domestication paper, used because it directly and explicitly states that cultivated Vitis vinifera (the domesticated subspecies grown as table grapes, as opposed to wild dioecious V. vinifera ssp. sylvestris) bears hermaphroditic, self-pollinating flowers — i.e. does not require a separate pollinator vine. No SA-specific source contradicting or refining this general botanical fact was found; SA table-grape cultivar sheets/enterprise budgets checked in this session (e.g. the Elsenburg Flame Seedless budget) did not mention any cross-pollination requirement, consistent with self-fertility."
    }
  }
};
