// What changed in the build the farmer is about to refresh into.
//
// The update banner used to say only "New version available" — which tells you a number changed,
// not whether it is worth interrupting your work for, and gives you nothing to check afterwards.
// (Rory: "when you refresh i want the changes listed underneath the refresh button and in brief".)
//
// RULES FOR WRITING THESE. One line per change, in the farmer's language, describing what is
// different ON THEIR SCREEN — never the mechanism. "Zone maps now follow the zones you drew", not
// "buildZoneOverlay is composited on the model-chrome path". Newest build at the top, and keep the
// list to the last few builds: this is a "should I refresh, and what do I look at" note, not a
// changelog. Anything longer belongs in the repo's docs.
export interface ReleaseNote {
  /** Short human date — no clock time; the farmer only needs the ordering. */
  when: string;
  changes: string[];
  /**
   * The newest commit this entry covers.
   *
   * WHY A SHA IS IN A FARMER-FACING FILE. This list is written by hand, and on 2026-08-02 Rory
   * reported the banner "keeps showing me old updates not the new ones". Nothing was broken: the
   * banner faithfully renders the newest notes it has, and the newest notes were from 1 August
   * while FIFTY-FIVE commits touching app/, components/ and lib/ had landed since — a whole day
   * of money bugs, sheet fixes and a Mentor privilege hole, none of it written down. A build
   * number that moves while the notes stand still is worse than no notes, because it tells the
   * farmer these ARE the changes.
   *
   * So each entry records where it was written from, and `npm run notes:pending` lists what has
   * shipped since. The drift is now a question anyone can ask in one command instead of something
   * you notice weeks later from a screenshot.
   */
  sha?: string;
}

/** Shown newest-first under the Refresh button. The banner renders at most MAX_SHOWN lines total. */
export const RELEASE_NOTES: ReleaseNote[] = [
  {
    when: '29 August',
    sha: '813e78e',
    changes: [
      'Catalogue plants now show their own picture, with fruit and flowers easy to see',
      'The design map now uses the matching overhead crown for each named plant',
      'Sharing switches in the try-it farm now hold, instead of switching themselves off',
      'Text on the funder and NGO programme views is now easier to read on a phone',
    ],
  },
  {
    when: '29 August',
    sha: 'f4b01b6',
    changes: [
      'The smallest text on farmer pages has been bumped up to stay readable in the sun',
      'Map trees and garden pictures now stay on your phone after an update',
      'Those pictures are also much smaller now, so the first download costs far less data',
      'Tapping a report with no signal now tells you, instead of doing nothing at all',
      'When writing a report fails for lack of signal, it now says so in plain words',
      'Programme funders get their own view: progress, harvests and sales across a cohort',
      'That funder view only ever shows what each farmer has agreed to share',
      'A public page now introduces the app to NGOs and funders, with a link to get it',
      'Trying the app without an account now shows the funder and NGO screens with sample data',
    ],
  },
  {
    when: '27 August (late)',
    sha: 'f9b5338',
    changes: [
      'Choose your language first, before the Start button, when you set the app up',
      'You can change language on a phone now — Settings, at the top',
      'The language you pick in your account now actually changes the app',
      'The bar at the bottom asks Lima for help instead of waiting for typing',
    ],
  },
  {
    when: '27 August (evening)',
    sha: '80ae8f2',
    changes: [
      'The Journal is for notes and photos, not for logging harvests',
      'Harvest weights and sales go in My Records — the Journal now says so',
      'The Journal also tells you it is kept on this phone only',
      'The menu shows only the pages your account can open',
    ],
  },
  {
    when: '27 August',
    sha: '2a35eed',
    changes: [
      'The sharing switches you set yesterday now actually reach your programme',
      'Your programme sees only the categories you switched on — and only your own organisation',
      'If you share nothing, you are not on their list at all',
    ],
  },
  {
    when: '26 August',
    sha: '67080d0',
    changes: [
      'You decide what your programme can see: Account → What you share',
      'Nothing is shared until you switch it on — each thing separately',
      'Sharing what you harvested no longer shares what you earned',
      'One button stops all sharing, any time',
    ],
  },
  {
    when: '24 August',
    sha: '9e27855',
    changes: [
      'Your lender pack adds up: the table now matches the total above it',
      'Avocado and Avocados are one tree again, not two',
      'The panel your funder opens names your real crop, with the right picture',
      'Malabar spinach and pigeon peas stay in the orchard, not on a vegetable bed',
      'Your records are visible to your own organisation only',
    ],
  },
  {
    when: '23 August',
    sha: 'aec85dc',
    changes: [
      'Fruit, nuts and berries can be recorded now — your orchard is in the crop list',
      'The orchard has its own figures: kilograms picked, rand taken, and price a kilogram',
      'One fruit is one row, however you spelt its name when you logged it',
      'A staple plot standing bare for months is now named on your plan, with the reason',
      'An Orchard button counts the trees in your totals, or leaves them out',
      'When it leaves them out, the screen names the fruit and the kilograms \u2014 picked and sold',
      'Rand totals always count every sale — only the kilograms follow that button',
      'Finance opens with a cash-flow graph — money in against money out, month by month',
      'A harvest graph shows what you picked, what you sold, and what stayed on the farm',
      'A second view puts your plan\u2019s benchmark beside what you have actually picked',
      'Finance now lists what the crop plan says is coming up to harvest',
      'The menu button is on every screen, so no screen is a dead end',
      'Invoices head with your enterprise name and logo, with prices already suggested',
      'The finance demo runs in sample mode instead of writing rows into your real books',
      'The crop-plan picker draws each farm instead of listing it by name',
      'Kale can be scheduled now; its yield figure is labelled international, not South African',
    ],
  },
  {
    when: '22 August',
    sha: '3f44004',
    changes: [
      'A Production score says what a square metre of your plan earns, in rands',
      'That score is split between vegetable beds and staple plots, which earn very differently',
      'The score card names what it assumes you sell, what is lost, and which price',
      'A two-page quick print: a calendar for the wall, and the tasks that go with it',
      'The workload chart in the crop-plan PDF agrees with the field sheets beside it again',
      'The Field utilization chart lines up with its own month labels again',
      'Chilli is its own crop now, separate from peppers',
      'Onion, Swiss chard and potato sowing months follow the KZN department\u2019s own table',
    ],
  },
  {
    when: '21 August',
    sha: 'cfd0bd9',
    changes: [
      'A new figure says whether your plan\u2019s yield is in line with the ground it uses',
      'When a crop you chose does not make it into the plan, the plan says why',
      'A bed that is only part taken can take a starter crop in the room that is left',
      'A one-off sowing whose month has passed reads as history, not as work still ahead',
      'First-season notes no longer promise a gap the repeating cycle cannot close',
      'Starter crops are ranked by months they feed you, not how fast they clear ground',
    ],
  },
  {
    when: '20 August (evening)',
    sha: 'eb1fe7a',
    changes: [
      'The whole-year plan now adds one-off starter sowings to cover your first bare months',
      'Those rows are marked "first season only" — on screen, in the PDF and in the report',
      'A bed or plot is no longer shown carrying more crops at once than it has room for',
      'A starter raised in trays keeps its planting-out job and seedling list for that month',
      'A plot no longer gets two main crops sown over each other in its first season',
    ],
  },
  {
    when: '20 August',
    sha: '5187094',
    changes: [
      'Suggest a plan can now plan the whole year, not just from today',
      'It tries all 12 starting months and keeps the one with the fewest fresh-harvest gaps',
      'The whole-year card says what to sow now and which sowings wait for next season',
      'A crop whose window is open but has no room yet is named, with the month a spot opens',
      'Delete questions now show as proper in-app dialogs instead of quietly cancelling',
      '"Clear all" on the crop plan works again; the Back button no longer covers the header',
      "The map's Layers panel can be resized by its corner handle again",
      'Design Studio: a crop plan link in the header, and no more doubled preview map',
      'The crop plan farm picker lists Design Studio farms and tells twin names apart',
    ],
  },
  {
    when: '20 August',
    sha: 'f4d7acf',
    changes: [
      'Plan notes now lead with warnings in plain words; long lists fold behind one line',
      'Your plan keeps those notes after you accept it — "Why this plan chose what it chose"',
      'Crops waiting for their sowing window are listed with the month they can go in',
      'Adding a crop to a busy bed now names the crops it would compete with, and when',
      'The Seeds & seedlings list is grouped by the month to buy each packet or tray',
      'Task Planner shows the real jobs from your crop plan in every month they are due',
      'Stored crops now say how long they keep and what storage they need — tap a chart month',
      'Turnips now carry a sourced price; true spinach says honestly why it has none',
    ],
  },
  {
    when: '20 August',
    sha: '7fa68e3',
    changes: [
      'Commercial plans now use every bed you set aside — none are skipped in silence',
      'The plan now says why any bed was left empty, and what you can do about it',
      'Stored crops like maize and beans now show how long they feed you after harvest',
      'Two new crops: true spinach and turnips, with sourced planting windows',
      'Coastal farms can now be offered pepper and tomato sowings through spring',
      'Winter cover crops now prefer the rotation-friendly choice for each plot',
    ],
  },
  {
    when: '19 August',
    sha: '5f783d9',
    changes: [
      "Planting windows now follow your farm's own rainfall, not the nearest big city's",
      'Crop families no longer repeat in beds; seedlings stay there from planting month',
      'Harvest-loss slider now starts at 25% — the researched figure for SA farmers',
      'Your household size shows how much veg your family needs year-round',
      'Orange, Lemon and Grapefruit now have their own tree cards',
      'Painted map styles no longer cover the exact master drawing',
      'Weather panel icons are bigger and easier to read',
    ],
  },
  {
    when: '19 August',
    sha: '6c453fd',
    changes: [
      'Full-design maps now give the drawing more room and use one clear grouped legend',
    ],
  },
  {
    when: '19 August',
    sha: 'cb7290b',
    changes: [
      'Named tree cards now place immediately; use Other to choose from the full catalogue',
      'High-quality Gemini map renders now use Gemini Pro instead of the draft model',
    ],
  },
  {
    when: '18 August',
    sha: '032c90d',
    changes: [
      'Every expanded layer group now has its own Select box',
      'Saved maps now fill the centre so you can judge them at a useful size',
      'You can lock a map layer from moving while keeping it visible',
      'The Moringa card now has a larger, clearer tree picture',
    ],
  },
  {
    when: '18 August',
    sha: 'e95c732',
    changes: [
      'Gemini maps now start from cleaner placement marks for a less sticker-like aerial plan',
    ],
  },
  {
    when: '18 August',
    sha: 'e4efffe',
    changes: [
      'Every Layers row now opens so you can see the controls beneath it',
      'Planting controls are now a neater, single-column list',
      'The Moringa tree card now shows its long seed pods',
    ],
  },
  {
    when: '18 August',
    sha: 'e2a7bf7',
    changes: [
      'Tree cards show recognisable front views again while plan maps keep measured top views',
      'Water controls now open inside the Water layer instead of sitting in a separate section',
      'Whole-design AI maps no longer keep a result that erases the site into blank paper',
      'The full Layers panel now fits on desktop without scrolling',
      'Each saved map now has its own delete button',
    ],
  },
  {
    when: '17 August',
    sha: '01e05fb',
    changes: [
      'Preview & Export now opens your latest saved map for the selected sheet',
    ],
  },
  {
    when: '17 August',
    sha: 'fcdae3d',
    changes: [
      'Studio panels now switch layouts and resize from three element cards down to one',
    ],
  },
  {
    when: '17 August',
    sha: 'd416b12',
    changes: [
      'Layers now have clear map icons, visibility eyes and select-all ticks',
    ],
  },
  {
    when: '17 August',
    sha: 'da4ca5f',
    changes: [
      'Large saved-map galleries no longer crash phones before a sheet can render',
    ],
  },
  {
    when: '17 August',
    sha: 'dc5dd03',
    changes: [
      'Phone renders no longer get stuck while locking a High-quality exact map',
    ],
  },
  {
    when: '16 August',
    sha: '0d2f282',
    changes: [
      'Saved maps now marks older layouts clearly instead of presenting them as current',
    ],
  },
  {
    when: '16 August',
    sha: 'b731a32',
    changes: [
      'Try the photo again now restores the design photo after the app opens in light mode',
    ],
  },
  {
    when: '16 August',
    sha: '91712fb',
    changes: [
      'Gemini Zone maps now show exact colours and badges without leader lines crossing the farm',
      'Reference Blueprint Zone borders are thinner and roofs stay clear on soft satellite images',
      'Saved Gemini maps now say Gemini instead of gpt-image-2',
    ],
  },
  {
    when: '16 August',
    sha: 'feb3304',
    changes: [
      'Shade tunnels now fit their saved footprint and JoJo tanks have no dark halo',
      'Field Journal and My Records show examples when you have no entries yet',
      'Home quick actions now use clear illustrated pictures',
      'Upcoming farm tasks now show crop pictures instead of emoji',
      'The desktop LABELS control no longer covers the Elements panel',
    ],
  },
  {
    when: '16 August',
    sha: 'e2d0314',
    changes: [
      'Saved maps now lets you switch sites without leaving Preview & Export',
    ],
  },
  {
    when: '16 August',
    sha: '6e97f17',
    changes: [
      'JoJo tanks now look like upright ribbed tanks instead of dark rings on the map',
      'Shade tunnels and polytunnels now show the crops growing underneath',
      'Both tunnels keep the exact width and length you set in the Design Studio',
    ],
  },
  {
    when: '16 August',
    sha: 'dc08fd2464738dc6e260ae6030243d0011d08aef',
    changes: [
      'Weather now shows a real picture for the sky, not an emoji',
      'Field Journal entry types now show a real picture instead of an emoji',
    ],
  },
  {
    when: '16 August',
    sha: '6ee6919f5a7e925ac7885dc1dae6a91e6f8e67e2',
    changes: [
      'Playground now has a real picture in the Design Palette instead of an emoji',
    ],
  },
  {
    when: '16 August',
    sha: '2bdaa93b20e0b4ff62787a1fdc079a0f0a8748ad',
    changes: [
      'The banana circle now shows real banana bunches, not just leaves',
    ],
  },
  {
    when: '15 August',
    // Swarm round 2 — 15 branches, squash-merged into main this session.
    sha: '789d8dfadfa8a350f5de9c8f077f9ed232401994',
    changes: [
      'Dark mode no longer flashes bright white menus and buttons when the app opens',
      'Print buttons no longer go silent',
      'Multi-page reports keep their footer and header on every page',
      'No more raw error codes on the sale, insights and life-guide screens',
      'A failed load now shows a Retry button instead of looking empty or zero',
      'This covers Contact, Design, My Records and the facilitator dashboard',
      'My Records no longer double-counts a paid invoice',
      'December sales no longer disappear from the season view',
      'A failed message, post or report now tells you — it no longer pretends to send',
      'Reports, farm records and the site survey panel now open faster',
      '"Trace your boundary" on Home now actually starts tracing',
      'Crop Planner is no longer listed twice in the menu',
      'Crop Plan no longer crashes for a one-bed farm',
      'Maize now shows its real October sowing month',
      'The Planting Calendar now has its own menu entry',
      'Prices, weights and kg entries now accept a comma decimal',
      'The site survey warns before discarding your answers',
      'Traced ground features no longer vanish after switching a map layer off',
      'Undo and Redo no longer say Saved when a save actually failed',
      "Funders no longer see farmers' ID numbers",
      'A missing profile can no longer slip anyone into a staff dashboard',
      'Muted text, the Home date and the Back button are easier to read and tap in bright sun',
      'The wind compass arrow now matches its own text',
      'The Tank Calculator caption shows the right runoff number',
      'Evidence, profile and survey sheets now close with Escape',
      'These sheets now read properly with a screen reader',
    ],
  },
  {
    when: '15 August',
    sha: '7aa368b09cdab2ead8d96b4397b19de5519c5bc8',
    changes: [
      'A design with years of saved sheets and its own photo now opens without crashing',
      'Your saved sheets open with one tap instead of loading themselves and slowing things down',
    ],
  },
  {
    when: '15 August',
    sha: 'efc9884',
    changes: [
      'Share a listing straight to WhatsApp, so what you have to sell can reach a buyer',
      'A new Prices screen — tap a crop and see the wholesale and retail price per kg',
      'It says when a price is only an estimate, so you know what you are standing on',
      'The papers a funder asks for — PTO, ID, water licence — now have a place to live',
      'My Records can export a summary of your own harvests and sales to show a lender',
    ],
  },
  {
    when: '15 August',
    // Eight branches from the audit swarm. The language-plumbing commit (ba57337) is deliberately
    // NOT listed: it routes three farmer-facing strings through the dictionary but only adds the
    // ENGLISH keys, so nobody's screen changes until a first-language reviewer supplies the words.
    // Saying "now follows your language" would be a promise the build does not keep.
    sha: '92dd6a6',
    changes: [
      'The sign-in screen now follows your light or dark setting, like the rest of the app',
      'Signing up keeps the journal and crop plan you wrote before you had an account',
      'Logging a sale on a weak signal finishes instead of spinning forever',
      'The Task Planner says when it is showing an example, not your own beds',
      'Garden Survey now opens the survey that actually moves your progress bar',
      'The Planting Calendar finally has its own place in the menu',
      'The design page opens lighter, and pinch-zoom stops stuttering on a small phone',
    ],
  },
  {
    when: '15 August',
    sha: 'f65e6fa',
    changes: [
      'The sign-in screen now opens with a picture of a smallholding, not an empty box',
      'The example farm page does the same',
    ],
  },
  {
    when: '15 August',
    sha: '43f9692',
    changes: [
      'The designer now loads in parts, so it starts faster and fits weaker phones',
      'Photo import, the advisor and the step guide arrive when needed, not up front',
      'On phones, photo and satellite work now uses phone-sized memory, not print-sized',
      'Plans made on a laptop keep full print quality',
      'The automatic switch to the simple page is off — every page opens normally again',
      'It was catching healthy computers too, not only crashing phones',
    ],
  },
  {
    when: '15 August',
    sha: '74c67d7',
    changes: [
      'The crash rescue now steps in one reload sooner, before the grey error can appear',
      'The farm map page now has the same rescue as the designer',
      'Trying again from the simple page can never end on the grey error either',
      'When even the light designer cannot open, the simple page says so honestly',
    ],
  },
  {
    when: '15 August',
    sha: '2475744',
    changes: [
      'A phone that cannot open the designer at all now gets a simple page, never a grey error',
      'That page keeps your design safe and offers light and full ways back in',
      'After a single crash, the page now comes straight back light instead of dying again',
      'This now covers crashes at any moment — generating a map or a report included',
      'Switching apps or closing normally never counts as a crash',
      'This works even when the app is opened from a link inside another app',
    ],
  },
  {
    when: '14 August',
    sha: '5d3c231',
    changes: [
      'If generating a report keeps closing the app, the next try goes lighter and finishes',
      'When it does, the report says so — your maps still show on screen and in the PDF',
      'A design that keeps closing now says which step it closed on, so it can be fixed faster',
      'Your report now looks at the photos you took of your land, not just their number',
      'And it shows them, on screen and in the downloaded PDF, with your own notes',
      'So the soil, water and tree advice describes what is actually on the ground',
      'Photos saved before you picked a farm now reach the report instead of being lost',
    ],
  },
  {
    when: '14 August',
    sha: '9809304',
    changes: [
      'A design that kept crashing on a slow connection now opens light on its own',
      'The farmer map does the same — after repeated crashes it pauses and offers itself back',
      'Your reports, photos and places all keep working while the map waits',
      'Nothing is lost either way — drawings and measurements stay exact, only the pictures wait',
    ],
  },
  {
    when: '14 August',
    sha: '3ac34d5',
    changes: [
      'Fruit and nut trees now have larger, easier-to-see fruit and leaves on every map',
      'Avocados are olive-green instead of aubergine-purple, with fruit visible at map scale',
      'All five indigenous fruit trees now have their own recognisable fruit and foliage',
      'Apple, pear, plum, peach, fig, pomegranate and olive no longer share one tree picture',
      'Litchis show coral-red clusters, and banana clumps show curved yellow hands from above',
    ],
  },
  {
    when: '14 August',
    sha: 'e805e1c',
    changes: [
      'Preview & Export now keeps the same numbered layout whether you open Glossy or Preview map',
      'Sheet, underlay, labels, style, quality and finish now follow one numbered workflow',
      'The tiny Elements and Layers width sliders are gone — drag a panel edge to resize it',
      'The design steps now fill the top bar, and editing shortcuts leave more room for the map',
      'Citrus trees have larger leaves and oranges, with some fruit tucked behind the leaves',
      'Banana circles now show several banana plants around the open centre',
      'Taps, gates, nursery tables and other plan features now use an overhead view',
    ],
  },
  {
    when: '13 August',
    sha: '558f733',
    changes: [
      'The small update button now shows which build is waiting',
      'Elements and Layers stay beside the map, and both panels can resize or float',
      'Guidance stays at the bottom without hiding tools behind Guided or Pro modes',
      'AI finish choices appear sooner, with the longer explanation folded away',
      'Rain barrels, citrus fruit and shade structures are easier to recognise on the plan',
      'Click the full-screen map itself to minimise it',
      'Preview & Export now scrolls to every map and finish option on phones',
      'The mobile map header fits without hiding controls off the side',
      'The empty Wind and Seasonal sun badges no longer cover the map preview',
    ],
  },
  {
    when: '13 August',
    sha: '558f733',
    changes: [
      'Tap any plan preview to open it full screen, then use the top-right close button to return',
      'Place names and pins on the map are far easier to hit with a finger',
      'Tapping a place name on the map opens that place again on phones',
      'Buttons across the app now respond to the first tap, not the second',
      'Plan previews open straight onto the sheet instead of showing a large black area',
    ],
  },
  {
    when: '12 August',
    sha: 'd8aa77a',
    changes: [
      'Pull the bar at the top of any sheet downwards to close it',
      'Lima\u2019s button now steps aside while a sheet is open',
      'Find your land is no longer hidden behind the map\u2019s label switches',
      'Lima\u2019s button no longer sits on top of Add on the map',
      'Sites you had already analysed now pick up the corrected biome',
      'The report list in the menu now opens even before you have picked your farm',
      'All nine sheets can now be seen at once in Preview & Export',
      'Preview & Export now puts settings, your map and saved maps together',
      'The map preview now uses the full screen on computers and tablets',
      'Preview & Export now stacks cleanly on phones without a crowded header',
      'Your biome now comes from the national vegetation map, not a guess',
      'Inland farms are no longer called coastal',
      'So the trees, crops and water advice that follow from it are right too',
      'Farms on the coast are no longer told they are outside South Africa',
    ],
  },
  {
    when: '11 August',
    sha: 'f6e81b1',
    changes: [
      'Your design maps now show inside the report itself, not only in the download',
      'Tap any map in the report to see it full size',
      'The advice now reads those maps — where things sit, not just how big they are',
      'Site report is now in the menu, so you no longer have to find it on the map',
      'An empty report list now tells you how to make your first one',
    ],
  },
  {
    when: '10 August',
    // STAMPED. An unstamped top entry does not mean "not yet released" to the gate — it means the
    // gate falls through to the NEXT entry's sha and reports every commit since as unnoted. That
    // is how main sat red for 27 commits while every PR went green: the notes were written, the
    // stamp was not. Stamp at merge, always.
    //
    // AND THE STAMP CAN ONLY BE APPLIED AFTER THE MERGE, because the sha it names does not exist
    // until then — so a green PR is never evidence that this line is current. Main went red again
    // on 10 August with all 2247 tests passing and all three notes already written, purely
    // because this read fbecef9 while main had moved to 81d424c. A commit touching ONLY this file
    // is ignored by the gate (IGNORE in scripts/release-notes-pending.mjs), which is what makes a
    // follow-up restamp commit both safe and, after every merge, necessary.
    sha: 'a602888',
    changes: [
      'The report prints your latest version of each sheet, not every map you ever saved',
      'Shade tunnels and shade houses are see-through, so the beds under them still show',
      'Your design maps are now printed in the report, one to a page at the back',
      'Reports you download now have a contents page and numbered sections',
      'Tree and crop advice now matches the vegetation the map finds at your spot',
      'Fire risk is judged on that same vegetation, so fire-prone veld is told so',
      'The planting palette shows three drawings a row, so you scroll less to find one',
      'The species list now opens where there is room instead of off the top of the screen',
      'AI Polished now really is polished — the app no longer paints over what you paid for',
      'Your plants are the AI\u2019s artwork; ground, roofs and boundary stay exact as before',
      'A design that keeps closing the app now opens without its background photo',
      'Everything you drew, and every measurement, stays exactly the same when it does',
      'Add &safe=1 to a design link to open it that light way straight away',
      'If opening an AI render keeps crashing the app, it now stops retrying and tells you',
      'Finishing an AI render uses far less phone memory, so it should now survive',
      'The Seeds and Vegetables modules show their names instead of the word Title',
      'Making a sheet no longer throws you back to the start of the studio on phones',
      'Course module covers now show their real titles instead of "Title"',
      'The picture the AI is given is now white paper too, not a tan field',
      'On plain paper the AI now leaves the paper white instead of inventing a field',
      'Every building on your plan keeps its name and its legend row',
      'Pressing AI Polished now says AI Polished on the result, not hybrid',
      'Big numbers read the same way all through your report',
      'The "get a local quote" warning no longer prints stray underscores',
      'Your report sections are numbered in order, and every one of them is in the Contents',
      'The exported PDF starts with one cover page instead of two',
      'The report cover names only the map, survey and crop plan you actually gave it',
      'Plain paper plans now print on white, so your drawing is no longer tinted twice',
      'The Sector sheet draws its arrows and arcs on white instead of dark grey',
      'Buildings are painted once, so no roof on a plan comes out darker than another',
      'With 50 reports saved, the app asks you to delete one instead of dropping the oldest',
      'Round beds are measured as circles, so their size and cost are honest',
      'Your crop planner warns you the moment it can no longer keep your changes',
      'If your phone is too full to save, the app now says so instead of Saved',
      'Rain arrows now show on the roof itself, running down to each gutter',
      'The month calendar now matches the crop guide, so nothing is listed too early',
      'Your bill no longer charges you for tanks and trees you already have',
      'Water runs off the roof, into your tank, and spreads out in the swale',
      'Every drawing on your plans is now the new artwork — sheds, hives, basins and beds',
      'Beds sit under tree canopies, and their vegetables are finally big enough to see',
      'Big canopies sit over small trees, and every plant carries a label',
      'Vetiver looks ragged and real, and berms have grassy edges',
      'Underlay always offers all three: your photo, satellite, or plain paper',
      'Your design now shows on the farmer map, read-only',
      'Two sheet finishes: Exact Canvas, free and instant, or AI Polished for one paid render',
      'Sheet labels and legend are never handed to the AI, so they stay sharp',
      'The labels and underlay buttons fit properly on a phone now',
    ],
  },
  {
    when: '9 August',
    sha: 'fbecef9',
    changes: [
      'Water tanks now wear their real colours — black, green, teal and sandstone by size',
      'The rain barrel card shows its typical size (about 200 litres)',
      'New Greywater section on the Water step — diverter, outlet, basin and soakaway',
      'Try the new card palette with the "New look" button — switch back any time',
      'Saved maps open faster and no longer crash the app on phones',
      'Ten identical beds now share one label with a count, instead of ten',
      'New Quality setting: High redraws sheets at 1.5x resolution for printing',
      'Buildings on plain-paper sheets now show a corrugated iron roof',
      'Staple plots are now painted fields — maize, beans and pumpkin in rows',
      'Staple rows now run with each plot, roofs are bolder, bed veg drawn bigger',
      'Sharper maps are now the default on computers; phones can switch in Quality',
      'Roofs lose their outline and gain real corrugated ribs',
      'The dashed circle around big trees is gone — plants still show on top',
      'Water arrows now stop and spread at swales and beds instead of crossing them',
      'Bed rows are painted vegetables now — cabbages, tomatoes, beans and more',
      'Tanks on the water map now wear their capacity colours from above',
    ],
  },
  {
    when: '9 August',
    sha: 'a4611f7',
    changes: [
      'Every tree in the palette now has its own drawing instead of an emoji',
      'Taps, filters, kraals and terraces are drawn instead of shown as symbols',
    ],
  },
  {
    when: '9 August',
    sha: '9c7243d',
    changes: [
      'Every element in the palette now has its own drawing instead of an emoji',
      'Water tanks are drawn at their real sizes, so you can tell 1000L from 10000L',
    ],
  },
  {
    when: '9 August',
    sha: '540c025',
    changes: [
      'Indigenous fruit trees now have their own section in the planting palette',
      'Marula and kei apple added — both with their own drawing on the planting sheet',
      'The planting palette is split into sections instead of one long row',
    ],
  },
  {
    when: '8 August',
    sha: '2179fd7',
    changes: [
      'Try Finance with sample data before you sign in',
      'Home and Finance have a lighter, cleaner background',
      'Avocado trees now have their own drawing on the planting sheet',
      'Your crop plan reads rain and frost from your mapped site instead of asking you',
      'Beds can be planted in full, half, third or quarter sections again',
    ],
  },
  {
    when: '7 August',
    changes: [
      'Invoices print on a full A4 page instead of a narrow tinted strip',
      'An invoice keeps the date it was issued, even if you reopen it later',
      'Cents print correctly — R37.50 no longer prints as R37,5',
      'A long invoice no longer loses items off the bottom of the page',
      'A family food plan is ready without choosing crops first',
      'Fewer long gaps between harvests, and less repeated garlic',
    ],
  },
  {
    when: '6 August',
    changes: [
      'Choose Satellite, your drone photo, or Blank to see the same plan on paper',
      'Blank keeps the same measurements as the base you just left',
      'Finance now shows yield, turnover and price per planted square metre',
      'Crop costs stay unassigned until you choose the crop they were for',
      'Moved the chat button and Add buttons so they do not cover the map logo',
    ],
  },
  {
    when: '6 August',
    sha: 'f28f34b',
    changes: [
      'Crop suggestions use only crops you choose; coriander is never assumed',
      'One crop no longer takes every bed while another chosen crop is available',
      'A one-bed plan starts a full crop now instead of reserving a tiny strip',
      'Sowing and harvest dates stay in order when a crop crosses New Year',
      'Unknown yield, spacing and storage figures are now shown as unknown',
    ],
  },
  {
    when: '6 August',
    sha: '78df299',
    changes: [
      'Your survey can now record food, livestock and sales you report yourself',
      'Food groups say what you reported, never a made-up nutrition score',
    ],
  },
  {
    when: '6 August',
    sha: 'df2a98d',
    changes: [
      'Design Studio tools now sit beside your map on a tablet or computer',
      'Water marks can be shown one at a time or faded while you explain the plan',
      'Element tiles show their real size and are ready for hand-drawn pictures',
    ],
  },
  {
    when: '6 August',
    sha: '41774a4',
    changes: [
      'Card and panel outlines are all the same colour now, instead of two shades',
      'When you sold more than you logged picking, Finance now says the kept amount is not known',
      'It no longer blames a short harvest on you when the picking was simply not written down',
      'The printed crop plan shows your climate again, instead of saying "Not set"',
      'The work-load chart no longer counts mulching twice, so busy months are not overstated',
      'The year summary now says when crops already growing are not counted in its total',
    ],
  },
  {
    when: '6 August',
    sha: 'aaa19e1',
    changes: [
      'Harvests, sales and invoices now have crop pickers with honest guide prices',
      'Paid invoice kg lines now appear in My Records automatically and count once',
    ],
  },
  {
    when: '6 August',
    sha: 'f19d925',
    changes: [
      'Log harvest now opens a full records page, without the map beside it',
    ],
  },
  {
    when: '6 August',
    sha: 'a5d9cc0',
    changes: [
      'Sample finance never shows income dated later today',
    ],
  },
  {
    when: '6 August',
    sha: 'a3f0977',
    changes: [
      'Money: Log harvest now opens your crop record, even before you map a site',
    ],
  },
  {
    when: '5 August (night)',
    sha: '96f0250',
    changes: [
      'Money: sales you log now appear in your sales total and recent-sales list',
    ],
  },
  {
    when: '5 August (night)',
    sha: '66b5ba2',
    changes: [
      'Money: log a harvest straight from Finance — no need to find a hidden screen',
    ],
  },
  {
    when: '6 August (evening)',
    sha: '451cd18',
    changes: [
      'Your report now opens with a cover page and contents, and its sections are numbered',
      'It ends with a costed bill of quantities, measured off your own map',
      'It says plainly which items it could not price, instead of leaving them out',
      'It now carries a monitoring plan and a risk list, both built from your own figures',
      'New Network map: every farm in the programme - open one to read its record',
      'New Exchange and Field Journal pages, both in the menu',
      'New Atlas: look up growing conditions anywhere in the world',
      'Seed quantities corrected for 11 crops, from the KZN agriculture spacing table',
    ],
  },
  {
    when: '6 August',
    changes: [
      'The crop plan timeline now runs two full years - pan sideways to see year two',
      'Year two is drawn faded: the same cycle again, not a plan you have decided on',
      'No more empty months at the end of the timeline',
    ],
  },
  {
    when: '5 August (late night)',
    sha: '092e10a',
    changes: [
      'Bed 1 keeps its July planting - one crop no longer swallows a whole bed',
      'Every bed now sows into the winter tail - July is planted, not skipped',
      'The AI-polished map gets its legend and labels back, without ghost ribbons',
    ],
  },
  {
    when: '5 August (night)',
    sha: '5b7d3b5',
    changes: [
      'Gardens of 25-75 beds waste less bed space and plan more food',
      'The field sheet says "Beds 3, 7, 12" once, not the same job per bed',
    ],
  },
  {
    when: '5 August (evening)',
    sha: '36d41c9',
    changes: [
      'Beds no longer end up with a strip too small to plant anything in',
      'Bed 1 goes from 78% to 89% used, and July is no longer bare',
    ],
  },
  {
    when: '5 August (later)',
    sha: '038bfcc',
    changes: [
      'The printed plan now opens with your year at a glance, not a wall of text',
      'One page shows every bed and plot across all twelve months',
      'Each month is a tick-off field sheet with room to write what you did',
      'Sowing into trays and planting into the bed are now separate jobs',
    ],
  },
  {
    when: '5 August',
    sha: 'e84e988',
    changes: [
      'The kg beside each bed now add up to the year total on the cover',
      'The plan no longer says more beds are staggered than your farm has',
    ],
  },
  {
    when: '4 August (late night)',
    sha: 'd12447a',
    changes: [
      'A bed now stays busy while its crop is still being picked, so no bed is planned twice over',
      'Seed amounts match the spacing printed beside them — beans, peas and garlic were too high',
      'The harvest figure in the chart and in the words beside it are now the same number',
      'On a computer the plan saves to your downloads, or opens ready to print',
    ],
  },
  {
    when: '4 August (night)',
    sha: 'c76dbc0',
    changes: [
      'Send your whole crop plan to your phone calendar, with a reminder before each job',
      'Print the crop plan, including when to buy each seed and seedling',
      'The "(tr)" mark on the timeline now says "transplant" — tap it to see what it means',
    ],
  },
  {
    when: '4 August (late)',
    sha: 'f56e4b7',
    changes: [
      'Your staple plots now grow staples — maize, beans, pumpkin, potatoes — not salad crops',
      'Maize goes in the field where it can be block-planted, never in a narrow raised bed',
      'One crop can no longer take over half your beds, and more of your crops get planted',
      'Site reports no longer describe a dam or borehole your farm does not have',
      'Export PDF works on the report, and the report now fits and reads properly on a phone',
      'Saving the course to your phone now includes the spoken lessons, not just the pictures',
    ],
  },
  {
    when: '4 August (evening)',
    sha: 'f8f98dd',
    changes: [
      'The crop plan now plants something in every sowable month — winter included',
      'Charts show "An established year" by default: the full rhythm once your plan repeats',
      'Your staple plots from the map are now rows in the crop plan — one crop, full plot',
      'Auto-suggest gives four plots four different courses and rotates them each season',
      'A beds button in the crop plan header lists every bed and plot with its real size',
    ],
  },
  {
    when: '4 August (afternoon)',
    sha: 'c22fa37',
    changes: [
      'Generate report and photo analysis work again — both were failing with a plain "500"',
      'The old Design canvas is retired — the Design Studio is the one place designs are made',
      '"What’s new" in the menu keeps the full list of updates and fixed bugs',
    ],
  },
  {
    when: '4 August',
    // Stamped at commit time by the same push that carries these changes.
    sha: 'e79c07e',
    changes: [
      'The crop plan no longer rests half the garden all winter — long crops bridge May–August',
      'Suggested sowings can start later in the year and flow into next season',
      'Field utilization no longer counts crops that already finished — it matches your beds',
      'The questionnaire fills in roof areas from your traced roofs — store room included',
      '"Boundary traced" now accepts a boundary drawn in the Design Studio',
      'The "Your land" card shows area and perimeter from your Studio boundary too',
      'iPhone HEIC photos convert automatically; an unreadable photo now says so',
      'Comprehensive reports no longer fail with a plain "500"',
    ],
  },
  {
    when: '3 August',
    sha: '40bc865',
    changes: [
      'The Studio drew narrow things too wide — a hedge is now its real width',
      'Printed and exported sheets are half as sharp again (150 dpi pages were the cause)',
      'Trees on the fence line are no longer sliced off by the edge of the page',
      'Vegetable beds get their name back on the plan',
      'An area like a staple garden is named across the area, not on a line off the side',
      'Plant labels have a third choice: the name printed under each plant',
      'A tree with planting under it now has a dashed edge, so you can see what is beneath it',
      'Every tree is now named on the plan — no more "Moringa x5" pointing at one of them',
      'Labels moved off the drawing into a clear margin down each side of the map',
      'Beds, rows and strips stay grouped with a count, so a big garden is one label not thirty',
      'Plant labels are now a choice: short codes on every plant, or names in the margin',
      'Vetiver hedges are drawn at the width you set them, not wider',
      'On plain paper the house and driveway sit back — the planting is the subject',
      'New "Plain paper" choice: your plan drawn on paper, with no photo behind it',
      'Every tree now stands in a mulched basin instead of on a white disc',
      'Each staple plot is one crop — maize on one, beans on the next',
      'Vetiver is drawn as a hedge seen from above, not a photo taken from the side',
      'Map callouts keep one size — a long name drops one step, never five sizes',
      'Trees wear a thin dark outline instead of a white halo',
      'Unassigned veg beds show a mixed garden, not seven identical patches',
      'The swale is back on the water sheet, so the runoff arrows point at something',
      'The property line no longer draws across tree canopies',
      'Summer sun is warm and winter sun cool, and the two noon suns no longer overlap',
    ],
  },
  {
    when: '2 August',
    sha: 'a6d035f',
    changes: [
      'Plan sheets fill the whole page now — the blank border is real aerial photo instead',
      'Money: one sale could be counted twice, and the app pushed you into doing it',
      'Money: with no signal the app showed R0 as if it were true, and offered to write it in',
      'Clearing a crop price no longer wipes that crop\'s income for good',
      'Invoices: 12.5 kg was billed as 12 kg, and a save that failed still printed',
      'Only invited mentors can see your farm — signing up as one no longer works',
      'The bill of quantities stops charging you for things already standing on your land',
      'Save several sheets at once: pick the format and size, then download or share',
      'Zones are flat colour you can tell apart, and your buildings are no longer black holes',
      'Water sheet shows where rain runs on the ground, separately from where it runs off a roof',
      'Earthworks 05: what you dig now appears on the sheet that tells you to dig it',
      'The legend says which parts of the plan are already there and which are still to build',
      'Map callouts sit on their own plaque, and merge when crowded instead of vanishing',
      'Nothing on a sheet with a scale bar is drawn bigger than it really is',
      'Printed PDFs use the same renderer as the screen — that is why fixes kept missing paper',
      'Trees in the examples are drawn as trees; the artwork was never being loaded',
    ],
  },
  {
    when: '1 August',
    sha: '1ec415e',
    changes: [
      'NEW: Earthworks is its own step — swales, berms and terraces have their own place',
      'NEW: a Staple garden — mielies, beans and pumpkin grow there on the AI maps',
      'Earthworks 05 prints the Earthworks sheet, not the masterplan',
      'Preview map opens with all nine sheets, so Earthworks is one tap away',
      'Zone numbers stop landing on top of each other, and stay where you drag them',
      'Pick a tree species and it goes down as a tree, not a square',
      'The winter sun path is drawn at its real angle, with a sun at each end',
      'Vegetable beds on the AI maps grow vegetables instead of turning into a hedge',
      'On a Photo Plan your real photo stays sharp — the design sits on top of it',
      'The staple garden turns off with your planting, not with what was already here',
      'Map labels stop marching all the way to the edge of the sheet',
    ],
  },
  {
    when: '31 July',
    changes: [
      'The sun diagram shows summer and winter paths, at your latitude\'s real angles',
      'It also gives the midwinter shadow length — where a shade tree can stand',
      'Zone numbers no longer land on top of each other',
      'NEW: a Playground, so play areas are on the plan and kept clear',
      'The bed-block row only appears when you are actually placing beds',
      'Your traced house and driveway now follow the Fill slider like everything else',
      'Fill and Plants sliders go all the way to 100%',
      'Drip all beds in one tap — a line down the centre of each; you add the mainline',
      'Tidy now squares up a slab or shed you traced by hand',
      'Legend text is bigger and in one clear typeface on every sheet',
      'Snap reaches further when nothing is close enough, and says so',
      'Snap to neighbour works — the update notice was sitting on top of its Confirm button',
      'The update notice shrinks out of the way, and you can close it',
      'Zone numbers sit on top of the shapes instead of being buried under them',
      'Select anything and its chip lights up, so you can tell what it is',
      'Zones can be see-through colour instead of hatching, with a strength slider',
      'Pick a shape and the ones around it stop grabbing your taps — tap the map to let it go',
      'A shape only moves once your finger really moves, so a tap no longer nudges it',
      'Zone numbers grow with the Size slider like every other label',
      'The ruler is now the only thing listening — measuring never selects a shape by mistake',
      'The selected chip is unmistakable now, on every colour',
      'Drag the edge handle and the panel follows your finger — down to just the map',
      'Every section has an ×, so you can close the one that is in your way and keep the rest',
      'The photo controls now stay while everything else folds away, instead of going first',
      'Your own photo now goes in at the right size, not leaving your farm a tiny patch',
      'Photos keep their detail instead of being shrunk when you add them',
      'Switch between satellite and your photo freely — your photo is kept either way',
      'Turn and resize your photo to line it up, without changing any measurement',
      'Hold an arrow down to keep nudging, instead of tapping over and over',
      'You can remove a photo you no longer want',
      'The studio no longer freezes while you are working on your photo',
      'Bed paths show up between your beds',
      'Your parcels stay with their own place, instead of showing under every place',
      'Every screen has a way back',
      'Tips close themselves, and you can close them yourself',
      'Plan sheets know which shapes are buildings, so slabs stop growing roofs',
    ],
  },
  {
    when: 'Earlier',
    changes: [
      'Paid AI maps are checked — if one comes back unchanged, you are told, not shown a copy',
      'Water sheets stop numbering the beds your irrigation feeds',
      'Zone maps keep zone names in the key instead of scattering them over the map',
      'Water notes say where the overflow goes, instead of implying your tank is too small',
      'A plan area nobody measured is left unpriced instead of printed as free',
      'The whole design studio speaks your language now, not just parts of it',
      'The same design gives the same advice every time you open it',
      'Snap now works on zones — it reaches the gaps, and stops claiming moves it never made',
      'Map labels are readable: they now match the size the AI picks on the same plan',
      'AI maps stop numbering your beds — seven beds get one label, not "×1" to "×7"',
      'Plan sheets print evenly: the phasing sheet is now the same shape as the rest',
      'The phasing schedule no longer strikes a line through its own week dates',
      'Map labels grow and shrink with the sheet instead of staying one size',
      'Long labels stay on the map on every sheet, not just Water',
      'Hand-drawn shapes read as clean plan lines — your saved drawing is untouched',
      'Crop rotation really rotates: the same plant family cannot follow itself in a bed',
      'The design studio steps can now speak your language',
      'Slide 13 now shows the dry method it teaches, not the wet one',
      'NEW: a Higher quality download for facilitators and funders on wifi — more data',
      'Plan sheets now take the shape of your farm — a long thin plot fills the page',
      'NEW: Open a module and the slides are there — press Play and it teaches itself through',
      'Downloaded clips now play by themselves; ones you have not downloaded still ask first',
      'NEW: Download a module, or the whole course, and use it with no airtime',
      'A downloaded module now survives app updates instead of being cleared',
      'Lessons are half the size to download — isiZulu slides and clips are much smaller',
      'The size on every play button is now the real size of the file',
      'The isiZulu deck is complete — slide 13 no longer shows in English',
      'Long water labels no longer run off the edge of the map',
      'Finished-map labels are larger and feature art no longer has white sticker outlines',
      'Sector maps now use three large slope arrows instead of five thin ones',
      'Sector wind and driving rain now stand out over a quieter aerial photo',
      'AI polish now keeps your selected style',
      'AI polish now paints your saved trees, beds, tanks and structures',
      'Protected roofs, driveways and boundaries are restored exactly',
      'The exact master stays in Saved maps while AI polish runs',
      'One press now continues from the exact map into paid AI polish',
      'AI-polished and Exact-only finishes are both clearly shown',
      'Sector maps now have bold marks, labels and illustrated keys',
      'Small Structures symbols now print clearly and paths no longer border the driveway',
      'Planting now distinguishes banana, pawpaw, moringa, keyhole beds, herb spirals and hedges',
      'Ponds, tree basins, greywater basins, taps, pumps and diverters now use painted artwork',
      'Hand-painted tanks, beds, trees and planting strips stay inside their saved footprints',
      'Structures now show painted compost, hives, chicken tractors, nursery tables and gates',
      'Drip is clear blue with fewer emitters; filtered greywater is now a solid purple line',
      'Water, Planting and Structures now share grouped editorial legends',
      'Unknown elements keep their safe exact symbol instead of becoming a guessed object',
      'Water uses a dark illustrated forest around a clear olive and moss property',
      'Blue, purple and drip routes now use slimmer technical ink',
      'Route labels name each network once; tank and basin counts stay factual',
      'Driveways stay quiet, flat and charcoal; traced geometry stays exact',
    ],
  },
  {
    when: 'Previous',
    changes: [
      'Water artwork is brighter and more natural; exact routes stay locked',
      'Illustrated Water maps keep the driveway and traced ground quieter behind the water system',
      'JoJo tanks and colour-coded water lines are now much easier to read on phones',
      'Water legends are now grouped into rainwater, irrigation, greywater and earthworks',
      'Geometry Lock Water sheets now use the full Water, Greywater & Irrigation title',
      'Water tanks, fittings and routes now stand out clearly over illustrated ground',
      'Rendered driveways are quieter, without a heavy decorative border',
      'Tiny aligned gaps in matching Water routes now close neatly on rendered maps',
      'AI receives only the Water features you saved; missing systems stay absent',
      'Drip and greywater routes now read as real tubing, emitters and inspection points',
      'Water sheets now stay focused: Vetiver Bank appears on Planting and Whole',
      'Vetiver banks now read as dense green hedges instead of brown strips',
      'Trees use finer top-down canopy texture instead of large circular blobs',
      'Duck ponds, animal pens and site fixtures now use their own plan symbols',
      'Sector numbers now separate cleanly when sun, wind and access share a bearing',
      'Refresh update now detects the new build even when it arrives before the first check',
      'Sector numbers now match the exact sun, wind, fire, access and fall marks on the map',
      'Water and infrastructure now use clear illustrated plan symbols',
      'Water maps now name and draw the old Mulch Bank correctly as Vetiver Bank',
      'Planting and Whole use fewer callouts; their legends still list everything',
      'Sector energies are decluttered and fully explained in the numbered legend',
      'The driveway is quieter and the full Phasing schedule now fits its cream panel',
      'Sector analysis now shows driveway access as its own energy, when a driveway is traced',
      'Stacked terraces each get their own fall arrow, not just one for the whole hillside',
      'You can now duplicate a placed, sized element instead of re-placing it from scratch',
      'Drawn lines (swales and the rest) can finally be named and labelled on the canvas',
      'A placed element no longer gets stuck locked the moment you place it, on some steps',
      'AI Sector: the data-strip and sources line stay readable, not just the title',
      'Placing a terrace now tells you the right method for your slope, and when to ask an expert',
      'Sector analysis shows real sun arcs, named winds and a fuller numbered legend',
      'A new Master Atlas style joins the style picker',
      'Sector title stays readable on AI, and labels can no longer hide behind the legend',
      'AI renders finally know what a tree basin, banana circle and greywater line look like',
      'Sector analysis can now be AI-styled too — the bearings are still measured, never guessed',
      'Sector analysis: your ground is drawn quietly so the sun, wind and water arrows read first',
      'Sector labels no longer print on top of each other, and the fire note is no longer cut off',
      'Sector analysis is exact-only again — the AI version kept drawing it off-register',
      'Fire sector removed until we can point it the right way — see below',
      'Sector analysis now shows and names your lawn, veg garden and cleared ground',
      'Picking a style on Site or Sector actually switches that sheet to AI',
      'One legend row per element — four taps no longer take three lines',
      'You can now draw a greywater line — Water step, next to Drip',
      'The driveway draws as tar on the ground, not as another roof',
      'Tree basins draw as the earthwork alone — no invented plant on the mound',
      'Your driveway now stays on every sheet',
      'Water plans stop drawing taps, valves and greywater pipes you never placed',
      'Tree basins draw correctly: tree up on a mound, mulched moat around it',
      'Planting and Structures sheets stop inventing irrigation lines that were never drawn',
      'Older saved maps are now marked, so you can tell them from freshly rendered ones',
      'The property boundary draws as a fence line, not a hatch over the whole plot',
      'Label leaders point at the edge of the area they name, not its middle',
      'Traced areas now nest — lawn cuts out the house, house cuts out the patio',
      'Area labels no longer pile on top of each other (drag one to move it)',
      'New "Other" element on Water, Planting and Structures — place it, then name it yourself',
      'Driveways draw flat, not as a raised slab beside the house',
      'Water plans name the beds and basins the irrigation feeds, under EXISTING',
      'The house, driveway and lawn stay unlabelled so the design stands out',
      'Sector analysis now reads on a light paper base instead of a dark one',
      'The boundary is now a proper post-and-wire fence, not a ticked line',
      'No more invented trees scattered across your plan',
      'Your driveway stays on every sheet',
      'Water plans now show the beds and basins your irrigation runs to',
      'Driveways stay driveways instead of being repainted as lawn',
      'Site and Sector sheets can now be AI-styled, not just exact',
      'Zone maps follow the zones you actually drew',
      'Your rendered maps are saved on this device and survive closing the app',
      'Fixed the phantom hedge along the fence, and the driveway merging into the house',
      'Beds, banana circles and tree basins moved to the Planting sheet where they belong',
    ],
  },
];

/** Never let the banner become a wall of text over the map. */
export const MAX_SHOWN = 5;

/** The lines to render, flattened and capped. Kept pure so it is testable without a DOM. */
export function visibleNotes(notes: ReleaseNote[] = RELEASE_NOTES, max = MAX_SHOWN): string[] {
  return notes.flatMap((n) => n.changes).slice(0, max);
}
