// Report figures — the site's own saved data, drawn.
//
// WHY THIS EXISTS. The site report described a real piece of ground in pages of bullets and never
// once showed it: no plan of the site, no picture of when the rain comes against what the roof can
// catch, no sun or wind diagram, nothing for the soil, nothing for the order of work. Rory: "i want
// visuals enriched into the site report… must be visual as well".
//
// Every figure here is drawn by code from typed, saved values — the design canvas, the measured
// facts, the site's climate and soil record, and the app's own sun, wind, tank and phasing maths.
// Nothing is generated by an image model and nothing is read back out of report prose, so a figure
// can never show a tank, a tree or a number the farmer did not save. Three rules hold throughout:
//
//   1. ONE MATHS. Roof catch comes from lib/roof-runoff, storage from lib/tank-sizing, the sun from
//      lib/solar via lib/sector, bed numbering from lib/design-beds-bridge. A figure that computed
//      its own answer would be a second opinion printed beside the first.
//   2. MISSING STAYS MISSING. No builder invents a default: it returns null, or draws the gap and
//      says what to record. A soil value that is only a generic estimate is drawn as "not measured".
//   3. NEVER COLOUR ALONE. Solid means already there or measured; a dashed outline means planned or
//      modelled. Every mark is labelled, so the page still reads on a black-and-white printer.
//
// Output is an SVG string, because the report rasterises one drawing for both the screen (<img>)
// and the PDF (lib/report-visual-pdf.ts). Inside an <img> no web font loads — hence Arial.

import type { DesignCanvasState, LineShape, GroundFeatureKind } from './design-canvas';
import { designBaseMode, statusOf } from './design-canvas';
import type { MapRefLayers } from './base-layers';
import { BED_DEF_IDS, canvasMetreExtent } from './design-beds-bridge';
import { ELEMENTS_BY_ID, type ElementCategory } from './design-elements';
import { plantCodesForSheet } from './plant-codes';
import type { LocationData } from './types';
import type { ReportSiteFacts } from './report-site-facts';
import { WATER_SHEET_ROOF_RUNOFF_COEFFICIENT, roofHarvestLitres } from './roof-runoff';
import { DAYS_IN_MONTH, computeTankSizing } from './tank-sizing';
import { deriveSectorModel, labelToBearing, sectorSiteFromLocation } from './sector';
import { isValidEarthLatitude } from './solar';
import { aspectLabel } from './biome';
import type { PhasePlan } from './phasing';

/** `note` says how to read the drawing and what it cannot tell you; `source` says where every mark came from. */
export type ReportFigure = { id: string; title: string; note: string; source: string; svg: string; width: number; height: number; alt: string };

export const FIGURE_WIDTH = 640;
const W = FIGURE_WIDTH;
const INK = '#1b3024', TEXT = '#263d30', MUTED = '#526258', HAIR = '#d5ded8', TRACK = '#edf1ee', PAPER = '#f7faf6';
const GREEN = '#245738', BLUE = '#24738a', AMBER = '#af6b24', VIOLET = '#766395', SLATE = '#52656a';
const FONT = 'Arial, sans-serif';

type Translate = (en: string, zu: string) => string;
const translator = (language: string): Translate => (en, zu) => language === 'zu' ? zu : en;
const finite = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);
const escapeXml = (s: string) => s.replace(/[<>&"']/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' }[c]!));
/** Space-grouped thousands and a decimal point, built by hand: en-ZA's own formatter groups with
 *  U+00A0 (which the PDF's WinAnsi font drops) and writes a decimal comma the report text never uses. */
export function figureNumber(value: number, digits = 0): string {
  const [whole, fraction = ''] = value.toFixed(digits).split('.');
  const grouped = whole.replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
  const kept = fraction.replace(/0+$/, '');
  return kept ? `${grouped}.${kept}` : grouped;
}
const px = (v: number) => Math.round(v * 10) / 10;
/** Arial averages a little over half an em per character; close enough to keep labels off each other. */
const textWidth = (value: string, size: number) => value.length * size * 0.56;
const clip = (value: string, max: number) => value.length > max ? `${value.slice(0, Math.max(1, max - 1)).trimEnd()}…` : value;

type TextOptions = { size?: number; anchor?: 'start' | 'middle' | 'end'; weight?: number; fill?: string; halo?: boolean };
type ShapeOptions = { fill?: string; stroke?: string; width?: number; dash?: string; opacity?: number; radius?: number };

/** A tiny string-building pen. One per figure, so <defs> ids never have to be globally unique. */
function pen() {
  const parts: string[] = [];
  const defs: string[] = [];
  const paint = (o: ShapeOptions) => `fill="${o.fill ?? 'none'}"${o.stroke ? ` stroke="${o.stroke}" stroke-width="${o.width ?? 1.5}"` : ''}${o.dash ? ` stroke-dasharray="${o.dash}"` : ''}${o.opacity !== undefined ? ` opacity="${o.opacity}"` : ''}`;
  return {
    raw: (value: string) => { parts.push(value); },
    def: (value: string) => { defs.push(value); },
    text: (x: number, y: number, value: string, o: TextOptions = {}) => {
      const halo = o.halo ? ' stroke="#ffffff" stroke-width="3.5" stroke-linejoin="round" paint-order="stroke"' : '';
      parts.push(`<text x="${px(x)}" y="${px(y)}" fill="${o.fill ?? TEXT}" font-family="${FONT}" font-size="${o.size ?? 15}" font-weight="${o.weight ?? 400}" text-anchor="${o.anchor ?? 'start'}"${halo}>${escapeXml(value)}</text>`);
    },
    rect: (x: number, y: number, w: number, h: number, o: ShapeOptions = {}) => { parts.push(`<rect x="${px(x)}" y="${px(y)}" width="${px(Math.max(0, w))}" height="${px(Math.max(0, h))}" rx="${o.radius ?? 0}" ${paint(o)}/>`); },
    circle: (cx: number, cy: number, r: number, o: ShapeOptions = {}) => { parts.push(`<circle cx="${px(cx)}" cy="${px(cy)}" r="${px(Math.max(0, r))}" ${paint(o)}/>`); },
    line: (x1: number, y1: number, x2: number, y2: number, o: ShapeOptions = {}) => { parts.push(`<path d="M${px(x1)} ${px(y1)}L${px(x2)} ${px(y2)}" stroke-linecap="round" ${paint({ stroke: INK, ...o, fill: 'none' })}/>`); },
    path: (d: string, o: ShapeOptions = {}) => { parts.push(`<path d="${d}" stroke-linejoin="round" stroke-linecap="round" ${paint(o)}/>`); },
    /** 45° hatch: the black-and-white way to say "this area is a different kind of thing". */
    hatch: (id: string, colour: string, gap = 7, width = 1.6) => { defs.push(`<pattern id="${id}" width="${gap}" height="${gap}" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="${gap}" height="${gap}" fill="#ffffff"/><path d="M0 0V${gap}" stroke="${colour}" stroke-width="${width}"/></pattern>`); return `url(#${id})`; },
    done: (height: number, width = W) => `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${Math.ceil(height)}" viewBox="0 0 ${width} ${Math.ceil(height)}">${defs.length ? `<defs>${defs.join('')}</defs>` : ''}<rect width="100%" height="100%" fill="#ffffff"/>${parts.join('')}</svg>`,
  };
}
type Pen = ReturnType<typeof pen>;

/** Wraps words to a pixel width; figures are read on phones, so no line may run off the drawing. */
function wrapText(value: string, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  let current = '';
  for (const word of value.split(/\s+/).filter(Boolean)) {
    const next = current ? `${current} ${word}` : word;
    if (current && textWidth(next, size) > maxWidth) { lines.push(current); current = word; } else current = next;
  }
  if (current) lines.push(current);
  return lines;
}

// ── 1. Site plan ──────────────────────────────────────────────────────────────────────────────

type PlanPaint = 'bed' | 'planting' | 'water' | 'structure' | 'earthworks' | 'animal' | 'access';
const CATEGORY_PAINT: Record<ElementCategory, PlanPaint> = { water: 'water', earthworks: 'earthworks', structure: 'structure', growing: 'planting', animal: 'animal', access: 'access' };
const PAINT_COLOUR: Record<PlanPaint, { solid: string; tint: string }> = {
  bed: { solid: GREEN, tint: '#e6efe6' },
  planting: { solid: GREEN, tint: '#dcebd9' },
  water: { solid: BLUE, tint: '#e1eef2' },
  structure: { solid: SLATE, tint: '#e8ecec' },
  earthworks: { solid: AMBER, tint: '#f5eadc' },
  animal: { solid: VIOLET, tint: '#ece8f1' },
  access: { solid: '#8a958f', tint: '#eef1ef' },
};
const GROUND_FILL: Partial<Record<GroundFeatureKind, string>> = { lawn: '#eaf3e3', cleared: '#f3efe4', veg_garden: '#e3efdc', orchard: '#dfeeda', patio: '#e4e7e5', driveway: '#dcdfdd' };
const NICE_METRES = [1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000];

type Box = { x: number; y: number; w: number; h: number };
const overlaps = (a: Box, b: Box) => a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;

type PlanItem = { paint: PlanPaint; round: boolean; cx: number; cy: number; w: number; h: number; rot: number; planned: boolean; label: string; inside: string };
type PlanArea = { id: string; feature: GroundFeatureKind; name: string; planned: boolean; points: Array<[number, number]> };
type RouteKind = LineShape['kind'] | 'driveway';
type PlanRoute = { kind: RouteKind; name: string; planned: boolean; points: Array<[number, number]> };
const ROUTE_STYLE: Record<RouteKind, { colour: string; width: number; ink: string }> = {
  swale: { colour: BLUE, width: 4, ink: BLUE }, fence: { colour: INK, width: 1.4, ink: INK }, path: { colour: '#b9a788', width: 5, ink: '#6f6248' }, bedpath: { colour: '#cbbfa6', width: 3, ink: '#6f6248' },
  pipe: { colour: BLUE, width: 1.6, ink: BLUE }, drip: { colour: BLUE, width: 1.2, ink: BLUE }, windbreak: { colour: GREEN, width: 4.5, ink: GREEN }, greywater: { colour: VIOLET, width: 2.4, ink: VIOLET },
  driveway: { colour: '#c4c9c5', width: 8, ink: '#5a635e' },
};

/**
 * The saved design as a labelled plan: north up, to scale, with a scale bar, and a key.
 *
 * Beds are numbered in the SAME order lib/design-beds-bridge numbers them ("Bed 3" in the crop plan
 * and the bill of quantities is bed 3 on this drawing), and plants carry the same two-letter codes
 * the plan sheets use, so the figure can be read against every list in the report.
 *
 * `mapLayers` are the boundary, house and driveway traced on the MAIN map, already projected into
 * this canvas's frame. A ring of the same kind drawn in the Design Studio wins, which is the rule
 * lib/base-layers applies for the plan sheets.
 *
 * lib/mini-plan.ts draws the same geometry as an unlabelled thumbnail and says of itself that it
 * "must never be printed or measured off". This is the printable one; the projection is shared.
 */
export function sitePlanFigure(canvas: DesignCanvasState | null | undefined, language = 'en', mapLayers?: MapRefLayers | null): ReportFigure | null {
  if (!canvas) return null;
  const t = translator(language);
  let wMetres = 0, hMetres = 0;
  try { ({ wMetres, hMetres } = canvasMetreExtent(canvas)); } catch { return null; }
  if (!(wMetres > 0) || !(hMetres > 0)) return null;
  const ring = (points: ReadonlyArray<readonly [number, number]> | undefined) => (points ?? []).filter(q => Array.isArray(q) && finite(q[0]) && finite(q[1])).map((q): [number, number] => [q[0] * wMetres, q[1] * hMetres]);
  // A map ring that lands far outside the frame was traced for some other ground; leave it out.
  const mapRing = (points: MapRefLayers['boundary'] | undefined, minimum: number) => { const usable = (points ?? []).every(q => Array.isArray(q) && q[0] > -2 && q[0] < 3 && q[1] > -2 && q[1] < 3); const out = usable ? ring(points) : []; return out.length >= minimum ? out : []; };

  // Collect, in metre space.
  const isBedDef = (defId: string) => (BED_DEF_IDS as readonly string[]).includes(defId);
  const codes = plantCodesForSheet(canvas.items.map(item => item.defId)); // every id, so the codes match the plan sheets'
  const items: PlanItem[] = [];
  const bedNames: string[] = [];
  let bedNumber = 0;
  for (const item of canvas.items) {
    const def = ELEMENTS_BY_ID[item.defId];
    if (!def) continue;
    const isBed = isBedDef(item.defId);
    if (isBed) bedNumber += 1; // counted before any skip below, exactly as bedsFromDesignCanvas counts
    if (!finite(item.x) || !finite(item.y)) continue;
    const w = finite(item.wM) && item.wM > 0 ? item.wM : def.wM, h = finite(item.hM) && item.hM > 0 ? item.hM : def.hM;
    if (!(w > 0) || !(h > 0)) continue;
    const custom = item.label?.trim() ?? '', numbered = custom.match(/^bed\s+(\d{1,3})$/i);
    if (isBed && custom && !numbered) bedNames.push(`${bedNumber} = ${clip(custom, 22)}`);
    items.push({
      paint: isBed ? 'bed' : CATEGORY_PAINT[def.category] ?? 'structure', round: def.shape === 'circle', cx: item.x * wMetres, cy: item.y * hMetres, w, h,
      rot: def.shape === 'circle' ? 0 : finite(item.rot) ? item.rot : 0, planned: statusOf(item) === 'proposed',
      inside: isBed ? (numbered ? numbered[1] : `${bedNumber}`) : codes.get(item.defId) ?? '',
      label: isBed || codes.has(item.defId) ? '' : clip(custom || def.name, 24),
    });
  }
  const areas: PlanArea[] = canvas.zones
    .filter(zone => zone.feature && Array.isArray(zone.points))
    .map(zone => ({ id: zone.id, feature: zone.feature!, name: zone.name?.trim() ?? '', planned: statusOf(zone) === 'proposed', points: ring(zone.points) }))
    .filter(area => area.points.length >= 3);
  const routes: PlanRoute[] = canvas.lines
    .filter(line => Array.isArray(line.points) && ROUTE_STYLE[line.kind])
    .map(line => ({ kind: line.kind as RouteKind, name: line.name?.trim() ?? '', planned: statusOf(line) === 'proposed', points: ring(line.points) }))
    .filter(route => route.points.length >= 2);
  const has = (kind: GroundFeatureKind) => areas.some(area => area.feature === kind);
  const mapBoundary = has('boundary') ? [] : mapRing(mapLayers?.boundary, 3);
  const mapHouse = has('house') ? [] : mapRing(mapLayers?.house, 3);
  const mapDrive = has('driveway') ? [] : mapRing(mapLayers?.driveway, mapLayers?.drivewayClosed ? 3 : 2);
  if (mapBoundary.length) areas.push({ id: 'map-boundary', feature: 'boundary', name: '', planned: false, points: mapBoundary });
  if (mapHouse.length) areas.push({ id: 'map-house', feature: 'house', name: '', planned: false, points: mapHouse });
  if (mapDrive.length && mapLayers?.drivewayClosed) areas.push({ id: 'map-driveway', feature: 'driveway', name: '', planned: false, points: mapDrive });
  else if (mapDrive.length) routes.push({ kind: 'driveway', name: '', planned: false, points: mapDrive });
  if (!items.length && !areas.length && !routes.length) return null;

  // Frame on the whole site. Only when the boundary would shrink the design to a speck does the
  // drawing close in on what was designed — and then the note says the boundary runs off the page.
  type Bounds = { minX: number; minY: number; maxX: number; maxY: number };
  const empty = (): Bounds => ({ minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity });
  const grow = (b: Bounds, x: number, y: number) => { if (x < b.minX) b.minX = x; if (x > b.maxX) b.maxX = x; if (y < b.minY) b.minY = y; if (y > b.maxY) b.maxY = y; };
  const span = (b: Bounds) => Math.max(b.maxX - b.minX, b.maxY - b.minY);
  const content = empty(), whole = empty();
  for (const item of items) { const rx = item.rot ? Math.hypot(item.w, item.h) / 2 : item.w / 2, ry = item.rot ? rx : item.h / 2; for (const b of [content, whole]) { grow(b, item.cx - rx, item.cy - ry); grow(b, item.cx + rx, item.cy + ry); } }
  for (const area of areas) for (const [x, y] of area.points) { grow(whole, x, y); if (area.feature !== 'boundary' && area.id !== 'map-driveway') grow(content, x, y); }
  for (const route of routes) for (const [x, y] of route.points) { grow(whole, x, y); if (route.kind !== 'driveway') grow(content, x, y); }
  const cropped = Number.isFinite(content.minX) && span(content) > 0 && span(whole) > span(content) * 3;
  const frame = cropped ? content : whole;
  const pad = Math.max(span(frame), 1) * (cropped ? 0.12 : 0.03);
  const minX = frame.minX - pad, minY = frame.minY - pad, maxX = frame.maxX + pad, maxY = frame.maxY + pad;
  const planW = W - 24, maxPlanH = 470, footH = 34;
  const scale = Math.min(planW / Math.max(maxX - minX, 0.5), maxPlanH / Math.max(maxY - minY, 0.5));
  const drawnW = (maxX - minX) * scale, drawnH = (maxY - minY) * scale;
  const left = (W - drawnW) / 2, top = 12, panelH = drawnH + 24 + footH;
  const X = (x: number) => left + (x - minX) * scale, Y = (y: number) => top + (y - minY) * scale;
  const pathOf = (points: Array<[number, number]>, close: boolean) => `${points.map(([x, y], i) => `${i ? 'L' : 'M'}${px(X(x))} ${px(Y(y))}`).join('')}${close ? 'Z' : ''}`;

  const p = pen();
  const plotHatch = p.hatch('plot', AMBER), bankHatch = p.hatch('bank', '#8a7355', 5, 1.2);
  p.rect(0.5, 0.5, W - 1, panelH, { fill: PAPER, stroke: HAIR, width: 1, radius: 6 });
  p.def(`<clipPath id="plan"><rect x="1.5" y="1.5" width="${W - 3}" height="${px(panelH - footH - 2)}"/></clipPath>`);
  p.raw('<g clip-path="url(#plan)">');

  // Ground first, then hard surfaces and buildings, then what grows and what holds water.
  const labels: Array<{ text: string; x: number; y: number; size: number; fill: string; weight: number; halo: boolean; box: Box }> = [];
  const obstacles: Box[] = [];
  const centroid = (points: Array<[number, number]>): [number, number] => [points.reduce((s, q) => s + q[0], 0) / points.length, points.reduce((s, q) => s + q[1], 0) / points.length];
  const within = (x: number, y: number, points: Array<[number, number]>) => { let hit = false; for (let i = 0, j = points.length - 1; i < points.length; j = i++) { const [xi, yi] = points[i], [xj, yj] = points[j]; if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) hit = !hit; } return hit; };
  const edgeDistance = (x: number, y: number, points: Array<[number, number]>) => { let best = Infinity; for (let i = 0, j = points.length - 1; i < points.length; j = i++) { const [ax, ay] = points[j], [bx, by] = points[i], dx = bx - ax, dy = by - ay, len = dx * dx + dy * dy, u = len ? Math.max(0, Math.min(1, ((x - ax) * dx + (y - ay) * dy) / len)) : 0; best = Math.min(best, Math.hypot(x - ax - u * dx, y - ay - u * dy)); } return best; };
  /** Where a name reads best: the roomiest spot inside the ring that no building covers — the centroid of an L-shaped driveway is usually not on the driveway. */
  const labelPoint = (points: Array<[number, number]>, avoid: Array<Array<[number, number]>>): [number, number] => {
    const xs = points.map(q => q[0]), ys = points.map(q => q[1]), x0 = Math.min(...xs), x1 = Math.max(...xs), y0 = Math.min(...ys), y1 = Math.max(...ys);
    let best: [number, number] | null = null, room = 0;
    for (let i = 1; i < 16; i += 1) for (let j = 1; j < 16; j += 1) {
      const x = x0 + ((x1 - x0) * i) / 16, y = y0 + ((y1 - y0) * j) / 16;
      if (!within(x, y, points) || avoid.some(other => within(x, y, other))) continue;
      // Width matters more than height for a line of text, so favour spots with sideways room.
      const clear = Math.min(edgeDistance(x, y, points), ...avoid.map(other => edgeDistance(x, y, other)));
      if (clear > room) { room = clear; best = [x, y]; }
    }
    const [mx, my] = centroid(points);
    const middleIsFine = within(mx, my, points) && !avoid.some(other => within(mx, my, other)) && Math.min(edgeDistance(mx, my, points), ...avoid.map(other => edgeDistance(mx, my, other))) >= room * 0.85;
    return middleIsFine || !best ? [mx, my] : best;
  };
  const featureName: Partial<Record<GroundFeatureKind, string>> = { house: t('House', 'Indlu'), patio: t('Patio', 'Isitubhi'), driveway: t('Driveway', 'Indlela yemoto'), lawn: t('Lawn', 'Utshani'), veg_garden: t('Veg garden', 'Ingadi yemifino'), orchard: t('Orchard', 'Insimu yezithelo'), cleared: t('Cleared ground', 'Indawo evulekile') };
  const order: GroundFeatureKind[] = ['lawn', 'cleared', 'veg_garden', 'orchard', 'driveway', 'patio', 'terrace_bank', 'staple_garden', 'house'];
  const buildings = areas.filter(area => area.feature === 'house').map(area => area.points);
  let plotNumber = 0;
  const plotLabel = new Map<string, string>();
  for (const area of areas) if (area.feature === 'staple_garden') { plotNumber += 1; plotLabel.set(area.id, `P${plotNumber}`); }
  const present = new Set<string>();
  let anyPlanned = false, anyExisting = false;
  const seen = (planned: boolean) => { if (planned) anyPlanned = true; else anyExisting = true; };
  for (const kind of order) for (const area of areas) {
    if (area.feature !== kind) continue;
    const { planned } = area, d = pathOf(area.points, true), [cx, cy] = kind === 'house' ? labelPoint(area.points, []) : labelPoint(area.points, buildings);
    present.add(kind === 'house' ? 'building' : kind === 'staple_garden' ? 'plot' : kind === 'terrace_bank' ? 'bank' : kind === 'patio' || kind === 'driveway' ? 'hard' : 'ground');
    seen(planned);
    if (kind === 'house') p.path(d, planned ? { fill: PAINT_COLOUR.structure.tint, stroke: SLATE, width: 1.8, dash: '6 4' } : { fill: SLATE, stroke: '#ffffff', width: 1 });
    else if (kind === 'staple_garden') p.path(d, { fill: plotHatch, stroke: AMBER, width: 1.6, dash: planned ? '6 4' : undefined });
    else if (kind === 'terrace_bank') p.path(d, { fill: bankHatch, stroke: '#8a7355', width: 1 });
    else p.path(d, { fill: GROUND_FILL[kind] ?? '#eef1ef', stroke: kind === 'veg_garden' || kind === 'orchard' ? '#9db897' : kind === 'lawn' || kind === 'cleared' ? undefined : '#b9c0bb', width: 1, dash: planned ? '5 4' : undefined });
    const xs = area.points.map(q => X(q[0])), ys = area.points.map(q => Y(q[1])), boxW = Math.max(...xs) - Math.min(...xs), boxH = Math.max(...ys) - Math.min(...ys);
    const text = kind === 'staple_garden' ? plotLabel.get(area.id) ?? '' : area.name ? clip(area.name, 18) : featureName[kind] ?? '';
    const size = kind === 'staple_garden' ? 14 : 13;
    if (text && textWidth(text, size) < boxW * 0.92 && boxH > size * 1.5) {
      const onDark = kind === 'house' && !planned;
      labels.push({ text, x: X(cx), y: Y(cy) + size * 0.35, size, fill: onDark ? '#ffffff' : INK, weight: 700, halo: !onDark, box: { x: X(cx) - textWidth(text, size) / 2, y: Y(cy) - size * 0.7, w: textWidth(text, size), h: size * 1.3 } });
    }
  }

  // Routes under the items, so a bed drawn across a path still reads as a bed.
  const routeName: Record<RouteKind, string> = { swale: t('Swale', 'Umsele wokubamba amanzi'), fence: t('Fence', 'Uthango'), path: t('Path', 'Indlela'), bedpath: t('Bed path', 'Indlela yemibhede'), pipe: t('Water pipe', 'Ipayipi lamanzi'), drip: t('Drip line', 'Ipayipi lokuconsa'), windbreak: t('Windbreak', 'Isivikelo somoya'), greywater: t('Greywater line', 'Amanzi asetshenzisiwe'), driveway: t('Driveway', 'Indlela yemoto') };
  const routeKinds = new Map<RouteKind, boolean>(); // kind -> every one of them is planned
  for (const route of routes) {
    const style = ROUTE_STYLE[route.kind];
    routeKinds.set(route.kind, (routeKinds.get(route.kind) ?? true) && route.planned); seen(route.planned);
    p.path(pathOf(route.points, false), { stroke: style.colour, width: style.width, dash: route.planned ? `${Math.max(5, style.width * 2)} ${Math.max(4, style.width * 1.4)}` : undefined });
  }

  // Items: plants underneath, beds and tanks on top. A footprint too small to see is drawn at a
  // minimum size — the note says so, because a symbol is not a measurement.
  const MIN = 7;
  let enlarged = false;
  const paintOrder: PlanPaint[] = ['planting', 'access', 'structure', 'earthworks', 'animal', 'water', 'bed'];
  const counts: Partial<Record<PlanPaint, { all: number; existing: number }>> = {};
  const itemLook = (paint: PlanPaint, planned: boolean, key = false): ShapeOptions => {
    const colour = PAINT_COLOUR[paint], soft = paint === 'planting';
    if (planned) return { fill: soft ? (key ? '#ffffff' : 'none') : colour.tint, stroke: colour.solid, width: 1.6, dash: '5 3' };
    return soft ? { fill: '#9fc79b', stroke: colour.solid, width: 1.3, opacity: 0.78 } : { fill: colour.solid, stroke: '#ffffff', width: 1 };
  };
  const attrs = (o: ShapeOptions) => `fill="${o.fill ?? 'none'}"${o.stroke ? ` stroke="${o.stroke}" stroke-width="${o.width}"` : ''}${o.dash ? ` stroke-dasharray="${o.dash}"` : ''}${o.opacity ? ` opacity="${o.opacity}"` : ''}`;
  const geometry = new Map<PlanItem, Box>();
  for (const item of items) {
    const w = Math.max(item.w * scale, MIN), h = Math.max(item.h * scale, MIN);
    if (item.w * scale < MIN || item.h * scale < MIN) enlarged = true;
    const r = item.round || !item.rot ? Math.max(w, h) / 2 : Math.hypot(w, h) / 2;
    const box = item.round || item.rot ? { x: X(item.cx) - r, y: Y(item.cy) - r, w: r * 2, h: r * 2 } : { x: X(item.cx) - w / 2, y: Y(item.cy) - h / 2, w, h };
    geometry.set(item, box); obstacles.push(box);
  }
  for (const paint of paintOrder) for (const item of items) {
    if (item.paint !== paint) continue;
    const tally = counts[paint] ?? { all: 0, existing: 0 }; tally.all += 1; if (!item.planned) tally.existing += 1; counts[paint] = tally; seen(item.planned);
    const cx = X(item.cx), cy = Y(item.cy), w = Math.max(item.w * scale, MIN), h = Math.max(item.h * scale, MIN), look = itemLook(paint, item.planned);
    if (item.round) p.raw(`<ellipse cx="${px(cx)}" cy="${px(cy)}" rx="${px(w / 2)}" ry="${px(h / 2)}" ${attrs(look)}/>`);
    else p.raw(`<rect x="${px(cx - w / 2)}" y="${px(cy - h / 2)}" width="${px(w)}" height="${px(h)}" rx="1.5" ${attrs(look)}${item.rot ? ` transform="rotate(${px(item.rot)} ${px(cx)} ${px(cy)})"` : ''}/>`);
    if (paint === 'planting' && !item.planned) p.circle(cx, cy, 1.6, { fill: GREEN });
  }

  // The boundary goes over the fills, so the edge of the site is never painted out.
  for (const area of areas) {
    if (area.feature !== 'boundary') continue;
    present.add('boundary');
    p.path(pathOf(area.points, true), { stroke: INK, width: 2, dash: '11 4 2 4' });
  }
  p.raw('</g>');

  // Labels. Inside the shape when it fits; otherwise beside it, first free side wins; otherwise
  // dropped — the key below still says what the colour and the code mean.
  const panel: Box = { x: 4, y: 4, w: W - 8, h: panelH - footH - 8 };
  const inside = (b: Box) => b.x >= panel.x && b.y >= panel.y && b.x + b.w <= panel.x + panel.w && b.y + b.h <= panel.y + panel.h;
  const taken: Box[] = labels.map(l => l.box);
  for (const item of items) {
    const own = geometry.get(item)!, cx = X(item.cx), cy = Y(item.cy);
    const text = item.inside || item.label;
    if (!text) continue;
    const wPx = Math.max(item.w * scale, MIN), hPx = Math.max(item.h * scale, MIN), short = Math.min(wPx, hPx);
    const roomW = item.round ? short * 0.78 : item.rot ? short : wPx, roomH = item.round ? short * 0.78 : item.rot ? short : hPx;
    const fitSize = [15, 14, 13, 12, 11, 10, 9].find(size => textWidth(text, size) <= roomW * 0.9 && size <= roomH * 0.86);
    if (item.inside && fitSize) {
      const solid = !item.planned && item.paint !== 'planting';
      const box = { x: cx - textWidth(text, fitSize) / 2, y: cy - fitSize * 0.6, w: textWidth(text, fitSize), h: fitSize * 1.2 };
      labels.push({ text, x: cx, y: cy + fitSize * 0.36, size: fitSize, fill: solid ? '#ffffff' : INK, weight: 700, halo: false, box });
      taken.push(box);
      continue;
    }
    const size = 12.5, tw = textWidth(text, size), gap = 4;
    const mid = Math.max(panel.x + tw / 2 + 2, Math.min(panel.x + panel.w - tw / 2 - 2, cx)); // a name above or below slides sideways to stay on the drawing
    const candidates: Array<{ x: number; y: number; box: Box }> = [
      { x: own.x + own.w + gap + tw / 2, y: cy + size * 0.36, box: { x: own.x + own.w + gap, y: cy - size * 0.65, w: tw, h: size * 1.3 } },
      { x: own.x - gap - tw / 2, y: cy + size * 0.36, box: { x: own.x - gap - tw, y: cy - size * 0.65, w: tw, h: size * 1.3 } },
      { x: mid, y: own.y - gap, box: { x: mid - tw / 2, y: own.y - gap - size, w: tw, h: size * 1.3 } },
      { x: mid, y: own.y + own.h + gap + size * 0.8, box: { x: mid - tw / 2, y: own.y + own.h + gap - 2, w: tw, h: size * 1.3 } },
    ];
    const spot = candidates.find(c => inside(c.box) && !taken.some(b => overlaps(b, c.box)) && !obstacles.some(b => b !== own && overlaps(b, c.box)));
    if (!spot) continue;
    labels.push({ text, x: spot.x, y: spot.y, size, fill: INK, weight: 600, halo: true, box: spot.box });
    taken.push(spot.box);
  }
  for (const route of routes) {
    // One name per route: the first clear spot found walking out from its middle.
    if (route.kind === 'bedpath') continue;
    const lengths = route.points.slice(1).map((q, i) => Math.hypot(q[0] - route.points[i][0], q[1] - route.points[i][1])), total = lengths.reduce((sum, len) => sum + len, 0);
    if (!(total > 0)) continue;
    const along = (fraction: number): [number, number] => { let left = total * fraction; for (let i = 0; i < lengths.length; i += 1) { if (left <= lengths[i] || i === lengths.length - 1) { const u = lengths[i] ? Math.min(1, left / lengths[i]) : 0; return [route.points[i][0] + (route.points[i + 1][0] - route.points[i][0]) * u, route.points[i][1] + (route.points[i + 1][1] - route.points[i][1]) * u]; } left -= lengths[i]; } return route.points[0]; };
    const text = clip(route.name || routeName[route.kind], 20), size = 12, tw = textWidth(text, size);
    search: for (const fraction of [0.5, 0.38, 0.62, 0.26, 0.74, 0.14, 0.86]) for (const dy of [-7, 15, -19, 27]) {
      const at = along(fraction), box = { x: X(at[0]) - tw / 2, y: Y(at[1]) + dy - size, w: tw, h: size * 1.3 };
      if (!inside(box) || taken.some(b => overlaps(b, box)) || obstacles.some(b => overlaps(b, box))) continue;
      labels.push({ text, x: X(at[0]), y: Y(at[1]) + dy, size, fill: ROUTE_STYLE[route.kind].ink, weight: 600, halo: true, box });
      taken.push(box);
      break search;
    }
  }
  for (const label of labels) p.text(label.x, label.y, label.text, { size: label.size, anchor: 'middle', weight: label.weight, fill: label.fill, halo: label.halo });

  // Scale bar and north arrow, in their own strip so they never sit on the drawing. Frames are
  // north-up with no rotation; a blank-paper design with no map boundary has no georeference at
  // all, so it gets no north arrow rather than a guessed one.
  const footY = panelH - footH;
  p.line(1, footY, W - 1, footY, { stroke: HAIR, width: 1 });
  const barMetres = [...NICE_METRES].reverse().find(m => m * scale <= 170) ?? 1, barPx = barMetres * scale, barX = 16, barY = footY + 20;
  p.rect(barX, barY - 4, barPx / 2, 7, { fill: INK }); p.rect(barX + barPx / 2, barY - 4, barPx / 2, 7, { fill: '#ffffff' });
  p.rect(barX, barY - 4, barPx, 7, { stroke: INK, width: 1 });
  p.text(barX + barPx + 8, barY + 4, `${figureNumber(barMetres)} m`, { size: 13, fill: INK, weight: 700 });
  const northUp = designBaseMode(canvas) !== 'blank' || mapBoundary.length > 0;
  if (northUp) {
    const nx = W - 24, ny = footY + 18;
    p.path(`M${nx} ${ny - 11}L${nx + 6.5} ${ny + 8}L${nx} ${ny + 3.5}L${nx - 6.5} ${ny + 8}Z`, { fill: INK });
    p.text(nx - 12, ny + 5, t('North', 'INyakatho'), { size: 13, weight: 700, anchor: 'end', fill: INK });
  }

  // The key: only what is actually on this drawing, drawn the way it is drawn above.
  type KeyRow = { draw: (x: number, y: number) => void; text: string };
  const key: KeyRow[] = [];
  const swatch = (paint: PlanPaint, round: boolean, mark = '') => (x: number, y: number) => {
    const planned = !(counts[paint]?.existing), look = itemLook(paint, planned, true);
    if (round) p.raw(`<circle cx="${px(x + 12)}" cy="${px(y)}" r="8.5" ${attrs(look)}/>`); else p.raw(`<rect x="${px(x + 2)}" y="${px(y - 7)}" width="20" height="14" rx="1.5" ${attrs(look)}/>`);
    if (mark) p.text(x + 12, y + 4, mark, { size: 11, weight: 700, fill: planned || paint === 'planting' ? INK : '#ffffff', anchor: 'middle' });
    else if (paint === 'planting' && !planned) p.circle(x + 12, y, 1.6, { fill: GREEN });
  };
  const some = (n: number, one: string, many: string) => `${figureNumber(n)} ${n === 1 ? one : many}`;
  if (present.has('boundary')) key.push({ draw: (x, y) => p.line(x, y, x + 24, y, { stroke: INK, width: 2, dash: '11 4 2 4' }), text: t('Site boundary', 'Umngcele wendawo') });
  if (present.has('building')) key.push({ draw: (x, y) => p.rect(x + 2, y - 7, 20, 14, { fill: SLATE }), text: t('Buildings', 'Izakhiwo') });
  if (counts.bed) key.push({ draw: swatch('bed', false, '1'), text: some(counts.bed.all, t('vegetable bed, numbered', 'umbhede wemifino, unenombolo'), t('vegetable beds, numbered', 'imibhede yemifino, inezinombolo')) });
  if (plotNumber) key.push({ draw: (x, y) => p.rect(x + 2, y - 7, 20, 14, { fill: plotHatch, stroke: AMBER, width: 1.4 }), text: plotNumber === 1 ? t('1 staple plot (P1)', 'isiza esiyisisekelo esi-1 (P1)') : t(`${plotNumber} staple plots (P1–P${plotNumber})`, `iziza eziyisisekelo ezi-${plotNumber} (P1–P${plotNumber})`) });
  if (counts.planting) key.push({ draw: swatch('planting', true), text: some(counts.planting.all, t('tree or planting, to scale', 'isihlahla noma isitshalo, ngesikali'), t('trees and plantings, to scale', 'izihlahla nezitshalo, ngesikali')) });
  if (counts.water) key.push({ draw: swatch('water', true), text: some(counts.water.all, t('water tank or water point', 'ithangi noma indawo yamanzi'), t('water tanks and points', 'amathangi nezindawo zamanzi')) });
  if (present.has('hard')) key.push({ draw: (x, y) => p.rect(x + 2, y - 7, 20, 14, { fill: GROUND_FILL.driveway, stroke: '#b9c0bb', width: 1 }), text: t('Paving and driveway', 'Indawo egandayiwe') });
  if (present.has('bank')) key.push({ draw: (x, y) => p.rect(x + 2, y - 7, 20, 14, { fill: bankHatch, stroke: '#8a7355', width: 1 }), text: t('Terrace bank', 'Udonga lwethala') });
  if (counts.structure) key.push({ draw: swatch('structure', false), text: some(counts.structure.all, t('structure', 'isakhiwo esincane'), t('structures', 'izakhiwo ezincane')) });
  if (counts.earthworks) key.push({ draw: swatch('earthworks', false), text: some(counts.earthworks.all, t('soil or earthworks item', 'into yomhlabathi'), t('soil and earthworks items', 'izinto zomhlabathi')) });
  if (counts.animal) key.push({ draw: swatch('animal', false), text: some(counts.animal.all, t('animal shelter', 'indawo yezilwane'), t('animal shelters', 'izindawo zezilwane')) });
  if (counts.access) key.push({ draw: swatch('access', false), text: some(counts.access.all, t('gate or access item', 'isango noma indlela'), t('gates and access items', 'amasango nezindlela')) });
  for (const [kind, planned] of routeKinds) key.push({ draw: (x, y) => p.line(x, y, x + 24, y, { stroke: ROUTE_STYLE[kind].colour, width: Math.min(ROUTE_STYLE[kind].width, 6), dash: planned ? '6 4' : undefined }), text: routeName[kind] });

  let y = panelH + 24;
  const columnW = (W - 12) / 2, keyChars = Math.floor((columnW - 40) / (13.5 * 0.56));
  key.forEach((row, i) => { const x = 8 + (i % 2) * columnW, rowY = y + Math.floor(i / 2) * 25; row.draw(x, rowY); p.text(x + 32, rowY + 5, clip(row.text, keyChars), { size: 13.5 }); });
  y += Math.ceil(key.length / 2) * 25;
  if (anyPlanned) {
    p.rect(9, y - 7, 10, 14, { fill: SLATE }); p.rect(22, y - 7, 10, 14, { fill: '#ffffff', stroke: SLATE, width: 1.5, dash: '4 2.5' });
    p.text(40, y + 5, anyExisting ? t('Solid = already there.  Dashed outline = planned, not built yet.', 'Okugcwele = sekukhona.  Umugqa onamachashaza = kuhleliwe, akukakhiwa.') : t('Dashed outlines: everything on this plan is planned, not built yet.', 'Imigqa enamachashaza: konke okukuleli pulani kuhleliwe, akukakhiwa.'), { size: 13.5, weight: 700, fill: INK });
    y += 25;
  }
  const plantNames = new Map<string, { code: string; name: string; count: number }>();
  for (const item of canvas.items) { const code = codes.get(item.defId), def = ELEMENTS_BY_ID[item.defId]; if (!code || !def || isBedDef(item.defId)) continue; const row = plantNames.get(item.defId) ?? { code, name: def.name, count: 0 }; row.count += 1; plantNames.set(item.defId, row); }
  const footnote = (value: string) => { for (const lineText of wrapText(value, 13, W - 20)) { p.text(8, y + 6, lineText, { size: 13, fill: MUTED }); y += 17; } y += 3; };
  if (plantNames.size) footnote(`${t('Plant codes', 'Amakhodi ezitshalo')}: ${[...plantNames.values()].sort((a, b) => a.code.localeCompare(b.code)).map(row => `${row.code} ${row.name}${row.count > 1 ? ` ×${row.count}` : ''}`).join('  ·  ')}`);
  if (bedNames.length) footnote(`${t('Bed names', 'Amagama emibhede')}: ${bedNames.slice(0, 16).join('  ·  ')}${bedNames.length > 16 ? ' …' : ''}`);

  const drawn = [counts.bed ? some(counts.bed.all, t('vegetable bed', 'umbhede wemifino'), t('vegetable beds', 'imibhede yemifino')) : '', plotNumber ? some(plotNumber, t('staple plot', 'isiza esiyisisekelo'), t('staple plots', 'iziza eziyisisekelo')) : '', counts.planting ? some(counts.planting.all, t('tree or planting', 'isihlahla'), t('trees and plantings', 'izihlahla nezitshalo')) : '', counts.water ? some(counts.water.all, t('water item', 'into yamanzi'), t('water items', 'izinto zamanzi')) : ''].filter(Boolean).join(', ');
  const saved = canvas.updatedAt && Number.isFinite(Date.parse(canvas.updatedAt)) ? new Date(canvas.updatedAt).toISOString().slice(0, 10) : '';
  const fromMap = mapBoundary.length || mapHouse.length || mapDrive.length;
  return {
    id: 'site-plan', title: t('Site plan', 'Ipulani lendawo'), svg: p.done(y + 6), width: W, height: Math.ceil(y + 6),
    note: `${t('Drawn to scale from the saved design.', 'Kudwetshwe ngesikali kusuka kumklamo ogciniwe.')} ${northUp ? t('North is up. ', 'INyakatho iphezulu. ') : ''}${counts.bed ? t('Bed numbers match the bed list. ', 'Izinombolo zemibhede ziyafana nezasohlwini lwemibhede. ') : ''}${cropped ? t('The boundary runs beyond this drawing, which closes in on the designed area. ', 'Umngcele udlulela ngale kwalo mdwebo, osondele endaweni eklanyiwe. ') : ''}${enlarged ? t('Very small items are drawn larger so they can be seen. ', 'Izinto ezincane kakhulu zidwetshwe zaba zinkulu ukuze zibonakale. ') : ''}${t('It is not a land survey.', 'Akusikho ukuhlolwa komhlaba.')}`,
    source: `${t('Saved design', 'Umklamo ogciniwe')}${saved ? ` (${saved})` : ''}${fromMap ? t('; boundary and buildings as traced on the map', '; umngcele nezakhiwo njengoba kudwetshwe kumephu') : ''}`,
    alt: `${t('Site plan drawn from the saved design', 'Ipulani lendawo elidwetshwe kumklamo ogciniwe')}${drawn ? `: ${drawn}` : ''}. ${t('Scale bar', 'Isikali')} ${barMetres} m.`,
  };
}

// ── Shared chart pieces ───────────────────────────────────────────────────────────────────────

// Every month axis runs Jan→Dec. A Jul→Jun "water year" was considered and declined: it suits a
// summer-rainfall site and splits the wet season of a winter-rainfall one, and the crop calendar,
// the tank calculator and the farmer's own diary all read Jan→Dec. The seasons are named instead.
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const twelve = (values: unknown): values is number[] => Array.isArray(values) && values.length === 12 && values.every(finite);

/** A zero-based axis with round steps (1, 2 or 5 × 10ⁿ) and about `target` divisions. */
function axis(max: number, target = 4) {
  const raw = Math.max(max, 1e-9) / target;
  const pow = 10 ** Math.floor(Math.log10(raw));
  const step = ([1, 2, 5, 10].find(m => m * pow >= raw - 1e-12) ?? 10) * pow;
  const top = Math.max(step, Math.ceil(max / step - 1e-9) * step);
  const ticks: number[] = [];
  for (let v = 0; v <= top + step / 2; v += step) ticks.push(v);
  return { top, ticks };
}

/** "Oct–Mar" → [9,10,11,0,1,2]. Anything it cannot read gives [] and that season is not drawn. */
function seasonMonths(label: string | undefined): number[] {
  const m = /^\s*([A-Za-z]{3})[a-z]*\s*[–—-]\s*([A-Za-z]{3})[a-z]*\s*$/.exec(label ?? '');
  if (!m) return [];
  const at = (s: string) => MONTHS.findIndex(x => x.toLowerCase() === s.toLowerCase());
  const from = at(m[1]), to = at(m[2]);
  if (from < 0 || to < 0) return [];
  const out: number[] = [];
  for (let i = from; out.length < 12; i = (i + 1) % 12) { out.push(i); if (i === to) break; }
  return out;
}

/** Flagged months as readable runs, joining a run that wraps the year end: "Nov–Feb, Jun". */
function monthRuns(flags: boolean[]): string {
  if (!flags.some(Boolean)) return '';
  if (flags.every(Boolean)) return 'Jan–Dec';
  const runs: string[] = [];
  const start = flags.indexOf(false);
  let open = -1;
  for (let k = 1; k <= 12; k++) {
    const i = (start + k) % 12;
    if (flags[i]) { if (open < 0) open = i; continue; }
    if (open >= 0) { const end = (i + 11) % 12; runs.push(open === end ? MONTHS[open] : `${MONTHS[open]}–${MONTHS[end]}`); open = -1; }
  }
  return runs.join(', ');
}

/** A bar standing on the baseline: soft at the data end, square where it meets the axis. */
function barPath(x: number, base: number, w: number, h: number, r = 4) {
  if (!(h > 0)) return '';
  const rr = Math.min(r, h, w / 2), y = base - h;
  return `M${px(x)} ${px(base)}V${px(y + rr)}Q${px(x)} ${px(y)} ${px(x + rr)} ${px(y)}H${px(x + w - rr)}Q${px(x + w)} ${px(y)} ${px(x + w)} ${px(y + rr)}V${px(base)}Z`;
}

const monthLabels = (p: Pen, left: number, slot: number, y: number) => MONTHS.forEach((m, i) => p.text(left + slot * (i + 0.5), y, m, { size: 12, fill: MUTED, anchor: 'middle' }));

type KeyEntry = { draw: (x: number, y: number) => void; label: string };
/** Key entries left to right, wrapping to the drawing's width. Returns the y under the last row. */
function keyRow(p: Pen, x0: number, y: number, entries: KeyEntry[], maxX = W - 14): number {
  let x = x0;
  for (const entry of entries) {
    const w = 28 + textWidth(entry.label, 12) + 16;
    if (x > x0 && x + w > maxX) { x = x0; y += 21; }
    entry.draw(x, y);
    p.text(x + 28, y + 4, entry.label, { size: 12 });
    x += w;
  }
  return y + 21;
}

/** Wrapped sentence block. Returns the y under the last line. */
function paragraph(p: Pen, x: number, y: number, value: string, width: number, o: TextOptions = {}): number {
  const size = o.size ?? 13;
  for (const line of wrapText(value, size, width)) { p.text(x, y, line, { ...o, size }); y += Math.round(size * 1.42); }
  return y;
}

const rainSourceLabel = (source: string | undefined, t: Translate) => source === 'nasa-power' ? 'NASA POWER (50 km climate grid)' : source === 'open-meteo' ? 'ERA5-Land via Open-Meteo (9 km grid)' : t('climate data service', 'isevisi yedatha yesimo sezulu');

// ── 2. Climate: when the rain comes, and how warm it is ───────────────────────────────────────

/**
 * Rain by month over temperature by month, on one Jan→Dec axis. Two panels, never two scales on
 * one panel: a dual-axis chart lets the eye read a crossing that means nothing.
 */
export function climateFigure(location: LocationData | null | undefined, language = 'en'): ReportFigure | null {
  const rain = location?.rainfall;
  if (!rain || !twelve(rain.monthly) || rain.monthly.some(v => v < 0) || !rain.monthly.some(v => v > 0)) return null;
  const t = translator(language);
  const p = pen();
  const monthly = rain.monthly;
  const annual = finite(rain.annual) && rain.annual > 0 ? rain.annual : monthly.reduce((a, b) => a + b, 0);
  const wettest = monthly.indexOf(Math.max(...monthly)), driest = monthly.indexOf(Math.min(...monthly));
  const left = 50, right = W - 14, slot = (right - left) / 12;

  p.text(14, 25, `${figureNumber(annual)} mm ${t('of rain in an average year', 'yemvula ngonyaka ojwayelekile')}`, { size: 17, weight: 700, fill: INK });
  p.text(14, 46, `${t('Wettest month', 'Inyanga enemvula kakhulu')}: ${MONTHS[wettest]} (${figureNumber(monthly[wettest])} mm)   ·   ${t('Driest month', 'Inyanga eyome kakhulu')}: ${MONTHS[driest]} (${figureNumber(monthly[driest])} mm)`, { size: 13, fill: MUTED });

  const top = 82, base = 226, scale = axis(Math.max(...monthly));
  p.text(left - 8, top - 12, 'mm', { size: 11, fill: MUTED, anchor: 'end' });
  for (const tick of scale.ticks) {
    const y = base - (tick / scale.top) * (base - top);
    p.line(left, y, right, y, { stroke: tick === 0 ? MUTED : HAIR, width: 1 });
    p.text(left - 8, y + 4, figureNumber(tick), { size: 11, fill: MUTED, anchor: 'end' });
  }
  monthly.forEach((value, i) => {
    const w = slot * 0.62, x = left + slot * i + (slot - w) / 2, h = (value / scale.top) * (base - top);
    p.path(barPath(x, base, w, h), { fill: BLUE });
    const strong = i === wettest || i === driest;
    p.text(x + w / 2, base - h - 5, figureNumber(value), { size: 11, anchor: 'middle', weight: strong ? 700 : 400, fill: strong ? INK : MUTED });
  });

  // The season strip says in shape, not only colour, which months the record calls wet and dry.
  const wet = seasonMonths(rain.wetSeason), dry = seasonMonths(rain.drySeason);
  const dryHatch = dry.length ? p.hatch('dry', AMBER, 5, 1.4) : '';
  if (wet.length || dry.length) for (let i = 0; i < 12; i++) {
    const x = left + slot * i + 1, w = slot - 2, y = base + 6;
    if (wet.includes(i)) p.rect(x, y, w, 7, { fill: BLUE });
    else if (dry.includes(i)) p.rect(x, y, w, 7, { fill: dryHatch, stroke: AMBER, width: 1 });
    else p.rect(x, y, w, 7, { fill: TRACK });
  }
  monthLabels(p, left, slot, base + 30);
  const entries: KeyEntry[] = [];
  if (wet.length) entries.push({ label: `${t('Wet season', 'Isikhathi semvula')} (${rain.wetSeason})`, draw: (x, y) => p.rect(x, y - 5, 20, 9, { fill: BLUE }) });
  if (dry.length) entries.push({ label: `${t('Dry season', 'Isikhathi sesomiso')} (${rain.drySeason})`, draw: (x, y) => p.rect(x, y - 5, 20, 9, { fill: dryHatch, stroke: AMBER, width: 1 }) });
  let height = entries.length ? keyRow(p, left, base + 52, entries) : base + 42;

  const temps = location?.climate?.monthlyTemp;
  let tempAlt = '';
  if (twelve(temps)) {
    const warm = temps.indexOf(Math.max(...temps)), cold = temps.indexOf(Math.min(...temps));
    p.text(14, height + 20, t('Average temperature each month (°C)', 'Izinga lokushisa elijwayelekile ngenyanga (°C)'), { size: 14, weight: 700, fill: INK });
    const tTop = height + 44, tBase = tTop + 92;
    const step = Math.max(...temps) - Math.min(...temps) > 16 ? 10 : 5;
    const lo = Math.floor((Math.min(...temps) - 1.5) / step) * step, hi = Math.ceil((Math.max(...temps) + 1.5) / step) * step;
    const yOf = (v: number) => tBase - ((v - lo) / (hi - lo)) * (tBase - tTop);
    for (let v = lo; v <= hi; v += step) { p.line(left, yOf(v), right, yOf(v), { stroke: HAIR, width: 1 }); p.text(left - 8, yOf(v) + 4, `${v}°`, { size: 11, fill: MUTED, anchor: 'end' }); }
    const pts = temps.map((v, i): [number, number] => [left + slot * (i + 0.5), yOf(v)]);
    p.path(`M${pts.map(([x, y]) => `${px(x)} ${px(y)}`).join('L')}`, { stroke: AMBER, width: 2.2 });
    pts.forEach(([x, y], i) => { const strong = i === warm || i === cold; p.circle(x, y, strong ? 5 : 3.2, { fill: strong ? AMBER : '#ffffff', stroke: strong ? '#ffffff' : AMBER, width: 2 }); });
    p.text(pts[warm][0], pts[warm][1] - 11, `${figureNumber(temps[warm], 1)} °C`, { size: 12, weight: 700, fill: INK, anchor: 'middle', halo: true });
    p.text(pts[cold][0], pts[cold][1] + 20, `${figureNumber(temps[cold], 1)} °C`, { size: 12, weight: 700, fill: INK, anchor: 'middle', halo: true });
    monthLabels(p, left, slot, tBase + 20);
    height = tBase + 30;
    tempAlt = ` ${t('Warmest month', 'Inyanga efudumele kakhulu')} ${MONTHS[warm]} ${figureNumber(temps[warm], 1)} °C, ${t('coolest', 'ebanda kakhulu')} ${MONTHS[cold]} ${figureNumber(temps[cold], 1)} °C.`;
  }

  return {
    id: 'climate', width: W, height: Math.ceil(height), svg: p.done(height),
    title: t('Rain and warmth through the year', 'Imvula nokufudumala phakathi nonyaka'),
    note: t('Long-term monthly averages for this location, not a forecast. Any one year can be much wetter or much drier than this.', 'Izilinganiso zesikhathi eside zale ndawo, akusona isibikezelo. Noma yimuphi unyaka ungaba nemvula eningi noma ube womile kakhulu kunalokhu.'),
    source: rainSourceLabel(rain.rainfallSource, t),
    alt: `${t('Rain by month', 'Imvula ngenyanga')}: ${figureNumber(annual)} mm ${t('a year', 'ngonyaka')}; ${t('wettest', 'enemvula kakhulu')} ${MONTHS[wettest]} ${figureNumber(monthly[wettest])} mm, ${t('driest', 'eyome kakhulu')} ${MONTHS[driest]} ${figureNumber(monthly[driest])} mm.${tempAlt}`,
  };
}

// ── 3. Water budget: what the traced roof can catch against what the site uses ────────────────

/**
 * Drawn only when a roof has actually been traced — a default roof would be an invented number
 * printed as a chart. Catch and need share ONE litre axis. The months that fall short are hatched,
 * and the storage needed to bridge them comes from lib/tank-sizing, the same sum the Tank
 * Calculator shows, so the report cannot disagree with the Design Studio.
 */
export function waterBudgetFigure(facts: ReportSiteFacts | null | undefined, location: LocationData | null | undefined, language = 'en'): ReportFigure | null {
  const roof = facts?.roof?.areaM2, rain = location?.rainfall;
  if (!finite(roof) || roof <= 0 || !rain || !twelve(rain.monthly) || rain.monthly.some(v => v < 0)) return null;
  const coefficient = WATER_SHEET_ROOF_RUNOFF_COEFFICIENT;
  const catchL = rain.monthly.map(mm => roofHarvestLitres(roof, mm, coefficient));
  if (!catchL.some(v => v > 0)) return null;
  const t = translator(language);
  const p = pen();
  const annualMm = finite(rain.annual) && rain.annual > 0 ? rain.annual : rain.monthly.reduce((a, b) => a + b, 0);
  // The same expression lib/report-site-facts prints in the report's evidence table.
  const annualCatch = Math.round(roofHarvestLitres(roof, annualMm, coefficient));
  const daily = facts?.measurements?.dailyWaterUseL;
  const needL = finite(daily) && daily > 0 ? DAYS_IN_MONTH.map(days => days * daily) : null;
  const sizing = needL && finite(daily) ? computeTankSizing({ monthlyRainfallMm: rain.monthly, roofAreaM2: roof, dailyUseL: daily }) : null;
  const short = needL ? catchL.map((v, i) => v < needL[i]) : catchL.map(() => false);
  const left = 62, right = W - 14, slot = (right - left) / 12;

  p.text(14, 25, `${t('This roof can catch', 'Lolu phahla lungabamba')} ${figureNumber(annualCatch)} L ${t('in an average year', 'ngonyaka ojwayelekile')}`, { size: 17, weight: 700, fill: INK });
  p.text(14, 46, `${figureNumber(roof)} m² ${t('of traced roof', 'yophahla oludwetshiwe')} × ${figureNumber(annualMm)} mm ${t('of rain', 'yemvula')} × ${coefficient} (${t('the rest is lost to splash and the first dirty flush', 'okunye kulahleka ngokuchaphazela nangamanzi okuqala angcolile')})`, { size: 12.5, fill: MUTED });

  const top = 84, base = 232, scale = axis(Math.max(...catchL, ...(needL ?? [0])));
  p.text(left - 8, top - 12, t('litres', 'amalitha'), { size: 11, fill: MUTED, anchor: 'end' });
  for (const tick of scale.ticks) {
    const y = base - (tick / scale.top) * (base - top);
    p.line(left, y, right, y, { stroke: tick === 0 ? MUTED : HAIR, width: 1 });
    p.text(left - 8, y + 4, figureNumber(tick), { size: 11, fill: MUTED, anchor: 'end' });
  }
  const gap = short.some(Boolean) ? p.hatch('short', AMBER, 5, 1.5) : '';
  catchL.forEach((value, i) => {
    const w = slot * 0.6, x = left + slot * i + (slot - w) / 2, h = (value / scale.top) * (base - top);
    p.path(barPath(x, base, w, h), { fill: BLUE });
    let labelY = base - h - 5;
    if (needL) {
      const needY = base - (needL[i] / scale.top) * (base - top);
      if (short[i]) p.rect(x, needY, w, Math.max(0, base - h - needY - 2), { fill: gap, stroke: AMBER, width: 1 });
      p.line(x - 5, needY, x + w + 5, needY, { stroke: INK, width: 2.6 });
      labelY = Math.min(labelY, needY - 6);
    }
    p.text(x + w / 2, labelY, figureNumber(Math.round(value / 100) * 100), { size: 10.5, anchor: 'middle', fill: short[i] ? INK : MUTED, weight: short[i] ? 700 : 400, halo: true });
  });
  monthLabels(p, left, slot, base + 19);
  const entries: KeyEntry[] = [{ label: t('Rain the roof catches that month', 'Imvula ebanjwa uphahla ngaleyo nyanga'), draw: (x, y) => p.rect(x + 2, y - 6, 15, 12, { fill: BLUE }) }];
  if (needL) entries.push({ label: `${t('Water used that month', 'Amanzi asetshenziswa ngaleyo nyanga')} (${figureNumber(daily as number)} L ${t('a day', 'ngosuku')})`, draw: (x, y) => p.line(x, y, x + 20, y, { stroke: INK, width: 2.6 }) });
  if (short.some(Boolean)) entries.push({ label: t('Short: must come from the tank or another source', 'Ukushoda: kumele kuvele ethangini noma komunye umthombo'), draw: (x, y) => p.rect(x + 2, y - 6, 15, 12, { fill: gap, stroke: AMBER, width: 1 }) });
  let y = keyRow(p, 14, base + 44, entries) + 8;

  // Storage: what is drawn on the plan against what would carry the site through the dry run.
  const stored = facts?.water?.statedStorageLitres ?? 0;
  const tanks = facts?.water?.tanks ?? [];
  const unknownTanks = facts?.water?.tanksOfUnknownCapacity ?? 0;
  const allBuilt = tanks.length > 0 && tanks.every(tank => tank.status === 'existing');
  const needed = sizing?.ok && sizing.recommendedStorageL > 0 ? sizing.recommendedStorageL : 0;
  if (stored > 0 || needed > 0) {
    p.line(14, y, W - 14, y, { stroke: HAIR, width: 1 });
    y += 24;
    p.text(14, y, t('Tank storage', 'Isitoreji samathangi'), { size: 14, weight: 700, fill: INK });
    y += 12;
    const barLeft = 14, barMax = W - 28 - 150, unit = barMax / Math.max(stored, needed, 1);
    const row = (label: string, litres: number, look: ShapeOptions) => {
      y += 18;
      p.text(barLeft, y, label, { size: 12.5 });
      y += 7;
      p.rect(barLeft, y, Math.max(3, litres * unit), 16, { radius: 3, ...look });
      p.text(barLeft + Math.max(3, litres * unit) + 8, y + 12.5, `${figureNumber(litres)} L`, { size: 13, weight: 700, fill: INK });
      y += 22;
    };
    if (stored > 0) row(`${t('On the plan', 'Kupulani')} — ${allBuilt ? t('already installed', 'sekufakiwe') : t('planned, not installed yet', 'kuhleliwe, akukafakwa')}${unknownTanks ? ` (+${unknownTanks} ${t('tank of unknown size, not counted', 'ithangi elingaziwa usayizi, alibalwanga')})` : ''}`, stored, allBuilt ? { fill: BLUE } : { fill: '#e1eef2', stroke: BLUE, width: 1.6, dash: '5 3' });
    if (needed > 0) row(t('Needed to carry this use through the dry months (Tank Calculator)', 'Okudingekayo ukuze kudlule izinyanga ezomile (Isibali Sethangi)'), needed, { fill: p.hatch('need', SLATE, 5, 1.4), stroke: SLATE, width: 1.2 });
    y += 4;
  }

  const lines: string[] = [];
  if (!needL) lines.push(t('Daily water use has not been recorded for this site, so this figure cannot show which months run short. Add it in the Design Studio, Water step.', 'Ukusetshenziswa kwamanzi kwansuku zonke akukaqoshwa kule ndawo, ngakho lo mdwebo awukwazi ukukhombisa izinyanga ezishodayo. Kufake ku-Design Studio, isinyathelo Samanzi.'));
  else if (short.some(Boolean)) {
    lines.push(`${t('The roof catches less than is used in', 'Uphahla lubamba okuncane kunalokho okusetshenziswayo ngo')} ${monthRuns(short)}.${sizing?.ok && sizing.dryRunShortfallL > 0 ? ` ${t('Over the longest dry run the gap adds up to', 'Esikhathini eside esomile igebe lifinyelela ku')} ${figureNumber(Math.round(sizing.dryRunShortfallL))} L.` : ''}`);
    if (sizing?.ok && sizing.waterNegative) lines.push(t('Over the whole year this roof catches less than the site uses. A bigger tank helps, but more roof or another water source is needed to close the gap.', 'Ngonyaka wonke lolu phahla lubamba okuncane kunalokho okusetshenziswa indawo. Ithangi elikhulu liyasiza, kodwa kudingeka uphahla olwengeziwe noma omunye umthombo wamanzi.'));
  } else lines.push(t('In an average year the roof catches more than is used in every month.', 'Ngonyaka ojwayelekile uphahla lubamba okungaphezu kwalokho okusetshenziswayo nyanga zonke.'));
  for (const line of lines) y = paragraph(p, 14, y + 6, line, W - 28) + 2;

  return {
    id: 'water-budget', width: W, height: Math.ceil(y + 4), svg: p.done(y + 4),
    title: t('Roof water: what comes in and what goes out', 'Amanzi ophahla: okungenayo nokuphumayo'),
    note: t('Average-year arithmetic, not a promise of rain. It counts only the roof that has been traced and only the tanks drawn on the plan; it says nothing about whether the water is safe to drink.', 'Izibalo zonyaka ojwayelekile, akusona isithembiso semvula. Kubalwa kuphela uphahla oludwetshiwe namathangi asepulanini; akusho lutho ngokuphepha kwamanzi okuphuzwa.'),
    source: `${t('Roof', 'Uphahla')}: ${facts?.roof?.source ?? t('traced area', 'indawo edwetshiwe')}. ${t('Rain', 'Imvula')}: ${rainSourceLabel(rain.rainfallSource, t)}.${needL ? ` ${t('Daily use: as recorded in the Design Studio.', 'Ukusetshenziswa kwansuku zonke: njengoba kuqoshwe ku-Design Studio.')}` : ''}`,
    alt: `${t('Roof catch by month', 'Okubanjwa uphahla ngenyanga')}: ${figureNumber(annualCatch)} L ${t('a year', 'ngonyaka')}${short.some(Boolean) ? `; ${t('short in', 'kuyashoda ngo')} ${monthRuns(short)}` : ''}${stored > 0 ? `; ${t('storage on the plan', 'isitoreji esikupulani')} ${figureNumber(stored)} L` : ''}${needed > 0 ? `; ${t('storage needed', 'isitoreji esidingekayo')} ${figureNumber(needed)} L` : ''}.`,
  };
}

// ── 4. Sun, wind and slope ────────────────────────────────────────────────────────────────────

const sentence = (value: string) => value ? value.charAt(0).toUpperCase() + value.slice(1).toLowerCase() : value;
/** Compass bearing → point on a north-up drawing. */
const polar = (cx: number, cy: number, r: number, bearingDeg: number): [number, number] => { const a = (bearingDeg * Math.PI) / 180; return [cx + r * Math.sin(a), cy - r * Math.cos(a)]; };
/** An arc between two bearings, sweeping clockwise or anticlockwise, sampled every 3°. */
function arcPoints(cx: number, cy: number, r: number, fromDeg: number, sweepDeg: number, clockwise: boolean) {
  const out: Array<[number, number]> = [];
  const steps = Math.max(2, Math.ceil(sweepDeg / 3));
  for (let i = 0; i <= steps; i++) out.push(polar(cx, cy, r, fromDeg + (clockwise ? 1 : -1) * (sweepDeg * i) / steps));
  return out;
}
const pathOf = (points: Array<[number, number]>, close = false) => `M${points.map(([x, y]) => `${px(x)} ${px(y)}`).join('L')}${close ? 'Z' : ''}`;
/** A ring segment centred on a bearing: the shape of "it comes from somewhere in here". */
const wedgePath = (cx: number, cy: number, r0: number, r1: number, bearingDeg: number, halfWidthDeg: number) => pathOf([...arcPoints(cx, cy, r1, bearingDeg - halfWidthDeg, halfWidthDeg * 2, true), ...arcPoints(cx, cy, r0, bearingDeg + halfWidthDeg, halfWidthDeg * 2, false)], true);
function arrow(p: Pen, from: [number, number], to: [number, number], o: ShapeOptions & { head?: number } = {}) {
  const head = o.head ?? 9, a = Math.atan2(to[1] - from[1], to[0] - from[0]);
  const stop: [number, number] = [to[0] - Math.cos(a) * head * 0.8, to[1] - Math.sin(a) * head * 0.8];
  p.line(from[0], from[1], stop[0], stop[1], { stroke: o.stroke ?? INK, width: o.width ?? 2.4, dash: o.dash });
  p.path(pathOf([to, [to[0] - Math.cos(a - 0.42) * head * 1.5, to[1] - Math.sin(a - 0.42) * head * 1.5], [to[0] - Math.cos(a + 0.42) * head * 1.5, to[1] - Math.sin(a + 0.42) * head * 1.5]], true), { fill: o.stroke ?? INK });
}

/**
 * The permaculture sector drawing: where the sun travels in summer and in winter, where wind and
 * fire arrive from, and which way the ground falls. All of it comes from lib/sector — the model
 * the Design Studio's Sector sheet draws — so the two can never disagree.
 *
 * The NASA POWER seasonal wind means are deliberately NOT drawn. lib/sector demotes them because
 * the circular mean of a two-lobed wind rose points into the gap between the lobes, a direction
 * the wind never blows from. Only the sourced regional pattern (hatched: not measured here) and
 * the farmer's own observation (solid: seen on this ground) get a mark.
 */
export function sectorFigure(location: LocationData | null | undefined, facts: ReportSiteFacts | null | undefined, language = 'en'): ReportFigure | null {
  if (!location || !finite(location.lat) || !isValidEarthLatitude(location.lat)) return null;
  const model = deriveSectorModel(sectorSiteFromLocation(location), location.lat, finite(location.lon) ? location.lon : undefined);
  const t = translator(language);
  const p = pen();
  const cx = W / 2, cy = 276, R = 128;
  const side = (s: 'N' | 'S' | 'overhead') => s === 'S' ? t('to the south', 'eningizimu') : s === 'N' ? t('to the north', 'enyakatho') : t('overhead', 'phezulu ngqo');
  const { summer, winter } = model.solar;

  // The finding first: the low winter sun is what decides where shade falls when it matters most.
  p.text(14, 25, winter.noonSide === 'overhead' ? t('The midday sun stands almost overhead', 'Ilanga lasemini licishe libe phezulu ngqo') : `${t('The midday sun stands', 'Ilanga lasemini lima')} ${side(winter.noonSide)}`, { size: 17, weight: 700, fill: INK });
  const shadowOf = (path: typeof winter) => { if (!finite(path.shadowRatio) || path.shadowRatio <= 0.05) return ''; const n = figureNumber(path.shadowRatio, 1); return t(`a 1 m post throws a ${n} m shadow`, `isigxobo esingu-1 m senza isithunzi esingu-${n} m`); };
  p.text(14, 46, `${t('Winter', 'Ubusika')}: ${Math.round(winter.noonAltitudeDeg)}° ${t('above the horizon', 'ngaphezu komkhathizwe')}${shadowOf(winter) ? `, ${shadowOf(winter)}` : ''}   ·   ${t('Summer', 'Ihlobo')}: ${Math.round(summer.noonAltitudeDeg)}°`, { size: 13, fill: MUTED });

  p.circle(cx, cy, R, { fill: PAPER, stroke: HAIR, width: 1.5 });
  for (let b = 0; b < 360; b += 22.5) { const major = b % 90 === 0; const [x1, y1] = polar(cx, cy, R, b), [x2, y2] = polar(cx, cy, R - (major ? 9 : 5), b); p.line(x1, y1, x2, y2, { stroke: major ? MUTED : HAIR, width: major ? 1.6 : 1 }); }

  const described: string[] = [];
  const key: KeyEntry[] = [];
  const sunArc = (path: typeof summer, r: number, isWinter: boolean, name: string) => {
    if (!finite(path.sunriseAzDeg) || !finite(path.sunsetAzDeg)) return;
    const viaSouth = path.noonSide === 'S' || (path.noonSide === 'overhead' && !model.southernHemisphere);
    const sweep = viaSouth ? path.sunsetAzDeg - path.sunriseAzDeg : path.sunriseAzDeg + (360 - path.sunsetAzDeg);
    const points = arcPoints(cx, cy, r, path.sunriseAzDeg, sweep, viaSouth);
    p.path(pathOf(points), { stroke: AMBER, width: 7 });
    if (isWinter) p.path(pathOf(points), { stroke: '#ffffff', width: 2.4 });
    for (const end of [points[0], points[points.length - 1]]) p.circle(end[0], end[1], 5.5, { fill: '#ffffff', stroke: AMBER, width: 2.4 });
    const [lx, ly] = polar(cx, cy, r, viaSouth ? 180 : 0);
    p.text(lx, ly + (viaSouth ? -11 : 20), name, { size: 12, weight: 700, fill: INK, anchor: 'middle', halo: true });
    key.push({ draw: (x, y) => { p.line(x, y, x + 20, y, { stroke: AMBER, width: 7 }); if (isWinter) p.line(x, y, x + 20, y, { stroke: '#ffffff', width: 2.4 }); }, label: `${name}: ${t('rises', 'liphuma')} ${path.riseLabel16}, ${t('sets', 'lishona')} ${path.setLabel16}` });
    described.push(`${name}: ${t('rises', 'liphuma')} ${path.riseLabel16}, ${t('sets', 'lishona')} ${path.setLabel16}, ${Math.round(path.noonAltitudeDeg)}° ${t('above the horizon at midday', 'ngaphezu komkhathizwe emini')}, ${side(path.noonSide)}.`);
  };
  // Same convention as the Sector sheet: the short winter path sits inside the long summer one.
  sunArc(summer, 92, false, t('Summer sun', 'Ilanga lasehlobo'));
  sunArc(winter, 60, true, t('Winter sun', 'Ilanga lasebusika'));

  // Every wedge is drawn (and its outline remembered) before any label is placed, so a label can
  // step outward along its bearing until it clears all of them, the header and the other labels.
  const outline: Array<[number, number]> = [];
  const wedge = (r0: number, r1: number, bearingDeg: number, halfWidthDeg: number, o: ShapeOptions) => {
    p.path(wedgePath(cx, cy, r0, r1, bearingDeg, halfWidthDeg), o);
    outline.push(...arcPoints(cx, cy, r1, bearingDeg - halfWidthDeg, halfWidthDeg * 2, true), ...arcPoints(cx, cy, (r0 + r1) / 2, bearingDeg - halfWidthDeg, halfWidthDeg * 2, true));
  };
  const placed: Box[] = [];
  const outside = (bearingDeg: number, fromR: number, lines: Array<{ value: string; bold?: boolean }>) => {
    const b = ((bearingDeg % 360) + 360) % 360, octant = Math.round(b / 45) % 8;
    // Which corner of the label touches the bearing line: N hangs above, NE sits up-right, and so on.
    const hx = [0.5, 0, 0, 0, 0.5, 1, 1, 1][octant], hy = [1, 1, 0.5, 0, 0, 0, 0.5, 1][octant];
    const maxWidth = octant === 2 || octant === 6 ? 128 : octant === 0 || octant === 4 ? 200 : 186;
    // A line that will not fit breaks at its ' · ' joints first, and only then between words.
    const rows = lines.flatMap(line => (textWidth(line.value, 12) * (line.bold ? 1.08 : 1) <= maxWidth ? [line.value] : line.value.split(' · ')).flatMap(part => wrapText(part, 12, maxWidth / (line.bold ? 1.08 : 1))).map(value => ({ value, bold: line.bold })));
    const w = Math.max(...rows.map(r => textWidth(r.value, 12) * (r.bold ? 1.08 : 1))), h = rows.length * 15;
    let box: Box = { x: 0, y: 0, w, h };
    for (let r = fromR; r <= fromR + 96; r += 6) {
      const [ax, ay] = polar(cx, cy, r, b);
      box = { x: Math.min(W - 10 - w, Math.max(10, ax - w * hx)), y: ay - h * hy, w, h };
      const grown: Box = { x: box.x - 4, y: box.y - 4, w: w + 8, h: h + 8 };
      if (box.y >= 56 && !placed.some(other => overlaps(grown, other)) && !outline.some(([x, y]) => x > grown.x && x < grown.x + grown.w && y > grown.y && y < grown.y + grown.h)) break;
    }
    placed.push(box);
    const anchor = hx === 0 ? 'start' : hx === 1 ? 'end' : 'middle';
    rows.forEach((row, i) => p.text(box.x + w * hx, box.y + 11 + i * 15, row.value, { size: 12, weight: row.bold ? 700 : 400, fill: row.bold ? INK : MUTED, anchor, halo: true }));
  };

  const windHatch = model.namedWind.length ? p.hatch('wind', SLATE, 5, 1.3) : '';
  const fireHatch = model.fire ? p.hatch('fire', AMBER, 4, 1.5) : '';
  const sameBearing = (x: number, y: number) => Math.abs(((x - y + 540) % 360) - 180) < 12;
  if (model.fire) wedge(R + 27, R + 41, model.fire.bearingDeg, model.fire.halfWidthDeg, { fill: fireHatch, stroke: AMBER, width: 1.4, dash: '5 3' });
  for (const wind of model.namedWind) {
    wedge(R + 4, R + 25, wind.bearingDeg, wind.halfWidthDeg, { fill: windHatch, stroke: SLATE, width: 1.3, dash: '5 3' });
    arrow(p, polar(cx, cy, R + 25, wind.bearingDeg), polar(cx, cy, R - 4, wind.bearingDeg), { stroke: SLATE, width: 2, dash: '5 3', head: 7 });
  }
  for (const wind of model.namedWind) {
    const carriesFire = !!model.fire && sameBearing(model.fire.bearingDeg, wind.bearingDeg);
    outside(wind.bearingDeg, R + (carriesFire ? 47 : 31), [{ value: sentence(wind.title), bold: true }, { value: `${t('from the', 'uvela e')} ${wind.fromLabel} · ${wind.season}` }, ...(carriesFire ? [{ value: t('fire follows this wind', 'umlilo ulandela lo moya') }] : [])]);
    described.push(`${sentence(wind.title)}: ${t('from the', 'uvela e')} ${wind.fromLabel}, ${wind.season} (${t('regional pattern', 'iphethini yesifunda')}).`);
  }
  if (model.fire) {
    const fire = model.fire;
    if (!model.namedWind.some(w => sameBearing(fire.bearingDeg, w.bearingDeg))) outside(fire.bearingDeg, R + 47, [{ value: t('Fire risk', 'Ingozi yomlilo'), bold: true }, { value: `${t('from the', 'uvela e')} ${fire.fromLabel}` }]);
    described.push(`${t('Fire is most likely to arrive from the', 'Umlilo kungenzeka ufike uvela e')} ${fire.fromLabel}. ${fire.seasonNote}`);
  }
  const observed = labelToBearing(facts?.measurements?.localWindFrom);
  if (observed !== null) {
    const strongest = facts?.measurements?.localWindStrongestFrom;
    arrow(p, polar(cx, cy, R - 6, observed), polar(cx, cy, 30, observed), { stroke: INK, width: 3.4, head: 10 });
    described.push(`${t('Wind recorded on this site: usually from the', 'Umoya oqoshwe kule ndawo: uvame ukuvela e')} ${facts?.measurements?.localWindFrom}${strongest ? `; ${t('strongest from the', 'onamandla kakhulu uvela e')} ${strongest}` : ''}.`);
    key.push({ draw: (x, y) => arrow(p, [x, y], [x + 21, y], { stroke: INK, width: 3, head: 7 }), label: `${t('Wind you recorded here: from the', 'Umoya owuqophe lapha: uvela e')} ${facts?.measurements?.localWindFrom}${strongest ? ` (${t('strongest', 'onamandla')} ${strongest})` : ''}` });
  }
  if (model.water && !model.flat) {
    const water = model.water;
    arrow(p, polar(cx, cy, 14, water.downhillBearingDeg), polar(cx, cy, 48, water.downhillBearingDeg), { stroke: BLUE, width: 3, dash: water.indicative ? '5 3' : undefined, head: 8 });
    described.push(`${t('The ground falls toward the', 'Umhlaba wehlela e')} ${aspectLabel(water.downhillBearingDeg)} (${figureNumber(water.slopePct, 1)} % ${t('slope', 'umthambeka')}).`);
    key.push({ draw: (x, y) => arrow(p, [x, y], [x + 21, y], { stroke: BLUE, width: 3, dash: water.indicative ? '4 2' : undefined, head: 7 }), label: `${t('Downhill, toward the', 'Ukwehla, ngase')} ${aspectLabel(water.downhillBearingDeg)} (${figureNumber(water.slopePct, 1)} %)${water.indicative ? ` — ${t('check with a level', 'hlola ngelevela')}` : ''}` });
  } else {
    described.push(t('The ground reads as nearly flat, so no downhill direction is drawn.', 'Umhlaba ubonakala ucishe ube yisicaba, ngakho akukho ndlela yokwehla edwetshiwe.'));
    key.push({ draw: (x, y) => p.circle(x + 10, y, 5, { stroke: BLUE, width: 1.6, dash: '3 2' }), label: t('Nearly flat: no downhill direction drawn — check with a level', 'Cishe yisicaba: akukho ndlela yokwehla — hlola ngelevela') });
  }
  if (model.namedWind.length) key.push({ draw: (x, y) => p.rect(x + 1, y - 7, 18, 13, { fill: windHatch, stroke: SLATE, width: 1.3, dash: '4 2' }), label: t('Wind of the region — not measured on this site', 'Umoya wesifunda — awulinganiswanga kule ndawo') });
  if (model.fire) key.push({ draw: (x, y) => p.rect(x + 1, y - 7, 18, 13, { fill: fireHatch, stroke: AMBER, width: 1.3, dash: '4 2' }), label: t('Where fire is most likely to come from (regional)', 'Lapho umlilo ungavela khona (isifunda)') });

  // Compass letters last, so no wedge or arrow can cover them; the site sits at the centre.
  ([['N', 0], ['E', 90], ['S', 180], ['W', 270]] as const).forEach(([label, b]) => { const [x, y] = polar(cx, cy, R - 20, b); p.text(x, y + 5, label, { size: label === 'N' ? 16 : 13, weight: 700, fill: label === 'N' ? INK : MUTED, anchor: 'middle', halo: true }); });
  p.path(`M${cx - 8} ${cy + 7}V${cy - 2}L${cx} ${cy - 10}L${cx + 8} ${cy - 2}V${cy + 7}Z`, { fill: INK });

  const lowest = Math.max(cy + R, ...outline.map(([, y]) => y), ...placed.map(box => box.y + box.h));
  const height = keyRow(p, 14, lowest + 32, key) + 4;
  const lat = `${Math.abs(location.lat).toFixed(2)}° ${location.lat < 0 ? 'S' : 'N'}`;
  return {
    id: 'sectors', width: W, height: Math.ceil(height), svg: p.done(height),
    title: t('Sun, wind and slope', 'Ilanga, umoya nomthambeka'),
    note: t('North is up; the house mark is this site. Sun paths are calculated from the latitude. Hatched marks are regional patterns, not measurements: check them against what you and your neighbours see.', 'INyakatho iphezulu; uphawu lwendlu yile ndawo. Izindlela zelanga zibalwa ngokwe-latitude. Izimpawu ezinemidwa ziyiphethini yesifunda, aziyona imilinganiso: ziqinisekise ngalokho wena nomakhelwane enikubonayo.'),
    source: `${t('Sun: calculated for latitude', 'Ilanga: kubalwe nge-latitude')} ${lat}.${model.namedWind.length || model.fire ? ` ${t('Wind and fire: regional pattern', 'Umoya nomlilo: iphethini yesifunda')}${model.regionKey ? ` (${model.regionKey})` : ''}.` : ''}${model.water ? ` ${t('Slope: elevation model.', 'Umthambeka: imodeli yokuphakama.')}` : ''}${observed !== null ? ` ${t('Observed wind: recorded in the Design Studio.', 'Umoya obonwe: uqoshwe ku-Design Studio.')}` : ''}`,
    alt: `${t('Sector diagram', 'Umdwebo wamasekta')}. ${described.join(' ')}`,
  };
}

// ── 5. Soil ───────────────────────────────────────────────────────────────────────────────────

/**
 * pH, texture and organic carbon. The MARK carries the provenance: a filled dot is a laboratory
 * result from this ground, a hollow dot is the SoilGrids world model's estimate for the location,
 * and anything else — including the generic fallback values the app carries when no source
 * answered — is drawn as an empty scale marked "not measured". Same rule as lib/report-summary.
 */
export function soilFigure(location: LocationData | null | undefined, language = 'en'): ReportFigure | null {
  const soil = location?.soil;
  if (!soil) return null;
  const t = translator(language);
  const p = pen();
  const lab = soil.soilSource === 'lab', known = lab || soil.soilSource === 'soilgrids';
  const x0 = 40, x1 = W - 40;
  const marker = (x: number, y: number) => p.circle(x, y, 8, lab ? { fill: INK, stroke: '#ffffff', width: 2 } : { fill: '#ffffff', stroke: INK, width: 2.6 });
  const empty = (y: number) => { p.rect(x0, y - 7, x1 - x0, 14, { fill: '#ffffff', stroke: MUTED, width: 1.2, dash: '5 4', radius: 7 }); p.text((x0 + x1) / 2, y + 4.5, t('not measured', 'akulinganiswanga'), { size: 12, fill: MUTED, anchor: 'middle' }); };
  let y = 24;

  // pH
  p.text(14, y, t('How sour or sweet the soil is (pH)', 'Ukuthi umhlabathi umuncu noma umnandi kangakanani (pH)'), { size: 14, weight: 700, fill: INK });
  const phY = y + 42, phOf = (v: number) => x0 + ((v - 4) / 5) * (x1 - x0);
  const ph = known && finite(soil.ph) && soil.ph >= 3 && soil.ph <= 10 ? soil.ph : null;
  if (ph !== null) {
    p.rect(x0, phY - 7, x1 - x0, 14, { fill: TRACK, radius: 7 });
    p.rect(phOf(6), phY - 7, phOf(7) - phOf(6), 14, { fill: p.hatch('veg', GREEN, 5, 1.3), stroke: GREEN, width: 1.2 });
    marker(phOf(Math.min(9, Math.max(4, ph))), phY);
    p.text(phOf(Math.min(9, Math.max(4, ph))), phY - 15, `pH ${figureNumber(ph, 1)}`, { size: 14, weight: 700, fill: INK, anchor: 'middle', halo: true });
  } else empty(phY);
  for (let v = 4; v <= 9; v++) { p.line(phOf(v), phY + 9, phOf(v), phY + 14, { stroke: MUTED, width: 1 }); p.text(phOf(v), phY + 28, String(v), { size: 12, fill: MUTED, anchor: 'middle' }); }
  p.text(x0, phY + 46, t('← more acid (sour)', '← umuncu kakhulu'), { size: 12, fill: MUTED });
  p.text(x1, phY + 46, t('more alkaline →', 'une-alkali kakhulu →'), { size: 12, fill: MUTED, anchor: 'end' });
  if (ph !== null) p.text((phOf(6) + phOf(7)) / 2, phY + 46, t('most vegetables: 6 to 7', 'imifino eminingi: 6 kuya ku-7'), { size: 12, fill: GREEN, weight: 700, anchor: 'middle' });
  y = phY + 78;

  // Texture
  const parts = [{ name: t('Sand', 'Isihlabathi'), value: soil.sand }, { name: t('Silt', 'Udaka olucolekile'), value: soil.silt }, { name: t('Clay', 'Ubumba'), value: soil.clay }];
  const total = parts.reduce((sum, part) => sum + (finite(part.value) ? part.value : NaN), 0);
  const textureOk = known && Number.isFinite(total) && total > 90 && total < 110 && parts.every(part => (part.value as number) >= 0);
  p.text(14, y, `${t('What the soil is made of', 'Ukuthi umhlabathi wenziwe ngani')}${textureOk && soil.textureClass ? `: ${soil.textureClass}` : ''}`, { size: 14, weight: 700, fill: INK });
  const barY = y + 16;
  if (textureOk) {
    const looks: ShapeOptions[] = [{ fill: '#f5eadc', stroke: AMBER }, { fill: p.hatch('silt', SLATE, 6, 1.2), stroke: SLATE }, { fill: AMBER, stroke: AMBER }];
    let x = x0;
    parts.forEach((part, i) => {
      const w = ((part.value as number) / total) * (x1 - x0);
      p.rect(x + 1, barY, Math.max(0, w - 2), 26, { ...looks[i], width: 1.4, dash: lab ? undefined : '5 3', radius: 3 });
      const label = `${part.name} ${Math.round(part.value as number)} %`;
      if (w > textWidth(label, 12.5) + 12) p.text(x + w / 2, barY + 44, label, { size: 12.5, weight: 700, fill: INK, anchor: 'middle' });
      else p.text(x + w / 2, barY + 44, `${Math.round(part.value as number)} %`, { size: 12, fill: INK, anchor: 'middle' });
      x += w;
    });
  } else empty(barY + 13);
  y = barY + 78;

  // Organic carbon
  p.text(14, y, t('Organic carbon: how much rotted plant matter the soil holds', 'Ikhabhoni yemvelo: ukuthi umhlabathi uphethe izinto zezitshalo ezibolile ezingakanani'), { size: 14, weight: 700, fill: INK });
  const ocY = y + 42, ocOf = (v: number) => x0 + (v / 5) * (x1 - x0);
  const oc = known && finite(soil.organicCarbon) && soil.organicCarbon >= 0 ? soil.organicCarbon : null;
  if (oc !== null) {
    p.rect(x0, ocY - 7, x1 - x0, 14, { fill: TRACK, radius: 7 });
    marker(ocOf(Math.min(5, oc)), ocY);
    p.text(ocOf(Math.min(5, oc)), ocY - 15, `${figureNumber(oc, 1)} %`, { size: 14, weight: 700, fill: INK, anchor: 'middle', halo: true });
  } else empty(ocY);
  for (let v = 0; v <= 5; v++) { p.line(ocOf(v), ocY + 9, ocOf(v), ocY + 14, { stroke: MUTED, width: 1 }); p.text(ocOf(v), ocY + 28, `${v}${v === 5 ? '+' : ''} %`, { size: 12, fill: MUTED, anchor: 'middle' }); }
  y = ocY + 52;

  p.line(14, y, W - 14, y, { stroke: HAIR, width: 1 });
  y += 24;
  if (known) { marker(24, y - 4); y = paragraph(p, 42, y, lab ? t('Filled dot: measured by a laboratory on a sample from this site.', 'Ichashazi eligcwele: kulinganiswe yilabhorethri kusampula yale ndawo.') : t('Hollow dot and dashed outlines: estimated for this location by the SoilGrids world soil model, not measured here. A soil test on your own sample will replace them.', 'Ichashazi elingenalutho nemidwa enqamukayo: kulinganiselwe le ndawo yimodeli yomhlabathi yomhlaba i-SoilGrids, akulinganiswanga lapha. Ukuhlolwa komhlabathi wakho kuzokuvala lokhu.'), W - 56, { size: 12.5 }); }
  else y = paragraph(p, 14, y, t('No soil measurement is recorded for this site, so nothing is plotted. Arrange a soil test: the result fills in all three scales.', 'Akukho ukulinganiswa komhlabathi okuqoshiwe kule ndawo, ngakho akukho okudwetshiwe. Hlela ukuhlolwa komhlabathi: umphumela uzogcwalisa zonke izikali ezintathu.'), W - 28, { size: 13, weight: 700, fill: INK });

  return {
    id: 'soil', width: W, height: Math.ceil(y + 4), svg: p.done(y + 4),
    title: t('Soil at a glance', 'Umhlabathi ngamafuphi'),
    note: t('Top 30 cm of soil. No "good" or "bad" bands are drawn for organic carbon because the right level depends on the soil type and climate.', 'Amasentimitha angu-30 aphezulu omhlabathi. Ayikho imigqa ethi "kuhle" noma "kubi" yekhabhoni yemvelo ngoba izinga elifanele lincike ohlotsheni lomhlabathi nesimo sezulu.'),
    source: lab ? t('Your uploaded laboratory soil test', 'Ukuhlolwa kwakho komhlabathi kwelabhorethri okulayishiwe') : known ? t('SoilGrids world soil model (ISRIC), 250 m grid: an estimate, not a measurement', 'Imodeli yomhlabathi yomhlaba i-SoilGrids (ISRIC), igridi engu-250 m: isilinganiso, akusona isilinganiso sangempela') : t('No soil measurement recorded', 'Akukho ukulinganiswa komhlabathi okuqoshiwe'),
    alt: known ? `${t('Soil', 'Umhlabathi')}: ${ph !== null ? `pH ${figureNumber(ph, 1)}; ` : ''}${textureOk ? `${parts.map(part => `${part.name} ${Math.round(part.value as number)} %`).join(', ')}; ` : ''}${oc !== null ? `${t('organic carbon', 'ikhabhoni yemvelo')} ${figureNumber(oc, 1)} %` : ''} (${lab ? t('laboratory result', 'umphumela welabhorethri') : t('SoilGrids estimate', 'isilinganiso se-SoilGrids')}).` : t('Soil not measured.', 'Umhlabathi awulinganiswanga.'),
  };
}

// ── 6. Order of work ──────────────────────────────────────────────────────────────────────────

/**
 * lib/phasing's build phases as bars on a weeks axis. Coarse on purpose: phases and hold points,
 * no task-level dependency arrows — the plan is a sequence to agree on, not a project schedule.
 * Every bar is work still to do, so every bar wears the "planned" look (tint, dashed outline).
 */
export function timelineFigure(plan: PhasePlan | null | undefined, language = 'en'): ReportFigure | null {
  const phases = plan?.phases ?? [];
  if (phases.length < 2 || !phases.every(ph => finite(ph.weekStart) && finite(ph.weekEnd) && ph.weekEnd >= ph.weekStart)) return null;
  const t = translator(language);
  const p = pen();
  const left = 22, right = W - 30;
  const last = phases[phases.length - 1];
  const maxWeek = Math.max(...phases.map(ph => ph.weekEnd), 1);
  const step = maxWeek <= 12 ? 1 : maxWeek <= 24 ? 2 : maxWeek <= 48 ? 4 : 8;
  const xOf = (week: number) => left + (week / maxWeek) * (right - left);
  const rowH = 46, top = 16, bottom = top + phases.length * rowH;
  for (let w = 0; w <= maxWeek; w += step) p.line(xOf(w), top, xOf(w), bottom + 4, { stroke: HAIR, width: 1 });
  phases.forEach((phase, i) => {
    const y = top + i * rowH, open = phase === last;
    p.text(left, y + 16, `${phase.n}. ${clip(phase.title, 58)}`, { size: 13.5, weight: 700, fill: INK, halo: true });
    p.text(right, y + 16, phase.weekRange, { size: 12, fill: MUTED, anchor: 'end', halo: true });
    const xa = xOf(phase.weekStart), xb = Math.max(xa + 8, xOf(phase.weekEnd));
    p.rect(xa, y + 23, xb - xa, 14, { fill: '#e6efe6', stroke: GREEN, width: 1.6, dash: '5 3', radius: 3 });
    if (open) p.path(pathOf([[xb + 2, y + 23], [xb + 13, y + 30], [xb + 2, y + 37]], true), { fill: GREEN });
    else { p.path(pathOf([[xb, y + 21], [xb + 9, y + 30], [xb, y + 39], [xb - 9, y + 30]], true), { fill: INK, stroke: '#ffffff', width: 1.5 }); p.text(xb, y + 33.5, String.fromCharCode(64 + phase.n), { size: 9.5, weight: 700, fill: '#ffffff', anchor: 'middle' }); }
  });
  p.line(left, bottom + 4, right, bottom + 4, { stroke: MUTED, width: 1 });
  for (let w = 0; w <= maxWeek; w += step) p.text(xOf(w), bottom + 20, String(w), { size: 11.5, fill: MUTED, anchor: 'middle' });
  p.text((left + right) / 2, bottom + 38, t('weeks from the day work starts', 'amaviki kusukela ngosuku umsebenzi oqala ngalo'), { size: 12, fill: MUTED, anchor: 'middle' });
  const y = keyRow(p, left, bottom + 62, [
    { label: t('Hold point: stop and check before the next phase', 'Iphuzu lokuma: yima uhlole ngaphambi kwesigaba esilandelayo'), draw: (x, yy) => p.path(pathOf([[x + 10, yy - 8], [x + 18, yy], [x + 10, yy + 8], [x + 2, yy]], true), { fill: INK }) },
    { label: t('Carries on', 'Kuyaqhubeka'), draw: (x, yy) => p.path(pathOf([[x + 4, yy - 7], [x + 16, yy], [x + 4, yy + 7]], true), { fill: GREEN }) },
  ]);
  return {
    id: 'timeline', width: W, height: Math.ceil(y + 2), svg: p.done(y + 2),
    title: t('Order of work', 'Ukulandelana komsebenzi'),
    note: t('The order and rough length of each phase, worked out from what is on the saved design. The weeks are a planning guide, not a promise: weather, money and labour will move them. The order should not change.', 'Ukulandelana nobude obulinganiselwe besigaba ngasinye, kubalwe kulokho okusemklamweni ogciniwe. Amaviki ayisiqondiso sokuhlela, akusona isithembiso: isimo sezulu, imali nabasebenzi kuzowashintsha. Ukulandelana akufanele kushintshe.'),
    source: t('Build phases derived from the saved design', 'Izigaba zokwakha ezithathwe kumklamo ogciniwe'),
    alt: `${t('Order of work', 'Ukulandelana komsebenzi')}: ${phases.map(ph => `${ph.n}. ${ph.title} (${ph.weekRange})`).join('; ')}.`,
  };
}

// ── 7. How the ground is used ─────────────────────────────────────────────────────────────────

/** One bar = the whole measured site; the pieces are the areas the design and the map measure. */
export function landUseFigure(facts: ReportSiteFacts | null | undefined, language = 'en'): ReportFigure | null {
  const total = facts?.boundary?.areaM2;
  if (!finite(total) || total <= 0) return null;
  const t = translator(language);
  const p = pen();
  const raw = [
    { name: t('Vegetable beds', 'Imibhede yemifino'), value: facts?.design?.bedAreaM2, look: { fill: GREEN } as ShapeOptions },
    { name: t('Staple crop plots', 'Iziza zezitshalo eziyisisekelo'), value: facts?.design?.plotAreaM2, look: { fill: p.hatch('plot', AMBER, 5, 1.5), stroke: AMBER, width: 1.2 } as ShapeOptions },
    { name: t('Roof', 'Uphahla'), value: facts?.roof?.areaM2, look: { fill: SLATE } as ShapeOptions },
  ];
  const parts = raw.filter((part): part is typeof raw[number] & { value: number } => finite(part.value) && part.value > 0);
  const used = parts.reduce((sum, part) => sum + part.value, 0);
  // Pieces that add up to more than the site mean one of the measurements is wrong; draw nothing.
  if (!parts.length || used > total) return null;
  const rows = [...parts, { name: t('Everything else: paths, trees, yard, open ground', 'Konke okunye: izindlela, izihlahla, igceke, umhlaba ovulekile'), value: total - used, look: { fill: TRACK, stroke: HAIR, width: 1 } as ShapeOptions }];
  const x0 = 14, x1 = W - 14;
  p.text(x0, 24, `${t('The whole site', 'Indawo yonke')}: ${figureNumber(total)} m²`, { size: 16, weight: 700, fill: INK });
  let x = x0;
  for (const part of rows) { const w = (part.value / total) * (x1 - x0); p.rect(x + 1, 38, Math.max(1.5, w - 2), 30, { ...part.look, radius: 3 }); x += w; }
  let y = 96;
  for (const part of rows) {
    p.rect(x0, y - 11, 18, 13, { ...part.look, radius: 2 });
    p.text(x0 + 28, y, part.name, { size: 13 });
    const share = (part.value / total) * 100;
    p.text(x1, y, `${figureNumber(part.value)} m²   ${share < 1 ? '<1' : figureNumber(share)} %`, { size: 13, weight: 700, fill: INK, anchor: 'end' });
    y += 23;
  }
  return {
    id: 'land-use', width: W, height: Math.ceil(y), svg: p.done(y),
    title: t('How the ground is used', 'Ukuthi umhlaba usetshenziswa kanjani'),
    note: t('Areas as drawn on the saved design and traced on the map, whether built yet or not. Trees, paths and tanks are not counted as areas.', 'Izindawo njengoba zidwetshwe kumklamo ogciniwe nakumephu, noma sezakhiwe noma cha. Izihlahla, izindlela namathangi akubalwa njengezindawo.'),
    source: `${t('Boundary', 'Umngcele')}: ${facts?.boundary?.source ?? t('traced on the map', 'udwetshwe kumephu')}. ${t('Beds and plots: saved design.', 'Imibhede neziza: umklamo ogciniwe.')}`,
    alt: `${t('Land use', 'Ukusetshenziswa komhlaba')}: ${rows.map(part => `${part.name} ${figureNumber(part.value)} m²`).join('; ')}.`,
  };
}

// ── 8. Built and still to build ───────────────────────────────────────────────────────────────

/** One mark per thing on the design: filled = already there, ring = planned. Repeated, never scaled. */
export function statusFigure(canvas: DesignCanvasState | null | undefined, language = 'en'): ReportFigure | null {
  if (!canvas) return null;
  const t = translator(language);
  const names: Record<PlanPaint | 'plot' | 'route', string> = {
    bed: t('Vegetable beds', 'Imibhede yemifino'), plot: t('Staple crop plots', 'Iziza zezitshalo eziyisisekelo'), planting: t('Trees and plants', 'Izihlahla nezitshalo'), water: t('Water', 'Amanzi'),
    structure: t('Structures', 'Izakhiwo'), earthworks: t('Earthworks', 'Imisebenzi yomhlaba'), animal: t('Animals', 'Izilwane'), access: t('Access', 'Ukufinyelela'), route: t('Paths, swales and pipes', 'Izindlela, imisele namapayipi'),
  };
  const order: Array<keyof typeof names> = ['bed', 'plot', 'planting', 'water', 'earthworks', 'structure', 'animal', 'access', 'route'];
  const tally = new Map<keyof typeof names, { built: number; planned: number }>();
  const add = (key: keyof typeof names, planned: boolean) => { const row = tally.get(key) ?? { built: 0, planned: 0 }; if (planned) row.planned += 1; else row.built += 1; tally.set(key, row); };
  for (const item of canvas.items ?? []) { const def = ELEMENTS_BY_ID[item.defId]; if (def) add((BED_DEF_IDS as readonly string[]).includes(item.defId) ? 'bed' : CATEGORY_PAINT[def.category], statusOf(item) === 'proposed'); }
  for (const zone of canvas.zones ?? []) if (zone.feature === 'staple_garden') add('plot', statusOf(zone) === 'proposed');
  for (const line of canvas.lines ?? []) add('route', statusOf(line) === 'proposed');
  const rows = order.filter(key => tally.has(key)).map(key => ({ key, ...tally.get(key)! }));
  if (!rows.length) return null;
  const p = pen();
  const built = rows.reduce((sum, row) => sum + row.built, 0), planned = rows.reduce((sum, row) => sum + row.planned, 0);
  p.text(14, 25, `${figureNumber(built)} ${t('already there', 'sekukhona')}  ·  ${figureNumber(planned)} ${t('still to build or plant', 'kusazokwakhiwa noma kutshalwe')}`, { size: 17, weight: 700, fill: INK });
  const dotsX = 196, pitch = 17, perRow = Math.floor((W - 14 - 96 - dotsX) / pitch);
  let y = 56;
  for (const row of rows) {
    p.text(14, y + 4, names[row.key], { size: 13 });
    const count = row.built + row.planned, shown = Math.min(count, perRow - 2);
    for (let i = 0; i < shown; i++) { const x = dotsX + i * pitch; if (i < row.built) p.circle(x, y, 6, { fill: GREEN }); else p.circle(x, y, 5.2, { fill: '#ffffff', stroke: GREEN, width: 1.8, dash: '3 2' }); }
    if (count > shown) p.text(dotsX + shown * pitch, y + 4, `+${count - shown}`, { size: 12, fill: MUTED });
    p.text(W - 14, y + 4, `${row.built} / ${count}`, { size: 13, weight: 700, fill: INK, anchor: 'end' });
    y += 25;
  }
  y = keyRow(p, 14, y + 8, [
    { label: t('Already there', 'Sekukhona'), draw: (x, yy) => p.circle(x + 10, yy, 6, { fill: GREEN }) },
    { label: t('Planned, not built or planted yet', 'Kuhleliwe, akukakhiwa noma kutshalwe'), draw: (x, yy) => p.circle(x + 10, yy, 5.2, { fill: '#ffffff', stroke: GREEN, width: 1.8, dash: '3 2' }) },
    { label: t('Numbers: there now / total', 'Izinombolo: okukhona manje / isamba'), draw: () => undefined },
  ]);
  return {
    id: 'status', width: W, height: Math.ceil(y), svg: p.done(y),
    title: t('Built, and still to build', 'Okwakhiwe, nokusazokwakhiwa'),
    note: t('One mark for each thing on the saved design, as it was marked there. Change an item to "existing" in the Design Studio once it is in the ground.', 'Uphawu olulodwa lwento ngayinye esemklamweni ogciniwe, njengoba yaphawulwa khona. Shintsha into ibe "ekhona" ku-Design Studio uma isisemhlabathini.'),
    source: `${t('Saved design', 'Umklamo ogciniwe')}${typeof canvas.updatedAt === 'string' ? ` (${canvas.updatedAt.slice(0, 10)})` : ''}`,
    alt: `${t('Built and planned', 'Okwakhiwe nokuhleliwe')}: ${rows.map(row => `${names[row.key]} ${row.built}/${row.built + row.planned}`).join('; ')}.`,
  };
}
