import { SAMPLE_GARDENS, type SampleGarden } from './sample-gardens';
import type { ReportSection } from './programme-report-pdf';

export const SAMPLE_REPORT_DATE = '2026-09-06';
const contexts: Record<string, { purpose: string; layout: string; assessment: string; priority: string; followup: string }> = {
  'Crèche garden': { purpose: 'A demonstration food garden supporting an early learning setting, with adult-managed growing and a separate play space.', layout: 'The schematic separates the crèche building and play space from vegetables and staple crops. The water point is shown away from the main growing blocks.', assessment: 'Illustrative assessment: keeping the play area clear and controlling adult access to tools and water are the main design considerations. Food production must fit the daily work of the carers.', priority: 'Review the separation of growing, play and storage spaces. Confirm who maintains the garden during closures and who records produce used in meals.', followup: 'Review the garden with the responsible adult and record any access or maintenance issues before the next reporting period.' },
  'School garden': { purpose: 'A demonstration school garden combining practical learning with adult-managed food production.', layout: 'The drawing includes a school building, a learning area, vegetable blocks, staple crops and trees. Growing space is separate from the learning gathering area.', assessment: 'Illustrative assessment: lesson access, tool storage and care during school holidays are the operational priorities. Adult programme participants are separate from pupil headcounts.', priority: 'Agree a holiday care roster, link practical sessions to attendance records and record how produce is used.', followup: 'Review learning participation and garden care with the school contact. Keep child-identifying information out of public reports.' },
  'Homestead garden': { purpose: 'A demonstration household garden with food-growing space alongside the home and yard.', layout: 'The schematic retains the home and yard, with vegetables, a staple area, trees and a water point shown separately.', assessment: 'Illustrative assessment: the garden should fit household routines, available labour and safe access around the home. The site boundary is larger than the planted area.', priority: 'Confirm household priorities and water access; record food kept at home separately from donations and sales.', followup: 'At the next visit, ask which tasks were manageable and which beds need support. Household financial or survey details require appropriate access.' },
  'Commercial garden': { purpose: 'A demonstration market-oriented garden with more intensive growing blocks and a store.', layout: 'The schematic shows repeated vegetable blocks, a staple area, perimeter trees, a store and a water point. It is an overview, not a construction drawing.', assessment: 'Illustrative assessment: production records, usable access and harvest handling are central. Recorded harvest weight alone does not establish sales, profit or buyer demand.', priority: 'Confirm the crop plan, produce destinations, water reliability and complete input costs before assessing margins.', followup: 'Review dated harvest and sales records together, checking losses and unsold produce rather than treating all harvest as revenue.' },
  'Community food forest': { purpose: 'A demonstration community planting area with a tree-dominated layout and a smaller vegetable section.', layout: 'The schematic contains a tree grid, vegetable beds, a store and a water point. No staple production allocation is included in this sample.', assessment: 'Illustrative assessment: establishment care and long-term responsibility are the main planning questions. A tree drawn on the plan is not evidence that it is planted or bearing fruit.', priority: 'Agree a care roster and a planting inventory, then monitor survival by planting cohort. Confirm water arrangements before adding planting commitments.', followup: 'Record the condition of planted trees and distinguish existing, new and replacement trees in later reports.' },
  'Community garden': { purpose: 'A demonstration shared growing site with communal production and a meeting space.', layout: 'The schematic separates the store, meeting area, vegetable blocks, staple area, trees and water point.', assessment: 'Illustrative assessment: shared responsibilities, water access and fair record keeping are the main operational issues. Group membership must not be inferred from photographs.', priority: 'Agree the work roster, access arrangements and produce distribution records. Assign an owner to each follow-up action.', followup: 'Review the roster and support needs with the group; compare dated records before reporting changes in results.' },
};

/** One shared report body for on-screen previews and prepared PDFs. */
export function sampleGardenReportSections(garden: SampleGarden): ReportSection[] {
  const c = contexts[garden.kind ?? 'Community garden'] ?? contexts['Community garden'];
  const planted = garden.production.vegetableM2 + garden.production.stapleM2;
  const n = (v: number) => v.toLocaleString('en-ZA', { maximumFractionDigits: 1 });
  return [
    { title: 'Executive summary', lines: [c.purpose, `${garden.name} is the ${garden.town} example. Its sample register contains ${garden.farmers} adult participants, ${n(garden.produceKg)} kg of illustrative produce and ${garden.training}% training progress.`, `Sample status: ${garden.status === 'support' ? 'Needs support' : garden.status === 'establishing' ? 'Establishing' : 'Thriving'}. Coordinator: ${garden.facilitator}.`, `Prepared ${SAMPLE_REPORT_DATE}. All figures, observations and people in this garden report are fictional demonstration content.`] },
    { title: 'Site and production area', lines: [`Garden type: ${garden.kind}. Sample group language: ${garden.language}.`, `Illustrative site boundary area: ${n(garden.areaM2 ?? 0)} m².`, `Vegetable beds: ${n(garden.production.vegetableM2)} m². Staple plots: ${n(garden.production.stapleM2)} m². Total planted area: ${n(planted)} m².`, 'The remaining site area includes schematic buildings, access, tree areas and other space. It is not automatically available for planting. Areas come from the sample register, not measurements inferred from the photograph.', `The map point refers to the ${garden.town} area; it is not a surveyed property or a navigation instruction.`] },
    { title: 'Layout and site assessment', lines: [c.layout, c.assessment, 'Illustrative soil review: bed condition and soil management should be considered with water and access. No measured laboratory result is supplied for this example, so no pH, nutrient concentration or amendment rate is asserted.', 'The reference photograph illustrates this garden type. Its visible details are not a verified inventory and cannot establish dimensions, ownership, water availability or soil properties.'] },
    { title: 'Water, infrastructure and planting needs', lines: ['The schematic marks a water point. Its source, storage capacity, reliability and installation status have not been measured in this sample.', 'Vegetable and staple allocations are recorded separately. Tree symbols indicate planning context; species, number planted, survival and maturity need their own evidence.', c.priority, 'Any water storage or solar proposal needs an appropriate specification, installation plan, costs and maintenance responsibility before it becomes a funded deliverable.'] },
    { title: 'Production, participation and learning', lines: [`Illustrative harvest total: ${n(garden.produceKg)} kg. This is the same total shown in this garden profile. It is not a yield forecast or independently verified result.`, `${garden.farmers} adult participants are in this example register. The displayed ${garden.training}% training figure is sample progress, not proof of improved livelihoods.`, 'The catalogue does not provide a common crop-by-crop reporting period for every garden. Do not calculate annual yield, profitability or household savings from these sample totals.', 'A live report should distinguish produce kept, donated, sold and lost, and use dated attendance and assessments for learning outcomes.'] },
    { title: 'BOQ and funding readiness', lines: [`Known sample quantity basis: ${n(garden.production.vegetableM2)} m² of vegetable area and ${n(garden.production.stapleM2)} m² of staple area. These allocations are not construction specifications.`, 'This overview has no measured construction quantities or supplier quotations. Unpriced needs are not zero-cost needs; no fictional funding commitment is represented as confirmed.', 'Assess complete packages where needed: water storage with its base and connections; planting with establishment care; solar equipment with commissioning. Verify quantities and dependencies before pricing.', 'Keep approved current-project work separate from additional needs outside the budget. The proposed Funding & delivery workflow will connect those needs to costed BOQs and funder allocations; that full workflow is not yet available.'] },
    { title: 'Delivery evidence and next actions', lines: [garden.status === 'support' ? 'Priority follow-up: arrange a support visit and agree the main constraint with the group before expanding the plan.' : garden.status === 'establishing' ? 'Priority follow-up: confirm establishment tasks, responsible people and the first dated progress check.' : 'Priority follow-up: maintain the work roster and review evidence before sharing the next programme update.', c.followup, 'Record installed tanks and storage capacity separately from measured water collected. Record commissioned solar capacity separately from energy produced. Record planted trees separately from survival and fruit harvest.', 'Use dated photos, receipts, visit records and appropriate operational checks. A paid invoice or an AI-generated image does not verify a completed installation.'] },
    { title: 'Report basis and limitations', lines: [`Snapshot: ${garden.id} / ${SAMPLE_REPORT_DATE}. Source: the shared fictional garden catalogue and its type-specific assessment narrative.`, 'The prepared report is a complete demonstration document, not a professional site survey or a new live AI analysis. It opens without making a paid AI request.', 'The photograph is AI-generated and the layout is schematic, not to scale. Adult portraits elsewhere in the sample may repeat.', 'Use the separate Ubhejane workspace for the connected editable farm design. Opening this garden report does not overwrite any real map or report.'] },
  ];
}

export function sampleGardenReportUrl(id: string): string | undefined {
  return SAMPLE_GARDENS.some(g => g.id === id) ? `/demo/reports/${id}.pdf` : undefined;
}
