/** Scripted demo conversations. Never sent as real user history to the chat API. */
export const SAMPLE_LIMA = {
  farmer: {title:'Aphids on a vegetable plant', question:'These insects are on my vegetable leaves. How can I deal with them?', image:'/demo/produce/aphids.jpg', answer:'This example photo illustrates aphids. On a real plant, check the undersides of nearby leaves and the tender shoots too. On sturdy plants, water can dislodge aphids without crushing the leaves. Protect useful insects such as ladybirds. If the plant is struggling or the problem spreads, ask your mentor to check it before choosing a treatment.', followup:'What should I show my mentor?', next:'Take a close photo of the insects, another of the whole plant, and note which crop and beds are affected. Record what you tried and arrange a follow-up check.', source:'https://ipm.ucanr.edu/home-and-landscape/aphids/'},
  mentor: {title:'Prepare a garden visit', question:'Help me prepare for visits to my assigned gardens.', answer:'Start with gardens that requested support and any overdue follow-ups. For each visit, review the previous note, agree the main question with the grower, and check the garden together. Record the place, visit date, observations, agreed actions and next follow-up.', followup:'What goes to the organisation?', next:'Share the visit summary, support needs and agreed next steps through your authorised records. Private household details should stay with the staff who need them. This example has not scheduled a visit or sent a message.'},
  ngo: {title:'Learn before the next project', question:'What should we review before starting the next project?', answer:'Compare the baseline with later assessments, review missing responses, and discuss training and mentor feedback. Check milestones against their evidence. Keep a learning action for each change, with an owner and review date. Include app difficulties that made fieldwork harder.', followup:'How do we request an app improvement?', next:'Use Report a bug or request a feature. Describe who is affected, the task they were doing, and the outcome they need. Link the request in your project learning notes. This example has not submitted a request.'},
  funder: {title:'Understand the evidence', question:'What should I check before interpreting the programme results?', answer:'Check the reporting period, which gardens submitted records, and whether the organisation has approved the evidence. Attendance counts participation; it does not by itself prove improved livelihoods. Compare later surveys with the baseline and read the limits alongside the figures.', followup:'Could harvested food have a retail value?', next:'Yes, as an estimate: match each crop quantity to a dated local retail price in the same unit. Show how much harvest is covered by prices. Keep this separate from actual sales income, profit and verified household savings.'},
  student: {title:'Prepare for a practical lesson', question:'How should I prepare for the garden lesson?', answer:'Open the assigned course material and note anything you want the facilitator to demonstrate. Bring your questions to the practical session and complete the assessment when you are ready.', followup:'Does reading this complete my course?', next:'No. This is a scripted example. Your lesson progress and assessments are recorded separately.'},
} as const;
export function sampleLimaFor(role: string) { return SAMPLE_LIMA[role as keyof typeof SAMPLE_LIMA] ?? SAMPLE_LIMA.farmer; }
