"use client";

import { useRef, useState } from 'react';
import Link from 'next/link';
import { SCALE_MODES, SCALE_NOTICE, scaleArrangement, scaleQuestions, checkScaleAnswers, scaleNumber as n, type ScalePair, type ScaleMode } from '@/lib/design-scale';
import DesignScaleDiagram from './DesignScaleDiagram';
import styles from './FinanceCourse.module.css';
import scale from './DesignScalePractice.module.css';

export default function DesignScalePractice({ pair }: { pair: ScalePair }) {
  const [mode, setMode] = useState<ScaleMode>('supplied');
  const [enlarged, setEnlarged] = useState(false);
  const [answers, setAnswers] = useState<Record<string,string>>({});
  const [checked, setChecked] = useState(false);
  const [downloadMessage, setDownloadMessage] = useState('');
  const svgRef = useRef<SVGSVGElement>(null);
  const model = scaleArrangement(pair, mode);
  const scenario = SCALE_MODES.find(item => item.id === mode)!;
  const checks = checkScaleAnswers(model, answers);
  function changeMode(next: ScaleMode) { setMode(next); setAnswers({}); setChecked(false); setDownloadMessage(''); }
  function download() {
    if (!svgRef.current) return;
    const copy = svgRef.current.cloneNode(true) as SVGSVGElement;
    copy.removeAttribute('style');
    const content = new XMLSerializer().serializeToString(copy);
    const url = URL.createObjectURL(new Blob([content], { type: 'image/svg+xml;charset=utf-8' }));
    const link = document.createElement('a'); link.href=url; link.download=`imbewu-scale-${mode}.svg`; document.body.appendChild(link); link.click(); link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url),1000);
    setDownloadMessage(`Diagram requested: imbewu-scale-${mode}.svg. It carries model dimensions, not a fixed printed scale.`);
  }
  return <>
    <aside className={`${styles.notice} ${styles.projectNotice}`}><p>{SCALE_NOTICE}</p></aside>
    <section className={styles.section} id="source"><p className={styles.eyebrow}>Read the source before the picture</p><h2>Two rectangles from the sample garden</h2><p>Bed 1 and Bed 2 each have a supplied width of <strong>{n(pair[0].widthM)} m</strong> and length of <strong>{n(pair[0].lengthM)} m</strong>. In the model they line up, with a clear gap of <strong>{n(scaleArrangement(pair, 'supplied').gapM)} m</strong> between their edges. These values describe a software example. Whether people can work and move comfortably needs a separate site check.</p><details><summary>See the source coordinates and units</summary><p>Coordinates locate the top-left corner in the sample model’s metre frame. They are not latitude and longitude or measurements taken by a learner. The exercise uses the same two bed records as the app’s sample garden.</p><div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Supplied model coordinates"><table><caption>Supplied model data, before any practice move</caption><thead><tr><th>Record</th><th>x (m)</th><th>y (m)</th><th>Width (m)</th><th>Length (m)</th></tr></thead><tbody>{pair.map(bed => <tr key={bed.reference}><th>{bed.label}<br /><small>{bed.reference}</small></th><td>{n(bed.xM)}</td><td>{n(bed.yM)}</td><td>{n(bed.widthM)}</td><td>{n(bed.lengthM)}</td></tr>)}</tbody></table></div><p>The supplied gap is the left edge of Bed 2 minus the right edge of Bed 1: {n(pair[1].xM)} − ({n(pair[0].xM)} + {n(pair[0].widthM)}) = {n(scaleArrangement(pair, 'supplied').gapM)} m.</p></details></section>
    <section className={styles.section} id="explore"><p className={styles.eyebrow}>Look, compare, explain</p><h2>What changes when a bed moves?</h2><div className={styles.actions} role="group" aria-label="Bed arrangement">{SCALE_MODES.map(item => <button key={item.id} type="button" aria-pressed={mode===item.id} onClick={()=>changeMode(item.id)}>{item.label}</button>)}</div><p aria-live="polite">{scenario.explanation} Bed widths and lengths stay the same.</p>
      <div className={scale.diagramGrid}><figure className={scale.figure}><div className={scale.viewport} data-enlarged={enlarged} tabIndex={0} role="region" aria-label="Scale diagram; enlarged view can be scrolled"><div className={enlarged ? scale.enlarged : scale.normal}><DesignScaleDiagram model={model} scenario={scenario.label} svgRef={svgRef} /></div></div><figcaption>Green: bed outlines. Sand: space between them. Orange with a dashed edge: an overlap. The outer rectangle shows their combined extent, not a property boundary.</figcaption></figure>
      <div className={scale.readout}><h3>{scenario.label}</h3><dl><dt>Each bed</dt><dd>{n(pair[0].widthM)} × {n(pair[0].lengthM)} m</dd><dt>{model.overlapM > 0 ? 'Overlap width' : 'Clear gap'}</dt><dd>{n(model.overlapM || model.gapM)} m</dd><dt>Outer rectangle</dt><dd>{n(model.outerWidthM)} × {n(pair[0].lengthM)} m</dd></dl><p>{mode === 'supplied' ? 'The gap is outside both bed outlines. Do not count it as bed area.' : mode === 'touching' ? 'Touching edges leave no gap. A neat rectangle does not prove there is usable access.' : 'The shared strip is one piece of ground. Two outlines cannot make it count twice.'}</p><button type="button" className={scale.viewButton} aria-pressed={enlarged} onClick={()=>setEnlarged(value=>!value)}>{enlarged ? 'Return to fitted view' : 'Enlarge the view'}</button><p className={scale.small}>Changing the view changes screen size only. It does not change the supplied dimensions or improve their evidence.</p></div></div>
    </section>
    <section className={styles.section} id="calculate"><h2>Check the ground, not just the shapes</h2><p>Use the current arrangement: <strong>{scenario.label.toLowerCase()}</strong>. Area of a rectangle = width × length. If two outlines overlap, subtract their shared area once when counting the ground they cover. Try on paper or enter your answers below; a comma or point can mark a decimal.</p><div className={scale.answers}>{scaleQuestions(model).map(question => <label className={styles.answerField} key={question.id} htmlFor={`scale-${question.id}`}><strong>{question.label} ({question.unit})</strong><input id={`scale-${question.id}`} type="text" inputMode="decimal" maxLength={24} value={answers[question.id] ?? ''} onChange={event=>{setAnswers(current=>({...current,[question.id]:event.target.value}));setChecked(false);}} /></label>)}</div><div className={styles.actions}><button type="button" className={styles.primary} disabled={checks.some(check=>check.entered===null)} onClick={()=>setChecked(true)}>Check these calculations</button></div><p>Enter a number in each box to check. This is practice; no result is saved or awarded as course credit. Changing the arrangement clears the previous answers.</p>
      <div aria-live="polite" aria-atomic="true">{checked && <div className={styles.practice}><h3>{checks.filter(check=>check.correct).length} of {checks.length} calculations match this model</h3><ul>{checks.map(check=><li key={check.id}><strong>{check.correct ? 'Matches' : 'Check again'} — {check.label}:</strong> {n(check.expected)} {check.unit}.</li>)}</ul><p>One bed: {n(pair[0].widthM)} × {n(pair[0].lengthM)} = {n(model.bedAreaM2)} m². {model.overlapM > 0 ? `Shared strip: ${n(model.overlapM)} × ${n(pair[0].lengthM)} = ${n(model.overlapAreaM2)} m². Ground covered once: ${n(model.bedAreaM2)} + ${n(model.bedAreaM2)} − ${n(model.overlapAreaM2)} = ${n(model.coveredM2)} m².` : `No overlap: ${n(model.bedAreaM2)} + ${n(model.bedAreaM2)} = ${n(model.coveredM2)} m² inside the bed outlines.`}</p><p>The outer rectangle covers {n(model.outerAreaM2)} m². {model.gapM > 0 ? `That includes ${n(model.gapAreaM2)} m² between the beds; this gap is not bed area.` : 'In this arrangement there is no gap between the outlines. That does not make it a suitable real layout.'}</p><p>Now explain whether the drawing establishes access, usable growing space or an expected harvest. It establishes only the supplied geometry; those real-world decisions need further evidence.</p></div>}</div>
    </section>
    <section className={styles.section}><h2>Keep the dimension, check the export</h2><p>The downloaded diagram includes its model dimensions. Its size on paper depends on the print settings: do not measure the print with a ruler and assume a ground distance unless you have established and checked the printed scale.</p><div className={styles.actions}><button type="button" onClick={download}>Download this diagram (SVG)</button><Link href="/student/design/folder#folder-d4">Record your fit and evidence checks →</Link></div><p role="status">{downloadMessage}</p><h3>Bring this method back to your design</h3><p>Keep the measured source, units and drawing revision together. Check the clear space between actual edges, not just the distance between centres. Then check it with the people doing the work, the proposed system and the relevant technical guidance. The full busy-yard plan still needs its own measured source pack.</p><div className={styles.actions}><Link href="/student/design/d4-1">Return to the measured-layout lesson →</Link><Link href="/student/guides/design">Practise editing a sample plan in the app →</Link></div></section>
  </>;
}
