"use client";

import { useRef, useState } from 'react';
import { SCALE_MODES, SCALE_NOTICE, scaleArrangement, scaleQuestions, checkScaleAnswers, scaleNumber as n, type ScalePair, type ScaleMode } from '@/lib/design-scale';
import DesignScaleDiagram from './DesignScaleDiagram';
import OfflinePageLink from './OfflinePageLink';
import DesignDraftCopy from './DesignDraftCopy';
import styles from './FinanceCourse.module.css';
import scale from './DesignScalePractice.module.css';

export default function DesignScalePractice({ pair }: { pair: ScalePair }) {
  const [mode, setMode] = useState<ScaleMode>('supplied');
  const [enlarged, setEnlarged] = useState(false);
  const [answers, setAnswers] = useState<Record<string,string>>({});
  const [checked, setChecked] = useState(false);
  const [downloadMessage, setDownloadMessage] = useState('');
  const svgRef = useRef<SVGSVGElement>(null);
  const model = scaleArrangement(pair, mode);
  const scenario = SCALE_MODES.find(item => item.id === mode)!;
  const checks = checkScaleAnswers(model, answers);
  function changeMode(next: ScaleMode) { setMode(next); setAnswers({}); setChecked(false); setDownloadMessage(''); }
  function download() {
    if (!svgRef.current) return;
    const copy = svgRef.current.cloneNode(true) as SVGSVGElement;
    copy.removeAttribute('style');
    const content = new XMLSerializer().serializeToString(copy);
    const url = URL.createObjectURL(new Blob([content], { type: 'image/svg+xml;charset=utf-8' }));
    const link = document.createElement('a'); link.href=url; link.download=`imbewu-scale-${mode}.svg`; document.body.appendChild(link); link.click(); link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url),1000);
    setDownloadMessage(`Diagram requested: imbewu-scale-${mode}.svg. It carries model dimensions, not a fixed printed scale.`);
  }
  return <>
    <aside className={`${styles.notice} ${styles.projectNotice}`}><p><DesignDraftCopy en={SCALE_NOTICE} zu="Umsebenzi wesikali olingiswayo. Lezi zilinganiso zivela kumodeli yesibonelo sohlelo lokusebenza, hhayi ekuhlolweni komhlaba. Aziwona ububanzi obunconyelwayo bemibhede noma bezindlela zokuhamba. Lokhu kuhlukile ecaleni legceke elimatasa elingalinganiswanga." /></p></aside>
    <section className={styles.section} id="source"><p className={styles.eyebrow}><DesignDraftCopy en="Read the source before the picture" zu="Funda umthombo ngaphambi kwesithombe" /></p><h2><DesignDraftCopy en="Two rectangles from the sample garden" zu="Onxande ababili abasengadini yesibonelo" /></h2><p>Bed 1 and Bed 2 each have a supplied width of <strong>{n(pair[0].widthM)} m</strong> and length of <strong>{n(pair[0].lengthM)} m</strong>. In the model they line up, with a clear gap of <strong>{n(scaleArrangement(pair, 'supplied').gapM)} m</strong> between their edges. These values describe a software example. Whether people can work and move comfortably needs a separate site check.</p><details><summary><DesignDraftCopy en="See the source coordinates and units" zu="Bona izixhumanisi namayunithi omthombo" /></summary><p>Coordinates locate the top-left corner in the sample model’s metre frame. They are not latitude and longitude or measurements taken by a learner. The exercise uses the same two bed records as the app’s sample garden.</p><div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Supplied model coordinates"><table><caption><DesignDraftCopy en="Supplied model data, before any practice move" zu="Idatha yemodeli enikeziwe, ngaphambi kokuzama ukuhambisa" /></caption><thead><tr><th>Record</th><th>x (m)</th><th>y (m)</th><th>Width (m)</th><th>Length (m)</th></tr></thead><tbody>{pair.map(bed => <tr key={bed.reference}><th>{bed.label}<br /><small>{bed.reference}</small></th><td>{n(bed.xM)}</td><td>{n(bed.yM)}</td><td>{n(bed.widthM)}</td><td>{n(bed.lengthM)}</td></tr>)}</tbody></table></div><p>The supplied gap is the left edge of Bed 2 minus the right edge of Bed 1: {n(pair[1].xM)} − ({n(pair[0].xM)} + {n(pair[0].widthM)}) = {n(scaleArrangement(pair, 'supplied').gapM)} m.</p></details></section>
    <section className={styles.section} id="explore"><p className={styles.eyebrow}><DesignDraftCopy en="Look, compare, explain" zu="Buka, qhathanisa, uchaze" /></p><h2><DesignDraftCopy en="What changes when a bed moves?" zu="Yini eshintshayo uma umbhede uhamba?" /></h2><div className={styles.actions} role="group" aria-label="Bed arrangement">{SCALE_MODES.map(item => <button key={item.id} type="button" aria-pressed={mode===item.id} onClick={()=>changeMode(item.id)}><DesignDraftCopy en={item.label} zu={{supplied:'Igebe elinikeziwe',touching:'Imiphetho iyathintana',overlap:'Imidwebo iyadlulana'}[item.id]} /></button>)}</div><p aria-live="polite">{scenario.explanation} Bed widths and lengths stay the same.</p>
      <div className={scale.diagramGrid}><figure className={scale.figure}><div className={scale.viewport} data-enlarged={enlarged} tabIndex={0} role="region" aria-label="Scale diagram; enlarged view can be scrolled"><div className={enlarged ? scale.enlarged : scale.normal}><DesignScaleDiagram model={model} scenario={scenario.label} svgRef={svgRef} /></div></div><figcaption><DesignDraftCopy en="Green: bed outlines. Sand: space between them. Orange with a dashed edge: an overlap. The outer rectangle shows their combined extent, not a property boundary." zu="Okuluhlaza: imiphetho yemibhede. Okusansundu: isikhala esiphakathi kwayo. Okuwolintshi okunomugqa ophukile: indawo edlulene. Unxande wangaphandle ubonisa indawo ehlanganisiwe, hhayi umngcele wendawo." /></figcaption></figure>
      <div className={scale.readout}><h3>{scenario.label}</h3><dl><dt><DesignDraftCopy en="Each bed" zu="Umbhede ngamunye" /></dt><dd>{n(pair[0].widthM)} × {n(pair[0].lengthM)} m</dd><dt><DesignDraftCopy en={model.overlapM > 0 ? 'Overlap width' : 'Clear gap'} zu={model.overlapM > 0 ? 'Ububanzi bokudlula kwemibhede' : 'Igebe elicacile'} /></dt><dd>{n(model.overlapM || model.gapM)} m</dd><dt><DesignDraftCopy en="Outer rectangle" zu="Unxande wangaphandle" /></dt><dd>{n(model.outerWidthM)} × {n(pair[0].lengthM)} m</dd></dl><p>{mode === 'supplied' ? 'The gap is outside both bed outlines. Do not count it as bed area.' : mode === 'touching' ? 'Touching edges leave no gap. A neat rectangle does not prove there is usable access.' : 'The shared strip is one piece of ground. Two outlines cannot make it count twice.'}</p><button type="button" className={scale.viewButton} aria-pressed={enlarged} onClick={()=>setEnlarged(value=>!value)}><DesignDraftCopy en={enlarged ? 'Return to fitted view' : 'Enlarge the view'} zu={enlarged ? 'Buyela ekubukeni okujwayelekile' : 'Khulisa ukubuka'} /></button><p className={scale.small}>Changing the view changes screen size only. It does not change the supplied dimensions or improve their evidence.</p></div></div>
    </section>
    <section className={styles.section} id="calculate"><h2><DesignDraftCopy en="Check the ground, not just the shapes" zu="Hlola umhlaba, hhayi izimo kuphela" /></h2><p>Use the current arrangement: <strong>{scenario.label.toLowerCase()}</strong>. Area of a rectangle = width × length. If two outlines overlap, subtract their shared area once when counting the ground they cover. Try on paper or enter your answers below; a comma or point can mark a decimal.</p><div className={scale.answers}>{scaleQuestions(model).map(question => <label className={styles.answerField} key={question.id} htmlFor={`scale-${question.id}`}><strong><DesignDraftCopy en={`${question.label} (${question.unit})`} zu={`${{bed:'Indawo yoMbhede 1',space:model.overlapM > 0 ? 'Ububanzi bokudlula' : 'Ububanzi begebe elicacile',covered:'Umhlaba ongaphakathi kwemidwebo yemibhede, kubalwa indawo edlulene kanye kuphela'}[question.id]} (${question.unit})`} /></strong><input id={`scale-${question.id}`} type="text" inputMode="decimal" maxLength={24} value={answers[question.id] ?? ''} onChange={event=>{setAnswers(current=>({...current,[question.id]:event.target.value}));setChecked(false);}} /></label>)}</div><div className={styles.actions}><button type="button" className={styles.primary} disabled={checks.some(check=>check.entered===null)} onClick={()=>setChecked(true)}><DesignDraftCopy en="Check these calculations" zu="Hlola lezi zibalo" /></button></div><p>Enter a number in each box to check. This is practice; no result is saved or awarded as course credit. Changing the arrangement clears the previous answers.</p>
      <div aria-live="polite" aria-atomic="true">{checked && <div className={styles.practice}><h3><DesignDraftCopy en={`${checks.filter(check=>check.correct).length} of ${checks.length} calculations match this model`} zu={`${checks.filter(check=>check.correct).length} kwezingu-${checks.length} izibalo ziyahambisana nale modeli`} /></h3><ul>{checks.map(check=><li key={check.id}><strong><DesignDraftCopy en={check.correct ? 'Matches' : 'Check again'} zu={check.correct ? 'Kuyahambisana' : 'Hlola futhi'} /> — {check.label}:</strong> {n(check.expected)} {check.unit}.</li>)}</ul><p>One bed: {n(pair[0].widthM)} × {n(pair[0].lengthM)} = {n(model.bedAreaM2)} m². {model.overlapM > 0 ? `Shared strip: ${n(model.overlapM)} × ${n(pair[0].lengthM)} = ${n(model.overlapAreaM2)} m². Ground covered once: ${n(model.bedAreaM2)} + ${n(model.bedAreaM2)} − ${n(model.overlapAreaM2)} = ${n(model.coveredM2)} m².` : `No overlap: ${n(model.bedAreaM2)} + ${n(model.bedAreaM2)} = ${n(model.coveredM2)} m² inside the bed outlines.`}</p><p>The outer rectangle covers {n(model.outerAreaM2)} m². {model.gapM > 0 ? `That includes ${n(model.gapAreaM2)} m² between the beds; this gap is not bed area.` : 'In this arrangement there is no gap between the outlines. That does not make it a suitable real layout.'}</p><p>Now explain whether the drawing establishes access, usable growing space or an expected harvest. It establishes only the supplied geometry; those real-world decisions need further evidence.</p></div>}</div>
    </section>
    <section className={styles.section}><h2><DesignDraftCopy en="Keep the dimension, check the export" zu="Gcina isilinganiso, uhlole ifayela elikhishiwe" /></h2><p>The downloaded diagram includes its model dimensions. Its size on paper depends on the print settings: do not measure the print with a ruler and assume a ground distance unless you have established and checked the printed scale.</p><div className={styles.actions}><button type="button" onClick={download}><DesignDraftCopy en="Download this diagram (SVG)" zu="Landa lo mdwebo (SVG)" /></button><OfflinePageLink href="/student/design/folder#folder-d4"><DesignDraftCopy en="Record your fit and evidence checks →" zu="Rekhoda ukuhlola ukulingana nobufakazi →" /></OfflinePageLink></div><p role="status">{downloadMessage && <DesignDraftCopy en={downloadMessage} zu={downloadMessage.startsWith('Diagram requested:') ? `Kucelwe umdwebo: ${downloadMessage.match(/^Diagram requested: (.+?)\. It carries model dimensions, not a fixed printed scale\.$/)?.[1] ?? 'ifayela'}. Uqukethe izilinganiso zemodeli, awusona isikali esinqunyiwe sokuphrinta.` : 'Ukulanda akukwazanga ukulungiswa. Gcina leli khasi livuliwe bese uzama futhi.'} />}</p><h3><DesignDraftCopy en="Bring this method back to your design" zu="Sebenzisa le ndlela ekudizayineni kwakho" /></h3><p>Keep the measured source, units and drawing revision together. Check the clear space between actual edges, not just the distance between centres. Then check it with the people doing the work, the proposed system and the relevant technical guidance. The full busy-yard plan still needs its own measured source pack.</p><div className={styles.actions}><OfflinePageLink href="/student/design/d4-1"><DesignDraftCopy en="Return to the measured-layout lesson →" zu="Buyela esifundweni sokuhlela esilinganisiwe →" /></OfflinePageLink><OfflinePageLink href="/student/guides/design"><DesignDraftCopy en="Practise editing a sample plan in the app →" zu="Zijwayeze ukuhlela uhlelo lwesibonelo kuhlelo lokusebenza →" /></OfflinePageLink></div></section>
  </>;
}
